desihub/desispec

bin/fluxCalib.py
Please Check for any bugs/steps etc. Comments are welcome.
=> flux_calibration code added

bin/desi_make_bricks.py, doc/coadd.rst, doc/index.rst, py/desispec/io/__init__.py, py/desispec/io/brick.py, py/desispec/io/fibermap.py, py/desispec/io/meta.py
This resolves #3 and is ready for review.
=> Update to write brick files from fibermaps and cframes

py/desispec/log.py, py/desispec/test/test_log.py
add DESI_LOGLEVEL environment variable, add doc, define WARNING... in module
add unit test/example of log
=> Improve logger

py/desispec/brick.py, py/desispec/fiberflat.py, py/desispec/fluxcalibration.py, py/desispec/io/fiberflat.py, py/desispec/io/fibermap.py, py/desispec/io/fluxcalibration.py, py/desispec/io/zfind.py, py/desispec/linalg.py, py/desispec/pipeline/run.py, py/desispec/sky.py
This PR addresses issue #17 to update the docstrings (again).  They aren't perfect, but they are fairly complete.  This also corrects a number of docstrings that were simply wrong about inputs and outputs (usually due to interfaces which changes but the docstring wasn't updated).
=> updated docstrings

bin/desi_compute_sky.py, doc/nb/QA_Exposure.ipynb, doc/nb/QA_Frame.ipynb, py/desispec/io/__init__.py, py/desispec/io/qa.py, py/desispec/qa/__init__.py, py/desispec/qa/qa_exposure.py, py/desispec/sky.py, py/desispec/test/test_io.py, py/desispec/test/test_qa.py
Generated a QA Class for pipeline assessment on
a given exposure.  
Includes simple QA on Skysub algorithm.
Includes simple I/O tests.
Includes an iPython Notebook for usage/tests.
=> QA Exposure

py/desispec/fiberflat.py, py/desispec/test/test_fiberflat.py
This fixes a "feature" of the fiber flat that was not converging to the correct solution when resolution and throughput vary a lot from fiber to fiber.
=> Fiberflat enhancement

py/desispec/maskbits.py
The straight forward examples are added in the docstring for future reference.
c.f.: https://github.com/desihub/desispec/issues/80
=> Add examples of get/set/has in docstring.

py/desispec/zfind/redmonster.py
updated to reflect class name changes in redmonster
=> PEP8 updates

bin/desi_bootcalib.py, doc/nb/Boot_Calibs_firsttry.ipynb, doc/nb/Boot_Calibs_fulltest.ipynb, py/desispec/bootcalib.py
Routines for QA generation.
An example file can be seen here:
https://dl.dropboxusercontent.com/u/6285549/DESI/tst_QA.pdf
=> bootstrap: QA included now

.travis.yml, bin/desi_bootcalib.py, doc/nb/Boot_Calibs_fulltest.ipynb, doc/nb/Bootstrap_tests.ipynb, py/desispec/bootcalib.py, py/desispec/test/test_bootcalib.py
Added a set of unit tests.
These pull two ~6Mb files from NERSC with urllib2
The test is failing on Travis, but I believe that is due to 
a stale desiutils integration.  
Works fine on my laptop.
=> bootstrap: Unit tests

bin/desi_compute_fiberflat.py, bin/desi_compute_sky.py, py/desispec/fiberflat.py, py/desispec/io/qa.py, py/desispec/qa/qa_exposure.py, py/desispec/sky.py, py/desispec/test/test_binscripts.py
QA for fiberflat
similar to QA for sky
failing Travis despite passing on my laptop..
=> QA for fiberflat

bin/desi_bootcalib.py, doc/nb/Boot_Calibs_fulltest.ipynb, py/desispec/bootcalib.py
Addresses Issue#107
Speeds up extraction
No new tests or docs
=> Bootcalib: Scripts and speed

bin/desi_bootcalib.py, py/desispec/bootcalib.py, py/desispec/test/test_bootcalib.py
* faster routine for fiber_gaus (gain of a factor 6), now total desi_bootcalib is 3 min per frame
* legendre degree as option
* some cosmetics for logging
=> Speedup fiber gauss

bin/desi_bootcalib.py, py/desispec/bootcalib.py
Small fix to wrongly defined WAVEMAX
Several modifications to improve robustness of 
wavelength solution in z-camera.
=> Bootcalib: WAVEMAX and z camera

bin/desi_compute_fiberflat.py, bin/desi_compute_fluxcalibration.py, bin/desi_compute_sky.py, doc/tex/qa.tex, etc/cron_dailytest.sh, py/desispec/fluxcalibration.py, py/desispec/frame.py, py/desispec/io/qa.py, py/desispec/qa/__init__.py, py/desispec/qa/qa_exposure.py, py/desispec/qa/qa_plots.py, py/desispec/sky.py, py/desispec/test/test_binscripts.py, py/desispec/test/test_flux_calibration.py, py/desispec/test/test_io.py, py/desispec/test/test_qa.py
QA document
QA for fluxcalib
New QA for Skysub and Fiberflat
Tests 
More to come, but worth a PR now
=> QA:  Advances on several fronts

bin/desi_zfind.py, doc/nb/QA_Brick.ipynb, py/desispec/io/__init__.py, py/desispec/io/qa.py, py/desispec/qa/__init__.py, py/desispec/qa/qa_brick.py, py/desispec/qa/qa_plots.py, py/desispec/test/test_qa.py, py/desispec/zfind/zfind.py
Establishes the architecture for QA on bricks, with
focus on the zbest output.
Integrated in desi_zfind
Includes a few tests and a Notebook 
related to development
=> QA_Brick: Architecture

bin/desi_bootcalib.py, doc/nb/Boot_Calibs_fulltest.ipynb, py/desispec/bootcalib.py
Mainly improvements to wavelength algorithms
Now tested on all frames in calibtest/20160310
=> Bootcalib: Improving robustenss

bin/desi_extract_spectra.py, bin/desi_pipe, bin/desi_pipe_calib, bin/desi_pipe_extract, bin/desi_pipe_psf, bin/desi_plan_calib, bin/desi_plan_extract, bin/desi_plan_psf, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py
This adds more intelligent generation of slurm scripts and the PSF combining step.  This completes the first pass at automation.  Merging this to master prior to tagging and starting on next improvement cycle.
=> Final fixes for v1 pipeline automation

bin/desi_zfind.py, doc/nb/QA_Brick.ipynb, py/desispec/qa/qa_brick.py, py/desispec/zfind/zfind.py
Additional measures on z output in a Brick.
Notebook edits too.
=> QA Brick: More redshift measures

py/desispec/fluxcalibration.py
The PR to fix the part of the calibration error due to a bias reaching 4% in compute_flux_calib (occurring even when the stellar models are perfect).
The bias was introduced by an averaging issue of the smooth fiber correction (correction per fiber to account for instance for fiber aperture loss). See issue #182
=> debias compute_flux_calibration

py/desispec/procalgs.py, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/quicklook.py
This PR adds post-extraction fiberflat and sky subtraction to the QL pipeline, for offline case. Next todo will be to add their QAs....
=> add post-extraction fiberflat and sky subtraction PAs

py/desispec/bootcalib.py
This PR improves the robustness of bootcalib by checking the XCOEFF and YCOEFF values vs. fiber number.  Assuming that the coefficients should vary smoothly with fiber number, it identifies outliers and replaces them with the interpolated value.  The attached plot shows an example from maple z2 where one fiber has a very bad fit but gets fixed.
I also added EXTNAMEs to the FITS headers while I was at it.
Note: bootcalib is doing calculations within its output function `bootcalib.write_psf()`.  Gack.  I didn't try to clean that up; I just added an additional check+fix that the fitted values were reasonable before writing them out.
=> check and fix bootcalib coefficient outliers

doc/nb/QA_Exposure.ipynb, py/desispec/qa/qa_exposure.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qa_prod.py
As titled.
Mainly NB changes to run with modified
code and madrone.
=> Small QA_Exposure edits

py/desispec/fluxcalibration.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_plots.py, py/desispec/scripts/fluxcalibration.py
As titled.
Simple refactoring to eliminate fiber calculations.
Should fix integration test, but I was not successful
on my laptop (other errors appeared).
=> Fluxcalib fixes

bin/desi_qa_skyresid, doc/changes.rst, py/desispec/qa/qa_plots.py, py/desispec/scripts/skysubresid.py
Script to generate plots on skysub residuals
Works on a full production or subesets of nights, exposures, channels
No tests
=> QA SkySub Residual

bin/desi_quicklook, py/desispec/data/quicklook/example-config-r0-00000002.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/procalgs.py, py/desispec/quicklook/quicklook.py
This PR 
- integrates preproc into QL Pipeline
- Adds option to output intermediate files after each pipeline step
- updated example config file and tested, relevant files at NERSC.
=> Quicklook preproc

doc/changes.rst, etc/desispec.module
Updates Module file to DESI+Anaconda infrastructure.
=> update module file

bin/desi_pipe, py/desispec/pipeline/plan.py
Several small fixes.  Tested on 48 core local machine with mpirun.  Will self merge after tests pass.
=> Fixes for running with MPI on non-nersc machines

bin/desi_pipe_status, py/desispec/pipeline/run.py
=> Fix several small pipeline issues

py/desispec/boxcar.py, py/desispec/psf.py, py/desispec/quicklook/procalgs.py
This PR improves Quicklook performance by O(10x)
=> Improve quicklook performance

py/desispec/boxcar.py, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py
This PR is not much update in itself, but fixes few issues before a larger update to QL. This includes
- using ivar directly from image in boxcar
- fix of few issues in QAs
=> Quicklook update

doc/changes.rst, py/desispec/sky.py
This PR fixes a bug in sky subtraction (sky.py) that was causing a crash whenever the final cholesky decomposition succeeded.
=> fixed bug in sky subtraction

py/desispec/parallel.py, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py, py/desispec/pipeline/task.py, py/desispec/scripts/pipe_prod.py, py/desispec/test/test_pipeline_run.py
desi_pipe now generates slurm scripts which use a specified docker image containing the desi software and dependencies.
=> Changes that allow the pipeline to run within a shifter container.

.travis.yml, doc/changes.rst
This PR:
* Closes #309.
* Shifts more tests to Python 3.5.
=> Travis updates

doc/changes.rst, py/desispec/fluxcalibration.py, py/desispec/frame.py, py/desispec/qa/qa_plots.py, py/desispec/test/test_flux_calibration.py, py/desispec/test/test_frame.py, py/desispec/test/test_qa.py, py/desispec/test/util.py
Address Issue #383 raised on boolean index.
Added test for QA frame_flux plot.
Pushed test utilties from test_fluxcalib to util.py in desispec.io
=> QA Warning fix and Test beginnings

doc/changes.rst, py/desispec/brick.py, py/desispec/test/test_brick.py
Added functionality to calculate the area of a brick. I'm messing around with 1o brick-scale fluctuations for target QA, and this seemed like an appropriate place to put the area calculation.
=> ADM brick area

doc/changes.rst, py/desispec/brick.py, py/desispec/test/test_brick.py
I'm writing some brick-based QA code for targets and need the vertices to plot the bricks. After this is merged I'll move brick.py to desiutil to close out https://github.com/desihub/desispec/issues/310
=> Add function to brick.py to calculate the vertices of each brick

doc/changes.rst, py/desispec/fluxcalibration.py, py/desispec/scripts/fluxcalibration.py, py/desispec/scripts/stdstars.py, py/desispec/test/test_binscripts.py
Several minor improvements.
Improvements on calibration illustrated on issue #357 are mostly due to improvements of BOSS wavelength
solution in boss2desi repo. In particular : no more Balmer residuals !
=> Fluxcalib3

py/desispec/qa/qa_quicklook.py
This PR:
- Provides a temporary fix for the xwsigma failure. Further debugging will continue to fully solve this issue.
=> temporary xwsigma fix

py/desispec/frame.py
Minor update to Frame.vet to log errors if vet fails rather than just returning an error code.
=> more logging when Frame.vet fails

.travis.yml
Starting a new PR to debug/test problems with "ImportError: numpy.core.multiarray failed to import" that are impacting multiple PRs #415, #413, #389, and desihub/desitarget#189.  Compared to master, the only change here is to add "conda list" to the travis install commands to get the final set of packages installed to check for inconsistencies and attempt to reproduce the problem outside of Travis.
=> debug Travis numpy.core.multiarray import problem

doc/changes.rst, doc/qa.rst, py/desispec/_version.py, py/desispec/qa/html.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qalib.py, py/desispec/scripts/qa_prod.py
Adds a new metric to QA SkySubtraction (MED_SKY).
Also allows for bright/dark split in production level,
time series QA.
updated docs
=> Offline QA: Bright/dark and MED_SKY metric

py/desispec/pipeline/task.py, py/desispec/scripts/specex.py
This is Julien's pipeline changes to be compatible with recent specex work.  Branch is rebased against current master.  Opening this PR for final testing.
=> Pipeline for new specex

py/desispec/database/datachallenge.py
This PR makes changes to reflect the current data model consistent with the minitest notebook.
=> Minitest database

py/desispec/scripts/trace_shifts.py, py/desispec/trace_shifts.py
Two commits concerning the fit of trace shifts.
=> Trace shifts

bin/desi_zcatalog
Option of redshift catalog to add data from the target table or truth file.
Example
```
desi_zcatalog -i spectro/redux/mini/spectra-64 -o spectro/redux/mini/zcat.fits --match targets/targets.fits  targets/truth.fits 
```
=> add option to join otehr tables such as truth.fits or target.fits

py/desispec/scripts/sky.py, py/desispec/scripts/trace_shifts.py, py/desispec/sky.py, py/desispec/trace_shifts.py
Several minor optimization of the measurement of trace shifts based on an analysis of the test stand data.
=> Trace shifts and sky

.travis.yml, doc/changes.rst, py/desispec/io/meta.py, py/desispec/io/qa.py, py/desispec/qa/html.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_prod.py, py/desispec/scripts/skysubresid.py, py/desispec/test/test_io.py
As titled.
Added a test for 'bad' files in the redux directory.
=> QA Edits for mini Test

.travis.yml, doc/changes.rst, py/desispec/io/__init__.py, py/desispec/io/meta.py, py/desispec/qa/__init__.py, py/desispec/scripts/qa_prod.py, py/desispec/scripts/skysubresid.py
A few additional modifications to QA (mainly paths)
to get QA running in the mini test Notebook.
=> QA edits for mini Notebook

py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/qlconfig.py
STAT-> STATUS, RsidRMS -> RESID are uniformly changed in both qa and quicklook directories. Changes from individual target names to a general target name (TGT) are done in ql_snr branch.
=> Minor edits on metric's names

py/desispec/pipeline/run.py, py/desispec/scripts/pipe.py
Such tasks must be manually cleared.  Also cleanup desi_pipe docstrings.  Closes #535
=> Do not attempt to run failed tasks.  

py/desispec/scripts/pipe.py
=> Do not overwrite existing productions.

py/desispec/scripts/pipe.py
=> spectra and redshift selection on night in desi_pipe task

py/desispec/pipeline/db.py, py/desispec/pipeline/defs.py, py/desispec/pipeline/prod.py, py/desispec/pipeline/run.py, py/desispec/pipeline/scriptgen.py, py/desispec/pipeline/tasks/__init__.py, py/desispec/pipeline/tasks/base.py, py/desispec/pipeline/tasks/fiberflatnight.py, py/desispec/pipeline/tasks/psfnight.py, py/desispec/scripts/night.py, py/desispec/scripts/pipe.py, py/desispec/test/test_scripts.py
Do not merge yet, this needs more testing.  Just opening a PR to track this.  Once merged, this will close #304 and #525 .
=> Initial implementation of nightly script

py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat_preproc.yaml, py/desispec/data/quicklook/qlconfig_greysurvey.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/merger.py, py/desispec/quicklook/qas.py, py/desispec/quicklook/qlconfig.py
This PR addresses following updates as part of QL clean up
- Fix Continuum and Peaks QA params for all program config files
- Manage uniformity for status keys ALARM/ WARN -> NORMAL/WARN 
- Fix the remaining MAGDIFF -> DELTAMAG keys
- Remove redundant arguments for sky continuum QA
@rkehoe @Srheft Please review and suggest if this addresses the items discussed for this PR
=> Ql Clean up 1

bin/desi_zcatalog
Single commit to desi_zcatalog to propagate magnitudes from the fibermaps into the redshift catalog.
=> Add MAG to z catalog with run with --fibermap option

py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/quicklook.py
This PR:
- Updates the SNR fit to include exposure time.
- Updates the conversion of imaging magnitude to flux.
- Includes minor updates for SNR plots.
- Adds imaging magnitudes to SNR output.
- Returns the median of sky fibers over sky peaks for QA Sky_Peaks.
=> Update QL SNR fit

py/desispec/data/quicklook/qlconfig_arcs.yaml, py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_flat_preproc.yaml, py/desispec/data/quicklook/qlconfig_greysurvey.yaml, py/desispec/io/qa.py, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/__init__.py, py/desispec/quicklook/merger.py, py/desispec/quicklook/quicklook.py, py/desispec/scripts/quicklook.py, py/desispec/test/test_ql.py, py/desispec/test/test_ql_qa.py
@rstaten, @rkehoe: hoping for a quick turnaround for merging this today.
=> ticket6+leftovers

py/desispec/pipeline/scriptgen.py
On behalf of Ted, opening this PR to add the realtime queue definitions to desispec.
=> Add realtime queue definitions.

bin/desi_fake_dts, py/desispec/pipeline/scriptgen.py, py/desispec/pipeline/tasks/preproc.py, py/desispec/pipeline/tasks/traceshift.py, py/desispec/scripts/night.py
Modifications to support different maxnodes and queue for big/small and redshift jobs when running nightly scripts.
=> More tweaks for realtime queue

bin/desi_fake_dts, py/desispec/pipeline/db.py
Fix nightly break timing in fake DTS.  Change DB print statements to use log.debug() for dumping out the SQL statements that are being executed.
=> Small cleanups to fake DTS and print statements

py/desispec/data/quicklook/qlconfig_arcs.yaml, py/desispec/data/quicklook/qlconfig_bias.yaml, py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darkcurrent.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_flat_preproc.yaml, py/desispec/data/quicklook/qlconfig_greysurvey.yaml, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/qlconfig.py, py/desispec/test/test_ql.py, py/desispec/test/test_ql_qa.py
This PR:
- Updates xwsigma scalar metric.
- Adds night for reference template.
- Uses merged json file instead of yaml.
@Srheft, @rkehoe Please review and make sure this satisfies requirements from the data meeting.
=> Data discussion updates

py/desispec/pipeline/tasks/traceshift.py, py/desispec/scripts/trace_shifts.py, py/desispec/trace_shifts.py
New PR for the trace shift acceleration (from 3min 30s to 20s, using numba).
Added trace shifts values in header of shifted PSF for the quicklook pipeline.
More details in issue #622.
=> faster trace shifts

py/desispec/test/integration_test.py, py/desispec/test/old_integration_test.py
This PR makes minor API/syntax/packagename updates to both the old and new integration tests, both of which were broken.
=> fixes integration tests

py/desispec/io/__init__.py, py/desispec/pipeline/db.py, py/desispec/pipeline/tasks/qadata.py, py/desispec/pipeline/tasks/qaframe.py, py/desispec/scripts/pipe.py
Primarily a new QADataTask in the tasks framework
of desi_pipe.
Tested on NERSC by JXP and Julien.
Gets the ball rolling for re-integrating QA within the main pipeline.
=> QA Data Task

bin/desi_compute_bias, bin/desi_compute_crosstalk, bin/desi_compute_dark, bin/desi_compute_mask, bin/desi_compute_pixel_flatfield, doc/changes.rst, py/desispec/bootcalib.py, py/desispec/io/fiberflat.py, py/desispec/io/fluxcalibration.py, py/desispec/io/frame.py, py/desispec/io/image.py, py/desispec/io/sky.py, py/desispec/io/spectra.py, py/desispec/quicklook/arcprocess.py, py/desispec/scripts/extract.py, py/desispec/scripts/specex.py, py/desispec/trace_shifts.py
=> Clobber to overwrite

py/desispec/scripts/extract.py, py/desispec/scripts/fiberflat.py, py/desispec/scripts/sky.py, py/desispec/scripts/stdstars.py, py/desispec/trace_shifts.py
A few minor commits to be able to run DESI pipeline on BOSS data (and it works!!).
(shorter arguments, debugged help message, and adapt extraction to the fact spectro # starts at 1 in BOSS)
=> BOSS with DESI

doc/changes.rst, py/desispec/io/fluxcalibration.py, py/desispec/io/spectra.py, py/desispec/pixgroup.py, py/desispec/scripts/extract.py, py/desispec/scripts/procexp.py, py/desispec/scripts/quicklook.py, py/desispec/test/test_extract.py
This PR closes #665.  I'd like to get an answer to #672 before merging though.
=> Make sure units are FITS-compliant

py/desispec/data/quicklook/qlconfig_arc.yaml, py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_graysurvey.yaml, py/desispec/data/quicklook/qlconfig_science.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/__init__.py, py/desispec/quicklook/merger.py, py/desispec/quicklook/procalgs.py, py/desispec/quicklook/qas.py, py/desispec/quicklook/qlconfig.py, py/desispec/quicklook/quicklook.py
=> Revert "QL config update and fibermap conform"

py/desispec/data/quicklook/qlconfig_arc.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_science.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/qas.py, py/desispec/scripts/quicklook.py
This PR has two small updates:
- for SNR, when we have 4 targets and one does not fit, we ignore that as not indicative on its own of data quality.  So the STATUS is taken as the worst case of the remaining N-1 target types.
- the specifications on all metrics were also updated by @rstaten after further study of distributions.
=> Ql updates

bin/desi_dts.sh, doc/changes.rst
This PR close #730 by incorporating a daily HPSS backup directly into the `desi_dts.sh` transfer script.
Please hold off on merging, I'd like to see this in operation for a few more days.
=> Add daily HPSS backup

py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/__init__.py, py/desispec/quicklook/merger.py, py/desispec/quicklook/quicklook.py
This PR improves the fit of SNR vs. fiber magnitude by increasing the granularity of the ‘a’ parameter in the fit from 0.01 to 0.0001.  This improves the fit itself, and also facilitates convergence on extreme cases where fits might fail.
Thanks @rrstaten for this update!
=> Ql SNR Fit

doc/changes.rst, py/desispec/database/redshift.py
This fixes problems with database loading reported in desihub/tutorials#22.  This PR should be merged into master *before* merging desihub/tutorials#24.
=> Fix problems with fiberassign loading

doc/api.rst, py/desispec/calibfinder.py, py/desispec/io/params.py, py/desispec/io/xytraceset.py, py/desispec/qproc/qextract.py, py/desispec/qproc/qframe.py, py/desispec/quicklook/qlresolution.py, py/desispec/scripts/average_fiberflat.py, py/desispec/scripts/trace_shifts.py, py/desispec/specscore.py, py/desispec/spectra.py, py/desispec/trace_shifts.py, py/desispec/xytraceset.py
While working on something else, I noticed that the doc/api.rst file had not been updated in quite a long time, and as a result, many docstrings had never been tested.  There are no changes to code, but some docstrings had to be substantially modified.
=> Update API documentation

bin/desi_compute_psf_gradients, py/desispec/cosmics.py, py/desispec/scripts/preproc.py
- new gradient parameters from average of SP2 PSF
- new default value =0.5 for the parameter "c2fudge" which encodes the gradient threshold in units of the PSF gradient.
See issue #762 for more information.
=> Improve cosmics

bin/desi_header, py/desispec/calibfinder.py, py/desispec/io/meta.py, py/desispec/qproc/flavor.py, py/desispec/scripts/qproc.py
Opening the PR on behalf of @julienguy .  It includes some small bug fixes for qproc, and added "flavor guessing" which is useful for QA of teststand data where anything with the shutter open is called FLAVOR="science" even if the calibration lamps are on.
=> qproc updates

bin/desi_compute_dark, py/desispec/qproc/flavor.py, py/desispec/qproc/qsky.py, py/desispec/scripts/qproc.py
Modified desi_qproc to use the new OBSTYPE keyword instead of FLAVOR used by ICS.
=> Use OBSTYPE in desi_qproc

bin/desi_proc, py/desispec/frame.py
This PR fixes #840 where desi_proc was double applying the fiberflat.  Tested @ KPNO.
=> Fixes double application of fiberflat

bin/desi_proc, py/desispec/fiberflat.py
```
--nofiberflat         Do not apply fiberflat
--noskysub            Do not subtract the sky
--psf PSF             use this input psf (trace shifts will still be computed)
--fiberflat FIBERFLAT use this fiberflat
```
=> Adding a few options to desi_proc

py/desispec/calibfinder.py, py/desispec/io/raw.py
All is in the title.
spectro calib SVN repo has also been updated.
=> Adapt to SMX naming

bin/desi_proc
Add --calibnight option to desi_proc
=> add --calibnight option

bin/desi_fit_scattered_light_kernel, py/desispec/scatteredlight.py
add code to fit for the shape of the scattered light convolution kernel per camera.
kernel shapes are for the moment saved in the routine scatteredlight.py
=> fit a scattered light kernel

py/desispec/fluxcalibration.py, py/desispec/scripts/fluxcalibration.py
Fix indexation BUG in the standard stars spectra when computing the flux calibration vectors (sorted according to their S/N in desi_fit_stdstars while assumed sorted with increasing fiber number in desi_compute_fluxcalibration). This bug has been introduced recently.
=> Bug fix in flux calibration

bin/desi_dailyproc, bin/desi_proc
Can now specify what cameras to process and whether to do scattered light corrections or not at the level of desi_dailyproc. The options are passed down to desi_proc.
=> Dailyproc setcams

bin/desi_proc, py/desispec/heliocentric.py, py/desispec/scripts/extract.py
Barycentric velocity correction in desi_proc
=> add barycentric correction

bin/desi_offset_fiber_traces, bin/plot_fiber_traces, bin/plot_frame
Add scripts used to debug and fix trace shifts in PSF files. Used to fix issue #891 .
* desi_offset_fiber_traces
* plot_fiber_traces
* plot_frame
=> Traceshift

py/desispec/scripts/coadd_spectra.py
Added logic to coadd_spectra that removes incomplete exposure triplets of b,r,z.
Loops through nights, exposures, spectrograph number, and cameras. Makes sure for a given night+exposure+spectrograph all three cameras are there. Otherwise it removes the one or two cameras so that all exposures have complete three-camera coadds and the code further down the line doesn't fail.
I fixed all instances if this circumstance in the data, but tested it by manually removing a cframe from the input list and the code correctly identifies the lack of a camera and removes the additional two so that all exposures that proceed are complete.
=> coadd_spectra removes incomplete exposure triplets of b,r,z

py/desispec/scripts/extract.py
Addressed issue #941 .  Also goes ahead and refactors extract.py to remove repeated code.
Tested using different numbers of tasks and cpus-per-task ( `srun ... -n  -c` ).
Tested with night 20200314, exposure 55445. 
Barycentric correction is applied appropriately now. Below I show examples in cam=z1.
Normal `-n 20 -c 2`:
Using `-n 2 -c 32`:
No mpi:
The two mpi versions have bitwise-identical data.
The non-mpi version does differ to a minor extent, I believe this is due to the precision loss in the read/write operations in the mpi version which writes temp files before consolidation.
Below I show the sum of all differences in a given HDU (over all values in the HDU.data). 
> **b1**
> FLUX    -0.012568751
> IVAR    9.1393304e-08
> RESOLUTION     2.3883758e-05
> CHI2PIX    0.0015733168
> 
> …
=> Fixed bary_corr issue in and refactor of extract.py to remove repeated code

bin/desi_compute_mask_dark, py/desispec/maskbits.py
The following changes were made:
- The name of one of the ccd mask bit has been changed (saturated->highvar) 
- A script to generate pix masks from darks had been added to /bin
@julienguy
=> Scripts for creating pixmasks

.travis.yml, doc/conf.py, py/desispec/io/__init__.py, py/desispec/io/download.py, py/desispec/io/meta.py, py/desispec/test/test_io.py
Creating a PR to make it easier to track this work.  Do not merge yet.
To Do
=> [WIP] Update desispec.io.download for data.desi.lbl.gov

bin/desi_compute_mask_dark
This pull request updates the following:
- Updates the code to be compatible with recent modifications to the desispec preproc API
- Makes the number of binary closing iterations as a user given input rather than a hard coded value.
=> Update CCD mask generating code

py/desispec/preproc.py
Bug fix issue #1001 .
It looked bad but it had a very minor effect because the dark current is low.
=> subtract dark after applying gain and take into account dark poisson noise

py/desispec/qproc/qextract.py
Nightwatch is unable to handle images with !=500 fibers and this branch issues specific warnings about that.
=> Nightwatch issue162 warning

py/desispec/scripts/stdstars.py
Use extinction_total_to_selective_ratio func to get extinction from EBV for the fit of standard stars.
=> use extinction_total_to_selective_ratio func to get extinction from EBV

py/desispec/fluxcalibration.py
This is a hack to work around a problem on 20201214 where the SV1_DESI_TARGET bits were zeroed out in the fiberassign files, but the FA_TYPE bits were still ok for determining what was a standard star.  I'm running this via a PR for a post-facto review but want to merge and run tonight before NERSC is out.  If people think this hack is just way too hacky we can undo it.
=> fallback to using FA_TYPE if no stdstars in (SVn_)DESI_TARGET

py/desispec/fluxcalibration.py
The PR cures an issue we had on the edges of the flux calibration vectors. The flux calibration fit  which comprises convolutions of the model with the resolution matrix is now performed on a data frame with margins along wavelength, and then trimmed back to the original size. The following figure shows in orange the old fluxcalib vector and in blue the new ones, without the unphysical spikes on the edges.
=> Fix unphysical spikes on the edges of the flux calibration vectors

py/desispec/scripts/fluxcalibration.py
This PR in response to issue #1066.
The flux calibration selection of stars is now more verbose.
Example for `frame-r6-00068675.fits`
```
INFO:fluxcalibration.py:95:main: compute flux calibration
INFO:fluxcalibration.py:111:main: apply cut |delta color|<0.1
INFO:fluxcalibration.py:117:main:  discard 1 stars with dcolor= [0.19936935785406895]
ERROR:fluxcalibration.py:142:main: selection cuts discarded all stars
```
The delta color test is based on the color of the best fit stellar model. Here a delta color of 0.2 indicates a pretty bad fit.
The color difference can be larger than the initial color selection range because the standard star fitting code includes more stellar parameter grid nodes than given by the script color selection cut in order to have a well behaved input grid geometry …
=> Print out messages explaining star selection

py/desispec/trace_shifts.py
Minor bug fix when a fiber is fully masked because of a dead column.
=> Fix trace shifts

py/desispec/coaddition.py, py/desispec/io/fibermap.py, py/desispec/test/test_coadd.py
and COADD_EXPTIME to coadded fibermap
add EXPTIME column to fibermap of single exposures
=> EXPTIME and COADD_EXPTIME in fibermap 

py/desispec/fluxcalibration.py
Add new Gaia standards for the flux calibration ( see https://github.com/desihub/fiberassign/issues/304 )
=> add a new gaia standards

.github/workflows/python-package.yml
=> Add token to coverage test

py/desispec/pixgroup.py
This PR adds support for coadding input frames that have heterogeneous fibermaps, e.g. Dec2020 vs. Jan2021 data, which added the EXPTIME column.  It now logs a warning and passes forward only the submit of columns found in all fibermaps.  There will be pathological cases where the output coadd won't be particularly useful (e.g. if an input is missing TARGETID), but this at least handles the 3 failing cases listed below originally from @Cyeche and @araichoor.  Detail: EXPTIME was added to enable COADD_EXPTIME, but the code already gracefully handled the case of missing EXPTIME.
I plan to merge this quickly so that @Cyeche et al can use it for tile 80605 mixing Blanc (Dec 2020) and daily (Jan/Feb 2021) exposures while waiting for Cascades.  At the same time, post-facto commentary is welcome …
=> support coaddition of heterogeneous fibermaps

py/desispec/scripts/stdstars.py, py/desispec/test/test_binscripts.py
Fix of stdstars to support PHOTSYS='G' (see #1132 )
=> Photsys fix

py/desispec/coaddition.py
=> Check number of good and bad pixels before trying interpolation

py/desispec/tsnr.py
=> Dust transmission inclusion.

bin/desi_tsnr_afterburner
Minor bug fix in desi_tsnr_afterburner
=> fix bug with duplicated entries in tsnr_summary

py/desispec/desi_proc_dashboard.py
Transferred from PR1173. There might some problems with the version in PR#1173 that the newest revision was not correctly updated. Start a new PR to ensure everything is correct.
=> New desi_proc_dashboard.py transfered from  PR1173

py/desispec/desi_proc_dashboard.py
Save night_info to json files for each night. If the exposure is GOOD, use the archive result instead of scanning again.
=> Save night_info to json files for each night

bin/desi_tsnr_afterburner, py/desispec/tilecompleteness.py
* FAPRGM instead of FAFLAVOR, ZDONE=false/true instead of ZSTATUS
* new ordering of columns and rows
* check for zbest and coadd file and sets ZDONE=true if a least 8 petals.
```
tsnr-exposures.csv
NIGHT,EXPID,TILEID,SURVEY,FAPRGM,EXPTIME,EFFTIME_SPEC,GOALTIME,GOALTYPE,MINTFRAC,SEEING_ETC,EFFTIME_ETC,TSNR2_ELG,TSNR2_QSO,TSNR2_LRG,TSNR2_LYA,TSNR2_BGS,ELG_EFFTIME_DARK,BGS_EFFTIME_BRIGHT,LYA_EFFTIME_DARK
...
20210324,81857,81062,sv2,bright,835.3,45.5,150.0,bright,0.9,1.8,32.7,5.3,1.2,3.0,2.9,259.1,45.5,36.3,26.1
20210324,81859,81062,sv2,bright,835.3,70.5,150.0,bright,0.9,0.0,0.0,8.2,1.9,4.7,5.2,419.6,70.5,58.7,47.3
20210324,81860,81060,sv2,bright,1064.7,218.8,150.0,bright,0.9,0.0,0.0,25.4,5.6,14.4,13.8,1253.3,218.8,175.5,125.4
20210324,81861,81060,sv2,bright,1064.7,203.7,150.0,bright,0.9,0.0, …
```
=> More modifications to the exposurs and tile completeness table

py/desispec/tilecompleteness.py
This PR adds a LASTNIGHT column to the tile completeness table (e.g. daily/tiles.csv), containing the last YEARMMDD on which each tile was observed to simplify looking up `tiles/cumulative/TILEID/YEARMMDD/*-thruYEARMMDD.*`
@julienguy
=> add LASTNIGHT column to tile completeness table

bin/desi_proc, bin/desi_proc_joint_fit, bin/desi_run_night, bin/desi_tile_redshifts, py/desispec/data/batch_config.yaml, py/desispec/scripts/submit_night.py, py/desispec/workflow/batch.py, py/desispec/workflow/desi_proc_funcs.py, py/desispec/workflow/procfuncs.py
This PR replaces #1215, adding `--system-name` support for `desi_run_night` and `desi_tile_redshifts`, and resolving merge conflicts due to PR #1217 (thus the new PR with a newly rebased "knl2" branch).
@akremin please review.
=> workflow hooks for KNL

doc/changes.rst, doc/conf.py, setup.py
This PR adds data files to the installation config since these were incorrectly not being installed.
=> fix files missing from data installation

bin/desi_tsnr_afterburner, py/desispec/tilecompleteness.py
- Fix one bug when chosing the dark or bright version of EFFTIME_SPEC.
- Improve the printed messages when running the scripts, showing the number of unchanged,modified and added tiles.
Current comparison between EFFTIME_ETC and EFFTIME_SPEC is not great. I am going to add the EFFTIME_DARK,... computed with GFA data + offline pipeline sky mag as a cross-check.
=> Exposures and tiles summary files

py/desispec/skymag.py
PR with minor correction to the sky spectrum wavelength range per camera.
(used to compute sky mags)
=> Improved stitching of sky spectra from different cameras

bin/desi_tsnr_afterburner, py/desispec/io/meta.py
Retrieve etc efftime from json if ACTTEFF not in frame headers (as true of early main survey data). 
Aside: do not add missing prod exposures if args.expids is not None.
=> Retrieve etc efftime from json

py/desispec/qproc/qfiberflat.py
This PR fixes #1191 and re-reported #1299, where the z5 CCD pixel mask completely masked fiber 2664 (index 164 on that CCD) resulting in qfiberflat failing in interpolating and spline fitting 0 good wavelengths.  This only impacted qproc (used by nightwatch); the offline pipeline was already robust to this case.
The failing qproc command in #1191 now completes with
```
desi_qproc -i /global/cfs/cdirs/desi/spectro/data/20210318/00080924/desi-00080924.fits.fz --fibermap /global/cfs/cdirs/desi/spectro/data/20210318/00080924/fibermap-00080924.fits --auto --auto-output-dir $p/desi/users/sjbailey/temp --cam z5
...
INFO:qfiberflat.py:49:qproc_compute_fiberflat: Starting...
WARNING:qfiberflat.py:98:qproc_compute_fiberflat: All wavelengths of fiber 164 are masked; setting fflat=1 fivar=0 …
```
=> check for completely masked fibers in qfiberflat

py/desispec/pixgroup.py, py/desispec/test/test_pixgroup.py, py/desispec/test/test_spectra.py
One liner fix to #1324.
@sybenzvi wants to add a unit test for the SpectraLite class before merging.
=> fix for self.extra_catalog undefined for SpectraLite object in pixgrouping

bin/desi_qso_catalog_maker
This PR fixes the desi_qso_catalog_maker from PR #1322 after it was broken by PRs #1330 and #1338.  I will request some additional format changes, but this at least gets it back to running.
=> fix qso_catalog_maker after zbest/redrock changes

py/desispec/scripts/tile_redshifts.py
This PR into the "everest" branch fixes `desi_tile_redshifts --group cumulative` which was broken by PR #1350 which refactored redshift jobs to support healpix-based redshifts.  This PR was tested while cleaning up bad exposure 20210203/74464/z0 reported in #1351 which required re-running all flavors of redshifts (perexp, pernight, cumulative, and healpix).
=> bug fixes for desi_tile_redshifts --group cumulative

doc/changes.rst, py/desispec/sky.py
Detect sky fibers with contamination for star or galaxy and mask them.
=> Bad sky fibers

py/desispec/coaddition.py, py/desispec/test/test_coadd.py
Effort to address issue #1365 by reducing and speeding up comparisons of the camera wavelength grids in `coadd_cameras`.
=> Speed up coadd_cameras

py/desispec/preproc.py
Add the Poisson noise from the zero exposure dark current in the read noise.
A good estimate of this Poisson noise variance is the master bias value (which had the electronic pedestal subtracted), after multiplication by the gain (to convert ADUs to electrons).
This correction increases the read noise std deviation by 10% for the blue cameras. It explains the variation of the measured read noise rms with the CCD row or column.
The average ratio of the noise measured in the active region of the CCDs to its estimate based on the overscan columns and the master bias and darks is now of 0.994,0.985,0.985 in BLUE,RED
and NIR CCDs respectively. 
See https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=6431.
=> Add the Poisson noise from the zero exposure dark current (=bias value)

py/desispec/exposure_qa.py, py/desispec/fluxcalibration.py, py/desispec/io/fluxcalibration.py
PR to save the information about the final set of std stars used for the calibration of a frame in the fluxcalib file.
The fibermap info for the standard stars participating to the fit is saved in HDU STDSTAR_FIBERMAP.
This information is used in the exposure_qa to verify the calibration of stars if it exists (i.e. the qa is backward compatible).
=> Stdstars in fluxcalib

py/desispec/tilecompleteness.py
- add missing columns before trying to merge tables
- ignore changes to columns ZDONE,QA,USER,OVERRIDE (because set by other code)
- ignore changes of GOALTIME for survey!='main'
- ignore changes from known values to 'unknown' for columns SURVEY and GOALTYPE
=> Other changes to desi_tiles_completeness

bin/desi_qso_mgii_afterburner, bin/desi_qso_qn_afterburner
Hi @sbailey, 
I create minimal file when there are no targets selected by the afterburner. 
This blanck file is here to track the possible problem during the processing of a tile and to avoid an error when the file is not here.
Edmond
=> add blanck file when no targets to write

py/desispec/sky.py
Minor change to sky subtraction: raise exception when no valid sky fibers.
(I am promoting this as a PR for the record because it addresses issue #1485  ).
=> raise exception when no valid sky fibers

py/desispec/tile_qa_plot.py
=> no n(z) comparison for backup program

py/desispec/workflow/desi_proc_funcs.py
Ensures at least 3.2 GB of memory is available per process on batch jobs for arc fits produced using `desi_proc ... --batch ...` to avoid `OOM` errors on KNL nodes that have been occurring in updated environments using MKL for BLAS in specex.
There is no change for 
```
desi_proc ... --batch --system-name cori-haswell
```
i.e. the launch command for arc fits on Haswell nodes remains
```
srun -N 10 -n 301 -c 2 ... 
```
For KNL nodes, however, the launch command changes from
```
srun -N 9 -n 301 -c 8 ...
```
to
```
srun -N 10 -n 301 -c 9 ...
```
This results in a slight decrease in wall-clock time of the PSF fit for `expid=106943`, from 660 to 600 sec, that cancels the effect of adding a node, so it is expected that the average cost in NERSC-hours for arc fits on KNL is not affected …
=> Revise size of KNL batch jobs for arc fits

py/desispec/preproc.py
Subtract the mean of the overscan cols to the overscan rows (instead of using the overscan pixels of reach overscan row).
This allows us to fix the bias offset in r4-B due to contamination of the overscan columns by the leftover charges from the active pixels cause by the charge trap.
One can see the exponential tail in the overscan region in the following raw image:
Test this PR at NERSC with `export DESI_SPECTRO_CALIB=/global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib`.
because I  add to `sm1/sm1-r.yaml` for the corresponding config.
```
USE_ORSEC: true
```
Profile in vertical band to the right (after fiber 499) of the active region of the r4 CCD for exposure 116770 (LED 1s exposure).
before this modification (step of ~-1elec):
after (residual positive step of ~0.25 elec):
=> remove average of overscan cols to overscan rows

py/desispec/tile_qa.py
Include in QAFIBERSTATUS  bitwise_and(FIBERSTATUS of exposures).
This allows us to propagate the FIBERSTATUS bits added during the processing, in particular the BADAMPB,BADAMPR,BADAMPZ bits.
=> Add information to QAFIBERSTATUS

py/desispec/tile_qa_plot.py
This PR adds a small correction to the `get_tilecov()` function introduced in PR https://github.com/desihub/desispec/pull/1613.
It now relies solely on `exposures-daily.fits` to obtain what has been observed (restricting to EFFTIME_SPEC > 0 exposures), instead of using a combination of `tiles-SURVEY.ecsv` and `tiles-specstatus.ecsv`.
This reduces the dependencies; in particular, to consider previous night observations in the counting, it just requires for the 10am pacific update of `exposures-daily.fits`, and not anymore for the dailyops updates of the `tiles-SURVEY.ecsv` and `tiles-specstatus.ecsv` files.
It should also more correctly cases where an overlapping tiles has been observed in several nights (e.g. NIGHT_A and NIGHT_B), and the function is called with `lastnight=night`, where …
=> Tile qa plot: get_tilecov() v2

py/desispec/night_qa.py
This PR discards main tiles with EFFTIME < MINTFRAC * GOALTIME in the `petalnz-NIGHT.pdf` plots.
The reason is because those not-finished-yet tiles artificially worsen the statistics (and should not be considered anyway).
Example for NIGHT=20211222, before this PR:
And with this PR, where 3 dark tiles are discarded:
```
INFO:night_qa.py:840:create_petalnz_pdf: discarding main survey TILEID=2576, as EFFTIME=316.1 < MINTFRAC*GOALTIME=0.85*1000=850.0
INFO:night_qa.py:840:create_petalnz_pdf: discarding main survey TILEID=6744, as EFFTIME=631.7 < MINTFRAC*GOALTIME=0.85*1000=850.0
INFO:night_qa.py:840:create_petalnz_pdf: discarding main survey TILEID=7454, as EFFTIME=817.3 < MINTFRAC*GOALTIME=0.85*1000=850.0
```
=> Nightqa: discard main tiles with EFFTIME<MINTFRAC*GOALTIME

py/desispec/ccdcalib.py, py/desispec/scripts/nightly_bias.py
Trivial PR: default min number of bias lowered to 15 instead of 20.
Related to issue #1661 .
=> default min number of bias lowered to 15

py/desispec/fiberbitmasking.py, py/desispec/fiberflat_vs_humidity.py, py/desispec/night_qa.py
Specmask badfiber PR rebased to fuji.
(I had to do a manual edit of a patch file)
I am going to run 1 exposure with this to check it's ok.
=> specmask badfiber rebased to fuji

.github/workflows/python-package.yml
I think this will fix desispec doctests on GitHub, using the fix that @weaverba137 applied to desihub/redrock#210 .
=> fix doctests I hope

py/desispec/preproc.py
Change recipe for routine `preproc.find_overscan_cosmic_trails` :
* wider inspected active region
* max instead of sum per row
* also require outlier in overscan col
This recipe was tuned to fix all cases described in issue #1619 since it was reopened, see details there.
=> Change recipe for find_overscan_cosmic_trails

py/desispec/workflow/desi_proc_funcs.py, py/desispec/workflow/procfuncs.py
This PR fixes #1739 by trying desi_daily_proc_manager sbatch 3 times before giving up, and by printing the stdout/stderr message when it does fail.
I'll test this branch with tonight's processing to make sure I at least didn't make things worse (e.g. by introducing a typo).  Full validation of whether it helps will take more time since recently we've been getting an sbatch failure about once per week.
=> daily proc retry sbatch before giving up

py/desispec/scripts/proc.py
@akremin this PR fixes #1849 where desi_proc biasnight step was incorrectly reporting an error if it determined that the default bias was better than the nightly bias (bug introduced by me in PR #1844 while doing other biasnight cleanup).
I tested this in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/biasnight where I trimmed 20220910 down to just the zeros and dark and then ran `desi_run_night -n 20220910`.  The ccdcalib step ran and reported success even though r9 and z9 are using the default bias.
Caveat 1: I have not tested the case where both biasnight and biasnighttest are missing, indicating a genuine error, because I don't know if any cases where both actually are missing.  Please double check my logic for what would happen in that case, and if you are concerned we could …
=> biasnight not a failure if default bias is better anyway

py/desispec/scripts/proc_tilenight.py
This PR is a small usability update to desi_proc_tilenight for the case where there are no good exposures on that tilenight.  Previously it would skip all preproc steps (no good exposures...) and then create a malformed call to desi_proc_joint_fit (no good exposures...) and crash.  Now it just exits early with an informative error message.
It also reads the exposure table on just rank 0 and broadcasts it to reduce I/O load and log chatter.
I added this code while trying to figure out why desi_proc_tilenight was crashing until I realized I had asked for a bad tile in my randomly selected debug case, but by then I had some code to submit for this PR.
=> tilenight exit early if no good exposures

py/desispec/scripts/proc_joint_fit.py
This PR avoids a crash-inducing MPI race condition in making the calibnight output directory, which happened for himalayas 20211128.  I tested this branch by resubmitting that job with this branch (successfully).  I intend to self-merge as soon as tests pass so that I can go back to using main for the rest of processing that night.
=> avoid makedirs race condition

bin/desi_job_graph
This is a rebased PR replacement for PR #1909 to reduce the size of jobgraph mermaid diagrams.
=> relative log links for smaller mermaid diagrams

py/desispec/night_qa.py
This PR adds in the nightqa ctedet plot the range of columns with known offsets (for each amplifier).
So that we stop bugging @julienguy with known issues..
This parses the `$DESI_SPECTRO_CALIB/spec/sm*/sm*-?.yaml` files through the `desispec.calibfinder.CalibFinder()` function.
Thanks to @julienguy for the guidelines!
Examples for 20221215:
The color scheme follows what s displays (ie AMPA and AMPB in orange, AMPC and AMPD in blue).
Hopefully, it should work for all cases (in addition to 20221215, I ve tested it on 20210708, where AMPA and AMPD have some known columns offsets).
From a code-implementation point-of-view, I ve added a dictionary as a default value for the new argument `yoffcols={"A" : -2.5, "B" : -3.5, "C" : -2.5, "D" : -3.5}`; I don t know if this is a bad habit; if so, I …
=> create_ctdet_pdf(): display the known offsets

py/desispec/preproc.py
This is a duplicate of the change that was made to main for #1927. This change also needs to be made for daily. See comments there for more details.
=> NaN fix for negative CCD bkg (daily)

py/desispec/night_qa.py
This PR is (hopefully) a small upgrade of https://github.com/desihub/desispec/pull/1926.
In the night_qa sframesky plots, the `IVAR=0` pixels are now displayed as before, but with a transparent overlay.
I struggled a bit with how to do that, probably because of my lack of familiarity with the `ax.imshow()` routine...
Example before this PR (where the `IVAR=0` pixels are just displayed in yellow, with no indication of the `FLUX` values):
and with this PR:
I had hard times to decide the transparency scale, i.e. what is the right balance between seeing the `FLUX` values and seeing if it has `IVAR=0`.
And I picked the "green" color.
All that can be changed of course; @schlafly : any suggestion is welcome!
=> Night qa : create_sframesky_pdf(): transparency for IVAR=0 pixels

py/desispec/validredshifts.py
This PR adds a script that assesses the redshift quality (and performs quasar classification) using the criteria described in the DESI target selection papers. @julienguy first suggested creating this script, and @araichoor @echaussidon and @ashleyjross helped validated the script.
=> Assess the redshift quality of DESI galaxies and quasars

py/desispec/coaddition.py
Minor modification to be able to coadd pectra files with COADD_FIBERMAP instead of FIBERMAP.
Test case :
```
desi_coadd_spectra -i /global/cfs/cdirs/desi/science/lya/y1-kp6/iron/catalogs/dla-0/tmp/dla_coadd_491.fits --coadd-cameras -o coadd-cam-491.fits
desi_coadd_spectra -i coadd-cam-491.fits --log10-step 0.0001 --wave-min 3600 --wave-max 9800 -o coadd-loglam-491.fits --fast --nsig 0
```
=> Changes to coadd spectra files with COADD_FIBERMAP instead of FIBERMAP

bin/desi_daily_proc_manager, py/desispec/scripts/daily_processing.py, py/desispec/scripts/proc_tilenight.py, py/desispec/scripts/submit_night.py, py/desispec/workflow/procfuncs.py
Implements #1908 with modifications of `daily_processing.py` that are nearly identical to those of `submit_tilenight.py` in #1802. 
@sbailey please review, thanks.
=> add tilenight support to desi_daily_proc_manager

py/desispec/io/photo.py
This PR addresses an issue discussed off-list but which affects the EDR/Fuji database and the lsdr9-photometry VAC. Briefly, it has to do with the bricks which were patched in DR9 which led to some SV targets having `RELEASE=9010` before the impacted bricks were patched and `RELEASE=9012` afterwards.
Here's one example with the current code (note the RA,Dec discrepancy, in particular):
```
import os
import fitsio
from desispec.io.photo import gather_tractorphot
tt = Table(fitsio.read('/global/cfs/cdirs/desi/public/edr/vac/edr/lsdr9-photometry/fuji/v2.0/observed-targets/targetphot-sv1-fuji.fits'))
print(tt[tt['TARGETID'] == 39628509856928374]['TARGETID', 'RA', 'DEC', 'BRICK_OBJID', 'BRICKNAME', 'RELEASE', 'BRICKID', 'SURVEY', 'PROGRAM', …
```
=> handle the release 9010 vs 9012 bug

py/desispec/io/photo.py
Fixes #2061.
@sbailey I'm testing to make sure there's no unintended impacts on the lsdr9-photometry VAC, so please hold off on merging.
=> handle non-unique bricknames when patching release 9010 tractor photometry

py/desispec/coaddition.py, py/desispec/test/test_coadd.py
This PR adds the following five columns to the output coadded fibermap :
- `FIRSTNIGHT, LASTNIGHT` as int32
- `MIN_MJD, MEAN_MJD, MAX_MJD` as float64
Example test code for a case that has a different value of MEAN_MJD from all exposures vs. the subset of "good_coadds" exposures:
```
from desispec import coaddition
survey = 'sv1'
program = 'bright'
healpix = 22960
hpxgrp = healpix//100
test_id = 39627798029009428
path = f"/global/cfs/cdirs/desi/spectro/redux/fuji/healpix/{survey}/{program}/{hpxgrp}/{healpix}/"
specfile = path+f"spectra-{survey}-{program}-{healpix}.fits"
coaddfile = path+f"coadd-{survey}-{program}-{healpix}.fits"
fibermap_input = Table.read(specfile, hdu=1)
tfmap, exp_fibermap = coaddition.coadd_fibermap(fibermap_input) …
```
=> add NIGHT and MJD columns

bin/desi_compute_fiberflat_vs_humidity
Minor PR: Add first night option to desi_compute_fiberflat_vs_humidity
=> Add first night option to desi_compute_fiberflat_vs_humidity

bin/desi_compute_gain
New exptime keyword and allow small differences in exposure time when pairing exposures.
=> Minor changes to desi_compute_gains

py/desispec/preproc.py
This PR fixes desihub/desisurveyops#164, when combined with a $DESI_SPECTRO_CALIB/ccd/ccd-region-mask.csv entry (NIGHT,EXPID,CAMERA,XMIN,XMAX,YMIN,YMAX,COMMENT) to mask 4 rows impacted bit a large cosmic tail on night 20231208 exp 208688 camera b6:
```
20231208,208688,b6,2048,4096,3928,3932,'tail from cosmic impacts overscan OSTEP; see https://github.com/desihub/desisurveyops/issues/164'
```
The code change is to interpolate the overscan region for rows that are entirely masked in the active region; previously the cosmic tail leaking into the overscan region resulted in an OSTEP trigger and masking the entire amp.
Original daily mask (left), new mask from this PR (right):
Data file in /pscratch/sd/s/sjbailey/desi/dev/ostep_mask/preproc-b6-00208688.fits, to be compared with …
=> preproc interpolate overscan if active region entirely masked

py/desispec/scripts/zcatalog.py
`desi_zcatalog --minimal ...` includes only a minimal set of fibermap columns in the stacked redshift catalogs instead of all 100+ columns.  It turns out the current default set is so minimal that it doesn't even in include the columns needed to determine unique spectra and trace back to their parent coadd/spectra files.  This PR adds those additional columns: TILEID, LASTNIGHT, HEALPIX, SURVEY, PROGRAM, with existence-checks because e.g. healpix-based files don't have a TILEID column.
This is *not* intended to be the final answer for the ongoing discussion about paring down the zcatalog columns to make the  files a more manageable size.  It's just adding the columns needed for uniqueness, which should have been in the `--minimal` set in the first place.  I needed this while assembling …
=> expand zcat minimal columns

py/desispec/scripts/autocalib_fiberflat.py
This PR is a followup to #2180 .  I had made some minor updates to the logging but forgot to push them before merging.  This represents what I actually tested in the end, and is algorithmically identical to #2180.
=> fiberflat gradient log tweaks

py/desispec/io/emlinefit.py
This PR addresses https://github.com/desihub/desispec/issues/1985 and https://github.com/desihub/desispec/issues/2186.
The workaround is just to not fit the few spectra with `EBV >= 2`.
Based from the discussion in https://github.com/desihub/desispec/issues/2186, this should concerns only few spectra close to the Galactic plane.
This is controlled by a new argument in `desispec.io.emline.read_emlines_inputs()`, `ebvmax`, which defaults to 2.
`read_emlines_inputs()` will set `ivar=0` for all pixels of spectra with `ebv >= ebvmax`.
Once read, those values are then feeded to `desispec.emlinefit.get_emlines()`:
https://github.com/desihub/desispec/blob/fe5a567126659dea873c55c1d9afc864eb6dcf7d/py/desispec/scripts/emlinefit.py#L139-L163
For those spectra, as no pixel is considered as valid, the …
=> emlinefit: do not fit ebv >= ebvmax=2 spectra

py/desispec/ccdcalib.py, py/desispec/io/raw.py, py/desispec/scripts/qproc.py
This might fix #2203, please have a look @sybenzvi.
=> Test fallback on dark fof

bin/assemble_fibermap
=> Remove redundant assemble_fibermap script

py/desispec/scripts/qsoqn.py
This PR fixes #2231 to update the qsoqn (quasarnet) afterburner to correctly parse the new structure of redrock-templates.  It will raise an exception if it doesn't find any templates, and it will log an error but not crash if the number found isn't 2 (HIZ and LOZ expected, but potentially could be different in the future).
This is required for correct qsoqn afterburner runs in Jura (current main silently finds 0 templates and never does the "rerun Redrock with a prior around the QN redshift" step).
I'll leave this open for an hour or so if there are rapid comments, but we need to merge it for testing tonight after Perlmutter is back.  Heads up @dylanagreen @echaussidon @akremin @ashleyjross @geordie666 .
I tested this with
```
desispec.scripts.qsoqn.main([
'--coadd', …
```
=> fix QuasarNET afterburner parsing of Redrock templates

doc/changes.rst, py/desispec/io/fibermap.py
=> Reorder DESINAME in assemble_fibermap

py/desispec/scripts/healpix_redshifts.py
Opening the PR with a branch from @akremin to add `--dry-run-level N` functionality. I added additional start/end log messages and help string info in commit c4b03ba7e012d0da5cd6c1a7aea1cf943ef7328a .
e.g. for Jura,
```
desi_healpix_redshifts --survey main --program bright --bundle-healpix 10 --dry-run-level 3
...
INFO:healpix_redshifts.py:166:main: Dry run: would have submitted 1791 batch scripts
INFO:healpix_redshifts.py:169:main: All done at Tue May 28 14:47:04 2024; duration 5.25 minutes
```
This allows planning the number of jobs that will be added to the queue prior to launching them so that we don't hit the 5k submit limit.  I confirmed that running in --dry-run-level 3 will not attempt to generate any files (I ran it under my own account, so it would have crashed if it had tried).
=> Healpix dryrun

py/desispec/night_qa.py
This PR addresses https://github.com/desihub/desispec/issues/2268.
Remark: I ignored `create_mp4()` which is not used/deprecated.
=> night_qa: use temporary files first, then os.rename

etc/desi_bundle.py, py/desispec/calibfinder.py, py/desispec/ccdcalib.py, py/desispec/fluxcalibration.py, py/desispec/focus.py, py/desispec/preproc.py, py/desispec/scripts/autocalib_fiberflat.py, py/desispec/scripts/emlinefit.py, py/desispec/scripts/fibercrosstalk.py, py/desispec/tile_qa.py, py/desispec/trace_shifts.py
While running pyright checker on desispec, I've seen a few obvious undefined variable cases. 
This fixes most of them where it was clear to me what was code's intention.
=> fix few obvious issues with undefined variables reported by static checker

py/desispec/scripts/qsoqn.py
This PR fixes a corner case where all input spectra are masked, e.g. healpix on the edges of the footprint where no fibers are assigned to targets.  It also adds more assert statements to check indexing assumptions, which highlighted that the `desi_qso_qn_afterburner --target_selection qso ...` option is broken.
After discussion with @akremin, we decided to proceed with this fix to finish off Loa since the `desi_qso_qn_afterburner --target_selection qso ...` option isn't needed for either productions nor daily ops.  We'll try to fix that later.  In the meantime, the code raises a NotImplementedError if that option isn't "all".
Tests on loa and daily:
```
#- WORKS (failed between PRs #2402 and #2407)
desi_qso_qn_afterburner \
--coadd …
```
=> fix qsoqn no input bug; more indexing tests

bin/desi_make_dark_tables
=> use better error message

py/desispec/ccdcalib.py
=> allow fallback to darks/biases in DESI_SPECTRO_CALIB if running ccdcalib

py/desispec/scripts/trace_shifts.py
Fixes the #2427 
Sorry for introducing it. 
(can't test it myself, but I think it should do it).
=> Fix the traceshift undefined variable bug

py/desispec/io/frame.py, py/desispec/io/meta.py, py/desispec/io/spectra.py, py/desispec/io/util.py, py/desispec/preproc.py, py/desispec/scripts/preproc.py, py/desispec/test/test_io.py
Add the possibility to choose the fits files compression mode with a DESI_COMPRESSION environment variable.
- default is 'GZ' (gzip compression), as in current pipeline (for instance if DESI_COMPRESSION is not set).
- possible values are DESI_COMPRESSION=GZ or DESI_COMPRESSION=NONE.
This feature is very useful for hardware tests because compression takes some time and this is sometimes inconvenient when doing real time tests.
=> DESI_COMPRESSION

py/desispec/preproc.py
Improved test whether the CCD is read to the left or to the right using DATASEC and BIASSEC header keywords.
This is needed for SM10 z1 that is now read in 2 amp mode to the left with amps A and C.
=> check whether the CCD is read to the left or to the right

bin/desi_compute_pixmask
More flexible version of desi_compute_pixmask.
=> Changes to desi_compute_pixmask

py/desispec/scripts/select_calib_stars.py
PR addresses #2479. Example changes using the loa redux shown below.
=> add psf correction to RCALIBFRAC

py/desispec/coaddition.py
- Very minor PR to allow coadding spectra with no resolution data (as is the case in Lyman-alpha sims).
- This has no impact on the processing of real data.
=> can coadd spectra with no resolution data

py/desispec/io/emlinefit.py
This PR fixes the underlying problem in #2434 for why Loa ended up with 3 corrupted emline files.  It updates desi_emline_fit to use a temporary file on output so that if the job is interrupted, it doesn't leave a corrupted file with the correct final name in place that gets skipped over upon rerun.  I tested this with
```
cd /global/cfs/cdirs/desi/spectro/redux/loa/tiles/cumulative/20432/20210617
desi_emlinefit_afterburner --coadd coadd-5-20432-thru20210617.fits --redrock redrock-5-20432-thru20210617.fits  --output $SCRATCH/desi/temp/emline-5-20432-thru20210617.fits
```
/pscratch/sd/s/sjbailey/desi/temp/emline-5-20432-thru20210617.fits was correctly written.  Reruns correctly remove that file and write a new one.
=> emline use tempfile for output

py/desispec/preproc.py
Minor PR to fix issue #2524 .
The code now writes the bias filename in the header
=> save bias filename in header
