doc/tex/Makefile
This PR adds a Makefile to the doc/tex directory.  It supports `make` and `make clean`.  It should work on any system that has pdflatex installed.
=> Add Makefile to doc/tex

bin/desi_zfind.py, py/desispec/zfind/__init__.py, py/desispec/zfind/redmonster.py, py/desispec/zfind/zfind.py
This branch refactors zfind to make redmonster an optional dependency, i.e. you only need to have redmonster if you are actually doing redshift fitting.  The previous master inadvertently had a redmonster dependency for every stage via io.read/write_zbest.
=> Zfind dirs

py/desispec/interpolation.py, py/desispec/test/test_resample.py
Improved (clarified) interpolation 
- integration in output bins of piece-wise linear function of input
- consider the flux density=0 outside of the edges of the input bins
- passes test of conservation of flux density, total integrated flux, inverse variance scaling with bin size,
total inverse variance
=> Fix interpolation

py/desispec/resolution.py
This fixes issue #19 to allow the Resolution object to be created with an odd but otherwise arbitrary number of diagonals.  This is needed for an upcoming specter bug fix that will auto-tune the number of diagonals based upon the PSF size and wavelength step of extractions.
David K: can you review this to make sure I've covered the various cases for Resolution created with sparse input?  I added a few more tests and I think this is correct, but your original code had already covered some cases that I hadn't originally thought about so another pair of eyes on this edit would be appreciated.
(sorry for all the git pushes that probably generated emails leading up to this...)
=> Allow various number of diagonals when creating Resolution matrix

doc/api.rst, doc/conf.py, py/desispec/zfind/redmonster.py
Fixes #32. Fixes #33.
Moving the import of redmonster code inside the `__init__()` function allows the redmonster.py module to compile even if redmonster is not installed.
Also adds a test for the presence of the Sphinx extension 'napoleon' in the doc/conf.py file.
=> Redmonster doc

.travis.yml, README.rst, doc/conf.py
This PR adds a .travis.yml file to support basic tests.  Right now `python setup.py test` is *not* run, because I wasn't sure how ready we were for that.  Only basic tests of package integrity & documentation are performed.
=> Add Travis CI functionality.

.travis.yml, py/desispec/test/desispec_test_suite.py, setup.py
This PR enables tests to be run with `python setup.py test` and adds that test mechanism to the Travis builds.
=> Adding test suite to setup.py

bin/copyprod.py, bin/desi_compute_fiberflat.py, bin/desi_compute_fluxcalibration.py, bin/desi_compute_sky.py, bin/desi_dailytest.py, bin/desi_fit_stdstars.py, bin/desi_inspect.py, bin/desi_make_bricks.py, bin/desi_process_exposure.py, bin/desi_update_coadds.py, doc/conf.py, py/desispec/brick.py, py/desispec/coaddition.py, py/desispec/fiberflat.py, py/desispec/fluxcalibration.py, py/desispec/interpolation.py, py/desispec/io/frame.py, py/desispec/io/zfind.py, py/desispec/log.py, py/desispec/pipeline/core.py, py/desispec/test/integration_test.py, py/desispec/test/test_log.py, setup.py
This PR removes as many `print` statements as possible, replacing them with log messages.  For the few `print` statements remaining, they have been converted into `print()` functions.  Here are the remaining files that still contain `print()` functions:
* bin/copyprod.py
* bin/desi_dailytest.py  -- also note this file has a significant code overlap with py/desispec/test/integration_test.py
* bin/desi_inspect.py -- Prints astropy Table objects, so not sure how that would work in a log system.
* py/desispec/brick.py
* py/desispec/test/test_log.py -- a bit crazy to have print statements in the function that tests the logger
* py/desispec/test/integration_test.py
* py/desispec/log.py -- print is used to print a message in case the logging can't be set up.  Maybe raising an exception would be …
=> Print statement sweep

py/desispec/io/util.py
I moved desisim.obs._dict2ndarray (which Stephen wrote) to desispec.io.util and incorporated it into desispec.io.util.write_bintable so that one can now seamlessly pass this function either a dictionary (of meta-data), a numpy recarray, or an Astropy Table (which in this context is operationally identical to a dictionary).
From what I could determine this does not break any other code.
=> write_bintable now accepts a dictionary, Astropy Table, or numpy.ndarray

.travis.yml, doc/api.rst, py/desispec/fluxcalibration.py, py/desispec/interpolation.py, py/desispec/io/__init__.py, py/desispec/io/download.py, py/desispec/io/fluxcalibration.py, py/desispec/io/meta.py, py/desispec/linalg.py, py/desispec/test/test_io.py
This PR:
* adds download support via `desispec.io.download()` (closes #48)
* adds download keyword option to `desispec.io.findfile()` (closes #49)
* Includes new tests for `findfile()`
* Includes tests of downloads, however, tests are
- skipped if no ~/.netrc file is present
- only performed on one file, which automatically disables multiprocessing
* Incidentally fixes some documentation bugs.
=> Support for file download

bin/desi_compute_sky.py, py/desispec/frame.py, py/desispec/sky.py, py/desispec/test/test_binscripts.py, py/desispec/test/test_fiberflat.py, py/desispec/test/test_frame.py, py/desispec/test/test_sky.py
After further reflection, we decided to require the assignment
of the fibers attribute (via fibers=, spectrograph= or meta=).
Put in consistency checks and new tests.
Eliminated usage of specmin attribute.
=> fiddling more with meta and fibers in frame

bin/desi_compute_fluxcalibration.py, bin/desi_fit_stdstars.py, py/desispec/test/integration_test.py
Two changes in this pull request:
1. fixes the integration test to work with `newexp-desi` instead of `pixsim-desi --newexp`
2. fixes two bugs in bin/ scripts related to the `Frame.header` -> `Frame.meta` rename.  These would have been caught by the integration test, if (1) hadn't been broken.
Unit tests and integration test pass on my laptop.
=> Fixdailytest

py/desispec/io/download.py, py/desispec/io/meta.py, py/desispec/test/test_io.py
This PR:
* Will check the http return code and will not try to write a file or get its modification time unless the return code is 200 (OK).  Fixes #59.
* Validates the inputs to findfile().  Inputs that are required but missing raise an exception. Fixes #58.
=> Download and filename fixes

py/desispec/image.py, py/desispec/test/test_image.py
Enables slicing of Image objects, e.g.
img1 = Image(pix, ivar, mask)
img2 = img1[0:100, 0:200]
img3 = img1[0:100]
img4 = img1[:, 0:200]
If NAXIS1 and NAXIS2 are in the meta header, those are updated with the new slice dimensions.  Tests are included.
=> Allow Image slicing

py/desispec/image.py, py/desispec/maskbits.py, py/desispec/test/test_image.py
Adds input validation when slicing Image objects.  Includes tests for bad slicing.
=> test Image slicing inputs

py/desispec/image.py, py/desispec/io/image.py, py/desispec/test/test_image.py, py/desispec/test/test_io.py
It appears that astropy.io.fits has a bug when writing compressed images of uint16.  It gets the TFIELD and BITPIX header keywords in the wrong order, which can choke other fits io libraries like cfitsio.  This PR works around that by storing the Image.mask as a int16 rather than uint16, and then casting back to uint16 upon reading.  I was unable to find a workable verify option to get astropy.io.fits to write it correctly in the first place.
If you want to chase the astropy.io.fits bug to see if there is a more direct workaround, here is example bad fits output:
from astropy.io import fits
hx = fits.HDUList()
hx.append( fits.PrimaryHDU(np.zeros(10)) )
hx.append( fits.CompImageHDU(np.zeros(10).astype(np.uint16)) )
hx.writeto('blat.fits', clobber=True)
The resulting …
=> Image io workaround for astropy.io.fits bug on uint16 output

py/desispec/test/integration_test.py
stellar_templates directory at NERSC had been renamed to "star_templates", which broke the end-to-end pipeline tests (flux calib uses those files).  This one liner fixes that.
=> fixes new location of star templates

py/desispec/cosmics.py
It appears that numpy 1.10 has become more persnickety about what kind of boolean operations are allowed.  if x is dtype=bool, then `x *= 0` is no longer allowed, but `x *= False` is allowed.  This PR is a one-line change in the cosmics code to fix this.  The unit tests caught this after I upgraded to numpy 1.10.  Yay unit tests.
Note:
* `x*0` and `x+0` are still allowed, since that creates a new array with a new dtype to match the integer.
* The problem with `x *= 0` is that it is an in-place operation on x that doesn't change its type, and it doesn't want to downcast the integer into a simple True/False.
=> fix bool*int logic for numpy 1.10

py/desispec/resolution.py, py/desispec/test/test_resolution.py
This PR adds the ability to generate a sparse Resolution matrix from a 1D array of Gaussian sigmas (in addition to the other input options of dense arrays, dense data from sparse arrays, or sparse matrices).  I developed this for quickly generating Resolution matrices for test cases, but it could also be useful for quickgen.
@dkirkby could you take a look?
=> add ability to create Resolution from 1D array of Gaussian sigmas

.travis.yml, bin/desi_compute_sky.py, doc/nb/QA_Frame.ipynb, py/desispec/io/qa.py, py/desispec/qa/qa_exposure.py, py/desispec/qa/qa_plots.py, py/desispec/test/test_binscripts.py, py/desispec/test/test_io.py, py/desispec/test/test_qa.py
Generated a new module for producing QA plots.  Now includes 
a case for sky subtraction residuals.
Also:
1. modified QA_Frame to initialize with a Frame
2. added QA to the binscript test for compute_sky
3. Modified travis.yaml to handle plots (i.e. matplotlib is now a dependency)
4. Update the QA_Frame notebook
Tested on laptop, edison, and Travis
=> QA Frame; now producing plots

py/desispec/io/meta.py, py/desispec/test/test_io.py
desispec.io.findfile() was requiring $DESI_SPECTRO_DATA and $DESI_SPECTRO_REDUX even if they weren't actually needed for finding a given particular file.  e.g. finding a fibermap needs DATA but not REDUX, while finding a brick needs REDUX but not DATA.  This PR cleans up the environment checking so that it will only fail if it is missing an environment variable that it actually needs.  And it includes tests, of course.
Note: we were already doing that for the input variables (e.g. finding a fibermap wouldn't fail if brickid wasn't set, but finding a brick file would require brickid to be set).  This PR updates the logic to include environment variables too.
=> don't require unnecessary envvars in io.findfile

bin/desi_zcatalog, py/desispec/io/__init__.py, py/desispec/io/meta.py, py/desispec/io/util.py
Adds code to collect individual zbest files into a single zcatalog file.  This will be used as input for LSS catalog creation and as feedback to operations about what targets have been observed with what redshifts/classifications.
Also introduces a utility function desispec.io.iterfiles(root, prefix) that looks through a directory root and its subdirectories for files that start with that prefix.
=> Adds zcatalog creation from zbest files

py/desispec/fluxcalibration.py
This PR fixes #89 (fix flux calibration crash).  The problem was that the standard star templates switch from using SDSS mags to DECAM mags, and desi_fit_stdstars.py was looking for an SDSS r magnitude.  Upon not finding it, it wrote a bogus stdstars*.fits file, which caused the next step of desi_compute_fluxcalibration.py to crash.
This fix allows stdstars to have either SDSS or DECAM fluxes.  I'll open a separate ticket to address future issues: what desi_fit_stdstars should do if it can't find an appropriate flux and how to handle DECam vs. Bok r.
=> stdstar filter SDSS_R or DECAM_R

bin/desi_zfind.py, py/desispec/zfind/redmonster.py
This PR adds a --objtype option to desi_zfind.py to restrict which templates are considered.  This is especially useful for leaving out the slow QSO templates while debugging ELGs and LRGs.  Redmonster doesn't distinguish between ELG and LRG so those are mapped to GALAXY.  Default is to fit GALAXY,STAR,QSO.
Examples:
```
desi_zfind.py -o blat.fits -b {brickname} --objtype ELG
desi_zfind.py -o blat.fits -b {brickname} --objtype GALAXY,STAR
desi_zfind.py -o blat.fits -b {brickname}
```
=> Add --objtype option to desi_zfind

.travis.yml, py/desispec/bootcalib.py
This PR does 2 things:
1. updates travis tests to use desiutil 1.3.2, which fixes a problem with recent setuptools dropping setuptools.compat .  This fixes failing travis tests.
2. temporarily restores bootcalib to use astropy.stats.sigma_clip(data, sig=4) instead of sigma=4 so that it will work with both astropy 1.0.4 and astropy 1.1.  This results in deprecation warnings under 1.1, but it gives us a transition period before we drop support for astropy 1.0.4 (in particular, we need to get 1.1 installed at NERSC before we can require it...)
=> Desiutil test

.travis.yml, py/desispec/bootcalib.py
This PR deprecates our use of astropy 1.0.6 by updating sigma_clip to use sigma=4. instead of sig=4.  Astropy update required numpy update which required scipy update to find consistent combinations that work with travis+conda.  The current Travis tests combinations are
* astropy 1.1.1, numpy 1.10, scipy 0.16
* astropy 1.1.1, numpy 1.10.4, scipy 0.17.0
=> updating sigma_clip for astropy 1.1

.travis.yml, bin/desi_fit_stdstars.py, etc/travis_env_common.sh, py/desispec/fluxcalibration.py, py/desispec/io/__init__.py, py/desispec/io/filters.py, py/desispec/test/test_flux_calibration.py
This PR replaces #115 and #101 after some branch juggling.  It replaces the filters from desisim with those from speclite.filters, and adds tests of the flux calibration code.
=> Fluxcalib: speclite filters and tests

py/desispec/bootcalib.py
small kludge in fiber_gauss.
Deals with the rare case when a fiber trace goes nearly parallel to the
columns.  
Sets the Gaussian to the previous fiber value.
=> Bootcalib: Small kludge in fiber_gauss

bin/desi_fit_stdstars.py, py/desispec/fluxcalibration.py, py/desispec/test/test_flux_calibration.py
This PR corrects the flux units in the magnitude calculations in desispec.fluxcalibration.normalize_templates() .  Internally the fluxes are in 1e-17 erg/s/cm2/A but speclite filters have a default without the 1e-17, resulting in crazy magnitude calculations.  This adds an explicit unit.  The calculation is only ~100 us slower per stdstar.
It also upgrades the tests of desispec.fluxcalibration.normalize_templates() to check that the returned spectrum has the requested normalization.
=> fix flux units for mag calc

py/desispec/test/test_flux_calibration.py
This PR fixes the 1d dictionary inputs required for match_templates function for the STD stars spectra. It also increased the speed by ~5x for flux calib test and potentially solves #118 (Test passed without a single failure on ~50 runs)
=> Fixes the match_template inputs in flux calib test

py/desispec/bootcalib.py
This PR allows using the `DESISPEC` environment variable to set the path to the data directory, instead of relying on a semi-hard-coded path.  This addresses some of the concerns in #133.
=> prefer the DESISPEC environment variable

bin/desi_merge_bundles.py
Bundle merging wasn't propagating the fibermap into the frame files correctly for spectrograph>0.  Fixed.  Onwards with automation!
=> automatically propagate fibermap when merging bundles

bin/desi_fit_stdstars.py, py/desispec/bootcalib.py, py/desispec/io/__init__.py, py/desispec/io/fluxcalibration.py, py/desispec/test/test_bootcalib.py, py/desispec/test/test_brick.py, py/desispec/test/test_io.py
This PR addresses some low-hanging fruit for our test coverage with additional tests on io.fluxcalibration, bootcalib, and io.brick.  Fixes some minor consistency issues found along the way, but no outright bugs found with this pass.  These tests are about coverage and interfaces; they are not probing algorithmic correctness.
Our remaining biggies for bad coverage are:
* pipeline.plan and pipeline.run : WIP and interfaces might still change considerably; detailed tests might be premature
* bootcalib, in particular the write_psf and the qa_* routines
* qa.qa_plots : these should become part of the standard pipeline, and thus they deserve real tests too
* io.database : stalled WIP; requires setting up a fake directory of data to load
* zfind.redmonster : would require installing redmonster …
=> update tests for better coverage

bin/desi_compute_fluxcalibration.py, py/desispec/fluxcalibration.py, py/desispec/linalg.py, py/desispec/test/test_flux_calibration.py
This PR fixes #141 and adds better robustness with masked or bad inputs to flux calibration:
1. It starts with a median estimate of the flux calibration and uses that as a first pass for outlier rejection before proceeding with the linear algebra fitting.  This fixes a dc3a problem where some standard stars on some frames had large outliers that pulled the initial solution and ended up causing all spectra to be masked at some wavelengths in later iterations (details below).  That masking of all wavelengths resulted in poorly a poorly conditioned matrix and a LinAlgError crash.
2. The nightly integration tests only use one standard star and were failing when 2 or more wavelengths were masked — it was trying to solve for N wavelengths with information from only N-2 inputs and getting a …
=> Fix fluxcalib

bin/desi_zfind.py
This PR modifies desi_zfind.py to allow for multiprocessing. This follows from issue #144 by @sbailey. It uses Pull.map() from the python multiprocessing package. The number of cores to be used is passed as an option in the command line. 
Test: fitting 150 ELG spectra bricks using desi_zfind.py with option '--objtype elg' on cori@nersc:
ncores = 1: 27 min.
ncores = 32: 4 min.
=> Parallelize desi zfind

bin/desi_pipe, py/desispec/pipeline/__init__.py, py/desispec/pipeline/plan.py
Now that it uses multiprocessing, run one desi_zfind per node when generating slurm scripts.
=> Run desi_zfind with one process per node.

bin/desi_quicklook, py/desispec/boxcar.py, py/desispec/procalgs.py, py/desispec/psf.py, py/desispec/quicklook/quicklook.py
I don't understand why the original PR didn't work, but this is a replacement for PR #159.  GitHub claimed there was a conflict between ghungana:quicklook and desihub:quicklook that had to be resolved at the command line, but fetching both of those and merging didn't show any conflicts.  This PR contains the changes in gdhungana:quicklook that are not yet in desihub:quicklook.  I will add some additional git-fu comments to #159 and close that out, and review this one for merging.
The original PR comment:
> Still working on the pipeline but sufficient update for this PR. This PR updates the boxcar to be using the bootcalib psf, as well as specter.psf.PSF. A similar psf interface is added. This only works for CCD x/y centroids and the wavelength solution. No resolution accounted yet.
=> quicklook with bootcalib psf

bin/desi_compute_sky.py, bin/desi_extract_spectra.py
One line change in desi_extract_spectra.py to have images ivar=0 for mask!=0. This reduces considerably the cosmics spikes in the frames. Tested on expid 6 , spectro 1 of dc3c. It would be interesting to rerun the whole dc3c with this fix.
=> use mask in ivar of images

bin/desi_zfind.py
I've minimally modified desi_zfind.py to use as many filters as given as arguments, instead of requiring  "b", "r", and "z". This allows the user to run on the bricks produced from BOSS data, which have only "b" and "r".
=> Changed desi_zfind.py to accept less filters

bin/desi_preproc, py/desispec/image.py, py/desispec/io/image.py, py/desispec/io/meta.py, py/desispec/io/raw.py, py/desispec/preproc.py, py/desispec/scripts/preproc.py, py/desispec/test/test_io.py, py/desispec/test/test_preproc.py
Adds desi_preproc script and bug fixes/features needed to support raw data preprocessing.
```
usage: desi_preproc [-h] --infile INFILE [--outdir OUTDIR] [--pixfile PIXFILE]
[--cameras CAMERAS] [--bias BIAS] [--pixflat PIXFLAT]
[--mask MASK]
Preprocess DESI raw data
optional arguments:
-h, --help         show this help message and exit
--infile INFILE    path of DESI raw data file
--outdir OUTDIR    output directory
--pixfile PIXFILE  output preprocessed pixfile
--cameras CAMERAS  comma separated list of cameras
--bias BIAS        bias image calibration file
--pixflat PIXFLAT  pixflat image calibration file
--mask MASK        mask image calibration file
By default, all HDUs of the input file are processed and written to pix*.fits
files in the current directory; use --outdir to override the …
```
=> desi_preproc

etc/cron_dailytest.sh, py/desispec/test/integration_test.py
This PR updates `cron_dailytest` to also update and use desiutil/master; previously it was using the default installed tag of desiutil.
It also turns on `desi_qa_zfind --verbose` option.  The first test run with `desi_qa_zfind` hung while outputing the pdf file, but killing it and re-running worked.  I'll watch out for that as the daily tests run.
=> update cron_dailytest to update desiutil too

py/desispec/qa/qa_plots.py
It appears that 'Agg' is an interactive matplotlib backend, while 'agg' is a batch backend that doesn't require an X11 connection.  I'm not entirely sure that this is necessary, but changing Agg -> agg is part of a recipe that seems to work for running the integration tests with QA enabled in a cronjob.
=> QA plotting backend for cronjobs

.travis.yml, etc/travis_env_common.sh, etc/travis_env_linux.sh
The merge of new pipeline code (and improved tests) broke the travis build, since those tests were more realistic and required the real pipeline dependencies (harp, specex, and specter).  I caused this breakage- mea culpa.  This pull request appends the needed dependencies to the travis environment, and also switches to using the newer ubuntu 14.04 with a newer gcc that better supports C++11.  The build of HARP is quite slow.  I can work on making an ubuntu package to speed up the linux travis build, but the OS X install is more challenging to package.
The travis tests now take approximately 20 minutes to complete.
=> Update travis environment to include harp, specex, and specter.

py/desispec/test/integration_test.py
The original line fails with a ValueError instead of issuing a warning then die with sys.exit.
=> remove extra undefined variable in error messages

bin/desi_pipe_run, py/desispec/fluxcalibration.py, py/desispec/io/fluxcalibration.py, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py, py/desispec/pipeline/utils.py, py/desispec/scripts/stdstars.py, py/desispec/scripts/zfind.py, py/desispec/test/test_binscripts.py, py/desispec/test/test_flux_calibration.py, py/desispec/test/test_io.py, py/desispec/test/test_pipeline_core.py
This PR provides a new standard star template matching algorithm by @julienguy that has much better accuracy than the current code which usually selects the wrong template.  This plot shows the (model-truth)/truth for the old (top) and new (bottom) algorithms.  Note the 100x difference in y scale.
I updated the pipeline code to work with the new `desi_fit_stdstars` command line options.  It is also now multiprocessing parallelized.  I'll need some help from @tskisner for how that should really be done; it currently involves a hardcoded 24 processes.  But tests by hand on a batch node worked; real batch jobs are running now for final confirmation.  It may need some tweaking for number of nodes and threads and multiprocessing to get it to all fit within 30 minutes still.
This PR supercedes …
=> new stdstars fit

py/desispec/pipeline/utils.py, py/desispec/scripts/stdstars.py, py/desispec/scripts/zfind.py, py/desispec/test/integration_test.py, py/desispec/test/test_pipeline_core.py, py/desispec/util.py
This PR fixes a circular import dependency by moving `desispec.pipeline.utils.default_nproc` into `desispec.util.default_nproc`.  It also fixes the integration test to match @julienguy's new `desi_fit_stdstar` interface.
Prior to this PR, here is the circular dependency that I was hitting:
```
In [2]: import desispec.scripts.stdstars
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7483a0ce6f0a> in <module>()
----> 1 import desispec.scripts.stdstars
/Users/sbailey/temp/desispec/py/desispec/scripts/stdstars.py in <module>()
25 from desispec.interpolation import resample_flux
26 from desispec.log import get_logger
---> 27 from desispec.pipeline.utils import default_nproc …
```
=> fix default_nproc circular import dep

py/desispec/io/frame.py
Adds a default option in io.frame to write FIBERMIN
to the header if fibermap is not set.  
Also throws a log error if none of the options are set.
This enables making bricks with quickgen output products
=> Write FIBERMIN

bin/desi_compute_psf, bin/desi_pipe, py/desispec/pipeline/run.py, py/desispec/scripts/specex.py
This changes the logic in the specex MPI wrapper so that failures of a single bundle are consistently handled.  The code no longer "hangs", however this does not fix the sporadic subprocess failures at NERSC.  The solution for that will be to call a thin specex API directly using ctypes.  That will be coming soon in a separate pull request for specex.  Once that is in place, the subprocess calls in desispec.scripts.specex.main will turn into function calls and we will remove this final weak link.
=> Make specex MPI wrapper more robust

py/desispec/io/image.py, py/desispec/io/raw.py, py/desispec/preproc.py, py/desispec/quicklook/procalgs.py, py/desispec/scripts/bootcalib.py, py/desispec/scripts/extract.py, py/desispec/scripts/mergebundles.py, py/desispec/test/test_preproc.py
This PR fixes #215 to add robustness to the case where the user or input file incorrectly uses a uppercase camera name (B0, R1, Z9) instead of lowercase (good = b0, r1, z9).  desisim was already fixed to standardize on lowercase camera names, but this PR is a belt-and-suspenders approach to be able to use files that had been created in the meantime (and or future files or user inputs with uppercase camera names).
Note: the EXTNAME is still the uppercase camera name since some FITS libraries have difficulty with lowercase EXTNAMEs; it is the CAMERA keyword value and camera function arguments that should be lowercase.  Klaus has a different scheme for what the EXTNAMEs will be, but that is a separate issue that will be updated later.
=> add robustness for standardizing lowercase camera names

bin/desi_pipe, bin/desi_pipe_status, py/desispec/pipeline/run.py, py/desispec/scripts/specex.py
This removes subprocess calls from all python code which is on the execution path of production pipeline runs.  In particular, the code now calls specex directly using ctypes without forking a new process.  The only other place where subprocess was used is during the merging of PSF.  That functionality was in a small python script in specex, and this has now been copied directly into desispec.scripts.specex.  We can revisit that choice if we ever want to package the specex python tools into an actual python package.  In that case, we could then just call the function from there.
A 60-process test job now runs on 3 frames, using multiple groups of processes running specex to process a whole frame.  This job previously failed sporadically with subprocess errors.
=> Remove subprocess calls from high concurrency pipeline code

py/desispec/bootcalib.py
Change algorithm to find peaks in slice of CCD image in bootcalib.py , find_fiber_peaks. The original algorithm was failing in rare cases where two pixels in the median slice had the exact same value (possible with ADC counts). Now use first a clustering algorithm.
=> fix peak finder algorithm with clustering

bin/desi_pipe_status, py/desispec/pipeline/__init__.py, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py
The logs for each pipeline task are now routed to a per-task file by remapping stdout to a file.  Rewrite desi_pipe_status to allow exploring the state of the full pipeline, a pipeline step, or an individual task.  By redirecting stdout for each task to a file, previous fragility is reduced.  This is likely due to reducing the amount of data that must be buffered and merged by slurm.
=> Make substantial changes to the way that logging is handled.  

bin/desi_pipe, py/desispec/fluxcalibration.py, py/desispec/io/fluxcalibration.py, py/desispec/pipeline/run.py, py/desispec/scripts/zfind.py
This PR:
* disables multiprocessing in fluxcalibration.match_templates if ncpu=1 
* uses ncpu=1 when wrapping match_templates in the batch pipeline MPI wrapper; this works around a hang when combining MPI+multiprocessing
* adds some log.debug messages
* runs redmonster in the regular queue for 1 hour using 12 cores per brick.  This may also have the mpi4py+multiprocessing hang problem too, but the previous "debug queue for 30 min + 2 cores per brick" wasn't going to finish in time anyway, even with the trimmed down QSO templates
=> make stdstar multiprocessing optional

bin/desi_pipe, bin/desi_pipe_run, py/desispec/pipeline/run.py
This PR provides several small features for spectro pipeline 2016b:
* Pipeline batch jobs are now named for the step(s) they represent instead of "desipipe" for every step.  Closes #154.
* Extraction jobs allocate one core per process instead of 2 cores per process.  Closes #153.  See notes there for timing details.
* Adds logging messages to track python startup time and run time for each step.
=> meaningful job names; extraction scaling; timestamps in logs

py/desispec/zfind/redmonster.py
Added template groups into redmonster wrapper.  Default is to give each template class (galaxy, star, qso) a separate group.
I somehow lost the ability to give this a test run on my laptop, so this needs to be tested before being merged.
=> added template groups

py/desispec/scripts/stdstars.py, py/desispec/test/integration_test.py, py/desispec/test/old_integration_test.py
We should have run the integration test prior to merging John's big template refactor desihub/desisim#132 .  This PR fixes at least one issue:  standard stars now have WISE magnitudes included, but our default stdstar template set /project/projectdirs/desi/spectro/templates/star_templates/v1.1/star_templates_v1.1.fits doesn't have sufficient wavelength coverage to calculate WISE mags to compare those templates with the data mags.  Perhaps we need to update the template set?
This PR has a work around of simply not calculating the WISE magnitudes for these stdstar templates since we don't normalize to them anyway.
I'm still getting other random redshift failures, but it might be because the new templates are generating fainter ELGs that sometimes should fail.
i.e. don't merge yet, but I …
=> WISE mags for stdstars

.travis.yml, etc/anaconda_integration_test.sh, etc/desiInstall_integration_test.sh, py/desispec/io/filters.py
Minor changes to fix speclite usage in python3. 
Are the hardcoded versions in the integration test scripts meant to be updated like this?
See also dkirkby/speclite#23.
=> Speclite update

.travis.yml, doc/changes.rst, py/desispec/io/brick.py, py/desispec/scripts/zfind.py, py/desispec/test/test_resample.py, py/desispec/zfind/redmonster.py
This PR updates the desi_zfind wrapper of redmonster so that the results are reproducible between python 2.7 and 3.5.  Previously they weren't even reproducible from back-to-back runs under python 3.5 (!).  The changes are:
* always add the brick files in the same order; previously they were added in whatever order came out of `filters=list(brick.keys())`, which apparently under python 3.5 can vary from run to run.  The order matters due to the `resample_flux` issue raised in issue #272 .  A commented out test in `test_resample` could be used for studying #272, but the minimal change here at least makes the code reproducible.
* convenience: `Brick.get_target_ids()` will return them in the order in which they first appeared in the original input file.
* fixes #271 by storing the redmonster …
=> update redmonster wrapper for 2.7 vs. 3.5 reproducibility

py/desispec/pipeline/plan.py, py/desispec/scripts/makebricks.py, py/desispec/scripts/specex.py, py/desispec/zfind/redmonster.py
This cleans up several small things:  format strings, dictionary iteration, and disabling the (inherently broken) writing of serialized subtypes to a fixed-width ascii column of a binary FITS table. 
Tested this version from bootcalib to redshifts under python3.5 and python2.7, although some zfind tasks ran out of time.
=> Small fixes for python3

py/desispec/pipeline/run.py, py/desispec/scripts/extract.py, py/desispec/scripts/zfind.py, py/desispec/util.py
This work ensures that all outputs from all processes are captured by writing to per-process log files and then merging those into the corresponding per-task logfile.  It also ensures that all processes working on a single task raise an exception if any one process raises.  This prevents "hanging" at barriers at the end of each task.  At each pipeline step, if all tasks fail for some reason, then the pipeline stops.
=> Pipeline logging and reliability

py/desispec/io/brick.py, py/desispec/io/fiberflat.py, py/desispec/io/fluxcalibration.py, py/desispec/io/frame.py, py/desispec/io/sky.py, py/desispec/scripts/extract.py, py/desispec/scripts/procexp.py, py/desispec/test/test_extract.py, py/desispec/test/test_io.py
This PR:
- fixes #283 
- adds 1e-17 to the BUNIT keyword
=> updated BUNIT to proper units

py/desispec/resolution.py, py/desispec/test/test_resolution.py
This PR fixes #286 (Review resolution matrix requirements) to enable creating resolution matrices with a different number of upper/lower diagonals.  In particular, it enables desisim quickbrick and quickgen to work with the latest specsim, which now can return resolution matrices with an even number of diagonals (see desihub/specsim#50).
Tests are expanded to have 100% desispec.resolution code coverage.  I think algorithmic input options coverage is pretty good too, but let me know if you think there are important missing cases to test.
I implemented this by padding the underlying sparse resolution matrix to have (2\*n+1) diagonals (the main diagonal plus n upper and n lower diagonals).  An alternative would be to update the Frame file format to explicitly track the diagonals, but since …
=> enable asymmetric resolution matrix

py/desispec/bootcalib.py
This PR fixes #289 where bootcalib was failing with python 3.5 at NERSC due to non-ASCII characters in NIST line lists and NERSC not setting $LANG.
Thanks to @weaverba137 for pinging the astropy list about this, and Derek Homeier for providing the useful solution of `locale.setlocale(locale.LC_ALL, str('en_US.utf8'))` .
@weaverba137 also asked whether this should be moved into the `desispec.io` module.  As long as these files are used only for bootcalib and they remain a part of the package data, I think it is ok to keep their I/O as a detail inside bootcalib.  If we need to read these files for other reasons (e.g. a python-based PSF or wavelength fitter), then their I/O wrapper should move out into `desispec.io`.  For now, I left the location as-is for the minimal change to fix the bug. …
=> work around non-ASCII characters in NIST line lists

py/desispec/qa/qa_brick.py, py/desispec/qa/qa_exposure.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_prod.py, py/desispec/qa/qa_quicklook.py, py/desispec/test/test_io.py, py/desispec/test/test_qa.py
Update of QAs to bring 'offline' and 'online' into closer agreement.
- for 'online' QAs (those written originally for quicklook):  Add 'PARAMS' subdictionary to include configurable thresholds and reference values to 3 QAs (sky residual, countbins, countpix).  Adopt data subdirectory label 'METRICS'  (i.e. 'VALUES' --> 'METRICS')
- for 'offline' QAs (those written initially for offline pipeline): relabel data and parameter subdictionaries as 'METRICS' and 'PARAMS', respectively.
=> update of QA dictionaries: PARAMS and METRICS in online and offline QAs

doc/Makefile, doc/api.rst, doc/conf.py, py/desispec/pipeline/__init__.py, py/desispec/pipeline/common.py, py/desispec/pipeline/graph.py, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py, py/desispec/pipeline/state.py, py/desispec/pipeline/task.py, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/quicklook.py
Use sphinx-build rather than sphinx-build-2.7 when building docs (so it works under python3 as well).  Add speclite.filters to mock imports.  Fix quicklook docstrings so that sphinx runs without errors.
=> Make sphinx documentation build again

bin/desi_pipe_run_mpi, etc/desi_bundle.py, etc/desi_bundle.spec, py/desispec/pipeline/common.py, py/desispec/pipeline/graph.py, py/desispec/pipeline/run.py, py/desispec/pipeline/state.py, py/desispec/scripts/makebricks.py, py/desispec/scripts/pipe_prod.py, py/desispec/scripts/pipe_run.py, py/desispec/scripts/pipe_status.py
Do not attempt to do environment setup inside the SLURM script.  This has proven unreliable since SLURM itself has bugs that prevent it from working cleanly.  Instead, the desired DESI software packages must be loaded at the time of job submission.  I personally disagree with this kind of workflow, but since this is a limitation of SLURM, we don't have much choice.
Also change the string representing the state of running jobs ("wait") to be more informative ("running").
=> Do not setup the software environment inside of slurm scripts.

py/desispec/io/brick.py, py/desispec/test/test_io.py
This PR
- fix the HDU update in desispec.io.brick so that fits file written is not corrupted ( #312 )
- adds a unit test that fails in the previous case but passes for this update. The written file is reopened and appended to confirm if the file written is correct.
=> fix hdu update in brick I/O, add relevant test

py/desispec/boxcar.py
`xrange()` is a Python 2 function that should not be in our code.
Please merge this *before* #316.
=> replace xrange with range

doc/changes.rst, py/desispec/psf.py, py/desispec/test/test_bootcalib.py
Fixes #318 by closing the PSF file after initializing the PSF object (by using a context manager so that it will be closed even if an exception occurs while processing the file).  I'm running this via a PR to get Travis tests on multiple pythons.
=> close PSF file after initializing PSF object

py/desispec/qa/qa_frame.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/qlconfig.py, py/desispec/quicklook/quicklook.py, py/desispec/sky.py, py/desispec/test/test_binscripts.py, py/desispec/test/test_ql_qa.py
This pull request facilitates integration of QAs from quicklook at the offline spectroscopic pipeline.  It follows discussion with @profxj and implementation consistent with those discussions.  It 
includes:
- modification methods for signal-to-noise and sky residuals calculation, refactoring QA code to be reused readily in both quicklook and offline pipelines
- inclusion of signal-to-noise QA into offline QA for first time
- integration of data model of these two QAs at sky-subtraction step of pipeline
- integration of signal-to-noise into plotting for offline
- modification of quicklook to use new refactored code
- modification test_biscripts to accomdate changes
- addition of new unit tests for new refactored computation methods
- minor fixes for plotting
This will be used as a …
=> Qa refactor

doc/changes.rst, py/desispec/io/raw.py, py/desispec/pipeline/task.py, py/desispec/test/old_integration_test.py, py/desispec/test/test_ql_qa.py
This is a work in progress towards fixing the integration tests.
* A companion commit directly to desisim/master added 3 new required raw data header keywords: DOSVER, FEEVER, DETECTOR introduced in PR #331 .  This PR to desispec is required to make that fully work and get desisim and desispec master self-consistent again for raw data generation and preprocessing.
* this PR also fixes the `old_integration_test` for the new location of `runcmd`; that integration test now passes, i.e. the algorithms themselves are ok.
* There remain problems within the full pipelining graph logic that is tested by `integration_test`, e.g.
```
ERROR:run.py:254:run_step: FAILED: step sky task 20160726_sky-b0-00000002 (group 1/1 with 1 processes)
ERROR:run.py:257:run_step: Traceback (most recent call last): …
```
=> Fix integration test

doc/changes.rst, py/desispec/test/test_bootcalib.py
This PR fixes a bug in test_bootcalib, which requires downloading some example data from NERSC (which is still unavailable today).  The test had logic for a failure to download, but it wasn't catching the case of the server returning a 403 error code and some HTML text instead of a fits file.
I would appreciate a cross check from someone like @tskisner or @weaverba137: this code considers an HTTP return code of 200 as good, and any other code as bad.  Are there any other return codes that should be considered a success (418 perhaps)?
Thanks to @gdhungana for reporting the problem.
=> allow bootcalib tests to run even if NERSC is down

py/desispec/brick.py, py/desispec/test/test_brick.py
This speeds up ```brick.Bricks.brickname``` by looping on each unique brick row rather than looping on each object in the input array (see #310).
With 5M input objects the previous version took 6.81s vs 2.98s now.  Here's the snippet of code used for testing.
```
from time import time
from desispec.brick import Bricks
B = Bricks()
rand = np.random.RandomState(444)
nobj = 5000000
ra = rand.uniform(0.1, 359.1, nobj)
dec = rand.uniform(-89.0, 89.0, nobj)
%time brickname = B.brickname(ra, dec)
```
=> speed up brick.Bricks.brickname

doc/changes.rst, py/desispec/brick.py, py/desispec/test/test_brick.py
Minimal change to the `brick.brickname` function (*not* the `Bricks.brickname` method) to make the bricksize a variable input.  This input is needed for https://github.com/desihub/desitarget/issues/136.
=> add optional bricksize input to brick.brickname

py/desispec/parallel.py
PR #352 broke unit tests on a mac due to this code in `desispec.parallel`:
```python
libc = ctypes.CDLL(None)
c_stdout = ctypes.c_void_p.in_dll(libc, 'stdout')
c_stderr = ctypes.c_void_p.in_dll(libc, 'stderr')
```
Both @tskisner and Travis use Linux where this works, but on a Mac this causes:
```
...
File "/Users/sbailey/desi/git/desispec/py/desispec/test/test_util.py", line 13, in <module>
import desispec.parallel as dpl
File "/Users/sbailey/desi/git/desispec/py/desispec/parallel.py", line 27, in <module>
c_stdout = ctypes.c_void_p.in_dll(libc, 'stdout')
ValueError: dlsym(RTLD_DEFAULT, stdout): symbol not found
```
This PR provides the minimal workaround of only running that code on Linux.  `libc`, `c_stdout`, and `c_stderr` are only used in one place later to flush C stdout/stderr, and …
=> work around libc stdout/stderr unit test prob on Mac

bin/desi_end_night, bin/desi_start_night, bin/desi_update_night, doc/changes.rst, etc/desi_dts_delivery_test.sh, py/desispec/scripts/delivery.py, py/desispec/scripts/night.py, py/desispec/test/test_scripts.py
**Don't merge until we've thoroughly reviewed this!**
This PR:
* Closes #322 
* Fleshes out the DTS delivery script.
* Adds a DTS simulator script that calls the delivery script.
This is nearly done, but could probably use some tweaks, so I want to get the review process started. I *think* that most of the remaining work is configuration details; the bulk of the necessary *mechanisms* should be in place.
Here's how this currently works.
1. Log in to one of the data transfer nodes and become the 'desi' pseudo-user.  Set up environment to point at this branch of desispec.  In other words, everything below runs on the 'desi' account.
2. `etc/desi_dts_delivery_test.sh` This script copies simulated raw data files to a spool directory (a.k.a. "inbox") to simulate the arrival of files via DTS. …
=> Test DTS delivery

py/desispec/brick.py, py/desispec/test/test_brick.py
Fixes #372 (barfing on ra=360), and also includes a fix for handling negative RA (where the tests were previously wrong too!).
Locally tested on python 3.5; I'll let Travis tell me if I messed up strings vs. unicode for py2.7.
=> fix brickname for RA wraparound

py/desispec/scripts/fluxcalibration.py
This is a single character fix for flux calibration in the integration tests.  The problem is that the integration test uses a single standard star, but the chi2 clipping was requiring `chi2 < median_chi2 + 3*std(chi2)`.  Switching to `<=` allows this to work with a single star.  Real data will always have multiple standard stars per frame but it is handy to let the tests proceed quickly with a single standard star.
=> fix flux calibration for integration test

doc/changes.rst, py/desispec/brick.py, py/desispec/test/test_brick.py
This is needed to assign the `TARGETID` to sky locations (etc.) in `desitarget` but `desispec.brick` seemed like the logical place to add this functionality.
=> Added a function to calculate BRICKID given an RA, Dec location

.travis.yml, doc/changes.rst, py/desispec/io/fibermap.py, py/desispec/test/test_io.py
This PR adds 3 new columns to the fibermap based on [DESI-0530](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=530) and discussions with ICS (Klaus) and the focal plane (Joe):
* PETAL_LOC [0-9]: location of the petal (wedge) on the focal plane
* DEVICE_LOC [0-542]: location of the device on the petal
* LOCATION: for convenience, 1000*PETAL_LOC + DEVICE_LOC
It also fills in more default values in `desispec.io.fibermap.empty_fibermap()`, in particular the mapping of FIBER to LOCATION, using `desimodel.io.load_fiberpos()` which returns the canonical mapping from desimodel.
Notes:
* POSITIONER [0-5000] is deprecated; use LOCATION or (PETAL_LOC, DEVICE_LOC) instead
* (PETAL_LOC, DEVICE_LOC) will become the canonical way that we reference an object on the focal plane, e.g. for …
=> new fibermap columns LOCATION,DEVICE_LOC,PETAL_LOC

doc/changes.rst, py/desispec/io/brick.py, py/desispec/io/fibermap.py
This PR works around a change in behavior from astropy 1.2 to 1.3, likely related to the units issue we had to work around desihub/specsim#62:
Under astropy 1.2, assigning a value to a table column would retain the original dtype of that column.  Under astropy 1.3, the column gets the new dtype of the right-hand-side value.  This breaks some consistency checks for fibermap columns though I don't think it broke any actual functionality (for desispec).
This PR also fixes two smaller issues that I found while debugging this:
* previously `desispec.io.Brick` couldn't be created with a filename that didn't include a path (it would parse the path as '' and then try to create '' and complain)
* typo in #379 (new fibermap columns) resulted in both `LAMBDAREF` and `LAMBDA_REF`
I have tested with …
=> fix fibermap dtype for astropy 1.3

doc/changes.rst, py/desispec/io/meta.py, py/desispec/parallel.py, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py, py/desispec/pipeline/task.py, py/desispec/scripts/pipe_prod.py, py/desispec/test/test_parallel.py, py/desispec/test/test_pipeline_graph.py, py/desispec/test/test_pipeline_plan.py
This pull request:
- Passes the list of selected spectrographs down into the nightly planning function.  Only bricks from fibers with a matching spectrograph ID are accumulated.  This fixes a longstanding bug with creating productions that use only a subset of the spectrographs.
- Adds a --fakepix option to desi_pipe and lower level functions, which skips checking of the pix data files.  This allows creating a production compatible with using quickgen in place of the usual psf / extract steps.
- Add high level helper scripts to submit chains of nightly processing.  This allows running all nights of processing as independent chains of jobs prior to running redshift fitting.
- Changes the way that the size of pipeline jobs are computed.  Given a maximum number of nodes, processes per task, …
=> Pipeline Improvements

py/desispec/boxcar.py, py/desispec/data/quicklook/example-config-arcs-r0-00000000.yaml, py/desispec/psf.py, py/desispec/quicklook/arcprocess.py, py/desispec/quicklook/palib.py, py/desispec/quicklook/procalgs.py, py/desispec/quicklook/qlconfig.py, py/desispec/quicklook/quicklook.py, py/desispec/quicklook/util.py, py/desispec/scripts/quicklook.py, py/desispec/test/integration_test_quicklook.py
This PR takes a step in the direction of providing self-sufficiency of QuickLook.  It includes an implementation of a pipeline for arc lamp exposures to yield resolution information in the wavelength direction output to a PSF file.  A modification of the pipeline for science exposures allowing them to utilize the new PSF information for fiber flattening and sky subtraction.  Another element of this PR is directed at assisting QLF development by outputting merged QA dictionaries conforming to the merged data model specifics as discussed in fall.  This also facilitates QL functionality to compare ongoing metrics with prior established references.
Specifically, this PR
- Adds Quicklook PA classes for arcs and adds functions/modules for the arcs processing.
- low level psf fitting of …
=> Quicklook arcs+

py/desispec/fluxcalibration.py
PR with minor changes to the routine compute_flux_calibration 
- use frame mask in ivar
- propagate mask to calibration files
=> compute_flux_calibration using frame mask

.travis.yml, bin/desi_group_spectra, doc/conf.py, py/desispec/io/__init__.py, py/desispec/io/meta.py, py/desispec/io/spectra.py, py/desispec/io/util.py, py/desispec/maskbits.py, py/desispec/parallel.py, py/desispec/pipeline/__init__.py, py/desispec/pipeline/common.py, py/desispec/pipeline/graph.py, py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py, py/desispec/pipeline/task.py, py/desispec/scripts/group_spectra.py, py/desispec/scripts/pipe_prod.py, py/desispec/spectra.py, py/desispec/test/test_io.py, py/desispec/test/test_parallel.py, py/desispec/test/test_pipeline_graph.py, py/desispec/test/test_pipeline_plan.py, py/desispec/test/test_spectra.py, py/desispec/util.py
This work is focused on grouping spectra by healpix pixel and performing that re-grouping on either a full production or on an incremental update from a few frames:
- A new Spectra class can hold spectral data (wavelength, flux, ivar,
mask, resolution, etc) for one or more arbitrary bands.  There are
methods for returning a selection of spectra and for updating or
appending new spectral data.  Each band may have different number
of diagonals in the resolution matrix.
- The pipeline is now designed to work with these spectra objects rather
than bricks.
- A new MPI-aware entry point (desispec.scripts.group_spectra) is added
which distributes spectral group files among processes to perform the
regrouping.  Each process reads (and optionally caches) the frames
needed for its spectral groups. …
=> Spectral regrouping by HEALPix pixel

bin/desi_group_spectra, bin/desi_mpi_zfind, bin/desi_pipe_run_mpi, doc/changes.rst, py/desispec/parallel.py, py/desispec/pipeline/run.py, py/desispec/test/integration_test.py, py/desispec/test/test_parallel.py
Small changes that close #397 .  In the future, we may have more unit tests that genuinely cannot be run without MPI.  These should eventually be run with a separate optional test command.  Until then, comment out a unit test for a function that is not actually used anywhere in the code.
=> Update changes.rst and disable single unit test

bin/desi_zcatalog
This PR changes desi_zcatalog to use fitsio instead of astropy.io.table.Table to be 8x faster with 2.5x less memory when run on the 2% survey.
Example output on edison@NERSC:
`/scratch2/scratchdirs/sjbailey/desi/dc17a/spectro/redux/dc17a2/zcat-dc17a2.fits`
producted with
`/usr/bin/time desi_zcatalog --indir spectra-64/ --outfile blat.fits --verbose`
=> 8x faster in 2.5x less memory desi_zcatalog

doc/changes.rst, py/desispec/database/datachallenge.py
This PR deals with some minor changes needed to load the healpix based zbest files in `dc17a-twopct`.  In addition to filename changes, this also deals more intelligently with the duplicate `TARGETID` values that crept into these files.  Instead of rejecting the whole file if duplicates are found, it just rejects the rows in the file that are duplicates.
=> Load dc17a2

doc/changes.rst, py/desispec/io/meta.py, py/desispec/io/util.py
Updates `desispec.io.findfile` to match the spectra file directory structure of dc17a2, i.e.
```
spectra-{nside}/{pix//100}/{pix}/spectra-{nside}-{pix}.fits
e.g. spectra-64/191/19155/spectra-64-19155.fits
```
instead of
```
spectra/{supernside}-{superpix}/{nside}-{pix}/spectra-{nside}-{pix}.fits
e.g. spectra/8-299/64-19155/spectra-64-19155.fits
```
where `{superpix}` was a larger healpix hierarchy pixel.
We went back and forth about whether the intermediate subdirectory should be a strict healpix superpixel or not, but in the end I couldn't divide random integers by 64 fast enough in my head and went for the simpler `{pix}//100`.
=> change spectra output structure

py/desispec/io/spectra.py, py/desispec/scripts/group_spectra.py, py/desispec/spectra.py, py/desispec/test/test_spectra.py
Small cleanup item prior to advertising this class at the collaboration meeting:
For consistency with Frame.fibermap and former Brick.fibermap, rename Spectra.fmap to Spectra.fibermap.
this was originally going to address the metadata requests in #406, but Adam wisely warned me off that for today so I'm limiting it to a variable renaming.
=> fmap -> fibermap

doc/changes.rst, py/desispec/io/meta.py
fixes the desispec.io.findfile path to zbest and zcoadd files, under subdir spectra-{nside}/ and not just spectra/ .
See also PR #404 where this should have been fixed the first time (mea culpa)
=> fix zbest and coadd desispec.io.findfile filepath

bin/desi_qa_frame, doc/changes.rst, doc/index.rst, doc/qa.rst, py/desispec/io/__init__.py, py/desispec/io/frame.py, py/desispec/io/meta.py, py/desispec/io/qa.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_plots.py, py/desispec/scripts/qa_frame.py, py/desispec/scripts/qa_prod.py, py/desispec/test/test_io.py
Introduces a desi_qa_frame script to generate QA for an input frame file.
Adds new get_nights() and search_for_framefile() methods with tests.
Adds documentation on QA scripts (qa.rst)
Tested successfully on 2% challenge files.
=> QA frame script

py/desispec/qa/qa_exposure.py, py/desispec/test/integration_test.py, py/desispec/test/old_integration_test.py
This PR fixes some problems with the integration test and its compatibility with the latest QA code.  In particular, the QA code is correctly becoming more picky about allowable exposure flavors and the integration test was sloppy about program 'dark' vs.  flavor 'science'.
This remains an area where we need to coordinate with ICS to formalize the allowable values, but at least this gets us back into a self-consistent old integration test state.
It also fixes a simspec data model incompatibility in the full pipeline integration test, though that doesn't yet have redrock integration so it still doesn't complete without errors.  That will be a separate PR when redrock is integrated with pipeline.
=> fix integration test for QA updates

py/desispec/qa/qa_frame.py, py/desispec/qa/qa_prod.py, py/desispec/scripts/qa_frame.py, py/desispec/scripts/skysubresid.py, py/desispec/sky.py
Modify SkySub QA (post-pipeline) to flat-field prior
to subtraction.
This was the cause of the large residuals seen in the QA plots.
=> QA flat fix

bin/desi_compute_trace_shifts, py/desispec/scripts/trace_shifts.py, py/desispec/trace_shifts.py
Code to adjust the spectral traces using an external (sky) spectrum or a list of isolated emission lines. Tested on dark exposure of oak simulations. Details are given in issue #358.
New files are bin/desi_compute_trace_shifts desispec/trace_shifts.py desispec/scripts/trace_shifts.py
=> Trace shifts

.travis.yml, py/desispec/parallel.py
Fix discrete distribution for the extreme case of work items of very different sizes combined with a number of workers that is comparable to the number of work items.  Closes #442.  Example:
```
from desispec.parallel import dist_discrete
worksizes = [47, 151, 1052, 17, 126, 524, 284, 245, 1216, 1398, 2582, 1460,
131, 93, 523, 36, 156, 1179, 1515, 1198, 81, 16, 728, 191, 16, 31, 155,
362, 535, 480, 224, 521, 538, 46, 525, 461, 364, 388, 487, 18, 106,
1002, 16, 326, 177, 501, 523, 20, 454, 479, 423, 114, 16, 478, 1078, 830,
146, 16, 54, 177, 768, 1278, 74, 344, 1108, 184, 126]
workers = 38
for w in range(workers):
d = dist_discrete(worksizes, workers, w)
print("worker {} has items {} --> {} inclusive".format(w, d[0], d[0]+d[1]-1))
```
Outputs:
```
worker 0 has items 0 --> 7 inclusive …
```
=> Fix discrete distribution

py/desispec/scripts/extract.py
This PR adds a `--mpi` option to the `desi_extract_spectra` script to enable MPI parallelism at the command line level.  Previously this was only available when running extractions within the context of the pipeline, which directly calls `desispec.scripts.extract.main_mpi()`.
e.g.
```
srun -n 32 -c 2 --cpu_bind=cores desi_extract_spectra --mpi ...
```
It also fixes an inconsistency between the default wavelength step for the MPI vs. non-MPI versions.
=> enable optional MPI parallelism for desi_extract_spectra script

.travis.yml, doc/changes.rst, py/desispec/scripts/extract.py
This PR uses the specter.extract.ex2d nsubbundles option for faster extractions.  It uses a default of 6 subbundles per bundle, based upon timing tests on a Cori Haswell node.
This requires >=specter/0.8.0 to run real extractions, and >=specter/0.8.1 to pass tests (there was a bug with really small test extractions that were requesting more subbundles than fibers...).
=> use specter ex2d nsubbundles option

bin/desi_pipe_run_mpi, py/desispec/fiberflat.py, py/desispec/linalg.py, py/desispec/pipeline/run.py, py/desispec/pipeline/task.py, py/desispec/scripts/pipe_prod.py, py/desispec/scripts/specex.py
Few changes to run a month of data
- pipeline tasks default timing (see issue #443).
- minor changes to fiberflat to solve hanging issues occurring for some noise (+cosmics) realization.
- a hack to avoid an astropy.__init__ IO issue when many worker are starting at the same time. Add a random delay at the beginning of  bin/desi_pipe_run_mpi before importing astropy. this will be solved when running with docker/shifter, but the hack is efficient (no issue after running 8 nights of data)
This PR allows to run smoothly the pipeline from CCD images to calibrated spectra, for nights of 6 calibration exposures + 14 science exposures, on the edison debug queue, with a maximum spread of 213 nodes, and a total time of only 45minutes (8 nights done so far).
I tested with success spectra grouping …
=> Running a month of data

doc/qa.rst, py/desispec/io/qa.py, py/desispec/qa/__init__.py, py/desispec/qa/qa_exposure.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_plots.py, py/desispec/scripts/qa_exposure.py, py/desispec/test/test_qa.py
A little polishing of the docs.
Also had to allow for frames to be missing what I believe are
required keywords (e.g AIRMASS).
And I had to turn off the generation of the frame_skychi figure.
The method has simply vanished.  I worry it was part of branch
and got eaten on a merge.  Will buy anyone a beer that can
find it on GitHub...
Haven't tested on NERSC yet.  I imagine someone can do so
faster than I but I'll give it a shot tomorrow if not.
=> Fussing a bit with QA

py/desispec/cosmics.py, py/desispec/fiberflat.py, py/desispec/scripts/extract.py, py/desispec/scripts/fiberflat.py, py/desispec/scripts/procexp.py, py/desispec/scripts/sky.py, py/desispec/sky.py
- option to reject cosmics in 1D spectra (if gradient sharper than PSF from resolution matrix) in fiberflat, sky model, and frame processing.
- py/desispec/scripts/extract.py , change default option: do not decorrelate fibers (because this is biasing)
those changes allow a <5% catastrophic failure rate for all targets. tested on >1million targets.
=> Running a month of data3

py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/qas.py, py/desispec/test/test_ql_qa.py
Thanks @rstaten, @samikama for updating the dictionaries for references and status.  This PR fixes a couple glitches in the placement of _REF and _STAT reference and status QA fields into PARAM and METRICS blocks, respectively.  This looks ready to merge.
=> Move QA status to METRICS block and references to PARAMS block

doc/changes.rst, py/desispec/io/util.py, py/desispec/test/test_io.py
Fixes two bugs in `desispec.io.util.write_bintable`, and adds tests that would have caught them:
* extname=None previously didn't work; now it does
* header comments got dropped when writting
=> write_bintable bug fix when extname=None

py/desispec/scripts/group_spectra.py, py/desispec/test/old_integration_test.py
This PR:
* fixes `desi_group_spectra` which was broken by the merge into master from PR #473.  I swear I tested it in the branch, but either my tests were incomplete or the merge with master broke it.  This PR restores it to working with the integration test.
* fixes the redshift accounting at the end of the old integration test, which was broken by the removal of desispec.zfind (part of the knock-on-effects of removing bricks).
I'm re-running an integration test at NERSC now to double check before merging this, but opening the PR now to get Travis crunching too.
=> fixes grouping and integration test

py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_greysurvey.yaml, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/qlconfig.py, py/desispec/test/test_ql_qa.py
This PR implements a requested modification by @rstaten to the SNR QA which calculates the residual of each target with respect to the fit of SNR vs. imaging mag.  These residuals are provided now in the output list of QA metrics.  A plot of residual in RA, Dec is also provided to indicate any gradient with position in the focal plane.  
Results corresponding to the current implementation can be found at:
https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/Results
This update is intended to be the last before we request a desispec tag to freeze versions for the next round of QLF development.  Once outstanding questions are addressed, I will merge this PR.
=> Ql update qas

bin/desi_add_scores, py/desispec/frame.py, py/desispec/io/frame.py, py/desispec/io/util.py, py/desispec/scripts/extract.py, py/desispec/scripts/procexp.py, py/desispec/scripts/specscore.py, py/desispec/specscore.py, py/desispec/test/test_extract.py, py/desispec/test/test_scores.py
This PR for issue  #484
Scores are computed in desispec/specscore.py
- The following simple scores are computed for uncalibrated spectra
- SUM_COUNTS  = sum of counts in  wavelenght range
- MEDIAN_COUNTS per A  = median of counts/(bin size in A) in  wavelenght range
- MEDIAN_SNR per sqrt(A) = median of sqrt(ivar)*counts/sqrt(bin size in A)  in  wavelenght range
- The following simple scores are computed for calibrated spectra
- INTEG_FLUX  = sum of flux*(bin size in A) in  wavelenght range
- MEDIAN_FLUX  = median of flux in  wavelenght range
- MEDIAN_SNR per sqrt(A) = median of sqrt(ivar)*flux/sqrt(bin size in A)  in  wavelenght range
The wavelength range are hardcoded in  desispec/specscore.py
```tophat_wave={"b":[4000,5800],"r":[5800,7600],"z":[7600,9800]}```
- Scores are saved in HDU …
=> Add scores in frames

py/desispec/resolution.py
Fixes issue #468.
But I will open another issue on this because it is dangerous to have the constructor of Resolution interpret differently the data based on the input data shape.
=> fix bug in _gauss_pix routine

py/desispec/cosmics.py
Simple change to default arguments of cosmic ray finder , and propagate correctly dilate option.
The result is more cosmic ray flagged (on sims), and a reduction of redshift failures for ELGs
(see month5 prod result in orange in the figure below).
=> more aggressive cosmic ray rejection default options

doc/changes.rst, py/desispec/qa/qa_plots.py, py/desispec/qa/qalib.py
`scipy.stats.chisqprob` is deprecated; replace with `scipy.stats.distributions.chi2.sf` instead for compatibility with scipy 1.0.
=> replace deprecated scipy.stats.chisqprob

.travis.yml, py/desispec/io/meta.py, py/desispec/io/spectra.py, py/desispec/pixgroup.py, py/desispec/scripts/group_spectra.py, py/desispec/spectra.py, py/desispec/test/test_pixgroup.py, py/desispec/test/util.py
Opening this PR for review while I do the final cleanup (e.g. adding unit tests).
This PR is a complete rewrite of `desi_group_spectra` for several reasons:
* propagates SCORES tables from cframe files into spectra files
* 40x faster by using fitsio, optimized data appending, and smarter "do I really need to do this frame?" logic
* isolates "which spectra files need to be updated" logic into a single function, which could be replaced in a future update with a spectro-processing DB query
Known issues I want to fix before merging:
* no unit tests (I believe that was true of the previous version too)
* `--nights` option became `--night` (easy to fix)
Known issues that may wait for a further update.
* appending a new night that is completely missing one spectrograph channel for
every frame, …
=> new desi_group_spectra

py/desispec/pixgroup.py, py/desispec/scripts/group_spectra.py, py/desispec/test/test_pixgroup.py
This PR fixes two bugs with spectral regrouping that were introduced in PR #505:
* `--reduxdir` option was broken
* output spectra files didn't work with redrock because uncompressed uint32 HDUs can't be read with memmapping due to the BZERO / BSCALE transformations.
The updated implementation here also works around a fitsio bug esheldon/fitsio#150.
My penance for introducing the bugs in PR #505 was to write additional unit tests in this PR that would have caught them.
=> fix --reduxdir; fix fitsio compressed output

py/desispec/scripts/extract.py
* Insert an optional `timing=None` argument.  If this argument is a
`dict` then it will be updated with timing information while the
function is running.
* Mark points in time for various phases including `read_input`,
`preparation`, `total_extraction_time`, `total_output_time`,
and `merge` and compute elapsed time from differences.
* Marks and some timing computations are done whether or not any
`timing` argument is passed, but it is only set if a `dict` is
passed.  Any other type of argument, the timing data is lost.
In the long run a more uniform strategy for collecting timing data
should be considered and these changes supplanted by that, but this
is good for present purposes of understanding where the code is
spending its time at various concurrencies.
=> Add extract timing hook

py/desispec/parallel.py
When redirecting stdout to a file, loop over all registered loggers and redirect their outputs.  When exiting the context manager, verify that no new loggers have been added during the redirection.
This fixes https://github.com/desihub/desiutil/issues/98 as long as user code does not create new loggers while being redirected.  The redirection code will raise an exception if this happens.  A second-order fix to this would be to pre-create all possible loggers.
=> Fix logger redirection

py/desispec/scripts/sky.py, py/desispec/sky.py, py/desispec/test/test_sky.py
Implemented several routines to fit a non-uniform sky.
See issue #368 for details.
=> Non uniform sky

py/desispec/qa/qa_plots.py
Small fix in QA plotting for matplotlib 2.1.2.
Some tests call `exposure_map` with a `metric` that has an extra length-1 dimension compared to the input `x` and `y`, e.g. metric.shape=(10,1,2) vs. x.shape = (10,2) .  matplotlib 2.0.2 gracefully collapsed this dimension; matplotlib 2.1.2 does not.  This PR forces the shapes to match so that the plotting doesn't crash.
=> minor QA fix for for matplotlib 2.1.2

doc/changes.rst, py/desispec/database/datachallenge.py
This PR updates the results DB loading for desitarget 0.19.0, where OBSCONDITIONS is no longer included as a column in the target catalog.
While making changes for non-backwards compatible transitions in DB loading, I also updated `load_zcat` and `load_fiberassign` to fix #481.  This change makes these functions more like the other loading functions which aren't tied to a specific datachallenge directory structure.  
This PR doesn't go all the way to loading the single merged zcat files instead of the individual redrock zbest outputs; it just makes the minimal change to make the loading more directory agnostic and fix the old_integration_test along the way.
This requires an update to the minitest notebook (different repo) which I will include after finishing PRs for fiberassign and …
=> update results db loading for desitarget 0.19.0

bin/desi_update_spectra
At @julienguy's request, This PR adds a new `desi_update_spectra` to convert a list of frame files into an output spectra.fits file for a requested healpixel.  It is basically a lower level version of the pre-existing `desi_group_spectra`, which operates per night and does some fancy frame caching.  Example usage:
```
#- Create a new spectra file with data from some frames for healpix 5300
cd /project/projectdirs/desi/datachallenge/reference_runs/18.2a/spectro/redux/mini/exposures
desi_update_spectra --infiles 20200315/00000006/cframe-*9-*.fits \
--outfile $SCRATCH/temp/spectra.fits --healpix 5300
#- Add some more frames to that same file:
desi_update_spectra --infiles  20200315/00000011/cframe-*7-*.fits \
--outfile $SCRATCH/temp/spectra.fits --healpix 5300
desi_update_spectra --infiles …
```
=> add desi_update_spectra

py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/qlconfig.py, py/desispec/test/test_ql_qa.py
This PR 
- updates the keys for the QL QA metrics as defined in the new model
- removes the amp level granularity of the 1D level QAs
Note: Few of the new keys are placeholders that preserves the data structure but need to be calculated correctly. That will be addressed in subsequent update. At the moment this will facilitate for the QLF implementation. @rkehoe @Srheft Please review and comment if you see any inconsistencies or other issues.
=> Ql drilldown metrics update

py/desispec/pipeline/scriptgen.py, py/desispec/scripts/pipe.py
If the requested number of tasks for script generation is too large to fit in the specified queue and runtime, split this into multiple job scripts. Generated task lists and scripts are now written to a datestamped directory.  Closes #528 and #532 .
=> Job splitting

py/desispec/pipeline/defs.py, py/desispec/pipeline/scriptgen.py, py/desispec/pipeline/tasks/redshift.py, py/desispec/scripts/pipe.py, py/desispec/scripts/pipe_exec.py, py/desispec/test/integration_test.py, py/desispec/trace_shifts.py
This PR provides some file and directory naming cleanup:
* remove colons from spectro pipeline output directory and file names since they are a special character for Unix.
* old: `run/scripts/redshift_20180328-00:28:04/run_20180328-00:28:04.log`
* new: `run/scripts/redshift_20180328-002804/run_20180328-002804.log`
* the new scheme is admitted less obviously readable as a time, but easier to work with when cutting and pasting and browsing directories with tab completion.
* use `desispec.io.findfile()` to get correct redrock hdf5 output file name
Additional features that came along for the ride while debugging the above:
* Fixed "fail" vs. "failed" typos in pipeline state tracking
* Added a `--skip-psf` option to `desispec.test.integration_test` for testing without spexec installed
=> spec pipeline file/dir naming cleanup

doc/changes.rst, etc/desispec.module
The new spectro pipeline needs $DESI_CCD_CALIBRATION_DATA to be set for PSF fitting (and maybe trace shifting too?).  This PR updates the module file to set that to $DESI_ROOT/spectro/ccd_calibration_data/trunk .
In the future for real productions we should tie this to tags of that product, but this gets a placeholder in there to enable desiInstall'ed modules to have a working environment.
=> module file set DESI_CCD_CALIBRATION_DATA

py/desispec/pixgroup.py, py/desispec/scripts/group_spectra.py, py/desispec/scripts/procexp.py
This PR
* fixes #565 by adding HPXNSIDE, HPXPIXEL, HPXNEST keywords and restoring DEPNAME** and DEPVER** keywords to the primary HDU of hte output spectra files
* fixes #542 by restoring the BUNIT keywords in the output spectra files
* corrects the FLUX units in the output frame files
=> restore BUNIT, HPXNSIDE, HPXPIXEL keywords

doc/changes.rst, py/desispec/pipeline/tasks/redshift.py
This PR fixes #573 by allowing the pipeline wrapper of redrock to use the full number of cores per node instead of just 20 (which I'm guessing was a leftover from copying the extraction task as a template for the redshift task).
This was especially problematic for the minitest where the largest healpix dominates the overall runtime of the redshift fitting step.  For a large production runs with approximately equally sized pixels it wouldn't have mattered as much, though splitting pixels across nodes would probably still carry some performance penalty.
=> allow redrock to use a full node per healpix

py/desispec/pipeline/run.py, py/desispec/pipeline/scriptgen.py, py/desispec/scripts/pipe.py, py/desispec/scripts/pipe_exec.py
This adds extra checks to desi_pipe_exec to ensure that it exits with a non-zero return code in the case of all tasks failing or having zero tasks that are ready.  A non-zero return code causes the srun process and the slurm script to exit with a non-zero return.  Job dependencies now use "afterok" to exit if one of the jobs fails completely.  There are also checks in place now that refuse to create scripts with zero tasks.  Closes #569 .
=> Small fixes to handle job dependencies and failures

doc/changes.rst, py/desispec/frame.py, py/desispec/io/frame.py, py/desispec/io/meta.py, py/desispec/io/qa.py, py/desispec/qa/html.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_multiexp.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qa_prod.py, py/desispec/qa/utils.py, py/desispec/scripts/qa_frame.py, py/desispec/scripts/qa_prod.py, py/desispec/scripts/skysubresid.py
Changes to offline QA code, primarily to speed up performance
but also to enable testing within the mini Notebook's.  Here are
the specific changes:
* Add option to load Frame without reading Resolution matrix
* Refactor offline QA to use qaprod_dir more sensibly
* Include hooks in QA to previous fiberflat file location (calib2d)
* Inhibit scatter plot in skyredidual QA
Offline QA code figure generation now takes 7.5min on reference run 18.2 on cori
=> Speedup offline QA without Truth

py/desispec/scripts/preproc.py, py/desispec/test/old_integration_test.py
preproc is now a separate pipeline step and not a part of pixsim (the option was removed in desihub/desisim#354).  This PR fixes that for the old integration test (the new integration test and main spectro pipeline already did that).
=> preproc separate from pixsim

doc/changes.rst, py/desispec/pipeline/__init__.py, py/desispec/pipeline/db.py, py/desispec/pipeline/run.py, py/desispec/pipeline/scriptgen.py, py/desispec/scripts/pipe.py, py/desispec/scripts/pipe_exec.py
This work allows multiple task types to be selected with ```desi_pipe tasks``` and to be passed to the ```script``` and ```run``` commands.  ```desi_pipe run``` will now pack all tasks it receives into a single job script.  The ```desi_pipe chain``` command has a new option ```--pack``` with will generate a single job script with all pipeline steps in it.
Errors are generated in the following cases:
- Multiple pipeline steps are being packed, but one of those steps is already too big for the machine / queue constraints (which requires splitting).
- Multiple pipeline steps are being packed, but the total runtime of all steps exceeds the queue limit.
Note that ```desi_pipe chain``` can **either** chain together separate jobs with one task type per job **or** it can pack all task types into …
=> Job packing and multiple task types

py/desispec/data/quicklook/qlconfig_arcs.yaml, py/desispec/data/quicklook/qlconfig_bias.yaml, py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darkcurrent.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_flat_preproc.yaml, py/desispec/data/quicklook/qlconfig_greysurvey.yaml, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/qas.py, py/desispec/quicklook/qlconfig.py, py/desispec/test/test_ql.py, py/desispec/test/test_ql_qa.py
This PR addresses the issues #580 and #582 . The new format for the metrics block on those QAs are
- Count Pix: {'LITFRAC_AMP': [0.35, 0.37, 0.33, 0.35],
'LITFRAC_STATUS': 'NORMAL',
'NPIX_AMP': [1468029, 1555863, 1410426, 1488293]}
- Count Bins:  {'GOOD_FIBER': [1, 1,  1....,1, 1],  'NGOODFIB': 500,
'NGOODFIB_STATUS': 'NORMAL'}
- This also updates the respective tests and static plots to address new (and single) thresholds  and relevant keys.
@rkehoe @Srheft Please review when you get a chance. Let me know if this meets the requirements of those issues.
=> Ql countqas

.travis.yml, doc/changes.rst, py/desispec/pipeline/tasks/extract.py, py/desispec/scripts/extract.py
Add a psf error option to extractions. This is just to compute the chi2 and the BAD2DFIT mask bit, it's not used in the pixel weights (need merge of specter similar PR).
=> Add a psf error option to extractions 

py/desispec/pipeline/db.py, py/desispec/pipeline/prod.py, py/desispec/pipeline/scriptgen.py, py/desispec/scripts/night.py, py/desispec/scripts/pipe.py
desi_pipe task and chain options now accept an exposure ID.  This can be used for fine-grained task selection.  Note that not all exposure types are valid for all pipeline steps.  For example, selecting psf tasks for a science exposure will return an empty list of tasks.  I addressed another issue (#591) while working on this.  Closes #596 and closes #591.
=> Operate on a single exposure

bin/desi_end_night, bin/desi_fake_dts, bin/desi_night, bin/desi_start_night, bin/desi_update_night, doc/changes.rst, py/desispec/parallel.py, py/desispec/pipeline/db.py, py/desispec/pipeline/scriptgen.py, py/desispec/pipeline/tasks/base.py, py/desispec/pipeline/tasks/preproc.py, py/desispec/pipeline/tasks/psfnight.py, py/desispec/scripts/night.py, py/desispec/scripts/pipe.py, py/desispec/test/test_scripts.py, py/desispec/util.py
This is a re-write from scratch of the nightly scripts, and includes a "desi_fake_dts" script to copy data into DESI_SPECTRO_DATA at regular intervals.  Do not merge yet.  I have some some rough tests, but the queue time for full exposures has hampered testing.
As previously discussed with @sbailey , I am going to add "--spectrograph" options to desi_pipe and desi_night.  This will allow processing a much smaller set of data for testing, at least up through calibrated frames.  Hopefully that will enable better testing and finding of small bugs.
=> Rewrite of nightly scripts

py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/palib.py
This PR addresses shortcomings in QL when resampling to a fixed grid.  Results on arc and continuum lamp sims now agree at all wavelengths with input native grid, as in attached plots.
[QLgrid.pdf](https://github.com/desihub/desispec/files/2020818/QLgrid.pdf)
@Srheft,  @rstaten, please test this rigorously and on science data.
=> Qlresample

.travis.yml, doc/changes.rst
This PR is just updates to changes.rst and the specter version used in travis testing, but running via a PR to make sure that Travis is happy before making the 0.21.0 tag.
=> changes.rst and travis updates prior to 0.21.0 tag

doc/changes.rst, py/desispec/io/util.py
This PR fixes #522.  Files written with `desispec.io.util.write_bintable()` will have `EXTNAME = 'PRIMARY'` by default in HDU 0.  The value can be set with the keyword `primary_extname`.
=> Set EXTNAME on primary HDU

py/desispec/cosmics.py
Solves issue #612 . Reduced memory usage by a factor 4  using numba in the cosmic ray finder.
=> cosmic ray finder is faster uses less memory with numba

py/desispec/pipeline/scriptgen.py, py/desispec/scripts/pipe.py
This PR updates the edison realtime queue config to be 25 nodes instead of the previous 10.  This is needed for testing of the data transfer -> spectro pipeline.
@tskisner and/or @weaverba137 may have already done this in a separate branch, in which case they can close this PR.
Note: the testing will need this PR or equivalent, but it doesn't require the latest desiconda which isn't installed on edison yet.
=> edison realtime queue 25 nodes

py/desispec/trace_shifts.py
Small update for traceshifts to support PSF files that only have XTRACE and YTRACE HDUs but not a PSF HDU.
=> traceshift support PSF files with only traces but no PSF HDU

py/desispec/database/redshift.py
This PR fixes desihub/desitest#12 by updating the extension names.  Also, the extension names will no longer be hard-coded, except as defaults.  Updating the data model is a separate ticket, desihub/desidatamodel#51.
=> Update fiberassign extension name

doc/changes.rst, py/desispec/database/redshift.py
This PR fixes desihub/desitest#13 by allowing rows to be filtered using an arbitrary function.  Specifically this is to exclude rows in the ZCATALOG file that have TARGETID = -1.
=> Add row filter capability to database loader

doc/changes.rst, etc/desi_nersc_pipetest.py, py/desispec/scripts/night.py, py/desispec/scripts/pipe.py
This work: 
- Add new "desi_pipe go" command, which attempts to submit
a full set of jobs to process an entire production.  This
runs 3 jobs per night and then a final redshift job. The
dependencies are tracked within a night, and the redshift
job depends on the calibration jobs from all nights.
- If --nersc option is not specified, check NERSC_HOST
environment variable.
- Improve help message for desi_pipe, to better describe
commands as "high-level" vs "low-level".
You can now do:
```
$>  desi_pipe create <options>
$>  desi_pipe go
```
and all jobs needed to process the full production will be submitted in the regular queue on the current host.  @sbailey and @julienguy , comments welcome.
=> Small pipeline usability improvements

bin/desi_night, doc/changes.rst, py/desispec/pipeline/control.py, py/desispec/pipeline/db.py, py/desispec/pipeline/scriptgen.py, py/desispec/scripts/night.py
This PR increases the maximum jobtime for the edison realtime queue to enable redshifts to be run in the realtime queue instead of the debug queue.  It also adds more debug-level logging statements used for testing the job timing.
For kicks, here is a visualization of the realtime job timing for a summer night (May 15 2020 from the surveysims).  We get behind while processing the initial flood of calibration data and then catch up throughout the night with redshifts available about 2 hours after sunrise.  There are some job order anomalies that NERSC is helping us track down.  i.e. "redshifts by lunch" may become "redshifts by breakfast".
=> increase job maxtime in realtime queue

doc/changes.rst, py/desispec/qa/qa_quicklook.py
Small change but going via a PR for the record:
For efficiency, desihub/specter#69 changed the TraceSet object used by the PSFs to require either scalar or numpy arrays, but not lists or tuples (it was spending O(1%) of its time type checking, which would add up to millions of CPU hours over the lifetime of DESI...).  This inadvertently broke quicklook which had been passing in a list of wavelengths instead of an array of wavelengths.  This PR fixes that by casting the list to an array before passing to specter PSFs.
=> fix QL for specter list vs. array change

doc/changes.rst, py/desispec/io/fibermap.py
Companion to desihub/desitarget#338 and desihub/desitarget#341 to support the changing names of standard star bits: STD_FSTAR (old) vs. STD (recent) vs. STD_FAINT (new).
=> support STD/STD_FSTAR/STD_FAINT

py/desispec/io/__init__.py, py/desispec/io/xytraceset.py, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/arcprocess.py, py/desispec/quicklook/palib.py, py/desispec/quicklook/procalgs.py, py/desispec/quicklook/qlboxcar.py, py/desispec/test/test_extract.py, py/desispec/test/test_qlextract.py, py/desispec/xytraceset.py
Replace all instances of quicklook.qlpsf.PSF by in quicklook , modify read_xytraceset and add write_xytraceset.
This PR fixes the issue #681 .
=> xytraceset in quicklook

etc/desi_nersc_pipetest.py, py/desispec/qproc/__init__.py, py/desispec/scripts/night.py, py/desispec/scripts/pipe.py, py/desispec/test/integration_test.py
Add --shell option to desi_pipe, desi_night, and both integration tests, so that we can run those on the NERSC systems from serial bash scripts.  Also add missing qproc.__init__.py
Closes #683 
Closes #678
=> Add option to force generation of bash scripts instead of slurm scripts

py/desispec/pipeline/control.py, py/desispec/pipeline/tasks/psfnight.py, py/desispec/pipeline/tasks/starfit.py, py/desispec/scripts/pipe.py, py/desispec/scripts/pipe_exec.py
Several desi_pipe small bug fixes + the functionality ```desi_pipe go --resume ``` to
resume a full production (a yearly data assembly for instance) after some code improvements, or after a NERSC outage. 
There is still some work needed to be able to run smoothly a full data assembly, but that's for another day.
=> Several desi_pipe fixes + desi_pipe go --resume 

.travis.yml, py/desispec/test/integration_test.py, py/desispec/test/old_integration_test.py
Recent desisim PRs updated the simspec format to keep object metadata in different HDUs for different template types, since they have different columns.  This PR fixes the desispec integration tests to look for the OIIFLUX in the new TRUTH_ELG HDU instead of the original TRUTH HDU.
Note: LRGs also have OIIFLUX in their truth metadata, but that isn't used by the integration test so this just checks in the ELG case.
=> fix [OII] flux parsing for integration test

py/desispec/pipeline/control.py, py/desispec/pipeline/db.py, py/desispec/scripts/pipe.py
Adding option ```desi_pipe sync --force-spec-done``` to change the state of spectra and redshift tasks if spectra files exist even in case there is no cframe files on disk. This is useful to redo a redshift run starting from a pre-existing prod.
=> Desi pipe sync spectra

py/desispec/data/quicklook/qlconfig_arc.yaml, py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_graysurvey.yaml, py/desispec/data/quicklook/qlconfig_science.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/__init__.py, py/desispec/quicklook/merger.py, py/desispec/quicklook/procalgs.py, py/desispec/quicklook/qas.py, py/desispec/quicklook/qlconfig.py, py/desispec/quicklook/quicklook.py
This PR:
* updates arc configuration file
* migrates to science config for all three science programs [dark,gray,bright]
* moderate edits to XWSigma and SNR, calculation algorithm and few other QA calculations
@sbailey please see [ticket #698](https://github.com/desihub/desispec/issues/698). 
Keeping with our general rule, this PR will be tested in QLF  [with new format data] before merge.
=> QL config update and fibermap conform

py/desispec/data/quicklook/qlconfig_arc.yaml, py/desispec/data/quicklook/qlconfig_brightsurvey.yaml, py/desispec/data/quicklook/qlconfig_darksurvey.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/data/quicklook/qlconfig_graysurvey.yaml, py/desispec/data/quicklook/qlconfig_science.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/__init__.py, py/desispec/quicklook/merger.py, py/desispec/quicklook/procalgs.py, py/desispec/quicklook/qas.py, py/desispec/quicklook/qlconfig.py, py/desispec/quicklook/quicklook.py
This PR restores the changes removed with https://github.com/desihub/desispec/pull/701 and has all the changes from  https://github.com/desihub/desispec/pull/699.
The commit history and comments can be found on the other pull request.
=> QL config update and fibermap conform - #699 changes

doc/changes.rst, py/desispec/database/redshift.py
This PR is a workaround for desihub/desitarget#397.
Do not merge yet.  I also need to review changes to the data model (for example, the target table has added about 60 columns).
=> Workaround for bad flux values

bin/desi_zcatalog, doc/changes.rst, py/desispec/qa/qa_quicklook.py
This PR fixes desihub/desisim#448, where `desi_zcatalog --fibermap` didn't work for the new format fibermap.  This implementation works on zbest files with both old and new format fibermap tables, and adds columns `RA`, `DEC`, `FLUX_G`, `FLUX_R`, `FLUX_Z` in both cases, even though the old version used to write `MAG` instead.
Unlike the discussion in desihub/desisim#448 this morning, I actually have tested it this time, using the 18.7 (old) and 18.11 (new) reference runs in /project/projectdirs//desi/datachallenge/reference_runs/ .
@tetourneau please take a look if you'd like.  Otherwise I'll merge tomorrow morning.
=> fixes desi_zcatalog --fibermap for new format fibermap

doc/changes.rst, py/desispec/scripts/mergebundles.py, py/desispec/scripts/stdstars.py
This PR fixes #728 by supporting the mockobs fibermap format which had several fewer columns than the latest format.  This required 2 changes:
* mergebundles is now fibermap format agnostic, simply merging whatever it finds (the original problem in #728).
* stdstars will assume PHOTSYS='S' and MW_TRANSMISSION_G/R/Z=1.0 and EBV=0.0 if those columns are missing (while still printing a warning).
This PR is only for convenience for continuing to use the mockobs dataset for tests (e.g. data transfer + spectro pipeline testing); future simulations will include those columns.  This PR does *not* attempt to support the original fibermap format (e.g. in the redwood sims), though that could be done in a separate PR.
Tested with the following that fails under master but works with this branch:
``` …
```
=> support slightly older fibermap too

doc/changes.rst, py/desispec/qa/qa_exposure.py, py/desispec/qa/qa_frame.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qa_plots_ql.py, py/desispec/qa/qalib.py
Fussed with offline S/N QA to handle new data model
for QA metrics (which already accommodates new 
`DESI_TARGET` bits in `SNRFit`.
Now back where we were.  Example QA using 18.11 is attached.
Other QA appears to have been unaffected.
=> Refactor QA Offline for targeting bits

.travis.yml, doc/changes.rst, py/desispec/database/redshift.py
desitarget pull requests #429 (data) and #439 (sims) renamed target columns `PRIORITY` and `NUMOBS` to `PRIORITY_INIT` and `NUMOBS_INIT` (good).  This PR updates desispec db loading to use those names too.
Requires desitarget/0.27.0 or later for DB loading.
=> DB rename PRIORITY -> PRIORITY_INIT

py/desispec/quicklook/arcprocess.py
This PR minimizes the warnings generated by resolution fit. The algorithm runs fine, but if a line is not able to be fit, we do not need to log extra information.
@rkehoe Please check this and merge when possible.
@felipelm At your convenience, please include this update in your latest QLF version.
=> minimize warnings for resolution fit

py/desispec/data/quicklook/qlconfig_arc.yaml, py/desispec/data/quicklook/qlconfig_flat.yaml, py/desispec/qa/qa_quicklook.py, py/desispec/quicklook/qlconfig.py
This PR will update the specifications for specific QA scalar metrics used in calibration exposure pipelines of QuickLook. 
Since we are updating desispec one last time, this PR includes a minor update to re-include a drill down metric in Count_Spectral_Bins that should still be present, termed TOTCOUNT_FIB.  There is no need for any plotting of this metric.
=> Adjust Calibration Exposure QA Specifications

py/desispec/qa/qa_frame.py
PR #751 updated the inputs and outputs of `desispec.qa.qalib.SNRFit`, which broke the offline QA.  This PR fixes that.  QA needs more comprehensive unit tests to catch stuff like this, though I haven't tried to add that to this PR.
=> fix offline S2N QA for changes to qalib.SNRFit

py/desispec/calibfinder.py, py/desispec/pipeline/tasks/psf.py, py/desispec/scripts/specex.py
This PR updates the spectroscopic pipeline to work with the new spectro calib finder.  In particular, the pipeline no longer specifies the PSF to use when calling `desi_compute_psf`.  Instead, `desi_compute_psf` uses `desispec.calibfinder.findcalibfile` to look up the PSF to use based upon the input arc image headers, while still supporting overriding that choice for testing purposes.
Coming along for the ride, calibfinder now also supports using the `NIGHT` keyword instead of `DATE-OBS`.
=> update pipeline+specex for new calibfinder

py/desispec/fluxcalibration.py, py/desispec/test/integration_test.py, py/desispec/test/old_integration_test.py
move to a common definition of speedoflight. Step toward fixing issue https://github.com/desihub/desisim/issues/477.
The remaining one I can find, but I don't yet understand is the following.
@sbailey, what is that number `2.9979e18`? Is that `c in A/s`
```
<me>/Programs/desi/code/desispec> grep '2.99' -ri * --include \*.py
py/desispec/fluxcalibration.py:    ZP_fnu = ZP_flambda * wave**2 / (2.9979e18)  # c in A/s
```
=> import speed of light from scipy

.travis.yml, py/desispec/fluxcalibration.py, py/desispec/pipeline/run.py, py/desispec/pipeline/scriptgen.py, py/desispec/pipeline/tasks/base.py, py/desispec/pipeline/tasks/psf.py, py/desispec/qa/qa_plots.py, py/desispec/qa/qa_quicklook.py, py/desispec/qa/qalib.py, py/desispec/quicklook/procalgs.py, py/desispec/scripts/fluxcalibration.py, py/desispec/scripts/pipe_exec.py, py/desispec/scripts/preproc.py, py/desispec/scripts/stdstars.py
This PR adds support for SV data, in particular target catalogs and fibermaps with SV1_DESI_TARGET instead of DESI_TARGET.
There are also some additional pipeline logging message and small usability updates, e.g. optionally deriving the tasktype from the input tasks rather than requiring a redundant --tasktype option.
Tested with a mini SV run of 3 tiles x 11 exposures.
=> Support for SV1_DESI_TARGET

py/desispec/test/test_ql_qa.py
This PR addresses #774, removing temporary files generated by QuickLook unit tests that are not removed if test_ql_qa.py is killed while running.
- Note: only the files test-pix-abcde.fits and test-raw-abcde.fits mentioned in #774 are removed as the other files are not generated by test_ql_ql.py.
@rkehoe, @sbailey  Please review and/or provide any necessary additional comments.
=> remove leftover files when rerunning unit tests

py/desispec/io/meta.py, py/desispec/test/test_io.py
This PR fixes #779, to support `io.findfile(..., camera='r9')` and `io.findfile(..., camera='r', spectrograph=9)`.  Previously only the former was supported.
For context, the `spectrograph` argument was previously only used for stdstars, which span b/r/z and thus don't request a camera.
=> support findfile camera+spectrograph as b,r,z + 0-0 instead of b0,r1..z9

py/desispec/heliocentric.py, py/desispec/pipeline/tasks/extract.py, py/desispec/scripts/extract.py
- I resorted to use the routines of astropy.coordinates (and astropy.time). It is quite slow, slower than what a custom implementation would be, but it has the advantage of being debugged (hopefully).
- In the routine heliocentric.py , there is a main() function to compare with the IDL idlutils routine used for the BOSS/eBOSS projects. After correcting for a difference of sign due to different definition, the max difference I obtained for a range of coordinates is <0.2 km/s.
- The routine is called in scripts/extract.py 
- the heliocentric correction is computed based on the RA,DEC,MJD of the observations found in the preprocessed image header (coordinates of the center of the field of view)
- the wavelength of the extraction grid are the nominal wavelength array *divided* by the …
=> Heliocentric correction 

.travis.yml, py/desispec/bootcalib.py, py/desispec/calibfinder.py, py/desispec/io/params.py, py/desispec/io/qa.py, py/desispec/maskbits.py, py/desispec/qa/qalib.py, py/desispec/quicklook/qlconfig.py, py/desispec/quicklook/quicklook.py
Similar to desihub/desitarget#475 and desihub/desimodel#110, this PR replaces `yaml.load` with `yaml.safe_load` to get rid of deprecation warnings and clean things up before `yaml.load` completely disappears. `yaml.safe_load` has been around since 2006, so I think we're safe with any versions of yaml that we might be using out in the wild.
=> yaml.load -> yaml.safe_load

py/desispec/cosmics.py
This PR enables numba to understand the types used within `desispec.cosmics._reject_cosmic_rays_ala_sdss_single_numba` and `dilate_numba`.  I don't understand why it couldn't handle the previous more obvious `dtype=int` and `dtype=bool`, but that resulted in slews of numba deprecation warnings about falling back to object mode but finding lifted loops blah blah blah.
A secondary benefit of this is that it allows `@numba.jit(nopython=True)` which makes cosmic ray rejection ~2x faster resulting in ~20% faster preprocessing.
=> help numba know the types

py/desispec/pipeline/db.py, py/desispec/pipeline/scriptgen.py, py/desispec/pipeline/tasks/redshift.py, py/desispec/pipeline/tasks/spectra.py, py/desispec/scripts/pipe.py
Three bug fixes to the pipeline:
- no more overwriting the same job when multiple jobs of same task type are written
- db.getready checks  whether 'waiting' spectra or redshift are actually 'done'
- the spectra and redshift tasks modify the healpix_frame table when setting their state to 'done' in same transaction to avoid  getting an unconsistent state of the db when a job is crashing or is halted. The healpix_frame table modification was previously performed by rank 0 after all tasks are finished. The goal was to reduce overloading the db access, but this was fragile.
One convenient new feature for expert debugging:
- `desipe_pipe query` to directly query the db with sql syntax.
=> Desi pipe getready fix

bin/desi_coadd_spectra, bin/desi_inspect, py/desispec/coaddition.py, py/desispec/frame.py, py/desispec/scripts/coadd_spectra.py, py/desispec/scripts/pipe.py, py/desispec/test/test_coadd.py
Add functions and a script to coadd spectra. The intention is to add this as a pipeline task.
This inherits from the work of N. Busca, D. Kirkby and others, with large improvements on CPU time when resampling to another wavelength grid using 1D spectro-perfectionism and the divide and conquer method.
```
desi_coadd_spectra --help
usage: Coadd all spectra per target, and optionally resample on linear or logarithmic wavelength grid
[-h] [-i INFILE] [-o OUTFILE] [--nsig NSIG] [--lin-step LIN_STEP]
[--log10-step LOG10_STEP] [--wave-min WAVE_MIN] [--wave-max WAVE_MAX]
[--fast]
optional arguments:
-h, --help            show this help message and exit
-i INFILE, --infile INFILE
input spectra file
-o OUTFILE, --outfile OUTFILE
output spectra file
--nsig NSIG           nsigma rejection threshold …
```
=> Spectra coaddition

py/desispec/pipeline/plan.py, py/desispec/pipeline/run.py, py/desispec/pipeline/scriptgen.py
Do not merge this yet.  Test jobs are queued.
This change attempts to take the (duplicated in two places) runtime calculation of work distribution and isolate it with better comments and clearer program flow.
=> Move common calculation of runtime distribution to a separate function

py/desispec/pipeline/control.py, py/desispec/scripts/pipe.py
The goal of this new command is to allow faster querying of states and logs.  This is a real chore currently for large productions.  Based on the number of task types and number of nights specified the status command will print different levels of detail.  The `--task` option prints the full task log for that task and (soon) will print the job ID and the job log location.  Some examples are probably best:
```
$ desi_pipe status
```
```
$ desi_pipe status --tasktypes sky,starfit
```
```
$ desi_pipe status --nights 20200108,20200109
```
```
$ desi_pipe status --tasktypes sky --nights 20200108
```
```
$ desi_pipe status --task sky_20200108_b_3_00001148
```
=> Implement a "desi_pipe status" command

py/desispec/pipeline/tasks/base.py
To assist with NERSC debugging I/O failures in jobs, this PR adds a log message at the start of each task with the SLURM job id and node hostname.
I chose INFO level to that we will have it by default in every job, without requiring DESI_LOGLEVEL=debug which prints many many many other log lines too.
=> add hostname and job id to logging

py/desispec/coaddition.py, py/desispec/database/redshift.py, py/desispec/fiberflat.py, py/desispec/io/fibermap.py, py/desispec/io/frame.py, py/desispec/qa/qa_plots.py, py/desispec/sky.py, py/desispec/test/test_sky.py, py/desispec/test/test_spectra.py
This PR updates desispec to adapt to the fiberassign/fibermap rename of DESIGN_X/Y -> FIBERASSIGN_X/Y.  Fixes #819 
I attempted to retain backwards compatibility by intercepting and renaming the old column name in `desispec.io.read_frame()`.  I need to test that more but I'm opening a PR to get the ball rolling in the meantime.
In `desispec.io.fibermap.empty_fibermap` I added a few other columns that were missing (REF_EPOCH, PLATEMAKER_X/Y, ...) and removed a few that were removed upstream (DELTA_X/Y, DESIGN_Q/S, ...).  I found a bunch of columns in upstream targeting that are in the real fiberassign files that aren't in empty_fibermap but also aren't used by the pipeline.  I documented them in a comment but didn't go through the process of adding them all here.
=> Fibermap xy

py/desispec/parallel.py, py/desispec/pipeline/run.py, py/desispec/pipeline/tasks/redshift.py
Call rrdesi with the new --no-mpi-abort feature so that exceptions can be caught by the desispec pipeline and cleanly handled instead of having rrdesi itself call MPI Abort and bring everything crashing down.
Slightly more logging and some stdout flushing comes along for the ride.
=> use rrdesi --no-mpi-abort feature

.travis.yml, py/desispec/io/fibermap.py, py/desispec/io/image.py, py/desispec/scripts/extract.py, py/desispec/scripts/preproc.py, py/desispec/test/test_preproc.py
This PR supports extracting spectra from data without a fibermap (e.g. early CMX arc and flat frames like 20191009/00018082).
* Include a FIBERMAP HDU in the preproc file so that it becomes standalone input for the extractions without having to look back into the raw data directory for the fibermap.
* If the fibermap doesn't exist while preprocessing, create a bare minimum fibermap with the `location:fiber:x:y` mapping for positioners at their home position, using `desimodel.io.load_focalplane` instead of the deprecated `desimodel.io.load_fiberpos`
* extractions continue to support the `--fibermap` argument, but if not provided it will use what it finds in the input preproc file.
=> Support extractions of data without fibermaps

py/desispec/scripts/extract.py
Applies the same changes as #825 to support extractions of CMX data without fibermaps, but this time to `desispec.scripts.extract.main_mpi` so that it works with MPI too.  Tested at NERSC with:
```
datadir=$DESI_ROOT/spectro/data/
export DESI_SPECTRO_REDUX=$SCRATCH/desi/spectro/redux
export SPECPROD=test
night=20191022
expid=00019960
cd $DESI_SPECTRO_REDUX/$SPECPROD/
mkdir -p exposures/$night/$expid
mkdir -p preproc/$night/$expid
desi_preproc -i $datadir/$night/$expid/desi-$expid.fits.fz \
--outdir preproc/$night/$expid
srun -N 1 -n 20 -c 2 -C haswell --qos realtime -t 00:10:00 \
desi_extract_spectra --mpi \
-i preproc/$night/$expid/preproc-b3-$expid.fits \
-p $DESI_SPECTRO_CALIB/spec/sp3/psf-sm4-b-science-slit-20191015.fits \
-o exposures/$night/$expid/frame-b3-$expid.fits
```
=> mpi extract support no fibermap

py/desispec/fiberflat.py, py/desispec/scripts/extract.py, py/desispec/scripts/specex.py
This PR has two pragmatic hacks to facilitate processing CMX night 20191024 data:
* allow the extraction grid to extend slightly off the CCD (issue #833, but not a complete robust solution)
* add a short pause after writing per-bundle PSFs before merging them into the final PSF (issue #835; this change here is a real hand-wavy hack but it might help)
Neither of these is a particularly good solution but it is enough to make progress, and I don't think it makes the situation worse, so I'll pause long enough for Travis tests to pass and then merge unless I hear screams otherwise.  I suggest leaving both #833 and #835 open and not consider this to be a full solution to those.
=> Extraction wavelengths & PSF I/O pause before merging

bin/desi_proc
@julienguy please test this, since you seem quite good at immediately finding the problems that I missed... :)
This PR adds a work-in-progress script `desi_proc` to simplify processing a single exposure independent of other exposures and outside of the constraints of the pipeline (e.g. it works even if there aren't daily arcs/flats).
It looks for data in `$DESI_SPECTRO_DATA/{night}/{expid}/desi-{expid}.fits.fz` (or `--input filename`) and outputs to `$DESI_SPECTRO_REDUX/$SPECPROD/{night}/{expid}/preproc/` and `exposures/` following the same directory structure as the full pipeline (currently not overridable).
Examples are in /global/project/projectdirs/desi/spectro/redux/sjbailey/
It selects the steps to perform based upon the OBSTYPE, which can be overriden with the `--obstype` option. …
=> desi_proc single exposure script

py/desispec/io/raw.py, py/desispec/qproc/qextract.py, py/desispec/scripts/extract.py, py/desispec/scripts/preproc.py, py/desispec/scripts/qproc.py
This PR consolidates how the empty fibermap is created so that qproc and full processing are consistent.  Review carefully.
in particular, the empty fibermap creation is moved into io.read_raw instead of scripts.preproc (because qproc doesn't call scripts.preproc directly).
HACK: in lieu of calibfinder, desimodel, or header keywords actually knowing which petal we're plugged into, this PR adds the mapping.  When calibfinder (or others) know, this could would need to be updated anyway, so I added the mapping in the place that would need to be changed anyway.  Caveat emptor.
Do not merge until:
* tested with desi_proc
* tested with nightwatch
But reviews prior to that are welcome too...
=> qproc use correct fibermap

bin/desi_proc
This PR adds a --batch option to desi_proc which will write and submit a batch script to run desi_proc for that exposure, e.g.
```
[cori01] desi_proc --batch -n 20191030 -e 22954
Wrote /global/project/projectdirs/desi/spectro/redux/sjbailey/run/scripts/night/20191030/sky-20191030-00022954.slurm
Submitted batch job 25461743
```
Until we get fibermaps and arc/flat done sentinel files for the full pipeline + desi_night, this should let us automate processing data with the realtime queue (albeit inefficiently).
=> Batch desiproc

bin/desi_proc, py/desispec/cosmics.py, py/desispec/scripts/trace_shifts.py, py/desispec/trace_shifts.py
* Add options to `desi_proc`:
`--notraceshift`
`--no-extra-variance`
* Job name contains the "cameras" (to avoid overwriting job when running cameras in separate jobs)
* When fitting for trace shifts, only deg=0 corrections are considered (i.e. pure translation). 
* Modified inverse variance used in cross-correlations for trace shifts
=> More desiproc options

bin/desi_proc, py/desispec/cosmics.py, py/desispec/scripts/specex.py, py/desispec/scripts/trace_shifts.py, py/desispec/trace_shifts.py
PR to handle PSF fit with broken fibers.
* Added  option `--broken-fibers` in `desi_compute_psf(_mpi)`.
* Works with master version of specex where the option `--broken-fibers` was added.
* `desi_proc` add this option for PSF fit in keyword `BROKENFIBERS` found in calibration yaml files.
=> Psf with broken fibers

py/desispec/database/redshift.py, py/desispec/io/image.py
This PR bundles two small updates for 19.12 integration:
After ICS upgraded to fitsio 1.0.5, it started writing blank header keywords (previously they were blank strings), which caused problems for desi_qproc (used by nightwatch) on the nights prior to this being fixed.  This PR replaces blank keywords with None when writing the preproc images so that the problem doesn't further propagate downstream.  I have tested this with desi_qroc and verified that the previously blank keywords now pass fitsverify.
We changed the name of the fiberassign files at the start of commissioning (from tile-*.fits to fiberassign-*.fits).  This PR updates the DB loading to look for the new file names.  It does not attempt to be backwards compatible for loading the old file names.  I have tested this with the …
=> Blank keywords & DB loading

bin/desi_proc, py/desispec/preproc.py, py/desispec/scatteredlight.py, py/desispec/scripts/preproc.py
Code to subtract scattered light at the preprocessing level.
```
desi_preproc --scattered-light (--psf PSFFILE) ...
desi_proc --scattered-light ...
````
The method consists in:
- computing a "direct light" mask  centered on the spectral traces of a preprocessed CCD image using a PSF file
- computing a model M = (image * mask ) x K , where K is a tuned convolution kernel adjusted on arc images
- evaluating a calibration polynomial of CCD rows in the space between fiber bundles where there is only scattered light
- the final model is interpolated in the fiber bundles
The algorithm is in `desispec/scatteredlight.py`
Example (blue is the profile of a arc lamp image in NIR for the spectro SM4, and orange is the model)
I still need to optimize the kernel for different cameras so this is not yet …
=> Scattered light

py/desispec/fluxcalibration.py, py/desispec/scatteredlight.py, py/desispec/scripts/stdstars.py
Opening PR on behalf of @julienguy to get his flux calib updates into the fibermap branch, in prep for merging that branch back into master.
Main changes here are
* expanding the set of CMX bits that can be considered as standard stars,
with an upper limit of 50 per petal
* adjusting the scattered light model to be more robust to unmasked cosmics
=> Flux calib updates for fibermap branch

bin/desi_proc, py/desispec/fiberflat.py, py/desispec/fluxcalibration.py, py/desispec/maskedmedian.py, py/desispec/preproc.py, py/desispec/scripts/fluxcalibration.py, py/desispec/scripts/stdstars.py, py/desispec/sky.py, py/desispec/test/test_binscripts.py
Improved robustness of sky subtraction and flux calibration to poorly constrained wavelength regions and dead fibers, selection of standard stars. Also mask out the region between 4300 and 4500A with the throughput dip in the fit of standard stars.
For illustration, throughput per spectrograph of one exposure on a dither sequence (exposure 44565 from 2020/01/27):
=> Calibration

bin/desi_proc, py/desispec/fluxcalibration.py, py/desispec/scripts/fluxcalibration.py
Correct normalization of the average flux calibration in the current situation with a wide range of fiber aperture losses. Also add option to `desi_compute_fluxcalibration` to rely only on the stars with highest transmission for the normalization. This option is used by default in `desi_proc`.
=> Normalization of flux calib

bin/desi_proc
This PR improves the parallelism packing of `desi_proc ... --batch` scripts.
Previously it was run as a single srun command tuned for the extraction step, but this resulted in the later multiprocessing-based `desi_fit_stdstars` being every inefficient because most of the cores were tied up by MPI doing nothing instead of being available for multiprocessing.  This new version splits the script into two srun calls: one massively parallel srun for everything through sky subtraction, and then a separate call with less MPI parallelism but more multiprocessing parallelism for flux calibration.
Additionally, this packs the job into 5 nodes instead of 7, to allow two jobs to run simultaneously in the realtime queue.  extractions become 1.5 minutes slower, while flux calibration becomes 8 minutes …
=> more efficient parallelism packing

bin/desi_average_flux_calibration, bin/desi_proc, py/desispec/scripts/qproc.py
Minor modifications to accommodate for missing seeing and poor airmass sampling when computing and applying the average flux calibration. 
Related to this PR, the average calibration has been saved in the SVN repo there
https://desi.lbl.gov/trac/browser/calib/desi_spectro_calib/trunk/spec/fluxcalib?order=name
(it is the same calibration vector for all spectrographs because their difference of throughput is accounted for in the fiber flat fielding). Corresponding PSF and flatfields also have been updated.
The apparent low throughput is due to the fact we do not have yet fibers on targets to a sufficient precision.
I tested I could run `desi_qproc` with flux calibration (turned on automatically with the `--auto` option) on all 30 cameras (this is checking for typos in the svn yaml files). …
=> Average calibration

py/desispec/io/fibermap.py
This PR makes `assemble_fibermap` more robust to missing input columns from platemaker coordinates files.  e.g. 20200212/00048337/coordinates-00048337.fits doesn't have any FVC-related columns, e.g. FLAGS_CNT_0 or FVC_X_0.
=> more robust to missing columns in coordinates files

bin/desi_proc
This PR makes two changes to desi_proc to make debugging failures a bit more human friendly:
* if `assemble_fibermap` fails (e.g. due to a missing input file), exit immediately
instead of proceeding onto preprocessing and having N>>1 ranks fail with
interleaved messages about missing fibermaps.
* science exposures split the processing into two sruns with different
levels of parallelism -- now if the first step fails, exit the slurm script without
running the second step (which would just fail again with confusingly similar
log messages).
I tested this with `desi_proc --batch --traceshift --scattered-light -n 20200212 -e 48313` which indeed fails due to a science exposure with a missing input coordinates file, but now it exits more cleanly; see …
=> fail early if assemble_fibermap fails

bin/assemble_fibermap, py/desispec/io/fibermap.py
Adds `assemble_fibermap --force` option to keep going and make a basic fibermap even if missing the input coordinates and guide files.
Tested with:
```
assemble_fibermap -n 20200219 -e 51030 -o $SCRATCH/blat.fits
```
--> fails due to missing coordinates file
```
assemble_fibermap -n 20200219 -e 51030 -o $SCRATCH/blat.fits --force
```
--> complains about missing input but moves on anyway and creates a basic fibermap with some zeroed out columns of missing info.
Intended usage:
* standard desi_proc pipeline should expect the required inputs and will still fail if they are missing so that a human will notice
* if we decide that we really want those exposures anyway
* rerun `assemble_fibermap --force ...` for that exposure
* then resubmit desi_proc which will notice that the fibermap now …
=> assemble_fibermap --force option

bin/desi_nightly_redshifts
Adds a script `desi_nightly_redshifts` to run coadds and redshifts per tile per night (issue #889).  This is intended to be run from a batch job (the script itself runs srun multiple times), or to have it create a batch script and submit it:
```
desi_nightly_redshifts --batch YEARMMDD
```
will submit a batch script to the realtime queue to run:
* desi_group_tileframes
* desi_coadd_spectra
* rrdesi (redrock)
It auto-recognizes what tiles have already been run, so you can delete coadds/zbest/redrock files in $DESI_SPECTRO_REDUX/$SPECPROD/tiles/{TILEID}/{NIGHT}/ and resumit and it will redo whatever is left.
Things that could be better, but let's do that as a future PR:
* options to specify queue
* exit with meaningful error message if running without --batch from a login node
@kremin please …
=> add script to run nightly redshifts per tile

bin/desi_proc
Added --most-recent-calib flag that tells desi_proc to look for most recent psfs instead of immediately using a default. Searches backward 30 days before defaulting to the default.
Also corrected IERS lookup failure mode by using desisurvey.utils.freeze_icrs().
=> Mostrecentcalib

bin/desi_proc, py/desispec/fluxcalibration.py, py/desispec/scripts/fluxcalibration.py, py/desispec/scripts/stdstars.py
Several minor changes to improve the flux calibration, the important ones being:
- use only target bits STD_FAINT|STD_BRIGHT|SV0_STD_FAINT|SV0_STD_BRIGHT
- do not use any more option --highest-throughput in call to desi_compute_flux_calibration in desi_proc
- use 3 sigma outlier rejection of stars based on their median throughput by default in compute_flux_calibration
=> Fluxcalib minisv

py/desispec/io/spectra.py, py/desispec/scripts/coadd_spectra.py, py/desispec/specscore.py
This PR
* Adds a SCORES table HDU to coadds, with columns INTEG_COADD_FLUX_B/R/Z, MEDIAN_COADD_FLUX_B/R/Z, and MEDIAN_COADD_SNR_B/R/Z, similar to the scores tables in the frames.  The same columns are generated whether or not it is coadded across cameras.  Fixes #885.
* Adds INFILnnn header keywords with the input files used for this coadd.  Fixes #884.
```
cd /global/cfs/cdirs/desi/spectro/redux/daily
desi_coadd_spectra -i tiles/70004/20200219/cframe-?0-*.fits \
-o $SCRATCH/temp/coadd1.fits --coadd-cameras
desi_coadd_spectra -i tiles/70004/20200219/cframe-?0-*.fits \
-o $SCRATCH/temp/coadd2.fits
```
and then inspecting the coadd*.fits files to verify that they have SCORES HDUs and INFILnnn keywords.
This PR does *not* fix the propagation of the FIBERSTATUS column in the fibermap. …
=> Metadata propagation for coadds

py/desispec/io/fibermap.py
Fixed assemble_fibermap to correctly order columns and output with identical datatypes whether using --force or using real coords files
tested on exposures 51059 and 51060 from 20200219
51059 | 51060
-- | --
TARGETID >i8 | TARGETID >i8
PETAL_LOC >i2 | PETAL_LOC >i2
DEVICE_LOC >i4 | DEVICE_LOC >i4
LOCATION int64 | LOCATION int64
FIBER >i4 | FIBER >i4
FIBERSTATUS >i4 | FIBERSTATUS >i4
TARGET_RA >f8 | TARGET_RA >f8
TARGET_DEC >f8 | TARGET_DEC >f8
PMRA >f4 | PMRA >f4
PMDEC >f4 | PMDEC >f4
PMRA_IVAR >f4 | PMRA_IVAR >f4
PMDEC_IVAR >f4 | PMDEC_IVAR >f4
REF_EPOCH >f4 | REF_EPOCH >f4
LAMBDA_REF >f4 | LAMBDA_REF >f4
FA_TARGET >i8 | FA_TARGET >i8
FA_TYPE uint8 | FA_TYPE uint8
OBJTYPE <U3 | OBJTYPE <U3
FIBERASSIGN_X >f4 | FIBERASSIGN_X >f4
FIBERASSIGN_Y >f4 | FIBERASSIGN_Y >f4
NUMTARGET >i2 | …
=> Fixed assemble_fibermap to correctly order columns with --force

py/desispec/coaddition.py, py/desispec/test/test_coadd.py
updates `desispec.coaddition.coadd` and `.coadd_cameras` to not use input spectra with `fibermap['FIBERSTATUS'] != 0`.  Includes tests.  Fixes #886.
Behavior:
* for a given target, only use input spectra that have FIBERSTATUS==0 (i.e. ICS
thinks that the fiber isn't broken and the positioner is on target)
* in the output, add new fibermap column COADD_NUMEXP with the number of
input exposures that were used.
* if all input spectra for a target have FIBERSTATUS==0, the output coadd is still
created, but with flux = ivar = COADD_NUMEXP = 0.
e.g. 20200219/00051039 sp0 has 84 fibers with FIBERSTATUS != 0.  The same tile on 20200220/00051148 recovered 12 fibers so that there are 72 with FIBERSTATUS != 0.  The resulting coadd has
* 72 spectra with flux=ivar=COADD_NUMEXP=0 and FIBERSTATUS != 0
* …
=> don't use FIBERSTATUS!=0 spectra in coadds

bin/desi_dailyproc, py/desispec/desi_proc_dashboard.py
Include 4 new keywords to desi_dailyproc
```
-e, --skip-expid-file  : 
Relative pathname for file containing expid's to skip.
Automatically triggers '--skip--expids' to be true.
They are assumed to be in a columnformat, one per row.
Stored internally as integers, so zero padding is
accepted but not required.
```
```
--skip-expids  :    Skips this list of expid's and doesn't process them
--skip-today   :    Doesn't search for today's files unless explicitly told to in catchupfile
--do-zeros  :        Processes zeros in addition to arcs, flats, and sciences. If not set, zeros are skipped.
--do-short-scis : Processes all science exposures including those with EXPTIME < 60s. If not set, we skip them.
```
Also handles SPECPROD correctly in both desi_dailyproc and desi_proc_dashboard
Allows you …
=> Dailyproc more control

py/desispec/scripts/coadd_spectra.py
The `infile` argument is declared with the option `nargs='+'` so it's a list. When `len(args.infile)==1` it needs to be subscripted when calling `read_spectra` on the argument.
=> Must subscript infile on call to read_spectra.

bin/desi_proc, py/desispec/fiberflat.py
Changes to desi_proc to interpolate the PSF parameters of the fibers that have been blacklisted from the PSF fit (because broken, too faint, or with a trace on dead column).
This addresses issue #910 .
The code is also ready for the change of keyword in the calib yaml files: BROKENFIBERS to FIBERBLACKLIST.
=> Interpolate bad fibers

py/desispec/io/raw.py
Now find calibration yaml file in preproc and propagate fiber blacklist to fibermap fiberstatus bitmask.
Currently unsure if using the correct petal matching. Identifying fibers in blacklist with row using fibermap column "DEVICE_LOC" as they are both 0-499. Easy fix to FIBER with logic: FIBER % 500, but I didn't know which was correct.
Tested with a science exposure from March 1st:
```
export SPECPROD=kremin
desi_preproc -i /global/cfs/cdirs/desi/spectro/data/20200306/00053613/desi-00053613.fits.fz -o /global/cfs/cdirs/desi/spectro/redux/kremin/preproc/20200306/00053613/preproc-r4-00053613.fits --outdir /global/cfs/cdirs/desi/spectro/redux/kremin/preproc/20200306/00053613 --cameras r4
```
=> Propagate yaml blacklist to fibermap bitmask in preproc

bin/desi_dailyproc, py/desispec/calibfinder.py, py/desispec/fiberbitmasking.py, py/desispec/fiberflat.py, py/desispec/frame.py, py/desispec/io/raw.py, py/desispec/maskbits.py, py/desispec/scripts/fluxcalibration.py, py/desispec/scripts/procexp.py, py/desispec/scripts/stdstars.py, py/desispec/sky.py
Code now uses `fibermask.BADFIBER` bit assigned in `fibermap['FIBERSTATUS'] `for all fibers in the "blacklist" in the calibration yaml file.
Also added a new file `fiberbitmasking.py` that includes logic for altering the flux and ivar or `desispec.frame.Frame` objects implicitly or explicitly.
Also adds helper functions for defining the appropriate logical bit for each reduction step, which is the logical OR of many fibermask.* bits of relevance.
There is a further option to multiply the ivar by (frame.mask == 0), which was done when defining inverse variances in the code on almost all occasions.
Edited:
`fiberflat.py` :  flux and ivar taken and manipulated separately from the frame files, so only the separate arrays are manipulated using `fiberbitmasking.py` functions.
`sky.py` : most …
=> Fiberstatus

py/desispec/scripts/procexp.py, py/desispec/sky.py
Use copy of frame instead of applying twice the sky subtraction on the same frame with a correction coefficient; this was a source of a bug when all fiber has ivar=0.
=> Minor fix in sky subtraction when fiber has ivar=0

bin/desi_nightly_redshifts
@akremin this PR provides minor tweaks for the logging and srun launches for the nightly redshifts.  It doesn't fix the underlying problems but it helps a bit.  I used this to finish off 0315; please use it for finishing 0314 for testing.  It should successfully skip anything that is already done.
=> nightly redshifts logging and srun tweaks

bin/desi_proc, py/desispec/io/util.py, py/desispec/test/test_io.py
Shorten filename of slurm scripts and log files for desi_proc using create_camword. Corresponding function decrypt_camword can convert back to a list of cameras/spectrographs.
create_camword(cameras):
```
Function that takes in a list of cameras and creates a succinct listing                                                      
of all spectrographs in the list with cameras. It uses "a" followed by                                                       
numbers to mean that "all" (b,r,z) cameras are accounted for for those numbers.                                              
b, r, and z represent the camera of the same name. All trailing numbers                                                      
represent the spectrographs for which that camera exists in the list. …
```
=> shorten the desi_proc slurm and log filenames using new name convention

bin/desi_calib_config, py/desispec/calibfinder.py
Add utility script to write the many yaml spectrograph configuration files.
Tested and used to update the config of all 30 cameras with average PSFs and fiberflats from 20200306 to 20200315.
=> Calib config

py/desispec/io/fiberflat.py, py/desispec/io/frame.py, py/desispec/io/params.py
This PR fixes #931 by updating several pieces of code that were generating warnings (some quite verbosely):
* unclosed file in `desispec.io.read_fiberflat()`
* avoid adding FITS-reserved keywords to the frame.fibermap.meta dictionary in `desispec.io.read_frame()`
* use relative instead of absolute path for `resource_filename` in `desispec.io.read_params()`
I tested this by temporarily adding `import warnings; warnings.simplefilter("error")` to `bin/desi_proc`, confirming that it caused tracebacks while processing an exposure, and then fixing warnings until desi_proc could run to completion without warnings triggering errors.  I only tested this on post-extraction steps though, but it did get rid of the N>>1 astropy warnings like
```
WARNING: Meta-data keyword XTENSION will be ignored …
```
=> update code generating warnings

py/desispec/scripts/mergebundles.py
In PR #933 (avoiding astropy reserved keyword warnings) I said 
> I only tested this on post-extraction steps though...
of course that means I should have tested it on extractions too, which had more of those pesky warnings.  This PR fixes that (this time in the fibermap propagation of mergebundles).
=> avoid reserved keyword warnings

py/desispec/scripts/extract.py
This PR fixes the crash in PR #896 by trying the fibermap header if it can't find RA or TARGTRA in the primary HDU (as was the case in early commissioning data) for the purposes of barycentric corrections.
Tested on the command originally reported in #896 (20200122/00043028), and also on 20200315/00055611 (new data)
=> try fibermap header if (TARGT)RA isn't in primary header

bin/desi_proc
" --force" is an optional keyword to assemble_fibermap meant to be run if the code fails because of a missing coordinates file. We want the code to fail by default to indicate that ICS didn't provide coordinate information. However, early commissioning data sometimes didn't include this and for reprocessing of minisv2 and sv0 it is a known issue we would like to look past.
For future data we still want to know when coord* files aren't supplied, so the code still fails by default in those instances.
=> Force assemble_fibermap for nights before or during 20200310

bin/desi_proc
Just a change of options for desi_proc when calling `desi_compute_trace_shifts`.
The code was trying to re-adjust the wavelength solution from fiber to fiber by cross-correlating fast-extracted spectra on dome flats and twilight flats. This works fine for standard science exposures but leads to large wavelength errors for the flats. In this PR this feature is simply disabled.
"Flat-fielded" twilight sky data now look better but still show a significant EW gradient.
"Flat-field" dark sky data are noisier but provide an interesting data QA which highlight the problematic cameras.
=> Do not fit trace shifts along wavelength for dome or twilight flats

bin/desi_proc, py/desispec/io/sky.py, py/desispec/scripts/procexp.py, py/desispec/sky.py
Moved calculation of throughput corrections into a separate function and save the factors to `skymodel` files.
This includes the creation of a new function in `sky.py` called `calculate_throuhput_corrections()` that is run at the end of `compute_sky()`. 
`subtract_sky()` uses the values, which are saved in a 1D array in `skymodel`. The index corresponds to the fiber number. Its value is 1 by default.  The array is stored in `skymodel.throughput_corrections`
The array is saved in a new HDU within the `skymodel` fits file labeled `THRPUTCORR`. If that exists in a loaded file, it is assigned to  `skymodel.throughput_corrections` otherwise `None` is assigned.
This PR also changes the default of the pipeline to use sky corrections in fiber throughput. It changes the input flag of `procexp` …
=> calculate throughput corrections in a separate function and save the them to disk. change default to use sky correction

py/desispec/fiberbitmasking.py, py/desispec/fiberflat.py, py/desispec/scripts/autocalib_fiberflat.py, py/desispec/scripts/qproc.py
Several improvements to the averaging and merging of fiber flats.
- fix one bug in propagation of inverse variance in autocalib
- make sure we use the same list of exposures for each camera in autocalib 
- select valid fibers to compute the coefficient of each flat in the average
- select fewer fiber mask bits to mask out fibers in fiber flat computation
- improve averaging of mean spectrum when combining several flats.
This has been tested on the 2020/03 flat field data.
=> Average fiberflat

py/desispec/pixgroup.py, py/desispec/test/test_pixgroup.py
This PR fixes #852 by propagating the MJD-OBS header keyword to a MJD column in the output fibermap of spectra files (similar to propagating NIGHT, EXPID, and TILEID).
Tested with:
```
cd /global/cfs/cdirs/desi/spectro/redux/minisv2/tiles/70002/20200304
desi_group_spectra --inframes cframe-?0-*.fits --outfile $SCRATCH/spectra.fits
```
and verifying that the output file has an MJD column filled into the FIBERMAP table.
=> propagate MJD to spectra fibermap

bin/desi_nightly_redshifts, py/desispec/pixgroup.py, py/desispec/scripts/coadd_spectra.py, py/desispec/scripts/group_spectra.py
This addresses issue #914 .
Added lines to the bash script `desi_nightly_redshifts` to generate `spectra-64` files for each exposure and create coadds across exposures that are *not* across cameras (in addition to across cameras).
This PR also fixes bugs in `/scripts/coadd_spectra.py` that removed exposures without all three cameras even when `coadd-cameras` was not set. The removal code now sits under that flag.
It also looks in input frames for the relevant cameras (`bands`) in `frames2spectra` instead of assuming all three are present. That is in `pixgroup.py.`
Files were tested in my `SPECPROD` using:
```
salloc -N 10 -t 1:00:00 -C haswell -q interactive
export SPECPROD=kremin
desi_nightly_redshifts 20200314
```
outputs at nersc are in: …
=> Generate spectra-64 per exposure and also create coadds not across cameras

py/desispec/coaddition.py
Addresses issue  #919 .
This only allows the combination across cameras for coadds that had previously been combined across exposures/frames. It still *does not* support coaddition of exposures from coadds across cameras.
This was tested using the `cframes` and coadd files in:
`/global/cfs/cdirs/desi/spectro/redux/kremin/tiles/66000/20200314`
For co-adding coadds, I ran the following which I'll refer to throughout as "CAMS":
`desi_coadd_spectra -i coadd-0-66000-20200314.fits --coadd-cameras -o coadd-0-66000-20200314.cams.fits`
For comparison I generated an analogous coadd from the cframes (which I'll refer to as "FULL"):
`desi_coadd_spectra -i cframe-[brz]0-*.fits --coadd-cameras -o coadd-0-66000-20200314.full.fits`
The numeric values are identical:
The `fibermaps` differ slightly because …
=> Allow coadding across cameras of coadds

.travis.yml, bin/desi_proc
This PR replaces `desisurvey.utils.freeze_iers` with `desiutil.iers.freeze_iers` to remove the desisurvey dependency in desispec and get a version of `freeze_iers` that works with astropy 3.x and 4.x.  It also moves the import to after `desi_proc` arg parsing so that it doesn't bother freezing IERS if just asking for `--help`.
Requires desiutil >= 2.0.3 .
=> replace desisurvey.utils.freeze_iers with desiutil.iers.freeze_iers

py/desispec/coaddition.py, py/desispec/fiberbitmasking.py, py/desispec/fiberflat.py, py/desispec/io/raw.py, py/desispec/maskbits.py, py/desispec/pixgroup.py, py/desispec/scripts/group_spectra.py, py/desispec/test/test_coadd.py, py/desispec/test/test_pixgroup.py, py/desispec/test/util.py
Fibermap contains a `FIBERSTATUS` column that is camera dependent. This PR adds camera-specific bits to the `fibermask` bits, propagates them into the `FIBERSTATUS` column, and correctly bitwise OR's the three cameras (or however many bands are given to the function) to produce the combined `fibermap` for the spectra file. The bitwise OR takes place in the generation of the spectra files in `frames2spectra() `within `pixgroup.py `.
Test cases were run on two nights on two different tiles. This includes spectrographs SP2 and SP4 that have camera specific `FIBERSTATUS` bits. 
All fluxes, ivars, etc. are identical to files produced with the old code. 
Fibermaps are identical except for the `FIBERSTATUS` column in SP2 and SP4, and are completely identical in SP0 and SP9.
The data can be found …
=> Fibermask by camera

doc/changes.rst, etc/desispec.module, py/desispec/io/xytraceset.py, py/desispec/xytraceset.py
This PR updates the xytraceset usage of specter so that it becomes an optional dependency: if you are actually using xytraceset then it imports `specter.util.traceset` to use it, but specter is no longer required just to import `desispec.io` .
It also updates `etc/desispec.modules` to use desi_spectro_calib 0.1.1 for the 20.4 software release.  This change is unrelated to the specter dependencies, but comes along for the ride to avoid multiple PR+travistest iterations.
=> isolate specter dependency

py/desispec/maskbits.py, py/desispec/preproc.py, py/desispec/scripts/extract.py
This PR adds a new CCD mask bit BADREADNOISE and masks pixels with readnoise>100.  The value is hardcoded, but so are some of our other mask bit thresholds in the same part of preprocessing and I don't think it is worth calling that out into a separate config file (at least not right now).
Tested along with the branch in desihub/specter#78:
```
desi_preproc --cameras z4 \
-i /global/cfs/cdirs/desi/spectro/data/20200306/00053610/desi-00053610.fits.fz \
--outfile $SCRATCH/preproc-z4-00053610.fits
desi_extract_spectra -w 7520.0,9824.0,0.8 --psferr 0.1 --barycentric-correction \
-i $SCRATCH/preproc-z4-00053610.fits \
-p /global/cfs/cdirs/desi/spectro/redux/andes/exposures/20200306/00053610/psf-z4-00053610.fits \
--specmin 150 --nspec 25 \
-o $SCRATCH/frame-z4-00053610.fits
```
With resulting …
=> mask high readnoise CCD amps

bin/desi_proc
This PR updates arc and flat desi_proc jobs to use 10 nodes instead of 5, and shortens their requested wallclock time.  Timing tests in the interactive queue indicate that arcs typically take 18 minutes on 10 nodes, and flats take 6-7 minutes on 10 nodes.
This also helps with our current logic for when to merge arcs and flats because the exposures are processed sequentially and we don't have a race condition between two being processed simultaneously (we'll do a more robust fix later...).
Science exposures still use 5 nodes so that two can run in parallel to each other in our 10-node realtime queue allocation.  Later steps in the science processing (skies, flats) can't effectively us a full 10 nodes so 5 nodes was more efficient for getting work through.
=> run arcs and flats as 10-nodes jobs

py/desispec/scripts/extract.py
Currently the start of the exposure is used for the barycentric correction, but for 20 min exposure the difference in the correction between center of exposure and beginning can reach 0.4 km/s.
The commit fixes that.
=> use the center of the exposure for the barycentric correction

.travis.yml, py/desispec/io/image.py, py/desispec/io/qa.py, py/desispec/io/spectra.py, py/desispec/test/test_preproc.py, py/desispec/test/test_spectra.py, py/desispec/util.py
This PR fixes several items found while testing with python 3.8:
* a QA bug about changing dict keys while iterating over the dict keys
* use `collections.abc.Callable` instead of `collections.Callable`
* deprecated for a long time; will break in py3.9 (but now fixed here)
* FYI, "abc" = "Abstract Base Classes", not just a random submodule name
* Don't complain about nanomaggies as an invalid FITS unit
* in the test code, I left behind some commented hooks for how to treat a specific
warning as an error just for those tests, useful for tracking down where the warning
is coming from so you can know where to go to fix it.
=> support for python 3.8

bin/desi_zcatalog
This PR makes `bin/desi_zcatalog` much faster when merging the target table, by merging all new columns in a single call to `numpy.lib.recfunctions.append_fields` instead of adding them one by one (which copies the entire table in memory every time).
It also uses
```
np.zeros(k1.size, dtype=table2[k].dtype)
```
instead of
```
np.zeros(k1.size).astype(table2[k].dtype)
```
to avoid allocating the zeros array and then re-allocating under a different dtype.  This has the consequence for string columns as having a default of "" (blank string) instead of "0.0", which I think is more correct.  Other than that difference, I verified that this code produces identical output as the current code.
=> faster zcat target table merging

bin/desi_proc
Fix the following error:
File "/global/project/projectdirs/desi/users/zhangkai/desi/code/desispec/bin/desi_proc", line 213, in <module>
hdr = comm.bcast(hdr, root=0)
File "mpi4py/MPI/Comm.pyx", line 1257, in mpi4py.MPI.Comm.bcast
File "mpi4py/MPI/msgpickle.pxi", line 639, in mpi4py.MPI.PyMPI_bcast
File "mpi4py/MPI/msgpickle.pxi", line 111, in mpi4py.MPI.Pickle.load
File "mpi4py/MPI/msgpickle.pxi", line 101, in mpi4py.MPI.Pickle.cloads
TypeError: __new__() missing 1 required positional argument: 'table_header'
it looks like astropy 4 astropy.io.fits.hdu.compressed.CompImageHeader can't be broadcast with mpi4py.  master and 20.7 share the same underlying desiconda = python+mpi4py+numpy etc so both will fail the same way.  The integration tests covered …
=> Fixes mpi4py broadcasting problem

bin/desi_proc, bin/plot_timing
This PR uses the new `desiutil.timer.Timer` class to standardize timing in `bin/desi_proc`.  It uses some features in desihub/desiutil#152, so don't merge this until that PR is finalized.
New options to `desi_proc`:
* `--starttime $(date +%s)`: log the time between this starttime and the beginning of the python script (srun & python interpreter launch overhead).
* `--timingfile TIMINGFILE`: save timing information to a json file for later analysis.  When running in batch, this file is saved for each exposure.
New script `bin/plot_timing` uses the timing information saved with `--timingfile` to make plots like this:
@akremin please take a look to see if (or how badly) this will conflict with your changes in the desi_proc_mod branch.
=> update desi_proc timing logging

bin/desi_proc, etc/desispec.module, py/desispec/fluxcalibration.py
This PR adds MPICH_GNI_FORK_MODE=FULLCOPY to the desispec.module file, and adds checks for that in `desi_proc` when running.  This is required for MPI+multiprocessing to work together at NERSC.  In standard pipeline running, we were getting this environment variable via the redrock module file, but this PR makes sure that we also get it for desispec itself whether or not redrock is loaded, and provides some robustness when running development copies outside of the pre-installed modules.
Other changes that came along for the ride:
* also added KMP_AFFINITY=disabled, which we also set it redrock modules
* turns off an error message that wasn't really an error, so that greping for ^ERROR will focus on more genuine errors.
=> set MPICH_GNI_FORK_MODE=FULLCOPY

bin/desi_proc, py/desispec/workflow/desi_proc_funcs.py
This PR focuses on `desi_proc` and turning most of the early setup code into function calls. The functions are placed under `/py/desispec/workflow/` where a number of new files will eventually go in the ongoing updates. 
The new file is `desi_proc_funcs.py`. It has function definitions for creating the parser object, reading header information to infer undefined arguments based on arguments that are defined, determining the required resources for running a job, and writing the batch script to submit desi_proc to an HPC. It also moves a function that previously existed at the start of `desi_proc`.
The new parser functions make the old code generalized to be used in both desi_proc and a future joint fitting script `desi_proc_joint_fit`. The goal is to reduce the repeated code by putting …
=> Refactoring desi_proc

bin/desi_proc, bin/desi_proc_joint_fit, py/desispec/workflow/desi_proc_funcs.py
This adds a joint fitting script that acts very similarly to desi_proc except that it operates on multiple exposure ID's and is meant for joint fitting of: psf's, flat's, and standard stars within science's. These generate psfnight's, fiberflatnight's, and stdstar's.
This does not break backward compatibility, as it just adds a new script. It reimplements joint psf and flat fitting which has been commented out in desi_proc for quite a while.
The script is `desi_proc_joint_fit`. 
It takes many of the same arguments and flags as desi_proc. A previous refactor (PR #1012) allows the reuse of the same parser object, with a few specialized flags to account for the plural nature of the exposure ids (--expids rather than --expid). Tests were done to ensure the same results if using a list of …
=> Add desi_proc_joint_fit

py/desispec/workflow/desi_proc_funcs.py
Minor cleanup:  previously the default timing*.json file written by `desi_proc ... --batch` was dumped into whatever directory you were in when running `desi_proc`, instead of writing it into the batch script directory along with the other batch logs.  This PR adds an explicit path for the timing file so that it always ends up in the same place regardless of where `desi_proc ...` is run from.
@akremin please check (can use `desi_proc ... --batch --nosubmit`) and inspect the written script if you don't want to run a full exposure.  This might also explain that missing arc timing file from one of your runs.
=> write timing file to batch script dir with other logs

bin/desi_focus
Add script `desi_focus` to analyse a sequence of focus scans.
- preprocess exposures
- detect spots, fit gaussian per spot per exposure and save as csv table
- merge tables, bin or match values of given fiber/wavelength
- best fit focus for each bin or spot
- fit best focus plane as a function of xccd , yccd
- convert to gauge offsets for the 3 screws adjusting the cryostat piston and tilt
Example for SM10 red camera
```
desi_focus -i /global/homes/j/jguy/data/20200109/0003924{1,2,3,4,6,7,8}/desi-000*.fits.fz -o . --cam r1 --offsets=-150,-100,-50,0,50,100,150 --gauges=60.750,60.946,61.084 --plot --testslit
```
Average best fit piston
Sigma values for best exposure (note some fibers are off in test slit)
Best focus per spot (wavelength, fiber) and best plane fit
Comparison with analysis of …
=> Focus scan analysis

bin/desi_compute_bias, bin/desi_compute_dark, bin/desi_compute_dark_nonlinear, py/desispec/calibfinder.py, py/desispec/ccdcalib.py, py/desispec/desi_bias_dark_1d_model.py, py/desispec/desi_create_bias_dark.py, py/desispec/io/raw.py, py/desispec/io/util.py, py/desispec/preproc.py, py/desispec/scripts/preproc.py
This PR supersedes PR #1020 since I wanted to combine some changes from that branch (newbias4) with the dark/bias units updates from PR #1023 that had been merged into master.  Creates and uses new dark model:
model(x,y,t) = bias(x,y) + dark(x,y)*t + nonlinear(y,t)
Compared to master:
* moved `bin/desi_compute_bias` and `bin/desi_compute_dark` functionality into functions in `desispec.ccdcalib` so that they can be independently called from other scripts
* fixed units bug so that darks are consistently calculated and used in electron/s (not ADU/s).
Compared to newbias4 (PR #1020):
* combined `desi_create_bias_dark.py` and `desi_bias_dark_1d_model.py` into `bin/desi_compute_dark_nonlinear`.
* calculate dark model using overscan trimmed DARKs in electron/s instead of non-trimmed ADU/s
* …
=> New bias+dark model

py/desispec/scripts/specex.py
Fixing a trivial bug which is unfortunately difficult to debug inside a mpi script.
`srun -N 1 -n 20 desi_compute_psf_mpi -o psf.fits .... ` was hanging, and never running the psf for bundle 0 because rank 0 was trying to create a directory with an empty path. 
I fixed this, but we should find a way to have the mpi run aborted instead of hanging when python throws an exception in a rank (here `FileNotFoundError: [Errno 2] No such file or directory: ''`)
=> Fix bug in specex.py when trying to create directory with empty path

bin/desi_proc, py/desispec/io/__init__.py, py/desispec/io/util.py, py/desispec/test/test_io.py
This PR improves the robustness of `bin/desi_proc` calling `desispec.scripts.specex.main` by wrapping it in try/except.  Previously, a PSF fit failure due to bad data would throw an uncaught exception, causing those MPI ranks to hang and never reach the post-PSF MPI barrier, causing the entire job to hang.
It also fixes a bookkeeping bug when "psf" appeared in `$DESI_SPECTRO_REDUX/$SPECPROD`, due to use of code like `outpsf = inpsf.replace('psf', 'shifted-input-psf')`.  A new utility function `desispec.io.util.replace_prefix(filepath, oldprefix, newprefix)` will replace the prefix exactly once at the beginning of the filename, even if that same prefix appears elsewhere in the path or filename.
Tested with `$SPECPROD=psfmpi` and `desi_proc -n 20201114 -e 62809 --cameras b1,r1,z1 --batch`, …
=> more robust desi_proc spexec+MPI

bin/desi_preproc, py/desispec/scripts/preproc.py
This PR adds multiprocessing parallelism to `bin/desi_preproc`, using one process per camera, enabling all 30 cameras to be processed in ~2.5 minutes on a cori batch node.  If called with a single camera or `--ncpu 1` then multiprocessing will not be used and the cameras will be iterated over serially.  If there is a failure on a single camera a log error message will be printed but the others can proceed to finish.
This also adds convenient options `--night` and `--expid` which can be used instead of `--infile`.
=> add parallelism to desi_preproc

py/desispec/test/test_util.py
When running setup.py test on my laptop's VM, I ran into an edge case for test_util.py in test_utils_default_nproc. When using a single processor machine (or presumably if you request one processor on NERSC, etc) the test fails. 
This pull request fixes that test failure by ensuring that in the case there is one CPU, the automatic calculation involving multiprocessing.cpu_count()//2 is floored at 1 rather than 0.
=> RE: recent testing of this code

py/desispec/io/image.py, py/desispec/scripts/preproc.py, py/desispec/test/old_integration_test.py
This PR makes some minor changes to how the integration test interacts with desi_preproc, which has become more picky about success/failure return codes since PR #1032.  This has been tested at NERSC where current master fails, but this branch passes:
```
python -m desispec.test.old_integration_test
```
I'll self-merge so that this can be included in the nightly integration tests which are currently failing.
=> integration test updates for desi_preproc

bin/desi_preproc, py/desispec/scripts/preproc.py
Fixes #1037 by ensuring that the return code of `desispec.scripts.preproc.main` is an `int` instead of an `np.int64`, which was confusing `sys.exit(preproc.main(preproc.parse()))` resulting in the unix return code being 1 instead of 0, i.e. causing wrapper scripts to think that preproc had failed.
=> fix desi_preproc return code

py/desispec/database/redshift.py, py/desispec/io/fibermap.py, py/desispec/test/test_io.py
This PR adds support for gzipped fiberassign files as input, including tests. We will hopefully need this functionality next week. With the magic of globs it supports either fiberassign-\*.fits.gz or fiberassign-\*.fits (i.e. it is backwards compatible with non-gzipped fiberassign data).
=> add support for gzipped fiberassign files

py/desispec/io/fibermap.py, py/desispec/io/raw.py, py/desispec/io/util.py, py/desispec/preproc.py, py/desispec/test/test_io.py
Header keyword updates: this PR fixes #963 (FIBERMAP missing OBSTYPE) and fixes #964 (inconsistent EXPTIME in different HDUs).  Reviews are welcome if you can get them in by Friday noon, otherwise I'd like to merge Friday afternoon for test runs over the weekend prior to the NERSC outage next week.
In the case of EXPTIME, the problem was that the fibermap is generated from several input files and it was getting its EXPTIME from the guider file instead of the spectrograph raw data file, resulting in inconsistent numbers.
For OBSTYPE, it was originally coming from the guider file but arcs and flats don't have that input.  Now the fibermap also gets keywords from the raw data file, and thus picks up OBSTYPE too.
Tested with:
```
assemble_fibermap -n 20200315 -e 55612 -o …
```
=> fix preproc/fibermap keyword propagation

py/desispec/preproc.py
Minor change to preprocessing
- default saturation level = 2**16-1 (but all set in calib SVN repo)
- write header keywords SATULEVA,B,C,D (in ADU, prior to bias subtraction to have a meaningful numeric saturation value)
- and SATUELEA,B,C,D (in electrons, after bias subtraction and gain multiplication, for information)
=> Saturlev202012

py/desispec/io/fibermap.py, py/desispec/test/test_fibermap.py
Fixes a bug introduced in PR #1045 for older data which have an "SPS" instead of a "SPEC" HDU in the raw data.  My penance for introducing the bug is writing unit tests that would have caught the bug in the first place.  Since those tests require a substantial amount of real data, they only run at NERSC and are cleanly skipped elsewhere.  i.e. Travis / GitHub Actions / Laptop tests won't catch them, but the nightly integration tests at NERSC will.
Speaking of Travis, it is so bogged down now, I plan to merge and update at NERSC so that @akremin can proceed with 20.12 / blanc testing.  All tests pass on this branch at NERSC.  Retroactive comments are welcome for retroactive fixes.
This fix was tested with the unit tests and the commands
```
assemble_fibermap -n 20200219 -e 51039 -o …
```
=> fix assemble_fibermap for older data with SPS header

bin/desi_proc_joint_fit, py/desispec/workflow/desi_proc_funcs.py, py/desispec/workflow/procfuncs.py
Note I have *not* tested this yet, but can do so once dirac/NERSC is back. The changes are basic and should "just work." I tested the changes with toy code, but not within the desi_proc framework.
Cleans a few things in the code, but primarily this resolves issues #1051 and #1049. We now symbolic link with relative paths so that it works on mirrors outside NERSC. Also run with a max of 5 nodes in the realtime queue for flat cals.
=> Desiproc fixes to add relative sym links and realtime flat cal node reduction

bin/desi_daily_proc_manager, py/desispec/scripts/daily_processing.py, py/desispec/workflow/exptable.py, py/desispec/workflow/procfuncs.py
This PR includes two new command line options --ignore-expid-list and --ignore-expid-file. The file should be a text file with one exposure per line. The list should be given as a comma separated string. 
I tested this on Dec 15th data.
Tested with zero-padded and not (e.g. 67890 vs. 00067890), both work. Tested that with zero-padded and without, both worked. Lastly, I tested with both specified. It correctly used the superset of expids given in both options.
It skips all exposures specified, including tested arc, science, and flats. It doesn't use them in the joint fitting either. It catches the new flags for both arcs and flats.
=> Workflow mods to avoid specified exposures and use new end-of-cal flags

py/desispec/scripts/stdstars.py
Coadd the spectra of standard stars before fitting them in case of multiple exposures.
Use optimal weights: weight each exposure by its relative throughput * inverse variance.
=> Coadd fluxes in standard star fit with multiple exposures

py/desispec/scripts/stdstars.py
Check if all ivar=0 for the standard stars of a frame (can happen in case of a focal plane error for a whole petal).
Standard star fit will survive this if there is at least one valid exposure (and will fail with an error message otherwise).
=> std star fit: check if all ivar=0 for a petal/exposure

bin/desi_daily_proc_manager, bin/desi_proc, py/desispec/io/util.py, py/desispec/scripts/daily_processing.py, py/desispec/test/test_io.py, py/desispec/workflow/desi_proc_funcs.py, py/desispec/workflow/procfuncs.py
Creates a new function parse_cameras that takes a user-specified str from the command line and turns it into a "camword". That can be used and saved by the workflow or converted to a list of cameras using "decode_camword". The idea of camword and decode_camword were already implemented, this PR just replaces multiple instances of str parsing with a unified function that ties in nicely with the existing camword functions.
I tested this with numerous inputs and they all work, including some pretty non-standard ones. Examples are:
```
def test():
for camera in ['0,1,2,3,4', '01234' , 'a01234', 'a012345b6', 'a01234b5z5r5', 'a01234b56z56r5', 
'0,1,2,3,4,b5', 'b1,r1,z1,b2,r2', '0,1,2,a3,b4,5,6', 'a01234,b5,r5,z5', 'a01234,b5,r5,z56',
None, ['b1','r1','z1','b2'] ]: 
camword = …
```
=> Consistent Camera Argument Parsing

bin/desi_proc, py/desispec/workflow/desi_proc_funcs.py
Use variance model as default for `desi_proc` script.
- option `--model-variance` of `desi_preproc` (see PR #1008)
- option `--no-extra-variance` not set for `desi_compute sky`
This choice is based on a run without (current daily prod) and with (custom prod: variance-model) of tile 80605 and 80606 observed on 2020/12/16. (There are also other motivations from adopting a variance model: restore linearity; unbiased flux uncertainties). With the variance model, we do not see an excess at specific redshifts associated to sky lines. 
Both versions of the desi code give similar answers for the targets matched to SDSS DR16 observations.
=> Variance model

bin/desi_proc, py/desispec/workflow/desi_proc_funcs.py
This PR makes the number of nodes requested per job in the regular queue the same as those in the realtime queue.  Originally the regular queue tried to go wider and faster, but led to significant inefficiencies, e.g. PSFs with 19 nodes are only slightly faster than PSFs with 10 nodes due to how fast b vs. slow r,z cameras are distributed.  Pending better optimization, this PR makes the regular jobs the same as the realtime jobs which we know works fairly well.
Along for the ride:
* more logging around the PSF fitting
* drop unnecessary search for the default fiberflat when doing a PSF fit
* parallelize over cameras interpolation of PSF over bad fibers, saving ~1 min runtime
=> adjust number of nodes requested per job step

bin/desi_proc, py/desispec/io/__init__.py, py/desispec/io/meta.py, py/desispec/io/util.py, py/desispec/preproc.py, py/desispec/scripts/extract.py, py/desispec/scripts/fluxcalibration.py, py/desispec/scripts/procexp.py, py/desispec/scripts/sky.py, py/desispec/scripts/trace_shifts.py, py/desispec/test/test_io.py
This PR fixes #997 by adding header keywords to track which calibs were used.  Example outputs in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/test where 20200315/00055611 was processed with default calibs from $DESI_SPECTRO_CALIB, while 20201220/00069020 was processed with CCD calibs from $DESI_SPECTRO_CALIB but PSF and fiberflat from nightly calibs.
For low-level CCD calibs, I used DEPNAMnn/DEPVERnn keyword pairs to allow longer keyword names, e.g.
```
DEPNAM00= 'DESI_SPECTRO_CALIB'                                                  
DEPVER00= '/global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk'             
DEPNAM01= 'CCD_CALIB_BIAS'                                                      
DEPVER01= 'SPCALIB/ccd/bias-sm10-r1-20201115.fits.gz'                           
DEPNAM02= …
```
=> add input calib provenance keywords

bin/desi_proc_joint_fit
In `desi_proc_joint_fit` a set of nested if/else had an indentation bug such that previously successful `fiberflatnight-camera-{camera}-lamp-{n}.fits` files were not being added to the list of files to pass to `desi_autocalib_fiberflat`.
This was discovered, tested, and fixed on a genuine recovery case for 20201222, where the previous partially successful job had timed out, but the recovery job was skipping then ignoring the previously successful outputs.
Could you double check this @julienguy?  In particular, what is the minimum number of inputs to `desi_autocalib_fiberflat` for it to be worth trying?  If the answer is messy bookkeeping we might punt that to the future if/when we actually have a problem of missing lamps or similar.
=> fix desi_proc_joint_fit fiberflatnight indentation bug

py/desispec/io/fibermap.py
Fixes #1067 for dealing with updated fiberassign files on 20201214 by requiring that `assemble_fibermap` only considers `fiberassign-*.fits` and `fiberassign-*.fits.gz` and won't accidentally pickup `fiberassign-*.fits.orig`:
```
[cori10 temp] assemble_fibermap -n 20201214 -e 67710 -o fibermap-00067710.fits
INFO:fibermap.py:409:assemble_fibermap: Night 20201214 spectro expid 67710
INFO:fibermap.py:410:assemble_fibermap: Raw data file /global/cfs/cdirs/desi/spectro/data/20201214/00067710/desi-00067710.fits.fz
INFO:fibermap.py:411:assemble_fibermap: Fiberassign file /global/cfs/cdirs/desi/spectro/data/20201214/00067710/fiberassign-080605.fits.gz
INFO:fibermap.py:412:assemble_fibermap: Platemaker coordinates file /global/cfs/cdirs/desi/spectro/data/20201214/00067710/coordinates-00067710.fits …
```
=> assemble_fibermap only use fiberassign .fits and .fits.gz

py/desispec/io/fibermap.py, py/desispec/io/raw.py
This PR
* fixes #1063 by updating `assemble_fibermap` to support coordinates files that don't have any positioner iterations in them, e.g. 20201220/69082
* propagates FIBER_RA and FIBER_DEC if present in the coordinates file (e.g. 20201222/69415), but don't crash if they aren't (e.g. 20200315/55611)
* Renames long keyword "FIBERASSIGN" (>8 char) in early data to match current header name "FIBASSGN" that won't generate HIERARCH warnings.
Tested with
```
assemble_fibermap -n 20200315 -e 55611 -o fibermap-00055611.fits
assemble_fibermap -n 20201220 -e 69082 -o fibermap-00069082.fits
assemble_fibermap -n 20201222 -e 69415 -o fibermap-00069415.fits
```
And also tested end-to-end with an "unpositioned" exposure 20201220/69082 with
```
desi_proc -n 20201220 -e 69082 --batch --traceshift …
```
=> add FIBER_RA/DEC; support unpositioned coords files

py/desispec/calibfinder.py, py/desispec/io/raw.py, py/desispec/test/test_util.py, py/desispec/util.py, py/desispec/workflow/exptable.py
This PR provides `desispec.util.header2night` which standardizes how to get the YEARMMDD NIGHT from the raw data fits headers, including handling real-world problems that have come up:
* NIGHT keyword is completely missing
* NIGHT keyword is present but blank (i.e. None)
* NIGHT keyword is present but not an integer (e.g. '        ')
in these cases it falls back to using `DATE-OBS`, and then falls back to `MJD-OBS`, including handling the definition of "NIGHT" rolling over at noon MST (KPNO local time).
`dateobs2night` and `mjd2night` are also added as utility functions used by `header2night`.  These might be useful by other code too, but if you are deriving a YEARMMDD from a header, please use `header2night(header)` to handle the various bogus-header cases.
I have tested this with …
=> standardize getting NIGHT from raw data headers

py/desispec/io/fibermap.py
This PR provides robustness for `assemble_fibermap` for exposures like 20210105/00070965 and 20210105/00070969 where the full guide-EXPID.fits.fz file isn't present, but the acquisition guide-EXPID-0000.fits.fz file is (not sure why...).  Unfortunately they keep their full set of header keywords in different HDUs, but this catches that too.
@akremin please try for 20200105.
=> use acquisition guide file if full guide file isn't there

py/desispec/averagefluxcalibration.py
Minor change to the AverageFluxCalib class to use DESIMODEL for the geometric area and scipy.constants instead of hard coded numbers. This class is used to produce the average flux calibration used in night watch, and was also used for the throughput analysis in DESI-6043. There is the project to use this average calibration to constrain the calibration of each exposure.
The fitting function in the code has a provision to fit for an airmass term and a seeing term. This was tested in sims but has not yet been used with real data. We will use it when we have more data covering a representative range of airmass and seeing.
=> Average flux calibration

py/desispec/io/__init__.py, py/desispec/io/meta.py, py/desispec/io/spectra.py, py/desispec/spectra.py, py/desispec/test/test_spectra.py
This PR adds several usability improvements for working with Spectra objects:
* `desispec.io.read_tile_spectra(tileid, night, ...)`: read tile-based groupings of spectra or coadds from a production, optionally filtering by FIBER or TARGETID, and optionally also reading and row-matching the corresponding zbest files.
* Adds slicing logic to `Spectra` objects, e.g. `spectra[indices]` which can be used to filter or sort more flexibly than `Spectra.select`.  This takes care of indexing `flux`, `ivar`, `fibermap`, `scores`, etc. taking into account that e.g. `scores` are optional. 
* Adds `desispec.spectra.stack()` to combine multiple homogeneous spectra files (e.g. all with the same bands, scores or not, etc.).  This is way faster but less flexible than `Spectra.update`, which e.g. supports …
=> read_tile_spectra and Spectra utilities

bin/desi_coadd_frames, bin/desi_coadd_preproc, py/desispec/coaddition.py, py/desispec/scripts/coadd_frames.py, py/desispec/scripts/coadd_preproc.py, py/desispec/scripts/coadd_spectra.py
- Fix bug in coaddition with nsig>0 for cosmic ray rejection (a reference instead of a copy of the flux and ivar were used in the outlier identification routine)/
- Set nsig=4 to new default
- Add scripts `desi_coadd_frames` and `desi_coadd_preproc` that are useful for some studies.
I would like to add to the PR the possibility to coadd several spectra files (to be discussed). For now the code `desi_coadd_spectra` accepts either a single spectra file (with internally several exposures) or several frame files.
=> Coaddition

py/desispec/fluxcalibration.py, py/desispec/test/test_flux_calibration.py, requirements.txt
This PR fixes `desispec.fluxcalibration.isStdStar` for CMX fibermaps which don't have a MWS_TARGET column.  This was broken by PR #1105 which added support for Gaia standards in the (SVn_)MWS_TARGET columns without realizing that it would break CMX tiles.
Tests added for CMX, SV1, and Main fibermaps.  Additionally tested on a CMX fibermap with:
```
from desispec.fluxcalibration import isStdStar
fm = Table.read('/global/cfs/cdirs/desi/spectro/redux/blanc/preproc/20200315/00055670/fibermap-00055670.fits')
np.count_nonzero(isStdStar(fm))                                                                                                       
```
@julienguy does this fix the case you were crashing on?
=> fix isStdStar for CMX fibermaps

py/desispec/fluxcalibration.py, py/desispec/test/test_binscripts.py
If the median S/N in the standard stars is <2 , use a scaled version of the average DESI throughput, fitting a single scalar instead of a calibration coefficient per wavelength bin.
Addresses issue #1100
=> Flux calibration for exposures with very low transmission

py/desispec/fiberflat.py
Apply the heliocentric wavelength doppler factor to the fiberflat if it has been applied to the frame wavelength.
This solves #1111.
It's a significant correction that affects the calibration on the throughput dip for instance.
Below blue='blanc' orange= with this correction,
this is cframe-b0-00068334.fits
=> Apply heliocentric to fiberflat if any

bin/desi_compute_dark_nonlinear, bin/plot_spectra
This PR includes the code used for building the new bias+dark models for desi_spectro_calib 0.2.1, 0.2.2, and 0.2.3 used in blanc.  The substantive change is an option `--mindarks` to filter by number of darks for a given EXPTIME so that it won't try and fail on a single test dark.
=> Dark robustness for desi_spectro_calib 0.2.x

py/desispec/io/raw.py
Small but necessary fix for exposures like 20200219/51053 where the NIGHT header keyword was an int in HDU 1 and a str in the per-camera HDUs, resulting in a failure of a consistency check that had been added in PR #1083.  This has been fixed in the data itself in more recent nights, but we should be robust to this anyway.
=> fix int vs. str NIGHT in headers

bin/desi_proc, py/desispec/scripts/specex.py, py/desispec/sky.py, py/desispec/workflow/desi_proc_funcs.py
Significant improvement on sky subtraction.
Main change is adjustment of sky lines center and width on sky fibers, interpolated across other fibers and wavelength.
Report in  https://desi.lbl.gov/trac/wiki/DataSystems/Telecons/2021-02-02 
(in combination with change in arc lamp line list in branch linelist of specex)
=> Improve sky subtraction

bin/desi_compute_bias, bin/desi_compute_dark_nonlinear, py/desispec/ccdcalib.py, py/desispec/scripts/specex.py
This PR contributes some bookkeeping updates for computing biases and darks, documenting what was used for the 20210130 update to desi_spectro_calib for the new CCD timing files.
* `desi_compute_bias --expfilelist` option to specify input NIGHT EXPID in a file instead of N>>1 paths to raw files on the command line
* `desi_compute_dark_nonlinear` option to group darks with zeros by NIGHT (rolling over at noon, allowing a nighttime dark sequence to span midnight) vs. the previous grouping by DAY (rolling over at midnight, allowing a daytime dark sequence to span noon).  Either is supported now by specifying either `--days` or `--nights`
* `desi_compute_dark_nonlinear --first-expid` option to specific the first exposure ID to use (e.g. to exclude test exposures with a different configuration …
=> darkmodel bookkeeping; desi_compute_psf --specmin bugfix

py/desispec/io/qa.py, py/desispec/qa/qa_plots.py
This fixes a problem with interpreting NIGHT as an int vs. str in QA code.  The problem isn't triggered by unit tests but was caught by the nightly integration tests.  I plan to merge as soon as (if?) github tests pass so that the fix can be included in the nightly integration tests run tonight.
=> fixing int vs. str night for QA

py/desispec/io/raw.py, py/desispec/qproc/qextract.py, py/desispec/scripts/preproc.py
Allows to preprocess and extract early test stand data with sparse fiber slit, and with different or missing header keywords.
Hopefully harmless PR for recent data.
=> Backward compatibility

py/desispec/tsnr.py
This PR fixes a bug in the TSNR calculation when the frame wavelength grid doesn't match the pre-calculated ensemble grid, thus requiring the ensemble to be resampled.  I implemented that code but forgot that the ensemble is 2D not 1D (albeit with the first dimension of length 1 currently, but allows for some future expansion).  This case is not covered by unit tests but was covered by the nightly integration tests which caught the problem.  I tested the fix with the integration test code which now passes.
=> fix TSNR ensemble resampling

py/desispec/io/fibermap.py
This PR fixes #1076 where some fiberassign header keywords were not propagated into the fibermap files, thus losing some of the fiber assignment input provenance.  The problem was that we were propagating keywords from the 'FIBERASSIGN' HDU, but not additional keywords from HDU 0 of the fiberassign files.  Now assemble_fibermap propagates keywords from both HDUs into the fibermap file (along with keywords from the raw data).
Keywords that were previously missing that are now included when running `assemble_fibermap -n 20201215 -e 68065 -o fm-2.fits`:
```
GFA       /global/cfs/cdirs/desi/target/catalogs/dr9/0.47.0/gfas
SKY       /global/cfs/cdirs/desi/target/catalogs/dr9/0.47.0/skies
SKYSUPP   /global/cfs/cdirs/desi/target/catalogs/gaiadr2/0.47.0/skies-supp
TARG …
```
=> propagate fiberassign HDU0 keywords too

.github/workflows/python-package.yml, bin/desi_proc_joint_fit, py/desispec/util.py
This PR updates `desi_proc_joint_fit` to fail harder with an exit code if the joint fitting fails for all cameras, so that the job itself can exit with an error code and alter dependent jobs that they shouldn't run.  This is for psfnight, fiberflatnight, and stdstars.  In principle the same logic could/should be added to `desi_proc` for other steps but I'm trying to minimize the last-minute organizational changes for Cascades, and these joint fit steps are our most critical barrier steps where we don't want the pipeline to proceed if they fail.
It also fixes a bug where if rank 0 `desispec.scripts.specex.mean_psf` failed, all other ranks would be waiting at a barrier instead of letting the job exit.  We had fixed the equivalent problem in desi_proc individual arc fits, but not yet in the …
=> fail faster with error for joint fits

py/desispec/scripts/extract.py, py/desispec/test/test_extract.py
This PR updates the BUNIT units for frame files (and thus sky and sframe files) to be "electron/Angstrom" instead of "count/Angstrom", due to previous confusion about whether "count" meant ADU counts or electron (photon) counts.
I tested with `desi_proc -n 20201216 -e 68317 --cameras a1 --traceshift --batch` and confirmed that the output files had updated units as expected, and the cframe files still have BUNIT="10**-17 erg/(s cm2 Angstrom)"
=> change frame units to electron/Angstrom instead of count/Angstrom

bin/desi_run_night, py/desispec/scripts/submit_night.py, py/desispec/scripts/submit_prod.py, py/desispec/workflow/procfuncs.py
This adds two new flags to desi_run_night: `--ignore-existing` and `--reservation`.  `--ignore-existing` allows us to, by default, skip over a night if the night has already been submitted for the prod. This prevents overwriting of files, and rerunning slurm jobs. If it is resubmitted on purpose, then `--ignore-existing` can be set to do that.
The main point of the PR is for `--reservation`. This PR also includes the ability to set this in the yaml file for desi_run_prod. it also propagates `reservation` down into multiple function to where it actually calls `sbatch`.
I tested this on two separate nights with:
`desi_run_night -n 20210220 --reservation=cascades`
`desi_run_night -n 20210221 --reservation=cascades`
Below is a screenshot of `sqs` showing that the jobs were submitted to the …
=> Add argument to specify a slurm reservation

py/desispec/fiberbitmasking.py, py/desispec/io/meta.py
Minor fixes so that the following does not crash and does not set ivar=0 for entries where mask!=0.
```
desi_process_exposure -i /project/projectdirs/desi/spectro/redux/daily/exposures/20210101/00070317/frame-z1-00070317.fits --sky /project/projectdirs/desi/spectro/redux/daily/exposures/20210101/00070317/sky-z1-00070317.fits --fiberflat /project/projectdirs/desi/users/jguy/teststand/desi_spectro_calib/spec/sm10/fiberflatnight-z1-20201214.fits --no-zero-ivar --no-tsnr -o 20210101/sframe-z1-00070317.fits
```
=> Restore desi process exposure

bin/desi_average_flux_calibration
Undo the heliocentric correction when averaging the throughput of many exposures in desi_average_flux_calibration.
This is a minor bug fix that has no influence on the pipeline production (which does not use desi_average_flux_calibration).
As expected, the telluric features appear sharper after this applying this correction.
=> undo heliocentric correction

bin/desi_tsnr_afterburner
Changes to desi_tsnr_afterburner to write a summary exposure file from an existing prod with TSNR values already saved per frame in the SCORE HDU of the cframe files.
Examples:
```
desi_tsnr_afterburner -o $SCRATCH/tsnr-debug1.fits --prod cascades --nights 20201216,20201218
desi_tsnr_afterburner -o $SCRATCH/tsnr-debug2.fits --prod cascades --nights 20201216 --recompute
desi_tsnr_afterburner -o $SCRATCH/tsnr-debug3.fits --prod cascades --nights 20201216 --expids 68340 --recompute --cameras r0,r1 --details-dir toto
```
=> Add possibility to use the TSNR values in the cframes

bin/desi_merge_zbest_tiles, py/desispec/coaddition.py, py/desispec/scripts/coadd_spectra.py, py/desispec/specscore.py
This PR
* propagates sum(TSNR2) to the coadd SCORES table
* cleans up per-exposure vs. coadded columns in the coadd FIBERMAP
* adds `bin/desi_merge_zbest_tiles` used for merge redshift catalogs from multiple tiles, including combining with the coadded FIBERMAP and SCORES HDUs
Example outputs are at NERSC in `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/minicascades/`
* coadds: `tiles/*/deep/coadd*.fits`
* `zcatalog-minicascades-deep.fits`
Itemizing changes to the coadd FIBERMAP:
* FIBERASSIGN_X/Y -> MEAN/RMS_FIBERASSIGN_X/Y
* FIBER_X/Y -> MEAN/RMS_FIBER_X/Y
* FIBER_RA/DEC -> MEAN/RMS_FIBER_RA/DEC
* MJD -> FIRST/LAST/NUM_MJD
* per-exposure columns dropped that don't apply to a coadd:
* NUM_ITER
* EXPTIME (COADD_EXPTIME was kept)
* NIGHT (FIRST/LAST_NIGHT kept)
* EXPID …
=> Propagate sum(TSNR2) into coadds

py/desispec/coaddition.py, py/desispec/pixgroup.py
This PR fixes the ability to coadd cframes (coadding spectra was working, but not going directly from cframes -> coadd).  Tested with:
```
cd /global/cfs/cdirs/desi/spectro/redux/cascades/exposures/20210224/00077980
#- coadding frames
desi_coadd_spectra -i cframe-?9-*.fits -o $SCRATCH/coadd1.fits
#- coadding spectra still works
desi_group_spectra --inframes cframe-?9-*.fits --outfile $SCRATCH/spectra.fits
desi_coadd_spectra -i $SCRATCH/spectra.fits -o $SCRATCH/coadd2.fits
```
It is a bad sign that unit tests didn't catch this bug, but I haven't tried to address that in order to get a fix to @rongpu quickly.
Thanks to @rongpu and @akremin for reporting this.
=> fix coadds of cframes

bin/plot_frame, py/desispec/fluxcalibration.py
Simplification of the flux calibration now that we have good fiber positioning and standard star fit. A single scale factor is used per std star instead of a polynomial function of wavelength. This makes the code more robust. This normalization is used to discard problematic stars and to detect outlier flux values.  The solves issue #1156 . The resulting flux calibration vectors have the same average than before.
Here average of exposures 68265,68266,68272,68273 from 20201216.
=> Simplify fluxcalib

py/desispec/sky.py
This change should not affect the end results at all - fitsdiff shows that only timestamps are different.
However, the performance improvement is drastic. For the exposure I tested, desi_compute_sky goes from ~5m40s to ~1m30s.
=> Use sparse matrix types in compute_uniform_sky

bin/desi_tsnr_afterburner, py/desispec/data/tsnr/tsnr-efftime.yaml, py/desispec/scripts/procexp.py, py/desispec/tsnr.py
- improved read noise normalization (masking sky lines)
- averaging per exposure: use median across the valid fibers of a camera, but mean across spectrographs
- compute ELG_EFFTIME_DARK and BGS_EFFTIME_BRIGHT based on the analysis reported in https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=6110
- add multiprocessing option to `desi_tsnr_afterburner`
- add `--append` option to `desi_tsnr_afterburner` so that it can be run daily and it's output be used for the afternoon planning.
Example:
```
desi_tsnr_afterburner -o tsnr-exposures-daily.fits --update --prod daily --nights 20210304 --nproc 16
```
Figures from DESI-6110
=> Updates to TSNR

py/desispec/fluxcalibration.py
At the request of the MWS group, the flux calibration is now interpolated over the Ca and Na ISM lines.
Ca and Na lines appeared as residuals to the calibration with WDs (from Chris Manser):
Now interpolated (see following plots). A second systematic correction using WD flux residuals or QSO flux residuals could/will be applied in future versions.
=> Interpolate flux calibration over Ca and Na ISM lines

py/desispec/scripts/stdstars.py
This PR adds an option to `desi_fit_stdstars` to use MPI for parallelism instead of multiprocessing. 
This could allow the stdstar fitting step in `desi_proc` to run with the same node/task/cpu configuration as previous steps in the pipeline (`srun -N 5 -n 160 -c 2 ...`). This will also be useful for a GPU-accelerated version of the stdstar fit (WIP).
The performance is about the same on Cori Haswell:
```
> time srun -n 1 -c 32 --cpu-bind=cores $CMD
...
real	1m3.543s
user	0m0.061s
sys	0m0.043s
> time srun -n 16 -c 2 --cpu-bind=cores $CMD --mpi
...
real	0m57.977s
user	0m0.070s
sys	0m0.099s
```
Full test setup:
```
cd $SCRATCH
git clone git@github.com:dmargala/desispec.git
cd desispec
git checkout mpi-stdstars
salloc -C haswell -N 1 -q interactive -t 30 --exclusive 
source …
```
=> MPI-ify stdstar fit

py/desispec/scripts/daily_processing.py, py/desispec/scripts/submit_night.py, py/desispec/workflow/procfuncs.py
This PR fixes the bug observed in cascades (the data was fixed, but by hand) where an "undithered" exposure was kept and flux calibrated with a subsequent science tile as opposed to being flux calibrated on its own. This was due to a simple logic change that arose when `LASTSTEP` was implemented. 
This pull request fixes the incorrect logic. It goes further to do other sanity checks on the list of science exposures to ensure they are meant to be run (`row['LASTSTEP'] != skysub`) and that the tiles are the same. If tiles are different, it processes the exposures from the most common tile. This should add robustness to bugs similar to the primary motivation of this fix where a single extra exposure sneaks in with an otherwise correct set.
This was tested using the `desi_run_night` code and …
=> Fix workflow bug that arises when dither is followed by non-dither

doc/nb/Lya-tsnr-signal.ipynb
Adds a dedicated notebook under docs/nb for deriving a template Lya signal.  The output of which has been committed to desimodel/data by svn.
=> Lyman-alpha signal template for tsnr

bin/desi_tile_redshifts
@akremin this PR provides `desi_tile_redshifts` as an alternative to `desi_nightly_redshifts` (which I haven't deleted yet).  Instead of running all redshifts in a single job, this generates one batch script per tile-group, with filtering options for whether that group is all exposures on a single night, across multiple nights, from a separately curated external list, etc.  Examples:
```
All exposures of tile 80605 on night 20201215:
desi_tile_redshifts --tile 80605 --night 20201215
Exposures E1 E2 E3 on night 20201215 (auto splitting by TILEID if needed):
desi_tile_redshifts --night 20201215 --expid 67972 67973 67968 67969
Tile 80605 combined across multiple nights:
desi_tile_redshifts --tile 80605 --night 20201214 20201215 --group blat
Tile 80605 combined across all nights: …
```
=> desi_tile_redshifts

doc/changes.rst, py/desispec/spectra.py
Should be a non-controversial merge: in a coadded fibermap `NIGHT` is no longer (necessarily) part of the data model, but the  `spectra.Spectra.select` method was still looking for it.
=> handle missing NIGHT in coadded fibermap

py/desispec/fiberfluxcorr.py, py/desispec/fluxcalibration.py, py/desispec/io/fluxcalibration.py, py/desispec/magnitude.py, py/desispec/scripts/fluxcalibration.py, py/desispec/test/util.py, requirements.txt
This PR provides corrections to the flux calibration to account for variations of the fiber acceptance with seeing, focal plane position (because of the change of plate scale), source morphology.
- add two functions in `desispec.fiberfluxcorr`:
-  `flat_to_psf_flux_correction`:  Multiplicative factor to apply to the flat-fielded spectroscopic flux of a fiber
to calibrate the spectrum of a point source, given the current exposure seeing and change of platescale in the focal plane.
- `psf_to_fiber_flux_correction`: Multiplicative factor to apply to the psf flux of a fiber to obtain the fiber flux, given the current exposure seeing, accounting for the shape/morphology of the source. The fiber flux is the flux one would collect for this object in a fiber of 1.5 arcsec diameter, for a 1 arcsec …
=> Flux calibration: fiber acceptance correction as a function of seeing, focal plane position, source morphology

py/desispec/specscore.py
Addresses #1193.  Runs through the use case example provided there and passes other vetting on values. 
For future consideration: rename TSNR_QSO to TSNR_QSO_BRZ etc. to mirror nomenclature for flux etc.
=> TSNR camera coadd fix

bin/desi_tile_redshifts, doc/changes.rst
This PR fixes #1194 (desi_tile_redshifts not processing a spectrograph if any cframes were missing).  It does with with a "report loudly but proceed" approach, pending a more subtle future update that knows more about what is and isn't supposed to be there for input.
Tested with:
```
mkdir -p /global/cfs/cdirs/desi/users/$USER/spectro/redux
cd /global/cfs/cdirs/desi/users/$USER/spectro/redux
export DESI_SPECTRO_REDUX=$(pwd)
export SPECPROD=ztile
head -1 /global/cfs/cdirs/desi/spectro/redux/cascades/run/scripts/tiles/explist-all-sv1.txt > explist-80607-20201218.txt
grep 80607 /global/cfs/cdirs/desi/spectro/redux/cascades/run/scripts/tiles/explist-all-sv1.txt | grep 20201218 >> explist-80607-20201218.txt
copyprod --explist explist-80607-20201218.txt …
```
=> fix tile_redshifts when missing cframes

py/desispec/tilecompleteness.py
Trivial PR: adding LYA_EFFTIME_DARK to tiles.csv because useful for Lya WG.
=> ADD LYA_EFFTIME_DARK to tiles.csv

bin/desi_tiles_completeness, bin/desi_tsnr_afterburner, py/desispec/tilecompleteness.py
Several small modifications to the tsnr exposures table and the tiles table following comments received.
- GOALTYP[E]
- add SEEING_ETC EFFTIME_ETC from image header keywords (origin = ETC) …
- add MINTFRAC from fibermap header (origin = fiberassign) 
- replace upper case to lower case string 
- write csv exposure table
- guess GOALTYPE from FAFLAVOR if the former is missing
- guess SURVEY (cmx,sv1) from FAFLAVOR if exist
- drop TARGETS column (use FAFLAVOR instead) 
Example formats
```
tsnr2-exposures.csv
NIGHT,EXPID,TILEID,SEEING_ETC,EFFTIME_ETC,SURVEY,GOALTYPE,MINTFRAC,FAFLAVOR,GOALTIME,EXPTIME,TSNR2_ELG,TSNR2_BGS,TSNR2_QSO,TSNR2_LRG,ELG_EFFTIME_DARK,BGS_EFFTIME_BRIGHT,EFFTIME_SPEC,TSNR2_LYA,TSNR2_ALPHA,LYA_EFFTIME_DARK
20210116,72708,80661,0.0,0.0,sv1,bright,0.9,sv1bgsmws,0.0,300.1,5.8, …
```
=> Changes to the offline pipeline exposures and tiles tables

bin/desi_tile_redshifts, py/desispec/io/frame.py, py/desispec/pixgroup.py, py/desispec/tsnr.py
This PR updates `desi_tile_redshifts` to use the new tile redshift output directory organization, selected by the `--group` option, which is now required:
* cumulative: `tiles/cumulative/TILEID/YEARMMDD/zbest-SP-TILEID-thruYEARMMDD.fits`
* all exposures for TILEID through night YEARMMDD combined
* pernight: `tiles/pernight/TILEID/YEARMMDD/zbest-SP-TILEID-YEARMMDD.fits`
* exposures for TILEID on night YEARMMDD, but not other nights
* perexp: `tiles/perexp/TILEID/EXPID/zbest-SP-TILEID-expEXPID.fits`
* only exposure EXPID
* pernight-v0: `tiles/TILEID/YEARMMDD/zbest-SP-TILEID-YEARMMDD.fits`
* current output format with redshifts grouped per night, to be deprecated; note that "pernight" is the same as this with one additional level of hierarchy
* anythingelse: …
=> New tile redshift organization

bin/desi_tile_redshifts
This PR fixes #1210 by making desi_tile_redshifts robust to missing exposure tables, e.g. from early data in the daily runs.  If the table is missing after 20201201, it logs an error because we do expect those to exist, but it still continues.  Prior to 20201201 it will use a table if it finds it (e.g. for reruns of early commissioning data), but it won't log an error if missing.
=> robust to missing exposure tables

py/desispec/sky.py
This is similar to #1182
`fitsdiff` shows no difference in output other than the checksums and timestamps.
For 20200227/00052426 on camera z5, this change brings run time down from ~6m20s to ~1m40s.
P.S. I accidentally pushed this commit to master and then reverted it. Apologies! While I will pay extra attention before I push in the future, let me know if another solution (e.g. force-push) is preferred should this happen again.
=> Use sparse matrix types in compute_polynomial_times_sky

py/desispec/io/fluxcalibration.py, py/desispec/scripts/stdstars.py, py/desispec/test/test_binscripts.py, py/desispec/test/test_io.py
This PR improves standard star provenance by including 2 additional HDUs in the stdstars*.fits files:
* FIBERMAP: fibermap entries for the standard stars used in the fit, not including the columns like DELTA_X/Y, FIBER_X/Y that apply to specific exposures rather than the input targets (see note below).
* INPUT_FRAMES: a table with columns NIGHT, EXPID, CAMERA indicating which input frames were used for the joint standard star fit.
And example output file is in /global/cfs/cdirs/desi/users/sjbailey/dev/stdstars/stdstars-2-00081899.fits, to be compared with the original daily run in /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20210324/00081899/stdstars-2-00081899.fits .  This was run with
```
cd /global/cfs/cdirs/desi/spectro/redux/daily/
desi_fit_stdstars --delta-color 0.1 \ …
```
=> improve stdstar provenance

bin/desi_proc_joint_fit, py/desispec/fluxcalibration.py, py/desispec/scripts/stdstars.py
This PR adds support for using GPUs in the standard star fitting step of the pipeline. 
The main change is to move the median filter operation in `desispec.fluxcalibration.applySmoothingFilter` to the GPU. Here is a profile of the CPU version of the standard star fit that motivates this:
The GPU code is disabled by default and must be explicitly enabled by setting `desispec.fluxcalibration.use_gpu = True`. After importing, `desispec.fluxcalibration.gpu_available` is set to `True` if the `cupy` module is installed and able to detect a GPU.
I also made some changes to `desi_proc_joint_fit` for testing but those are still WIP. I'm open to feedback on how to integrate those changes with the existing pipeline setup.
```
module load python cuda/11.1.1 gcc openmpi
source activate …
```
=> Add support for using GPUs in standard star fit

bin/desi_daily_proc_manager, bin/desi_run_night, py/desispec/io/meta.py, py/desispec/io/util.py, py/desispec/scripts/daily_processing.py, py/desispec/scripts/submit_night.py, py/desispec/workflow/procfuncs.py, py/desispec/workflow/proctable.py
This pull request adds a new function `check_for_outputs_on_disk` that is run within the pipeline prior to creating or submitting a job to the queue during the reduction of spectra data. The motivation is the fact that we may submit jobs that will do nothing more than check if outputs exist for several sub-tasks and then exit, filling the queue for no reason. We may also submit large 5 node jobs to process 30 cameras where only 2 still need to be processed. This does that checking prior to submission and only requests resources and processing for the cameras that still need to be processed.
If all output files are present, then by default the job is not submitted. If some files are present, by default it submits a smaller job to only process the missing data. The expected files are …
=> Check file outputs before submitting a spectro pipeline job

bin/desi_tile_redshifts
This PR fixes the order of the sbatch --reservation option for jobs submitted by desi_tile_redshifts, putting it before the scriptname instead of after.
```
[cori07 denali-beta] desi_tile_redshifts -n 20210304 -t 80695 --batch-queue regular --batch-reservation denali -g pernight --system-name cori-knl
INFO:desi_tile_redshifts:349:<module>: Loading production exposure tables for nights [20210304]
INFO:desi_tile_redshifts:416:<module>: Tile 80695 nights=[20210304] expids=[79300 79301]
INFO:desi_tile_redshifts:262:batch_tile_redshifts: Wrote /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/denali-beta/run/scripts/tiles/pernight/80695/20210304/coadd-redshifts-80695-20210304.slurm
Submitted batch job 41277182
INFO:desi_tile_redshifts:278:batch_tile_redshifts: submitted …
```
=> fix order of sbatch --reservation option

py/desispec/io/fibermap.py
This PR puts in a loose 100 micron quality cut on fiber positioning.  For tonight I didn't put in a tighter cut because the impact of `FIBERSTATUS != 0` is pretty draconian, resulting in ivar=0 for all wavelengths and a guaranteed loss of redshift, limiting our ability to study borderline cases with a tighter cut.  Better would be a warning flag that doesn't automatically force the target to junk, but that takes more surgery.  I also explored catching this post-facto with cuts on the redrock side, but got bogged down with what to do if one exposure was good but another was borderline and another was bad...
Kevin has also identified some bit misinterpretation where we are flagging some good positioners as bad, but I need to talk to him more to determine the correct recipe, so this …
=> loose 100 um quality cut on fiber positioning

bin/desi_compute_skymags, bin/desi_tiles_completeness, bin/desi_tsnr_afterburner, py/desispec/efftime.py, py/desispec/io/__init__.py, py/desispec/skymag.py, py/desispec/tilecompleteness.py
- Add information from offline GFA analysis with  `desi_tsnr_afterburner --gfa-proc-dir `. New columns: `TRANSPARENCY_GFA,FWHM_ASEC_GFA,FIBER_FRACFLUX_GFA,FIBER_FRACFLUX_ELG_GFA,FIBER_FRACFLUX_BGS_GFA,SKY_MAG_AB_GFA`
- Add computation of sky magnitudes with ` desi_tsnr_afterburner --compute-skymags` (or use external file). New columns:  `SKY_MAG_G_SPEC,SKY_MAG_R_SPEC,SKY_MAG_Z_SPEC`
- Add `desispec/skymag.py` for computation sky magnitudes.
- Add routine to compute efftime_dark,efftime_bright,efftime_backup using formulae in https://desi.lbl.gov/trac/wiki/SurveyOps/SurveySpeed. New columns: `EFFTIME_GFA,EFFTIME_DARK_GFA,EFFTIME_BRIGHT_GFA,EFFTIME_BACKUP_GFA`
- Sum of `EFFTIME_GFA` in tiles summary file.
Options to add to the daily cronjob:
`desi_tsnr_afterburner --gfa …
=> Add effective time from GFA data to exposures and tiles tables

bin/assemble_fibermap, py/desispec/io/fibermap.py, py/desispec/io/meta.py
This PR adds/corrects `assemble_fibermap` support for split exposures where the second exposure coordinates file lacks fiber positioning info (current code falls back to accepting all of them, even those that were known to be off-target from the previous exposure).
If in the future ICS/platemaker analyze the FVC image and start providing updated locations, this code will automatically use them.  Lacking that, it uses the `VISITIDS` to find the first EXPID in the sequence and uses that coordinates file which has the original acquisition fiber positions.
Additionally, this corrects the old `FLAGS_EXP_n<200` recipe which was inadvertently discarding the best positioned locations with the (semi-)new CONVERGED bit 15 set (!).  Thanks for Kevin for noticing this.  Note: The current (bad) …
=> support split exposures when making fibermap

bin/desi_tiles_completeness, py/desispec/tilecompleteness.py
This PR fixes the tiles completion table LASTNIGHT column for the case where exposures were flagged as bad and not processed.  This is needed for final Denali wrapup.
=> fix LASTNIGHT logic for bad exposures

doc/changes.rst, py/desispec/specscore.py
This PR fixes #1227 where a missing input TSNR column could result in a coadd failure.  It was used in this denali branch to mop up a few cases even though most of denali was run from the 0.40.1 tag.
=> fix coadds with missing TSNR columns

bin/desi_tsnr_afterburner
@julienguy here's a pull request to switch to ex=2 of my offline GFA summary files rather than ex=3. ex=3 makes cuts that are not relevant for the forced photometry quantities that go into computing EFFTIME_GFA. This can lead EFFTIME_GFA to be missing occasionally when it should be available. An example of this situation was EXPID = 84935, which is present in ex=2 of offline_matched_coadd_ccds_SV3-thru_20210415.fits but not in ex=3.
=> use ex=2 of offline GFA file rather than ex=3

bin/desi_average_flux_calibration
This PR provides the desi_average_flux_calibration script version used in DocDB-6157.
The modifications are:
- list of exposures are now provided through the name of file with the exposure paths
- option to correct or no for transparency for each exposure, before fitting
- option to use FWHM_ASEC or RADPROF_FWHM_ASEC for the GFA seeing measurement
- relies on SV1 GFA catalogs to extract, for each exposure: airmass, seeing, transparency, fiber_fracflux
- the seeing-dependence is now corrected for for each exposure, and not fitted.
The dependence on SV1 GFA catalogs may be re-worked to be more general, for future SV3 or MAIN.
Now that the seeing-dependence is corrected for before fitting, the seeing-term fitting may be obselete; or maybe this seeing-dependence correction could turned …
=> bin/desi_average_flux_calibration: version used for DocDB-6157

py/desispec/fluxcalibration.py, py/desispec/scripts/stdstars.py
This work is a continuation of #1184. In addition to parallelizing over standard stars, this PR adds the capability for `match_templates` to utilize multiple MPI ranks as well. This means if there are enough ranks each standard star now gets more than 1 rank at its disposal.
Both multiprocessing and mpi invocations of this code passed `fitsdiff` manual inspection for 20201214/00067765.
There seems to be some modest improvement running on a single haswell node. I did not test how well the code scales on multiple nodes because I didn't fix the "file reads performed by each rank" problem yet.
```
real    0m34.602s
user    0m0.082s
sys     0m0.120s
real    0m35.900s
user    0m0.110s
sys     0m0.125s
real    0m38.513s
user    0m0.104s
sys     0m0.131s
real    0m35.980s
user    0m0.090s
sys …
```
=> Add MPI to match_templates

py/desispec/scripts/stdstars.py, py/desispec/test/test_binscripts.py
I propose a simple option to stdstars script allowing to override isStdStar()  by directly specifying TARGETIDs of standards. 
That should make it easier to do tests expanding standard selection, processing fields without enough standards etc.
=> add an option to stdstars allowing to use arbitrary TARGETIDs as standards

py/desispec/fluxcalibration.py, py/desispec/scripts/fluxcalibration.py
This is a continuation of PR #1257 that enables performing fluxcalibration using whatever 
fibers are in the model files without double checking again whether these are standards according to the
fibermap
It adds  --nostdcheck parameter. 
I didnt' add a test for this, as I wasnt' sure if it's worth extra CPU cycles, but I can if needed. 
With this PR and a previous one I was able to easily reprocess the M31 exposures using a custom standard selection.
=> enable performing fluxcalibration using whatever fibers are in the model file without additional checks

py/desispec/fiberbitmasking.py, py/desispec/fibercrosstalk.py, py/desispec/maskbits.py, py/desispec/qproc/io.py, py/desispec/scripts/qproc.py, py/desispec/sky.py
This PR adds support for stuck positioners assigned to blank sky locations (i.e. if OBJTYPE='SKY' it doesn't discard the fibers just because FIBERSTATUS STUCKPOSITIONER is set).
It additionally corrects a mismatch between the desispec and fiberassign bit definitions that were resulting in RETRACTED positioners being discarded, even if they were assigned to valid targets.  FIBERSTATUS changes on the desitarget side to match fiberassign:
* bit 3 BADTARGET -> bit 0 UNASSIGNED
* bit 3 now RETRACTED and not treated as a fatal bit
Note: there is more that we can/should do for FIBERSTATUS bit masking and not treating all bits as fatal, but I'm trying to focus this PR on the minimum necessary to support stuck positioners assigned to sky (first used on 81097 observed 20210430/00086750, albeit …
=> add support for stuck positioners assigned to sky locations

py/desispec/workflow/utils.py
This PR only impacts one function `desispec.workflow.utils.check_running()` used in the daily pipeline to check for other instances of itself. It didn't work in a cron environment because it checked for the python script name in the full process command of every running process, but cron launches a bash process with the python command in it. Since the bash process had a different PID, it always exited incorrectly thinking there was another python process. 
This change checks that the command be from python or the script itself rather than bash. It also checks that the other instance is from the same user (which I think is the correct thing to do and certainly proved useful when testing it as my user last night in parallel with the official pipeline under the desi user).
Usage of …
=> Fix instance checking in daily pipeline

py/desispec/tsnr.py
Include tracer poisson term in tsnr model var for bgs and backup programs. 
(yet another branch)
=> TSNR: Add tracer poisson term to model ivar

py/desispec/scripts/qproc.py
This PR makes qproc (and thus nightwatch) robust to raw data that has a blank SEEING keyword (e.g. 20210531/00090518/fibermap-00090518.fits, though I think the blank keywords started on 20210528).  It now has a "is not None" check, and tries keywords in this order: SEEING, ETCSEENG, PMSEEING.
This keyword is used for corrections to the average flux calibration vector.  More correct would be to use one of the ETCFRAC* keywords (exposure weighted average fiber input fraction loss calculated for PSF, ETC, and BGS), but that requires more work and may unnecessary at the level of fidelity of nightwatch.
This is needed for nightwatch to work, so I will merge it and re-install once tests pass.
=> qproc robustness to blank SEEING keyword

py/desispec/trace_shifts.py
Fix an indexing bug in the rebinning when computing the x trace shifts.
It has always been there but had a negligible impact. It was found because of an other error (bad CCD calibration file)
=> Fix an indexing bug in the rebinning when computing the x shifts

bin/copyprod, py/desispec/scripts/tile_redshifts.py, py/desispec/workflow/procfuncs.py
This PR
1. adds a `desi_tile_redshifts --run_zqso` option to run `make_zqso_files` after running redshifts
2. pipeline automatically includes `--run_zqso` for cumulative redshifts but not other groupings
3. adds `copyprod --night YEARMMDD` option, which can include a wildcard, like `copyprod --night 202106\* ...` (unreleated to `--run_zqso`, but used for testing).
I have tested (1) and (3), but not (2).
Outputs of `desi_tile_redshifts -n 20210601 -t 1207 -g cumulative --run_zqso` are in `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/zqso/tiles/cumulative/1207/20210601`
@akremin please check pipeline logic; @geordie666 and/or @eleanorlyke please check zqso outputs.
=> desi_tile_redshifts --run_zqso option

bin/desi_compute_dark_nonlinear, py/desispec/ccdcalib.py
This PR makes some small updates to desi_compute_dark_nonlinear that I used while generating updated darks to address the r6 negative offset reported in #1297:
* pre-write the speclog table when running `desispec.ccdcalib.make_dark_scripts` so that it can be edited to remove problematic exposures
* ensure that it can be read back in when lines are commented out
I plan to self merge after tests pass.  I'll update #1297 with the details about the updated dark model.
=> pre-write speclog file for darks

py/desispec/workflow/exptable.py
This PR fixes a corner case where ACTTEFF is defined in the raw data header but is set to an empty (non-numeric) value. This caused the pipeline to crash. Now we test that it can be transformed into a float within a `try` statement.
This was part of a larger discussion that led to the choice of deprecating `ACTTEFF` in favor of `ETCTEFF`, which is also in the raw data header. For future dates on or after 20210614, only `ETCTEFF` will be checked. The old keyword is kept for compatibility with old data (under an assertion that `night<20210614`).
I tested this on nights in Dec 2020, Jan 2021, Feb 2021, April 2021, May 2021, and June 14 2021. No issues on any date.
=> Pipeline robustness when reading ETC values from raw data header

py/desispec/data/qa/qa-params.yaml
Change exposure QA parameter `max_frac_of_bad_positions_per_petal` from 0.5 to 0.6, i.e. a slightly looser cut on how many bad positions are allows before discarding the entire petal.  i.e. >40% of fibers much have <30 microns positioning accuracy for the petal to be considered good.
This implements a decision by @julienguy, @djschlegel and myself after email and zoom discussions with multiple others about exactly what the thresholds should be.
=> change QA max allowable bad positioning fraction from 0.5 to 0.6

bin/make_zmtl_files, py/desispec/io/meta.py, py/desispec/scripts/tile_redshifts.py, py/desispec/test/test_io.py, py/desispec/workflow/procfuncs.py, py/desispec/zmtl.py
This PR adds support for combining tile_qa with zmtl creation (formerly zqso, owned by desitarget now ported to desispec).  This PR requires desihub/desitarget#754 (branch zwarn_badspecqa) to get two additional ZWARN bit definitions for BAD_SPECQA and BAD_PETALQA.
Example outputs are in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/zmtl , see README with details e.g.
```
[setup the prod, then...]
desi_tile_qa -n 20210606 -t 1230,1246,1394
make_zmtl_files -n 20210606 -t 1230
make_zmtl_files -n 20210606 -t 1246
make_zmtl_files -n 20210606 -t 1394
```
I added updates for running this as part of the pipeline but haven't tested that yet.
Let's also re-check the QA before merging.  e.g. https://data.desi.lbl.gov/desi/users/sjbailey/spectro/redux/zmtl/tiles/cumulative/1394/20210606/tile-qa- …
=> add QA+zmtl support

py/desispec/scripts/daily_processing.py, py/desispec/workflow/exptable.py
This solves issue #1314 where we were missing the "`EndOfArcs`", "`EndOfFlats`", etc. flags sent via a `manifest` file because those "exposures" don't contain a raw data file, and we recently updated the pipeline to look for the raw data instead of `request` files.
This PR looks for `manifest` files in addition to the raw data, so it doesn't add a dependency on manifests. If no `manifest` files exist, that is okay.
I tested this on the three most recent nights 20210618, 20210618, and 20210620. It worked for all three of those nights in identifying the manifest files while still identifying all of the data exposures.
=> Look for manifests in nightly processing

py/desispec/scripts/extract.py, requirements.txt
**Note that this PR is currently WIP and should not be merged**
This PR adds support for using [gpu_specter](https://github.com/sbailey/gpu_specter) in place of specter in desi_extract_spectra. gpu_specter is essentially a refactor of `desispec.extract.main_mpi`+`specter.extract.ex2d` with support for running on GPUs. 
desi-related todo:
extraction-related todo (implemention needed in gpu_specter):
=> [WIP] add support for gpu_specter in desi_extract_spectra

py/desispec/desi_proc_dashboard.py
The dashboard updates included logic to determine when a row is "completed" such that we can archive the information and re-use it instead of searching the filesystem each time the code is run. Over the weekend flats were being displayed with missing fiberflats even though they existed on disk. It was because those rows were being archived as "complete" and reused with incomplete information with less than 30 fiberflat files counted.
The code assumed frames were the last filetype generated for flats rather than fiberflats, and that the existence of those frames implied the flats could be labeled as completed. 
This fixes the order of filetypes in the dashboard code such that the logic that determines when a flat is "complete" is based on fiberflat files instead of frame files. 
I tested …
=> Fix dashboard bug for flats

py/desispec/io/fibermap.py, py/desispec/test/test_fibermap.py
This PR fixes #1288 by adding PLATE_RA=TARGET_RA and PLATE_DEC=TARGET_DEC if they are missing from the input fiberassign file.  This provides data model consistency during sv3 (PLATE_RA, PLATE_DEC were added mid-way through).
A unit tests confirms that this column is added.  I also added a unit test confirming that the underlying problem of issue #1327 was already fixed (split exposures missing FIBER_X, FIBER_Y etc. and needing to fetch from the first exp in the sequence).
I'll leave this open for a bit but will self-merge if there are no comments since we want this before starting extractions of Everest science exposures.
=> add PLATE_RA, PLATE_DEC if missing

py/desispec/data/qa/qa-params.yaml, py/desispec/exposure_qa.py, py/desispec/fiberbitmasking.py, py/desispec/io/fibermap.py
This PR sets FIBERSTATUS bit POORPOSITION for positioners with 30 < offset < 100 microns (above 100 microns it is BADPOSITION).    Previously this bit was only set post-facto in QAFIBERSTATUS.  The parameters for what is bad vs. poor are taken from the qa-params.yaml file for consistency with QA cuts.
Targets with POORPOSITION are excluded from standard star calculations for flux calibration, but are otherwise propagated forward with just that bit set (unlike BADPOSITION, which forces ivar=0).  A separate desihub/redrock#197 issue will propagate this into a ZWARN POORDATA bit, but this PR gets us through cframes / spectra / coadds.
I tested this on tile 20878 night 20210706 expid 97680 sp4 in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/poorpos/exposures/20210706/00097680, …
=> flag POORPOSITION for 30 < offset < 100 um

bin/desi_qso_qn_afterburner
the zbest HDU from the new zbest file (new run of RR) is not in the same order than previously. The TARGETID order from ZBEST HDU does not match the order from the input targetid. 
I add, a sanity reorder to don't be messed with this later.
Edmond
=> Add sanity check readin the new zbest file

py/desispec/workflow/tableio.py
Check for comma_replacement instead of a comma when trying to find things to replace with a comma. 
Done as part of table input-output to avoid commas in saved tables but avoid semicolons in working memory since bash doesn't like semicolons.
=> fix table loading typo

py/desispec/desi_proc_dashboard.py
This changes the expected cameras for each exposure in the dashboard from the number in the processing table to something recomputed on-the-fly using the exposure table `CAMWORD`, `BADCAMWORD`, and `BADAMPS`.
There is no correct answer here but there are enough special treatment cases in a production that the processing tables weren't completely representative. We also expect the exposure tables to be accurate. If they are not, they should always be updated. So in that sense, this moves to the more correct choice.
This takes the `CAMWORD` and removes `BADCAMWORD` from the cameras expected. For arcs and flats, it also removes cameras associated with `BADAMPS` because those are not used in calibrations and therefore won't be found in the outputs.
This was tested on the ongoing Everest …
=> Recompute proccamword from exptable in dashboard

bin/desi_healpix_redshifts, py/desispec/pixgroup.py, py/desispec/scripts/group_spectra.py, py/desispec/scripts/healpix_redshifts.py, py/desispec/scripts/tile_redshifts.py
This PR:
* adds a new `desi_group_spectra --survey` option to filter by survey (e.g. sv3)
* adds desi_healpix_redshifts to generate job scripts for running healpix based coadds + redshifts + QSO afterburners analogous to desi_tile_redshifts
The relationship between desi_tile_redshifts and desi_healpix_redshifts for writing the batch script is a bit of a hack, but I need it for everest healpix so this is a fast solution.  It also still requires one call per healpix/survey/program which will get unwieldy so a future update could add a wrapper for that too to loop over pix.
I confirmed that this refactor produces identical scripts for desi_tile_redshifts, while supporting the minimal features needed for desi_healpix_redshifts.  I plan to self merge to be able to use tonight and postfacto …
=> desi_healpix_redshifts batch automation

bin/desi_zcatalog, py/desispec/io/util.py
This PR from "zcat" to "everest" (not master) branch updates `desi_zcatalog` to work with the new FIBERMAP + EXP_FIBERMAP + TSNR2 in Everest.  It also adds the ability to filter by TILEID (e.g. to make separate catalogs for sv1, sv2, sv3, main).  It removes `desi_merge_redrock_files` which was confusingly similar to `desi_zcatalog`.
By default, `desi_zcatalog` now merges the coadded FIBERMAP and TSNR2 HDUs into the output ZCATALOG table, and stacks the non-coadded input EXP_FIBERMAP into a separate HDU.  A new option `--minimal` only propagates TARGET_RA, TARGET_DEC, FLUX_G, FLUX_R, FLUX_Z instead of all of the fibermap columns.
The previous `--match` option is mostly not needed now due to propagating targeting information via the fibermap.  I disabled the option because I don't have time …
=> zcat for new fibermaps

py/desispec/scripts/group_spectra.py
This PR adds a `desi_group_spectra --healpix ...` option to re-generate only a specific set of healpix instead of all of them that it can find.  This is useful e.g. for reprocessing an everest healpix where we removed a bad exposure and then need to re-generate any healpix that it touched, without risking redoing all of the others too.
=> desi_group_spectra --healpix option

bin/desi_map_tilepix
This PR into the everest branch adds a `desi_map_tilepix` script which scans fibermaps to build a map of which healpix are covered by which tileid+petal_loc (petal_loc is equivalent to the spectrograph number in b0, r1, z9 etc.).  Example outputs are in
```
/global/cfs/cdirs/desi/spectro/redux/everest/healpix/tilepix.*
```
The fits file has a binary table with columns TILEID, PETAL_LOC, HEALPIX .  e.g. to find which healpix cover tile T petal P:
```
ii = (tilepix['TILEID'] == T) & (tilepix['PETAL_LOC'] == P)
healpix = np.unique(tilepix['HEALPIX'][ii]
```
The json file encodes this in a hierarchical structure:
```
healpix = tilepix[str(T)][str(P)]
```
Unfortunately the json format requires dictionary keys to be strings not integers, thus the `str(T)` and `str(P)`.
I'm hoping for Fuji we …
=> desi_map_tilepix script

doc/changes.rst, py/desispec/image_model.py, py/desispec/preproc.py, py/desispec/scripts/preproc.py, py/desispec/trace_shifts.py
- This PR adds a fit of a spectral traces offset (along x=cross-dispersion) between the input psf and the current image in the function compute_image_model. This function compute_image_model is called during preprocessing to build an inverse variance image.
- It improves the variance model, because there are variations as large as 1 pixel of the fiber traces location in the CCDs, expecially in z (that have been found to be correlated with humidity in the shack).
- This feature explains why we often have bad sky residual chi2 in z8 in the exposure QA (the default PSF for z8 is off by 1 pixel for some exposures).
This computation takes less than 2 seconds per frame (on one cori haswell process).
=> Adjust trace x when computing image model

py/desispec/trace_shifts.py
Do not modify the inverse variance of the input image of the function `trace_shifts.compute_dx_from_cross_dispersion_profiles`. This was the cause of a bug in the inverse variance of cosmic ray pixels in the preprocessing when adjusting the traces for the variance model.
=> do not modify the ivar in the input image

py/desispec/io/fibermap.py
This PR intercepts and corrects for the swapped fibers 3402 and 3429 in DESI data through July 2021.  It checks for the known incorrect FIBER:LOCATION and corrects only if needed.
Example:
```
assemble_fibermap -n 20201215 -e 68040 -o fibermap-00068040.fits
```
Python check:
```
fa1 = Table.read('/global/cfs/cdirs/desi/spectro/redux/everest/preproc/20201215/00068040/fibermap-00068040.fits')
fa2 = Table.read('fibermap-00068040.fits')
fa1.sort('LOCATION')
fa2.sort('LOCATION')
for col in ['TARGETID', 'LOCATION', 'TARGET_RA', 'TARGET_DEC', 'DESI_TARGET']:
assert np.all(fa1[col] == fa2[col])
ii1 = (fa1['FIBER'] == 3402) | (fa1['FIBER'] == 3429)
ii2 = (fa2['FIBER'] == 3402) | (fa2['FIBER'] == 3429)
print('Original swapped:\n', fa1['TARGETID', …
```
=> swap fibers 3402 and 3429 if needed

bin/desi_run_night, py/desispec/scripts/submit_night.py, py/desispec/workflow/procfuncs.py
This PR adds a `desi_run_night --tiles ...` option to filter what tiles would be submitted for that night.  This is primarily for testing where we'd like to re-run some test-tiles without rerunning all the tiles on a night, while still benefitting from the job dependency infrastructure to jointly fit standard stars across exposures, run redshifts, etc.
Examples, starting from a blank production with just the everest/exposure_tables/202006/*.* files:
Process exposures for just two tiles on a night:
```
desi_run_night -n 20210601 --dry-run-level 1 --tiles 80978,1399
```
--> generates jobs for exposures 90656, 90657, and 90660 for those tiles
Also include arcs and flats (tileid -99 in the exposure tables):
```
desi_run_night -n 20210601 --dry-run-level 1 --tiles 80978,1399,-99
```
--> same …
=> desi_run_night --tiles option

bin/assemble_fibermap, py/desispec/io/fibermap.py
This PR adds the hooks to allow fiberassign files in svn to override those in the raw data stream, e.g. to correct the secondary target bookkeeping bug (desihub/fiberassign#375) or the duplicate negative TARGETID bug (desihub/fiberassign#385).  At the same time, it checks columns used by operations to make sure that they didn't accidentally change: TARGETID, TARGET_RA, TARGET_DEC, PMRA, PMDEC, REF_EPOCH, LAMBDA_REF, LOCATION, PETAL_LOC, DEVICE_LOC .
`assemble_fibermap --no-svn-override ...` can be used to prevent using the svn copy if needed (but in that case it is better to fix whatever we don't like about the svn copy).  I did not implement the opposite of `--force-svn-override` to use the svn copy even if one of the operations columns listed about had a discrepancy.
Once special case: …
=> allow svn override of fiberassign files

bin/desi_tsnr_afterburner
This solves issue #1395 
It was tested on several nights in the `daily` prod: 20210214, 20210515, 20210516, 20210519, and 20210706. All successfully completed. (Nights 20210515 and 20210519 currently fail using `master`.)
I compared the outputs from 20210516 when running using `master` and using this branch and the outputs were the same for both the exposures file and the tiles file.
```
desi_tsnr_afterburner -o ./exposures.fits --prod daily --tile-completeness ./tiles.csv --gfa-proc-dir /global/cfs/cdirs/desi/survey/GFA/ --compute-skymags --update --nproc 8 --nights ${NIGHT}
```
```
WARNING:desi_tsnr_afterburner:306:compute_summary_tables: First row of summary_rows had colnames=['NIGHT', 'EXPID', 'TILEID', 'TILERA', 'TILEDEC', 'MJD', 'EXPTIME', 'AIRMASS', 'EBV', 'SEEING_ETC', …
```
=> Allow different numbers of tsnr columns in generating tsnr afterburner summary table

bin/desi_zcatalog
As  discussed in [issue #1370 ](https://github.com/desihub/desispec/issues/1370)  I'm adding an option to read the older format of zbest files so that desi_zcatalog can be used in existing "zbest" files, specially useful for the quickquasars mocks.
=> desi_zcatalog back compatibility 

py/desispec/scripts/proc_joint_fit.py, py/desispec/util.py
This PR fixes #1225 where multi-exposure stdstar fitting would fail if there was a single missing frame, even if other exposures from the same night had the camera.
e.g. tile 80694 on night 20210306: exposures 79570 had b8,r8,z8 but 79571 has only b8,r8 (z8 was lost due to a shutter light leak saturation event).  Previously the pipeline would fail due to the missing frame-z8-00079571.fits, but with this branch it succeeds because frame-z8-00079570.fits is available for the same tile on the same night for the multi-exposure stdstar fit.
Example:
```
export DESI_SPECTRO_REDUX=/global/cfs/cdirs/desi/users/$USER/spectro/redux
export SPECPROD=noz8
cd $DESI_SPECTRO_REDUX
copyprod --night 20210306 /global/cfs/cdirs/desi/spectro/redux/everest $SPECPROD
desi_proc_joint_fit --traceshift --obstype …
```
=> stdstars robust to missing individual frames

bin/desi_tsnr_afterburner
This is a few line fix to the `desi_tsnr_afterburner`. When running with the `--update` flag the code opens the old file and then makes updates on it before overwriting a new file with the same file name. When the current version is given an older file (like that in `daily` from pre-shutdown), it crashes because the HDU names have changed and it expects the new names. This first tries the new names, but catches the `KeyError` if it isn't found and then attempts the old names. 
Note: Because the afterburner overwrites the table it is given to update, the outputs are written in the new naming scheme and will not only change the table rows but also the names of the HDU to the new names.
=> Allow backward compatibility in tsnr exposure table HDU names

bin/desi_tiles_completeness, py/desispec/tilecompleteness.py
This PR fixes `desi_tiles_completeness` to be able to output a tiles-specstatus.ecsv file.  It currently requires another fix from @akremin to output a tsnr-exposures.fits (aka exposures-$SPECPROD.fits) file that included TILERA, TILEDEC, e.g. NERSC /global/cfs/cdirs/desi/users/kremin/workspace/tsnrhack/tsnr-exposures.fits .
Changes here:
* input HDU EXPOSURES (new) or TSNR2_EXPID (old)
* add OVERRIDE column (in tiles-specstatus.ecsv; not in original tiles.csv)
* when there are column mismatches; log a CRITICAL error and exit with a traceback instead of a print + sys.exit(12).
@akremin when you are done with your mid-day meetings, let's touch base about whether this should be merged into your upcoming PR (for TILERA, TILEDEC), or whether we should merge these separately.
=> fix desi_tiles_completeness

py/desispec/scripts/specex.py
Attempt to fix bugs preventing PSF and trace coefficients from being correctly averaged in `desispec.specex.mean_psf` whenever the wavelength range differs between the input PSF fits:
1. `legval` and `legfit` were not being imported from `numpy.polynomial.legendre`
2. traces were being averaged redundantly for every entry in the table of PSF coefficients 
3. traces were being re-fit using the wrong number of legendre polynomial coefficients
These changes may require further validation; there is no before and after comparison possible for the use case that has changed since it was crashing for these cases (i.e. whenever the wavelength range differs between the input PSF fits).
=> Averaging of PSFs with different wavelength ranges

py/desispec/workflow/exptable.py
This addresses issue #1375 
It updates the spectroscopic pipeline to use the new airmass dependence when estimating survey speed in the automated data quality cuts.
Change:
OLD:    `oldspeed =   (EFFTIME_ETC / EXPTIME) * (AIRFAC^2) * (EBVFAC^2)`
NEW:   `newspeed = (EFFTIME_ETC / EXPTIME) * AIRCORRECTION * (EBVFAC^2)`
with   `AIRCORRECTION = AIRMASS^1.75`
`AIRFAC` and `EBVFAC`, as well as the equations, are defined here: https://desi.lbl.gov/trac/wiki/SurveyOps/SurveySpeed 
It also removes `AIRFAC` from the spectro pipeline "exposure tables" for the more useful column `AIRMASS` . A separate PR will include a script capable of updating past tables to the new datamodel.
Finally, this also makes an unrelated change to check for uncompressed `fiberassign` files if the compressed version …
=> Updates survey speed metric in pipeline to new airmass dependence

py/desispec/sky.py
Compare the number of valid measurements per wavelength to the number of valid sky fibers (i.e. fibers that have some non null ivar values after the call to get_fiberbitmasked_frame_arrays) instead of comparing to the total number of sky fibers.
This feature caused sky subtraction to set ivar=0 to full frames. It happened in the first few nights after restart because many sky fibers have large positioning errors (>100 um).
=> Only consider valid sky fibers

bin/desi_tile_vi, bin/desi_tiles_completeness, bin/desi_update_tiles_specstatus, py/desispec/tilecompleteness.py
This PR adds `bin/desi_update_tiles_specstatus` to update svn surveyops/ops/tiles-specstatus.ecsv with with processing information from spectro/redux/daily/tiles.csv, without clobbering QA columns.
To decide (but doesn't apply to any current data): if specstatus['ZDONE'] == 'true' and (tiles['LASTNIGHT'] > specstatus['LASTNIGHT']), should we update the non-QA columns or not?  i.e. if we did QA and flagged a tile as done, but for some reason got more observations anyway, what should the default update do?  Freeze the EFFSTATUS_SPEC etc. at the state it was when we declared the tile done, or update it to the current status of data processing?
This script is useable as-is, but if I have time before final merging, some other items to do:
* add pre-check whether svn update needs to be run (an …
=> add desi_update_tiles_specstatus

doc/api.rst, py/desispec/scripts/proc.py, py/desispec/scripts/specex.py, py/desispec/workflow/desi_proc_funcs.py, py/desispec/workflow/schedule.py
Adds new functionality to schedule specex jobs dynamically in `py/desispec/scripts/proc.py`, by assigning each ccd image ('camera') to a group of 20 MPI processes ('group') for PSF fitting (one process for each bundle on the image) from a queue, such that when a group finishes PSF fitting for a given camera it is assigned the last undone camera on the list as currently created in `proc.py` . The process continues until all cameras have had their PSFs fit. 
Because an additional single 'scheduler' process is necessary, the number of processes available for PSF fitting is `nranks-1`. For example, if `proc.py` is run for 30 cameras ([b0,...,b9,r0,...,r9,z0,...z9]) and called with a total of 201 MPI processes available in MPI_COMM_WORLD, then 10 groups of 20 MPI processes will be created, and …
=> Job scheduler for specex

py/desispec/calibfinder.py, py/desispec/io/raw.py, py/desispec/maskbits.py, py/desispec/scripts/proc.py
PR on the handling of bad fibers in the spectroscopic pipeline.
- The spectrograph ccd calibration yaml files can now have 3 keywords:
BROKENFIBERS, BADCOLUMNFIBERS, LOWTRANSMISSIONFIBERS
with a list of fibers. For instance for z7, in the file sm8-z.yaml (not committed yet):
```
BROKENFIBERS: 2842
BADCOLUMNFIBERS: 2664:2675
```
(2664:2675 means all fibers >=2664 and <2675, as in python)
- The list of bad fibers is given by the routine calibfinder.badfibers() where one can optionally select one or several of the above keywords.
- This is used during processing to store this information in the fibermap 'FIBERSTATUS' column, with
the corresponding desispec.maskbits.fibermask bits BROKENFIBER BADCOLUMN LOWTRANSMISSION (new bit defined in this PR).
- It is also used by specex to select the …
=> Bad fibers

bin/desi_tile_qa, py/desispec/tile_qa_plot.py
This PR fixes a tsnrexpfits file from https://github.com/desihub/desispec/pull/1443, with a bugfix and a safer way to find the filename, looking for:
- tsnr-exposures.fits (daily)
- or exposures-{}.fits (everest)
- or tsnr-{prod}.fits (cascades, denali).
**Unrelated to the current changes:**
note that with testing for denali with some SV1 tile, I encounter the following error, where apparently the --args.outdir is not taken into account: 
```
desi_tile_qa --outdir ./ --nights 20201221 --prod denali --tileids 80622
...
File "/global/homes/r/raichoor/software_dev/desispec_tile_qa_plot_v2/py/desispec/tile_qa.py", line 72, in compute_tile_qa
write_exposure_qa(filename, exposure_fiberqa_table , exposure_petalqa_table)
...
PermissionError: [Errno 13] …
```
=> Tile qa plot v2bis

py/desispec/workflow/desi_proc_funcs.py
Reduce number of MPI processes while keeping the number of nodes fixed -- instead of keeping the number of MPI processes fixed and increasing the number of nodes -- until memory required per node is less than that available, for arc jobs on knl. 
E.g., running the following command
```
desi_proc --traceshift --cameras a0123456789 -n 20210710 -e 00098135 --mpi --batch --nosubmit --system-name cori-knl
```
on the master branch results in a batch file containing the lines:
```
#SBATCH -N 18
...
export OMP_NUM_THREADS=8
...
srun -N 18 -n 601 -c 8 ...
```
while running it on this branch results in a batch file containing the lines:
```
#SBATCH -N 9
...
export OMP_NUM_THREADS=8
...
srun -N 9 -n 301 -c 8 ...
```
Wall-clock is less than a factor of two larger in the latter case, indicating an …
=> Don't change number of nodes for arc jobs on knl

py/desispec/scripts/daily_processing.py, py/desispec/scripts/submit_night.py, py/desispec/workflow/procfuncs.py
This is the final PR in the effort to add the bias modeling and bad column identification into the pipeline. This pull request incorporates darks into the reprocessing code, `desi_run_night`. 
Most of the underlying functions were updated yesterday. This primarily edits the coordination script `desi_run_night` so that it keeps and submits dark jobs. While doing so I also implemented a small feature that moves the calibrations to the start of the exposures so that cals are always processed first, in order of: 1) the first 300s dark, 2) arcs+flats, 3) science exposures.
I also fixed a bug meant to catch darks of the wrong `EXPTIME`.
I've tested this on 20211020 with multiple darks and it runs the first dark and skips the subsequent darks as expected. I tested it on one "typical" night, …
=> Add nightly bias and bad column flagging into desi_run_night

py/desispec/preproc.py
In preproc.py ,
- Compute the range of variation of the median overscan per row along the CCD columns
- Save this value in the header keyword OSTEPX (with X the amplifier identifier).
- If OSTEPX<1 ADU, use the standard average value in the overscan region
- if 1<OSTEPX<15 ADU, use the median overscan per row 
- if OSTEPX>15 ADU (or readnoise>10 elec), set BADREADNOISE CCD mask bit, which is subsequently propagated to the FIBERMAX and effectively discards all the fiber traces of this amplifier.
The motivation for this PR is in described https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=6516
=> Metric for the variation of overscan per row

py/desispec/workflow/desi_proc_funcs.py
@akremin this PR fixes `desi_run_night` launching a dark+nightly bias by throttling all DARKs to use only 8 cores within `desispec.workflow.desi_proc_funcs.determine_resources`.  This isn't strictly optimal because we only need to throttle to 8 cores when the dark is combined with a nightlybias in desi_proc, but in practice we aren't processing other darks anyway via `desi_run_night`.
`desispec.workflow.desi_proc_funcs.create_desi_proc_batch_script` catches the `nightlybias` option and throttles the cores in addition to what `determine_resources` reports for a vanilla DARK, but I haven't traced why `desi_run_night` doesn't appear to go through that function when creating the batch script.
If you know of a more elegant / correct / better solution, go for it, but in the meantime this is a …
=> throttle darks to 8 cores due to combining with --nightlybias

bin/desi_run_night, py/desispec/scripts/daily_processing.py, py/desispec/scripts/submit_night.py
This fixes a bug in which joint-fit jobs were not given strictly_successful=True, which led to them being run even with failed inputs. This is what we want for the daily processing but not for reprocessing where we have already dealt with bad exposures and everything being processed should be successful. This was actually introduced in the late spring by another of my previous pull requests. The original version of the script had the proper "True" value set.
The remainder of the PR deals with existing processing tables. If a processing table is found and told to append to the table using `--append-to-proc-table`, the script now skips over exposures in the exposure table corresponding to exposures already present in the exposure table. 
Since this loads previous exposures, it checks to see …
=> Improve desi_run_night handling of prior processing table in the pipeline

py/desispec/io/raw.py, py/desispec/maskbits.py, py/desispec/preproc.py, py/desispec/scripts/extract.py, py/desispec/sky.py
In this PR the ccdmask.BADREADNOISE is propagated to the fibermap FIBERSTATUS during preprocessing
(it was only set in QA so far). This PR addresses issue #1470.
=> Set fibermap.FIBERSTATUS BADREADNOISE

py/desispec/scripts/proc.py, py/desispec/scripts/proc_joint_fit.py
This PR fixes #1471 by updating desi_proc to not use PSFs that have a masked bad amp, e.g. recent r8A.
It still generates the PSF file for post-facto debugging, but if the input CCD has a flagged amp it renames the psf to (origname).badreadnoise and skips the bad fiber interpolation step.  Because this doesn't result in a "fit-psf*.fits" file, it won't get picked up by the merging step.
Implementation detail: although currently we flag entire amps with the ccdmask.BADREADNOISE bit, I implemented this as a somewhat more generic >12.5% pixels (half of one amp) have BADREADNOISE set, just in case some future update changes how BADREADNOISE is set (I realize that readnoise physically comes from individual amps, but sometimes it "turns on" or off during readout and we also have effective …
=> don't use PSFs with bad amps

py/desispec/scripts/trace_shifts.py
Minor PR fixing a 1 time issue that revealed an actual weakness in the pipeline.
The fit of the trace shifts includes polynomial degrees as a function of CCD coordinates that become weakly constrained when an entire amplifier is masked.
Here we detect masked amplifiers (by inspecting the FIBERSTATUS values in the fibermap) and force a degree = 0 (i.e. single scalar shift) when at least one amplifier of a CCD is masked.
Example is exposure 20211107/00107853. The sky subtraction is ok with this version of the code.
=> Degraded trace shift when amplifier is masked

py/desispec/tile_qa_plot.py
This PR adds few features to the tile-qa*png plots:
- cutout: EBV contours (to see if some low-efftime fibers are due to high EBV)
- Z vs. FIBER plot:
- highlight petals boundaries (to ease crossing information with focal plane plots)
- isolate non-TGT fibers (to de-emphasize those, which are "noise" in this plot)
- invert the color scheme, with displaying QAFIBERSTATUS=0 as blue, QAFIBERSTATUS>0 as red
- n(z): extend xrange from Z=5 to Z=6 (for dark tiles, to help visualize any dubious bump at Z>5).
The EBV contours add a step to query the SFD maps for a grid of 10k points: it looks like it does not significantly slow the routine.
Example for TILEID=11648, NIGHT=20211102, where the EBV contours help to understand why fibers are rejected in PETAL_LOC=6:
Previously:
With this PR:
=> Tile qa plot v5

bin/desi_archive_tilenight, bin/desi_tile_vi, bin/desi_update_tiles_specstatus
This PR adds the infrastructure for archiving tiles/cumulative/TILEID/LASTNIGHT -> tiles/archive/TILEID/ARCHIVEDATE after desi_tile_vi has approved tiles as done.
For tiles that have already been released:
/global/cfs/cdirs/desi/users/sjbailey/svn/surveyops/ops/tiles-specstatus.ecsv is updated to include a new ARCHIVEDATE column, based upon surveyops/trunk/mtl/mtl-done-tiles.ecsv TIMESTAMP.
`desi_freeze_tilenight` is updated and renamed to `desi_archive_tilenight` so that it moves tiles/cumulative/TILEID/LASTNIGHT -> tiles/archive/TILEID/ARCHIVEDATE, removes write permission, and leave a link behind.  The new frozen tiles/archive/TILEID/ARCHIVEDATE is the location that future MTL code will use.
`desi_update_tiles_specstatus` is also updated to set ARCHIVEDATE=0 for any new tiles added to …
=> desi_archive_tilenight

py/desispec/desi_proc_dashboard.py
This combines a number of improvements I have built up on my "wish list" for the pipeline dashboard. The impetus was (2), which was causing the dashboard to not list some exposures as "processing" even though they were during the Oct 2021 rerun of post-shutdown data.
The main features/changes are: 
1. Linking to the correct log for sciences that fail in standard star fitting
2. Determines what is processed based on processing table _and_ directories in preproc
3. Using white space better
4. Moving `TILEID` next to `EXPID`
5. Adding `FA_SURV` `FAPRGRM`
6. Opening TILE fibersassign images in new tab
7. Code improvements, including better usage of the pipeline tables and making the columns more readable/editable.
(1) was a long standing limitation that needed to be addressed. (2) became …
=> Pipeline Dashboard Improvements

py/desispec/io/fibermap.py, py/desispec/io/util.py
An unintended side effect of PR #1454 to support fibermap reading with astropy 4.3.1 (i.e. by using fitsio instead and then putting into an astropy Table), was a bunch of warning messages when trying to write it back out as part of `desispec.io.frame.write_frame` due to it using `astropy.io.fits.convenience.table_to_hdu`:
Current master produces 178 warning messages per call to table_to_hdu (which gets multiplied by 30 when wrapped by the pipeline for 30 cameras in parallel...)
```python
>>> import desispec.io
>>> from astropy.io.fits.convenience import table_to_hdu
>>> fm = desispec.io.read_fibermap('fibermap.fits')
INFO:fibermap.py:335:read_fibermap: iotime 0.081 sec to read fibermap.fits at 2021-11-08T21:06:39.209923
>>> table_to_hdu(fm)
WARNING: Meta-data keyword XTENSION will be …
```
=> avoid TTYPE etc. FITS warnings when writing frames with fibermaps

py/desispec/io/fibermap.py, requirements.txt
This PR uses `desitarget.skybricks` to check OBJTYPE=SKY fibers on stuck positioners for whether they are still on valid sky locations, instead of just setting FIBERSTATUS BADPOSITION if they are "off target".  This addresses a problem first noticed by @araichoor where we were discarding many stuck SKY fibers due to a disagreement between fiberassign and platemaker about where they were expected to be (the underlying cause is still under investigation).
Example outputs for 20211106 are in /global/cfs/cdirs/desi/users/sjbailey/dev/stucksky, with a comparison of how many total SKY are retained:
Using `desitarget.skybricks` requires `$SKYBRICKS_DIR=/global/cfs/cdirs/desi/target/skybricks/v3/` [52 GB], which is an unfortunately large new input dependency, but it only adds minimal runtime to …
=> use desitarget.skybricks to check stuck sky locations

bin/desi_resubmit_queue_failures, py/desispec/scripts/daily_processing.py, py/desispec/scripts/submit_night.py, py/desispec/workflow/procfuncs.py, py/desispec/workflow/queue.py
Create a script `desi_resubmit_queue_failures` that can take a night or processing table pathname, understand what jobs failed because of a hardware/OS based issue, and resubmit those jobs along with any later dependencies.
This updates and debugs several pipeline functions that query a `Slurm` scheduler using `sacct` to get information on previously submitted queue jobs. These functions existed in `desispec` but were not used. I ended up refactoring things to work by querying the jobid's themselves rather than the user and a date range, because it is both more efficient and cleaner. The new function eliminated the need for NERSC start and stop times, which were removed from `desi_daily_proc_manager` and `desi_run_night`. I tested these scripts with `--dry-run` and confirmed they still …
=> Create script to resubmit jobs if they would run the second time

py/desispec/scripts/stdstars.py
This PR fixes #1356 by correcting the CAMERAS column name in the stdstars INPUT_FRAMES table (previously the cameras were in a column called "TILEID").
I did a paranoia check by running the same `desi_fit_stdstars` command with master and this branch and confirmed that the files differ only by that column name and timestamps.  That HDU is informational only and not used by downstream code (verified with grep, not with running) so the change of name shouldn't break anything else.
I intend to self-merge this simple fix.
=> fix CAMERA column name in stdstars INPUT_FRAMES

py/desispec/sky.py
This fixes #1486 which did not define the variable for good sky fibers in cases where none are bad.
=> move the definition of good so it's defined

py/desispec/exposure_qa.py
One line bug fix in exposure QA: the spectral inverse variance was not used when computing the scale factors used to estimate the quality of the flux calibration. This resulted in overestimated QA calibration RMS when many pixels of a spectrum of a std star are masked which happens for few exposures.
=> QA bug fix in the estimation of the calibration stars rms

doc/changes.rst, py/desispec/io/fibermap.py, py/desispec/test/test_fibermap.py
This PR adds dummy columns to the fibermap table for very early (February-March 2020) that still had DR8-era columns.  The affected columns are `SERSIC`, `SHAPE_R`, `SHAPE_E1`, `SHAPE_E2`.  I tested on these exposures:
```
assemble_fibermap -n 20200219 -e 51039 -o fm1.fits
assemble_fibermap -n 20200315 -e 55611 -o fm1.fits
```
=> assemble_fibermap for very early exposures

bin/desi_tile_vi
This PR adds a `desi_tile_vi --qastatus ...` option, e.g. to scan only QA=unsure tiles:
```
desi_tile_vi --qastatus unsure
```
=> tile VI add QA status filter

py/desispec/scripts/daily_processing.py
This addresses issue #1500 by requiring all dependencies to be "afterok". The consequence of this is that a failure in a calibration exposure (or joint calibration job) will cause all science exposures to be cancelled. This is still the best approach, however, because we want to either flag, rerun, or fix the issue in the cals so that we can use them for the sciences.
The change is straight forward and now mirrors the re-processing script that has used this logic successfully in the past.
=> afterok for all jobs in daily processing

py/desispec/scripts/daily_processing.py, py/desispec/scripts/proc.py, py/desispec/scripts/submit_night.py
This pull request solves issue #1499. It adds new logic in the handling of `OBSTYPE==flat` exposures so that short flats used for monitoring CTE issues in the cameras will not be used to generate `fiberflat`'s. 
Two small changes were made:
- `desi_daily_proc_manager` and `desi_run_night` were updated to process the short flat, but not include it in the joint fit of the `nightlyflat`. This is done by requiring the `EXPTIME > 100s` for a flat to be used for the `nightlyflat` file generation.
- `desi_proc` was updated to load the exposure time of the flat and only produce `fiberflat`'s if `EXPTIME > 10s`. 
The specific hardcoded times are somewhat arbitrary, but the idea is to only use long flats for the ubercal and to not bother creating an individual fiberflat for very short exposures. …
=> Handle new short QA flats in the pipeline

bin/desi_tsnr_afterburner, py/desispec/tilecompleteness.py
This PR fixes a number of corner cases in desi_tsnr_afterburner that were resulting in SURVEY='unknown' and other oddities:
* All FAFLAVOR/FAPRGRM dith* tiles now have SURVEY=cmx GOALTYPE=other instead of SURVEY=GOALTYPE=unknown (which previously occurred for some but not all dither tiles)
* Tiles where all exposures are rejected as bad and have EFFTIME_SPEC=0.0 are listed as OBSSTATUS=other instead of OBSSTATUS=unknown.
* @schlafly I could make this OBSSTATUS=obsstart if that would make life easier to afternoon planning, but currently they only get OBSSTATUS=obsstart if EFFTIME_SPEC>0.0
* Adding bad/missing exposures is now opt-in (`--add-badexp`) with the intention that we would use this for daily processing so that afternoon planning can know about exposures that we have rejected, but …
=> fix tsnr_afterburner "unknown" entries
