py/desispec/io/fibermap.py

Night 20211126 exposure 111105 had GFA readout problems, resulting in "EXPTIME" not being in the guider header, causing assemble_fibermap to trip on removing a keyword that wasn't there (normally we remove it because we want the spectrograph EXPTIME, not the guider EXPTIME while propagating header keywords).  It's not yet clear whether that exposure is good, but we shouldn't trip on a missing keyword that we're trying to remove anyway and this PR will at least let us process the exposure to inspect the spectral quality.
Side note: EXPTIME actually ends up as a column rather than a header keyword, which makes it easier to stack fibermaps for coaddes, summary tables, etc.
For the record, the nightlog messages were:
```
01:50 [08:50] Incorrect image size preventing GFA readout.; AlarmID: …
```

robust to missing guider EXPTIME

---

bin/desi_tile_vi

This PR adds an option to desi_tile_vi to specify the programs of interest.  The default value is ['dark', 'bright'].  This means that by default we don't see backup tiles in VI.  We don't have real plots for them anyway, so it's just confusing to get them at the moment.  I've been encouraging VIers not to enter anything for these tiles, but that requires skipping through an accumulating number of backup tiles, which is dumb.
This also sets the default value of the --survey argument to 'main'.  This is not future-proofed, so in five years or whatever when we do have another survey for which we want to be doing VI & MTL updates, we'd have to do two separate VI invocations to get them.  But let's leave that to another day.

Only show main survey, dark/bright tiles by default.

---

py/desispec/scripts/daily_processing.py
py/desispec/workflow/procfuncs.py

There is a corner case when re-loading flats after a script crash where upon restarting the script the 1s short flat will be included with the other flats for use in producing the `nightlyflat`'s. This corrects that by only adding a flat if it is over 100s, but still allowing the loop to continue looking for additional flats of the correct type.
This also improves the saving of tables by writing out after joint fitting. Previously the tables were only written out after a single exposure processing, so some jobs could be submitted but not saved to the table on disk before a crash. Now we write out after each joint fit.
I tested this using `dry-run-level=2`, which produces the tables but doesn't submit jobs. I killed the script after joint fits and found the joint jobs were written out …

Improvements to short flat handling in daily pipeline

---

py/desispec/io/fibermap.py

This PR fixes a bug identified by Arjun in #1447, where fibers with FIBER_X=FIBER_Y=0.0 still had FIBERSTATUS=0 (i.e. good).  They are now flagged as FIBERSTATUS.MISSINGPOSITION because we don't have any position information for them from platemaker.
An example of this was retired tile 80713 observed on night 20210110 expid 71721 .  The input fibermap had NaN, resulting in platemaker confusion and FIBER_X=FIBER_Y=0.0 .  This tile was replaced and reobserved as 80715.
```
assemble_fibermap -n 20210110 -e 71721 -o blat.fits
```
In this particular case we're retiring the tile anyway, but if FIBER_X=FIBER_Y=0.0 comes up again, we shouldn't be treating those as good positions.

flag FIBER_X/Y==0 as FIBERSTATUS MISSING

---

bin/desi_archive_tilenight
bin/desi_tile_vi

This PR updates the tile QA + archive workflow to separate the concepts of tile QA from actually archiving those tiles and making them available to MTL:
* `desi_tile_vi` only updates tiles-specstatus.ecsv QA column; it no longer sets ZDONE=true nor ARCHIVEDATE
* `desi_archive_tilenight` now updates ARCHIVEDATE and sets ZDONE=true when it is done archiving
* new options `--thru` and `--since` allow filtering by LASTNIGHT, e.g. to archive QA=good tiles while excluding recent nights that are still being post-QA vetted.
No changes are needed on the MTL side since it looks for ZDONE=true.  The idea is that we would continue to do QA (desi_tile_vi) on a daily basis, but we'd optionally archive tiles less frequently and with a couple-day delay in case new problems come up that weren't caught in …

separate tile QA and tile archive

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR handles in the night qa scripts the case where no (main) science exposures are taken.
The same set of files will be created, but some will be empty (sframesky, tileqa, skyzfiber, petalnz); the page is still useful to monitor the rest.
An example here: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/20211209/nightqa-20211209.html
To inform the inspector, I also now report at the top of the page the number of exposures/tiles, so that it is clearly stated if there is no science exposures.

Nightqa v2

---

py/desispec/workflow/desi_proc_funcs.py

This PR makes a special case for KNL arc jobs to *not* apply the normal 3x extra time factor, since the default Haswell jobs are already 45 minutes (to allow for fluctuations in realtime processing), even though a normal Haswell arc job is <10 min and a normal KNL arc job is <20 minutes.
Histogram of Haswell arc runtimes (from Nov 2021 arc jobs that finished), and a current KNL test production:
Motivation: the default 45min x 3 = 2h15m makes the jobs harder to schedule into the regular queue, and 45 minutes is still ~3x longer than typical.
@akremin

KNL arcs also 45min

---

bin/desi_daily_proc_manager
py/desispec/desi_proc_dashboard.py
py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/specex.py
py/desispec/scripts/tile_redshifts.py
py/desispec/workflow/desi_proc_funcs.py

This PR has a potpourri  of updates that I made while trying to restore the ability of the pipeline to run efficiently on KNL.  Most of them turned out to be unrelated, but I'm opening this PR to re-establish a working baseline for further updates.  Changes include:
* dashboard outputs to $DESI_SPECTRO_REDUX/$SPECPROD/dashboard by default instead of $HOME
* more user friendly time logging in desi_proc output:
* instead of dumping full json into the log, log only the duration.max per step (details are still in the *.json files)
* include the total duration as the last line in the log
* parallelize over cameras while merging the PSFs in desi_proc_joint_fit
* The previous code was asking for 200 cores but apparently only using 1; now it asks for 30 ranks and uses all of them.
* There has …

restore pipeline operations on KNL

---

py/desispec/database/redshift.py
py/desispec/io/frame.py
py/desispec/io/meta.py
py/desispec/joincosmics.py
py/desispec/qa/qa_quicklook.py
py/desispec/qproc/io.py
py/desispec/scripts/calibrate_tsnr_ensemble.py
py/desispec/spectra.py
py/desispec/tsnr.py

Housecleaning for Fuji -- this PR fixes deprecation warnings when using newer versions of python, numpy, astropy, and skimage:
* np.bool / np.int / np.float -> bool, int, float
* previously np.int was an alias for int, etc. but now generates a deprecation warning
* in some cases I used e.g. np.float32 or np.int64 when I specifically wanted to specify the precision or needed to support array input
* python 3.9.x is more picky about escape sequences, thus making some regular expressions into raw strings, e.g. `'fiberassign\-(\d+)\.fits'` -> `f'fiberassign\-(\d+)\.fits'` due to the '\-'
* `skimage.morphology.binary_closing` changed "selem" -> "footprint"; this PR supports both without generating warnings
* selem still works with 0.19.0, abeit with a warning, so I didn't try to fine tune …

fix deprecation warnings

---

py/desispec/mgii_afterburner.py

This PR updates desi_qso_mgii_afterburner to support astropy 5.x which (IMHO) incorrectly interprets FITS table blank strings as masked values instead of just passing forward blank strings.  This is the same issue as the fibermap reading problem in PR #1454, but here I'm just fixing the impacted column (SUBTYPE) instead of bringing in an fitsio dependency.  The relevant change is:
```python
if hasattr(redshifts['SUBTYPE'], 'mask'):
redshifts['SUBTYPE'][redshifts['SUBTYPE'].mask] = ''
```
Without this change, desi_qso_mgii_afterburner fails with:
```
File "/global/common/software/desi/users/malvarez/desiconda2/code/desispec/master/bin/desi_qso_mgii_afterburner", line 265, in <module>
QSO_from_MGII = select_targets_with_mgii_fitter(redrock, fibermap, …
```

support astropy 5.x masked columns

---

py/desispec/io/fibermap.py
py/desispec/io/meta.py
py/desispec/io/util.py
py/desispec/test/test_io.py

This PR fixes #1272 where the "look in previous exposures for the fiberassign file" could end up grabbing the wrong fiberassign file.  I originally was just going to turn off this look-back behavior since it isn't needed in normal ops, but there may be special test cases of setting up on a tile and then doing some manual exposures that could result in spectrograph exposures without a matching fiberassign file in the same EXPID, so the updated logic is:
* if the raw data has a TILEID keyword, insist that the fiberassign file matches that
* if looking to previous exposures without knowing the TILEID, check the data TARGTRA,TARGTDEC vs. fiberassign TILERA,TILEDEC for whatever fiberassign file is found and only accept it if they match
It also corrects a case where the coordinates file is …

more robust when fiberassign in earlier expid

---

bin/desi_run_night
py/desispec/scripts/submit_night.py

This PR addresses #1531 by adding a `desi_run_night --surveys` option to filter by survey when processing a night.
However, it requires "SURVEY" to be in the exposures table, but exposure tables from the sv/main overlap time 20210517 - 20210610 don't yet have that column, so I might be getting ahead of myself.  OTOH, that column is only required if the `--surveys` option is requested, so this doesn't break current functionality.
In the input fiberassign files, by understanding in that "FA_SURV" refers to what kind of targets were used, but "SURVEY" refers to what output survey the tile should belong to, e.g. to enable test tiles with main survey targets by using FA_SURV=main but SURVEY=special.
@akremin heads up for coordination on your cleaned up exposure tables (and review of this in …

desi_run_night --surveys option

---

py/desispec/io/fibermap.py

For the special case of exposure 80502 from 20210314, estimate DX_1, DY_1 using the FVC coordinates of both the blind and correction move along with the values of DX_0, DY_0.  Use this to estimate FIBER_X, FIBER_Y, DELTA_X, DELTA_Y.
It is an approximation because we cannot redo PM here. So the DELTA_X,DELTA_Y are a bit pessimistic. But most fibers of exposure 80502 are still within 30 microns.

Approximate fix to fibermap if FVC but no FP coordinates from correction move.

---

py/desispec/io/fibermap.py

This PR fixes a bug I introduced in PR #1529, which was causing assemble_fibermap to crash if it couldn't find an alternate fiberassign file in svn.  This PR restores the previous behavior of using the fiberassign file in the raw data (while still preserving the original features of #1529; this bug was a side-effect of trying to standardize on using checkgzip instead of repeated if/then logic).
Example case that crashes in master but works with this branch:
```
assemble_fibermap --overwrite -o blat.fits -n 20211215 -e 114228
```

fix case where svn doesn't have alternate FA file

---

py/desispec/preproc.py
py/desispec/scripts/proc.py
py/desispec/scripts/trace_shifts.py

This PR fixes a desi_proc MPI logic bug that resulted in a job hang if one of the cameras was missing a necessary input for extractions.  This was motivated by 20201214/00067628 where the b0 preproc gets completely masked (see #1541), causing the traceshifts to fail, causing one of the extraction groups to be missing the PSF input, causing them to never make it to a barrier where all the other ranks were waiting.
This command hangs on current master, and with this branch it processes 29 good cameras to completion and then exits without waiting for the job to timeout:
```
srun -N 7 -n 200 -c 2 desi_proc --mpi --traceshift --cameras a0123456789 -n 20201214 -e 67628
```
Other changes:
* all preproc log messages include the camera to assist understanding when 30 cameras are being processed in …

fix desi_proc MPI bug causing hang if extractions missing inputs

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR adds few modifications to the nightqa page creation.
The principal motivation is to move away from restricting to Main tiles only.
The chosen approach now considers all OBSTYPE="SCIENCE" exposures.
For the sframesky, tileqa, skyzfiber plots, we thus now include any SCIENCE observations.
The reason is because the type of survey should not prevent to inspect the exposures quality on those plots.
For the petalnz plot, we proceed a bit differently, as we stack the n(z) per tracer, per night.
We here:
- restrict to sv1, sv2, sv3, main (which conveniently have the same bits for the 5 plotted tracers);
- we make a serie of plots for each survey of the night;
- we still generate one file only.
Along the way, several changes - hopefully improvements:
- get_surveys_night_expids(): not using …

Nightqa v3

---

py/desispec/preproc.py

In this PR we modify the estimator of the overscan step derived from an array of overscan values per CCD row.
After a median filter of 7 rows to reduce the noise, we measure the amplitude (max-min) of the difference between consecutive values instead of the max-min value of whole array. This removes the sensitivity to slow variation of the overscan while still detecting sharp changes, steps or horizontal bands.
On 20201214/00067628 B0 the steps originally of about 6 electrons are reduced to 1 to 1.2 electrons depending on the amplifier.
On the example exposures presented in https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=6516,
20211026/00106136 R8 amp A: 14.0 instead of 14.3 electrons
20211026/00106135 R8 amp A: 11.0 instead of 12.7 electrons
20211027/00106260 R8 amp A: 5.3 …

OSTEP: use difference between adjacent rows to measure the step

---

py/desispec/workflow/desi_proc_funcs.py

Fixes #1528 by ensuring that 21 MPI processes are used for a single camera. 
Following tests with this branch pass:
```
Cameras: z1
haswell: srun -N 1 -n 21 -c 3
knl: srun -N 1 -n 21 -c 12
Cameras: b1
haswell: srun -N 1 -n 21 -c 3
knl: srun -N 1 -n 21 -c 12
Cameras: r135
haswell: srun -N 1 -n 31 -c 2
knl: srun -N 1 -n 31 -c 8
Cameras: a3
haswell: srun -N 1 -n 31 -c 2
knl: srun -N 1 -n 31 -c 8
Cameras: a0123456789
haswell: srun -N 10 -n 301 -c 2
knl: srun -N 10 -n 301 -c 9
```
Please review and merge if appropriate.

Fix desi_proc specex wrapper MPI rank bug for single camera

---

py/desispec/ccdcalib.py
py/desispec/scripts/proc.py

This PR implements (few lines changes) the proposal that we also use the nightly bias for red and nir cameras because this considerably reduces the number of 'BADCOLUMN'. Indeed most residuals in CCD columns are not due to dark current but charges generated at readout on specific pixels in the serial clock row. So we can remove them by using a recent bias.
Example from 2021/12/17 and 2021/12/18. Below are figures of the number of bad columns detected with `desi_inspect_dark` in the 300s dark exposure preprocessed with the default or nightly bias for the red and nir cameras.
The changes to the code simply consist in considering a nightly bias for all cameras, not just b, and to give an slight advantage in favor of the nightly bias over the default when comparing the residual levels after …

Nightly bias for all

---

py/desispec/ccdcalib.py
py/desispec/scripts/proc.py
py/desispec/workflow/desi_proc_funcs.py

This PR adjusts the memory and runtime for nightlybias, using 15 ranks across 2 nodes instead of 7 on one node.  It also splits the desi_proc --nightlybias srun from the regular exposure processing srun to allow e.g. darks to use more cores (and thus run faster).
It also restricts the nightlybias to use only CALIB ZEROs, and not other ZEROs that may have been taken on that night, and pre-emptively drops the first two which may have still be stabilizing.
I've tested this on Haswell and KNL, and with and without including a dark exposure.
This doesn't yet include the full pipeline logic for auto-determining how to run --nightlybias without a matching dark (issue #1524), but it lays the desi_proc groundwork for it.
Fast tracking this for merging to include in a Fuji test run.

adjust nightlybias

---

py/desispec/night_qa.py

This PR addresses a failure in `night_qa.create_petalnz_pdf()`, when there are no tiles only for one of the two analyzed BRIGHT and DARK programs (https://github.com/desihub/desispec/issues/1548).
@akremin: sorry for having ill-coded that part, missing that corner case.

nightqa petalnz: handle faprgrm with no tiles

---

py/desispec/night_qa.py

This PR corrects a bug (leftover from development test) introduced in PR https://github.com/desihub/desispec/pull/1549, reported in https://github.com/desihub/desispec/issues/1552.
Apologies for that...
(the test @akremin and I did on 20211220 for PR https://github.com/desihub/desispec/pull/1549 did work, because that night only has bright tiles).

petalnz: fix bug

---

bin/desi_interpolate_fiber_psf

Select preferentially fibers in the same bundle as reference to fix bad fibers.
Fix a bug in the interpolated x-coordinate of the bad fiber trace when the reference fiber is in another bundle.

Improvements to desi_interpolate_fiber_psf

---

bin/desi_resubmit_queue_failures
py/desispec/scripts/daily_processing.py
py/desispec/scripts/proc.py
py/desispec/scripts/processingtable.py
py/desispec/scripts/submit_night.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py
py/desispec/workflow/proctable.py

This implements the nightlybias functionality in both the daily processing and the reprocessing scripts for nights with no 300s calibration dark taken.
This builds off of PR #1547 and addresses issue #1524 .
The ability to submit the nightlybias required the addition of code to allow exposure-less jobs in the pipeline, which was done as part of this PR. In addition, this adds a fourth possible calibration dependency, so I moved to a dictionary object to look up the calibration dependencies, `calibjobs`, as a replacement for the stand-alone variables `arcjob`, `flatjob`, and `darkjob`. This also renames the dark+nightlybias job to `ccdcalib` (i.e. the `JOBDESC` is now `ccdcalib` for dark+nightlybias). This also implements the new `JOBDESC` of `nightlybias`.
I tested the abilities of both …

Run nightlybias on nights without a dark

---

py/desispec/preproc.py

Simple PR that changes the estimation of the readnoise when we are subtracting the overscan per CCD row
(in case where OSTEP>2 electrons).

Readnoise estimation whensubtracting the overscan per row

---

py/desispec/scripts/proc.py

This PR fixes a processing bug when a PSF fails due to bad readnoise, but desi_proc still tries to rename the (missing) PSF to fit-psf*.fits.badreadnoise and would crash.  The original case was where the readnoise was bad and we wanted to reject the PSF even if it had succeeded in writing an output file.
Tests will fail due to fitsio/numpy compatibility issue being sorted out in #1566 ; I intend to self-merge this to use for testing this afternoon.

badreadnoise PSF fail robustness

---

.github/workflows/python-package.yml
README.rst
requirements.txt

This PR has a minor doc change to trigger tests to study them in isolation from other algorithmic changes.  Original test failures noticed in #1564, where the default installed fitsio+numpy appear to be incompatible leading to fitsio import errors.

PR to test GitHub test failures

---

py/desispec/tile_qa_plot.py

This PR adds few safety checks around the cutout displaying in the tile-qa*png file, as this has been causing some issues (https://github.com/desihub/desispec/issues/1563, https://github.com/desihub/desispec/issues/1576).
As said in https://github.com/desihub/desispec/issues/1563, the root cause of the problem is not clear to me, but hopefully those changes should handle those.
Besides, I've taken advantage of the introduction of the use of `log()`, to change some `print()` to `log.info()` or `log.warning()`.

Tile qa plot v6

---

py/desispec/preproc.py

PR to fix issue #1580 .
- convolve preproc image with lorentzian profile along cross-dispersion axis as a proxy for scattered light / psf tails. 
- compute value of convolved image in interblock regions
- flag affected interblocks and replace value by average per amp before computing CCD background
Results:
- flagged 5 blocks of 20220107/00117268 camera b7
- no blocks of  20211215/00114225 camera b9 (a dark frame) are masked (this is one of the exposures used for the original algorithm development) 
Central band profile of preprocessed image 20220107/00117268 camera b7 before (blue) and after (orange) this fix.
zoom of same figure in region with largest effect

Estimate contribution from scattered light in the regions between CCD blocks

---

bin/desi_inspect_dark

This PR fixes #1567 (large number of b5 bad columns) by adding a 6-sigma significance cut on identified bad columns, which dramatically reduces the number of false positive bad columns on noisy b5 during May 2021.  Other changes include adding a SIGMA column to the output file and using the same pixel mask as the extractions (which ignores the BADREADNOISE bit).
Example outputs are in:
```
/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/badcol/calibnight/20210507
/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/badcol/calibnight/20210509
```
for comparison with badcolumns*.csv in /global/cfs/cdirs/desi/spectro/redux/f4/calibnight/20210507 and 20210509.
For non-b5 CCDs, all originally identified bad columns are preserved on both nights.
For b5 20210507 464 -> 0 and 20210509 206 -> …

badcolumns with noisy input data (b5 May 2021)

---

bin/desi_archive_tilenight

This PR fixes a bug in desi_archive_tilenight, where previously it would set tiles-specstatus.ecsv ARCHIVEDATE for a tile as being archived, even if the actual act of archiving it had failed.  The example that triggered this was TILEID=21743 on LASTNIGHT=20211216 which we had initially flagged as QA=good, but then retroactively decided to discard it.  When I ran `desi_archive_tilenight -n 20211216` it tried to archive 21743, found that the tiles/cumulative/21743/20211216 directory was missing but flagged it as ARCHIVEDATE=20220105 anyway and updated tiles-specstatus.ecsv.
Now the code tracks errors while moving / updating permissions on directories, and it will only set ARCHIVEDATE if the actual operations succeeded, and it also prints a CRITICAL log message at the end if any tiles failed …

don't flag a tile as archived if archiving failed

---

bin/desi_night_qa
bin/desi_tile_qa
py/desispec/exposure_qa.py
py/desispec/io/meta.py
py/desispec/night_qa.py
py/desispec/test/test_io.py
py/desispec/tile_qa.py
py/desispec/tile_qa_plot.py

This PR adds a new `--group` option to `desi_tile_qa` and `desi_night_qa` to support "pernight" tile-based redshifts in addition to the default "cumulative" redshifts.  This required updates to `desispec.io.findfile`, and updating tile/night QA to use that.  An example output is at:
https://data.desi.lbl.gov/desi/users/sjbailey/spectro/redux/humidity/nightqa/20211220/nightqa-20211220.html
Generated with
```
desi_tile_qa -n 20211220 -g pernight
desi_night_qa -n 20211220 -g pernight
```
Note: the test prod didn't include darks or zmtl thus the dark plots and n(z) per petal are missing.
A few other changes:
* Fix exposure-qa bug that was failing to write a "EFFTIME" header keyword if all fibers were bad; now it writes EFFTIME=0.0.
* Add another even higher-level try/except wrapper around …

tile/night QA pernight

---

bin/assemble_fibermap
bin/desi_map_tilepix
py/desispec/pixgroup.py
py/desispec/scripts/humidity_corrected_fiberflat.py
py/desispec/scripts/proc.py

This PR
* adds a `assemble_fibermap --tilepix` option to save a JSON dictionary of healpix covered by the petals of this tile.  This will streamline the downstream healpix bookkeeping by being able to look that up for each exposure instead of having to re-read every fibermap to recalculate it.
* fixes a bug in the fiberflat humidity corrects when the fiberflatnight is missing and it has to fall back to using a default fiberflat (it was using the NIGHT of the science exposure instead of the NIGHT of the fiberflat when looking up the humidity of the fiberflat)
I've tested this as part of pre-f5 vetting and plan to merge ASAP for a tag.

fix humidity calibnight, add assemble_fibermap --tilepix

---

bin/desi_tile_vi
py/desispec/io/meta.py
py/desispec/test/test_io.py

This PR solves a small bug due to changes in PR https://github.com/desihub/desispec/pull/1578, which introduced the need to specify the `groupname` argument for the `findfile()` call for the tileqa and tileqapng cases.
For the change in `desi_tile_vi`, I've hard-coded `groupname="cumulative"`, as I think we'll only use the cumulative reduction to do the tile vi.
Also, I'm wondering if there would be other places where that update would need to be done.
With looking for "tileqa" and "findfile" in the github desispec repository, maybe those places:
https://github.com/desihub/desispec/blob/fbfcf33867ad774e9627fc38546577db7105c9e2/py/desispec/zmtl.py#L837
https://github.com/desihub/desispec/blob/55cd93510339f077ae3c9667b4ffa0bc396a66b0/py/desispec/test/test_io.py#L801-L803
and maybe here, I …

tile/night QA pernight v2

---

py/desispec/io/fibermap.py

This PR is an implementation of turbulence corrections from issue #1538 .  However, just as I was finishing this update I discovered that the `FPA_X/Y_n`, `DX/DY_n` etc. columns that we have been using do have the turbulence corrections already applied and maybe we should just keep using those.
I also implemented the `FIBER_RA/DEC` recalculation suggested in #1538.  I also considered applying a `TURB_X/Y_n` correction to `FIBER_RA/DEC` instead of completely replacing it, but it looks like the TURB corrections are larger than the FIBER_DX/DY corrections, so I think the original suggestion is better.
Example files are in /global/cfs/cdirs/desi/users/sjbailey/dev/turbulence:
* expid 114319, before turbulence corrections were turned on
* fibermap-114319-old.fits - current master
* …

updates for turbulence corrections on exp 114320 onwards

---

bin/desi_night_qa

This PR corrects a simple bug/leftover introduced in PR https://github.com/desihub/desispec/pull/1584 (the tests I perforned were for the function `get_dark_night_expid()`, not with calling `desi_night_qa` itself).
Apologies for that.

nightqa: 5min DARK expid selection bug-fix

---

py/desispec/fiberflat_vs_humidity.py

This short PR fixes one bug in the fiberflat_vs_humidity correction when
the best fit humidity is on the edge of the humidity range (of the templates).

Bug fix in fiberflat_vs_humidity

---

bin/desi_proc
py/desispec/scripts/proc.py

This PR improves desi_proc error tracking:
* it keeps a running count of errors, and if any of the substeps fail desi_proc exits with an error code at the end, avoiding jobs and logs claiming "SUCCESS"
* add missing inputs checks to sframe, and wrap with try/except for good measure (this step doesn't use `runcmd` which does that for most other steps)
* add inputs list for desi_select_calib_stars runcmd (i.e. if an input is missing, it won't run in the first place, instead of running and crashing due to the missing input)
This is a companion PR to #1589 addressing the fiberflat humidity failures on 20220112.  That PR fixed the underlying algorithm (bug when current night has humidity outside the range of the models); this PR fixes the jobs hangs so that they would have failed faster and …

better desi_proc error tracking

---

py/desispec/io/fibermap.py

This PR makes `assemble_fibermap` stricter about requiring good inputs unless `--force` is used.  Previously it would exit if the coordinates file wasn't found, but on split exposure tests on 20210314 (e.g. exp 80458, 80459) the coordinates file existed but was corrupted and didn't have all the necessary input, and assemble_fibermap was continuing with dummy values anyway.  Now it will do that only if `--force` is provided.
See #1591 for which exposures to flag as bad; this PR will make any other missing ones fail faster instead of leaving it to later steps like sky subtraction to fail due to missing fibermap info.
Tested with
```
assemble_fibermap -n 20210314 -e 80459 -o blat.fits --overwrite 
```
Previously this would
```
...
ERROR:fibermap.py:804:assemble_fibermap: Unable to find …
```

assemble_fibermap fail faster unless --force

---

py/desispec/data/batch_config.yaml
py/desispec/workflow/desi_proc_funcs.py

Produce correct Slurm batch files when the argument `--system-name perlmutter-gpu` is used with `desi_proc`, appropriate for [Phase 1 of Perlmutter ](https://docs.nersc.gov/systems/perlmutter/system_details/#system-overview-phase-1). Specifically, 
- `cores_per_node` is changed from 128 to 64
- `--constraint=gpu` is added to the batch file
-  `#SBATCH --qos regular` is used (`realtime` is not currently available)
- `#SBATCH --account desi_g` is used (`perlmutter-gpu` requires projects name with "`_g`" appended)
These changes do not affect the behavior of `desi_proc` when `--system-name perlmutter-gpu` is not used.
@sbailey please review and merge if appropriate.

Batch file generation for perlmutter-gpu (Phase 1)

---

bin/desi_qso_catalog_maker
bin/desi_qso_qn_afterburner

I modified the extname for the qn afterburner file to avoid errors when using the new version of fitsio (>= 1.1.3). For retro compatibility, I add a flag in the argparser of desi_qso_catalog_maker to enable someone to run the script with Everest or older files.
Reference: see BACKWARDS INCOMPATIBLE CHANGES in version 1.1.3: https://github.com/esheldon/fitsio/blob/master/CHANGES.md

modify extname for newer version of fitsio

---

py/desispec/night_qa.py

This PR adds three panels to the `NIGHT-skyzfiber.png` plot, one for each of the Main BACKUP/BRIGHT/DARK program (per suggestion of @julienguy).
I identify the tile `FAFLAVOR` with looking for a `fiberassign-TILEID.fits*` file in the `$DESI_ROOT/spectro/data/NIGHT/*/` folders; if no `fiberassign-TILEID.fits*` file is there, or if `FAFLAVOR` is not in the header, I just don't include that tile in the newly added panels.
I've also changed the y-axis (redshifts) to a log scale, as in the `tile-qa-TILEID-thruNIGHT.png` plots.
Example of a new plot:

Nightqa: per-program skyzfiber plot

---

bin/desi_compute_skycorr_pca

Discard sky corrections with delta_wave>0.3A and delta_lsf>2A.
This removes 3 exposures for b3 that were the cause of very large PCA components in fiber 1680. The pca skycorr file `$DESI_SPECTRO_CALIB/spec/sm6/skycorr-pca-sm6-b3.fits` has been updated. Using this file solves issue #1593 .

Outlier rejection in skycorr PCA

---

bin/desi_resubmit_queue_failures
py/desispec/workflow/procfuncs.py
py/desispec/workflow/proctable.py

This addresses issue #1558 
By default `desi_resubmit_queue_failures` now includes `FAILED` job states. I updated the default in the executing script itself rather than the underlying functions because the underlying code could be used elsewhere where that behavior isn't desirable. I also added a flag `--dont-resub-failed` for instances where we don't want to submit `FAILED` jobs.
Finally, I added logic to verify that all dependencies of a job are either completed or can be re-submitted given the resubmission states provided to the script. This should resolve the second issue flagged in 1558, where later jobs were being submitted even though they depended on jobs that were still in a compromised state.
I tested this on the daily processing table from Jan 11, 2022, which had a job failure …

Include FAILED jobs in resubmissions and add flag to avoid that behavior

---

py/desispec/tile_qa.py
py/desispec/tile_qa_plot.py

This PR addresses the issue #1599, where the tile_qa routines crash for special/early tiles with some missing header keywords.
The workaround is to set MINTFRAC and GOALTIME to ~nominal values (https://github.com/desihub/fiberassign/blob/c9ef922dae336860959ae8cf1d2c07b1b8eb99a3/bin/fba_launch#L40-L66):
- GOALTIME: if missing, set GOALTIME=1000/150/30 for dark,cmx/bright/backup, using the TARG header keyword from the fiberassign-TILEID.fits.gz file; if no fiberassign file or no TARG keyword or no correct TARG value, raise an error;
- MINTFRAC: if missing, set MINTFRAC=0.9.
Along the way, this PR has two additional "fixes" in `tile_qa_plot.py` for this issue case:
- handle cases when SURVEY, FAPRGRM, or EBVFAC is not present in the header (with setting them to "none", "none", -1, …

Tile qa specialtile

---

py/desispec/io/frame.py
py/desispec/io/spectra.py

This PR adds calls to `desiutil.depend.set_dependencies` for FIBERMAP HDUs as well when writing frame, spectra, and coadd files.  Although this replicates some metadata in HDU 0, the fibermaps are sometimes used semi-independently and it can be handy to have the metadata tracked there as well without having to read multiple HDUs.
This is a followup to desihub/desiutil#183 and desihub/redrock#200.

add dependencies to fibermap HDUs too

---

bin/desi_run_night
py/desispec/scripts/daily_processing.py
py/desispec/scripts/submit_night.py
py/desispec/workflow/exptable.py
py/desispec/workflow/procfuncs.py
py/desispec/workflow/proctable.py

This is a potpourri pull request with several minor improvements to the `desi_run_night` and underlying `submit_night()` function, along with a bug fix for the recently implemented `nightlybias` code.
1. Avoid submitting `nightlybias` unless either 'bias' or 'dark' is in `proc_obstypes`.  This is a bug fix for both `desi_run_night` and the nightly `desi_daily_proc_manager`.
2. Update the redshift log so that if a tile is observed more than once on a night with other tiles in between, the nightly and cumulative redshifts are only submitted after the final set of observations. `perexp` redshifts are still submitted as they arise though.
3. I also added a check to verify that the 300s dark exposure used for the `ccdcalib` is actually a "calib dark".
4. I've changed the logic such that new …

desi_run_night enhancements and bug fixes

---

py/desispec/badcolumn.py
py/desispec/fiberbitmasking.py
py/desispec/fibercrosstalk.py
py/desispec/io/raw.py
py/desispec/maskbits.py

- Use fibermask bits BADAMPB, BADAMPR, BADAMPZ to flag fibers affected by bad CCD columns instead of using the fibermask bit BADCOLUMN that does not specify the CCD.
-  This avoid having coaddition masked whole spectra when only one camera is affected. 
- Code tested on tile 273 SP5. One Lya quasar that was fully masked in f5 run is now successfully fitted with redrock.
This addresses issue #1604 .

Bad column fibermask

---

py/desispec/test/test_zcatalog.py
py/desispec/zcatalog.py

Made the following major changes:
- Added ZWARN_NOT_ZERO to give priority to ZWARN = 0 spectra and then select primary spectra based on sort_column for cases where ZWARN != 0
- Added optional keyword to change the sorting column. default = TSNR2_LRG
- Made other minor changes

zcatalog changes

---

doc/changes.rst
py/desispec/coaddition.py
py/desispec/scripts/coadd_spectra.py

This simple PR addresses #1349 and #1359.
1. With this branch, coadding previously coadded cframe files (which currently crashes, as reported by @rongpu in #1359), now completes:
```
export INDIR=/global/cfs/cdirs/desi/spectro/redux/everest/exposures
desi_coadd_spectra -i $INDIR/20210324/00081833/cframe-[brz]0-*.fits $INDIR/20210324/00081834/cframe-[brz]0-*.fits -o test.fits
INFO:coadd_spectra.py:71:main: reading input ...
/global/cfs/cdirs/desi/spectro/redux/everest/exposures/20210324/00081833/cframe-b0-00081833.fits is a frame
/global/cfs/cdirs/desi/spectro/redux/everest/exposures/20210324/00081833/cframe-r0-00081833.fits is a frame
/global/cfs/cdirs/desi/spectro/redux/everest/exposures/20210324/00081833/cframe-z0-00081833.fits is a frame …
```

fix bookkeeping of nights and tiles in coadds; enable coadding previously coadded cframe files

---

bin/desi_zcatalog
py/desispec/io/spectra.py
py/desispec/scripts/group_spectra.py
py/desispec/scripts/tile_redshifts.py
py/desispec/test/test_util.py
py/desispec/util.py

This PR (and a companion PR in redrock to be opened next) adds header keywords so that spectra, coadd, and redrock files know what spectral group they are in (perexp, pernight, cumulative, healpix) and their TILEID, NIGHT, EXPID, and PETAL=SPECTRO.  i.e. you shouldn't need to parse the filename and directory to discover this information anymore.  Keywords added:
* SPGRP = perexp, pernight, cumulative, healpix
* SPGRPVAL = int expid, night, lastnight, healpix value to match whatever the input group was
* TILEID, PETAL, SPECTRO (for tile-based groups)
* note: PETAL=SPECTRO, but I added both anyway
* EXPID (for SPGRP=perexp)
* NIGHT (for SPGRP=perexp, pernight, or cumulative)
* HPXPIXEL (for SPGRP=healpix)
* this keyword was already there for healpix based redshifts, but I list it here for …

specgroup metadata in spectra, coadd files

---

bin/desi_compute_fiberflat_vs_humidity

In this PR is modified the script `desi_compute_fiberflat_vs_humidity` that generates the humidity correction templates.
The broadband flat field correction of each fiber is normalized to 1.
New templates have been generated but have not been committed yet in DESI_SPECTRO_CALIB in case we want to run a test production before. In order to test the changes at NERSC, one needs
`export DESI_SPECTRO_CALIB=/global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib`
Comparison of current and new template for b7 , humidity bin 9 (arbitrary choice),
This PR solves issue #1615 .

normalize fiberflat variation of each fiber

---

bin/desi_find_badpos

In preparation for Fuji and future data releases, it's useful to know when petals (on a given night and expid) need to be added to the bad exposure list. This PR contributes a simple script to help make these decisions:
E.g., running
```
time desi_find_badpos --reduxdir /global/cfs/cdirs/desi/spectro/redux/everest --mp 32 -o badpos-everest.fits
```
produces a table with the following content:
```
<Table length=36820>
NIGHT   EXPID PETAL_LOC   FBAD
int32   int32   int16   float32
-------- ----- --------- -------
20201214 67678         0   0.366
20201214 67678         1    0.23
20201214 67678         2   0.202
20201214 67678         3   0.272
[snip]
```
I ran the script on both the Everest data release and on the `daily` reductions. One can grab the results here: …

script to count the number of bad positions as a function of night-expid-petal 

---

py/desispec/fiberflat.py
py/desispec/test/test_fiberflat.py

Replacement of PR #1628 to merge into fuji branch instead of master (we'll deal with getting into master later):
This PR fixes a fiberflat failure on 20210320/00081166/frame-z5-00081166.fits :
Apparently spline_fit returns a ValueError if all inputs are masked, but a TypeError if only a very small number are unmasked leading to an insufficient number of degrees of freedom for the fit. The code was already catching the ValueError (everything masked) case; this PR also catches the TypeError (almost everything masked) case.
Example commands that previously failed and now succeed:
```
desi_compute_fiberflat -i /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220123/00119849/frame-z5-00119849.fits -o fiberflat.fits
desi_compute_fiberflat -i …
```

catch fiberflat splinefit error when almost all input is masked

---

py/desispec/tile_qa.py

originally from @julienguy , but reopening as a PR to fuji instead of master:
Minor PR for fuji (branched from fuji branch and to be remerged there).
In tile QA, if missing fiberassign-xxx.fits.gz file, try fiberassign-xxx.fits before raising an error.

if missing fiberassign-xxx.fits.gz file, try fiberassign-xxx.fits before raising an error

---

bin/desi_zcatalog
py/desispec/test/test_zcatalog.py
py/desispec/zcatalog.py

This PR fixes a typo (my fault) in desi_zcatalog that resulted in it writing only the last input redrock file read instead of the stack of all the inputs...

zcat stacking typo

---

py/desispec/tile_qa_plot.py

This simple PR fixes a bug in the `tile-qa-TILEID-thruNIGHT.png` plots, identified in https://github.com/desihub/desisurveyops/issues/5.
Without this PR, fibers falling outside the LS-DR9 footprint are not identified as "SKY" in the script, as those do not have the SKY bit on in DESI_TARGET.
With this PR, the SUPP_SKY bit is also checked.
(for the context: as the `OBJTYPE` column is not present in the `tile-qa-TILEID-thruNIGHT.fits` file, one has to use an indirect way to recover all the non-TGT fibers).
Example for one tile, where part of petal_loc=5 and 6 fall outside the LS-DR9 footprint:
Without this PR:
With this PR:

make_tile_qa_plot(): add SUPP_SKY to non-TGT

---

py/desispec/night_qa.py

This PR adds in the `petalnz-NIGHT.pdf` file a plot to assess that the  MTL-like Ly-a identification is not problematic.
The x-axis is the average number of previously observed tiles overlapping the considered tiles (from `desispec.tile_qa_plot.get_tilecov()`).
The y-axis is the number of identified Lya (using the same recipe as the MTL) for fibers on QSO targets observed for the first time (`PRIORITY=3400`); we restrict to valid fibers (using same recipe as the MTL), and normalize it to 3900 valid fibers (approximately the per-tile median value so far).
To guide the eye, the approximate 1-2-3 sigma regions of the expected locations are overplotted in blue-green-red.
That location comes from a simple fit `f(ntilecov)`, with an exponential law, to the main data so far.
The plot is added on …

Nightqa: plot for newly identified Ly-a

---

py/desispec/scripts/submit_night.py

The logic for selecting a dark exposure was recently updated to check that the dark was actually a calibration dark. This prevented dark sequence exposures from being selected instead of the "calib dark" on a night. This had two unintended consequences, however:
1. There are nights without a "calib dark". In those cases using a 300s dark sequence image is better than not having any at all. Though we want to prioritize the "calib dark" if both are available.
2. When selecting a dark, we remove all others from the list of exposures to process. However the updated logic meant we weren't capturing the dark sequence exposures and therefore weren't removing them.
This pull request solves the above by looking for "calib darks" darks specifically as well as other darks. If available, the first …

ignore all other 300s darks in submit_night.py

---

py/desispec/io/meta.py
py/desispec/test/test_io.py

This PR fixes a bug in `desispec.io.findfile(..., groupname='perexp')`.  e.g. these files from Fuji:
```
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/42/00084504/spectra-0-42-exp00084504.fits
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/42/00084504/coadd-0-42-exp00084504.fits
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/42/00084504/redrock-0-42-exp00084504.fits
/global/cfs/cdirs/desi/spectro/redux/fuji/tiles/perexp/42/00084504/rrdetails-0-42-exp00084504.h5
```
Current fuji branch:
```
findfile('redrock', tile=42, expid=84504, spectrograph=0, groupname='perexp')
--> ValueError: Required input 'night' is not set for type 'redrock'!
findfile('redrock', tile=42, night=20210412, expid=84504, spectrograph=0, groupname='perexp')
--> …
```

fix findfile with groupname=perexp

---

py/desispec/preproc.py
py/desispec/scripts/preproc.py

Changes
- compute the dark trail correction prior to the overscan subtraction and apply it to the overscan column.
- add option `--keep-overscan-cols` to `desi_preproc` for debugging.
Not in this PR but needed to fix r8 issue: update to `$DESI_SPECTRO_CALIB/spec/sm2/sm2-r.yaml` (committed but not updated at NERSC):  add back the parameter DARKTRAILAMPD: 0.00021 that was lost in recent configurations of this CCD (!)
Comparison before and after the change to the dark trails, but with the desi_proc option `--keep-overscan-cols` to see the effect. With this change, OSTEPD=0.54 instead of 4.5.
```
desi_preproc -i /global/cfs/cdirs/desi/spectro/data/20220106/00116955/desi-00116955.fits.fz --cam r8 -o preproc-r8-00116955-new-with-overscan.fits --keep-overscan-cols --nodark --nomask --nopixflat …
```

Dark trail in overscan

---

bin/desi_calib_config

Fixes a bug where a comment with a version name in a reference version prevented a new entry to be made based on it. Nothing else is changed.
@julienguy please review and merge.

Ignore version names in comments in desi_calib_config

---

py/desispec/night_qa.py

This PR makes few minor changes in the `petalnz-NIGHT.pdf` for the two Ly-a related plots (title, xlim, xlabel).
Noticely extends the x-axis for the "average number of previous observed, overlapping tiles" from 5 to 6.5.
Sorry for not having implemented all of that in the original PR...

Nightqa: few plot display changes for Ly-a plots

---

py/desispec/io/util.py
py/desispec/test/test_io.py
py/desispec/workflow/procfuncs.py
py/desispec/workflow/tableio.py

This is related to Issue #1645 in which the first exposure of a tile sequence had fewer cameras than later exposures. The pipeline originally assumed the `PROCCAMWORD` of the first exposure for the joint standard star fitting. This breaks when a transient hardware issue affects the first exposure but not later exposures. This pull request mitigates that by submitting all spectrographs that have full coverage when looking at all available exposures.
Instead of assuming all exposures have the same cameras, we now take the union of all cameras in all exposures. We explicitly restrict to spectrographs that have complete (b,r,z) camera sets, since any partial spectros will fail standard star fitting. We do, however, allow spectros who are incomplete in all individual exposures so long as they …

Use all available spectrographs when joint fitting standard stars

---

py/desispec/exposure_qa.py

This PR is a simple suggested fix for issue https://github.com/desihub/desispec/issues/1664.
I let @julienguy review.
My understanding is that for each fiber of a given petal, we get the TSNR2 with summing the values over the three cameras, i.e.: TSNR2 = TSNR2_ELG_B+TSNR2_ELG_R+TSNR2_ELG_Z (using ELG here)
https://github.com/desihub/desispec/blob/769b71295eed2cbc0de78fb2d5bdf94b215cb2f1/py/desispec/exposure_qa.py#L305-L312
(`entries` are the 500 indexes of the fibers for the considered petal).
This fix will just ignore a camera if the cframe file is missing.
In the issue case (z-camera missing for petal=7), we will have for petal=7: TSNR2 = TSNR2_ELG_B+TSNR2_ELG_R, and this will result in a lower efftime:
```
>>> d = Table.read("/global/cfs/cdirs/desi/users/raichoor/tmpdir/exposures/202104 …
```

handle missing cframe in tsnr2 summing

---

py/desispec/data/batch_config.yaml
py/desispec/scripts/tile_redshifts.py

Sets `#SBATCH --account desi_g` instead of `#SBATCH --account desi` when `--system-name perlmutter-gpu` is passed to `desi_tile_redshifts`. This change has been tested by verifying that running
```
source /global/common/software/desi/desi_environment.sh 22.1a
DESI_SPECTRO_REDUX=path_to_local_redux 
PYTHONPATH=path_to_this_desispec_branch:$PYTHONPATH
mkdir -p $DESI_SPECTRO_REDUX/$SPECPROD
cd $DESI_SPECTRO_REDUX/$SPECPROD
cp -r $DESI_ROOT/spectro/redux/exptabs/exposure_tables .
desi_tile_redshifts -n 20211102 --tileid 23441 --group cumulative --run_zmtl --system-name perlmutter-gpu --batch-queue regular
```
on Perlmutter results in a successful submission to the queue.
Note that some functionality in code modified in this PR for `desi_tile_redshifts` overlaps with that for `desi_proc` (see …

Run desi_tile_redshifts on Perlmutter

---

py/desispec/fluxcalibration.py

When the signal to noise is low, a simplified flux calibration is used. It consists in a simple scaling of the reference throughput.
This PR fixes a bug in the computation of this scale factor that ignored the 'flat to point source fiber aperture correction'. (This value is normalized to 1 on average but can vary from fiber to fiber quite substantially for some exposures with poor positioning).
Example here for exposure 20220206/00121616 mentioned in https://github.com/desihub/desisurveyops/issues/21 .
"calibrated" flux of standard stars before:
Same with the correction from this PR:

Use the flat to point source correction in the simplified flux calibration

---

py/desispec/tile_qa.py

This PR fixes the issue https://github.com/desihub/desispec/issues/1670.
The bug was: in a loop on expids, the night used to find the fiberassign file was the argument night; whereas it should the expid-related night.
Executing:
```
desi_tile_qa -g cumulative -t 80605 -n 20210205 --outdir $DESI_ROOT/users/raichoor/tmpdir --prod fuji
```
generates this tile-qa plot:

use exposure_night instead of night for fiberassign filename

---

bin/desi_tsnr_afterburner
py/desispec/tilecompleteness.py

This PR fixes the tsnr_afterburner exposures vs. tiles SURVEY inconsistency reported in #1649.  Admittedly it does this by adding another special case check in the exposures logic rather than attempting a deeper refactor to reduce technical debt.
Other updates:
Adds a PROGRAM column, which is the output of desispec.io.meta.faflavor2program(FAFLAVOR), standardizing the many sv1 flavors/faprgrm into the standardized dark/bright/backup/other to match current usage and to match how the healpix redshifts are grouped.  For sv3 and main tiles, FAPRGRM==PROGRAM, but for sv1 tiles this should make interpreting the healpix structure easier.
It also fixes an MPI logic bug if size>nights (the same night was proceeded by multiple ranks, leading to race conditions), and renames `--multinode` to `--mpi` …

fix tsnr_afterburner exposures SURVEY

---

py/desispec/fiberbitmasking.py
py/desispec/fiberflat_vs_humidity.py
py/desispec/night_qa.py

This PR fixes a bug/feature in the `fiberbitmask` functions, where the `specmask.BADFIBER` bit was set in the `frame.mask` whenever a `fibermask.BADAMP{B,R,Z}` bit was set in the `fibermap['FIBERSTATUS']`,  irrespectively of the frame camera.
As an example, with the change in this PR, the quasar spectra from SP1 in tile 1299 are recovered.
See https://data.desi.lbl.gov/desi/spectro/redux/jguy/tiles/pernight/1299/20210707/tile-qa-1299-20210707.png
compared to https://data.desi.lbl.gov/desi/spectro/redux/guadalupe/tiles/pernight/1299/20210707/tile-qa-1299-20210707.png
This PR fixes issue #1673

specmask.BADFIBER

---

py/desispec/specstatus.py

The new tiles PROGRAM column isn't in tiles-specstatus, which broke desi_update_tiles_specstatus.  This PR fixes that (tested on my own checkout of surveyops).

PROGRAM not in tiles-specstatus

---

py/desispec/scripts/daily_processing.py
py/desispec/scripts/submit_night.py

This is a PR of a branch from @akremin to correct the fiberflat logic on nights that included gain sequences, e.g. 20210616 (fixes #1671).  I've confirmed via a desi_run_night --dry-run that it selects the correct flats on that night, and as a paranoia check that it also selects the same flats as before on a normal calibration night.
Note: post-fuji we can update how calibration exposures are selected (e.g. via a config file, initially populated using PROGRAM filters in addition to OBSTYPE) to avoid hardcoding that calibration flats have to be 120 sec, but this PR is a simple fix for the problem we currently have (we don't currently have cases where the nightly calib fiberflats weren't 120 sec, but we do have cases where other fiberflats had different exposure times confusing the …

only use 120s flats for nightlyflat

---

bin/desi_purge_tilenight

This is a PR of a branch from @akremin adding a new script `desi_purge_tilenight` to remove all preproc, exposures, and tile-based redshifts for a requested set of tiles on a given night.  It archives the current processing table with a timestamp and writes a new one removing the entries for those tiles so that `desi_run_night --night ...` will work to resubmit the jobs for those tiles on that night.
It does not delete the previously existing jobs scripts/logs (I think that's a feature), nor does it delete any healpix based redshifts (we'll likely want to add that in the future, but it doesn't need to be a blocking factor here since we need to rerun all Fuji and Guadalupe healpix redshifts anyway...).
By default it does *not* remove any files, but requires `--not-dry-run` to be set before …

Purge tilenight script

---

py/desispec/pixgroup.py
py/desispec/scripts/healpix_redshifts.py

This PR fixes #1679 where @araichoor identified that the healpix redshift bookkeeping was incorrectly using only the first exposure for each overlapping tile, instead of all exposures.  This update preserves the I/O optimization of reading the tilepix map only once per tile, but then generates the final hpixexp map for all exposures.
Using sv1 dark healpix 17680 covered by tile 80605, the original hpixexp file only identified one exposure:
```
20201214,67710,80605,sv1,dark,0,17680
```
but now it identifies all the exposures reported in #1679 
```
20201214,67710,80605,sv1,dark,0,17680
20201214,67711,80605,sv1,dark,0,17680
20201214,67712,80605,sv1,dark,0,17680
20201214,67713,80605,sv1,dark,0,17680
20201215,67972,80605,sv1,dark,0,17680
20201215,67973,80605,sv1,dark,0,17680 …
```

fix healpix expid bookkeeping

---

bin/copyprod
bin/desi_tsnr_afterburner
py/desispec/io/meta.py
py/desispec/test/test_io.py

This PR
1. fixes #1690: tile 80866 unwisebrightblue now has PROGRAM=GOALTYPE="other" instead of "bright".  Includes unit tests.
2. fixes the inconsistent GOALTIME entries in tsnr_afterburner exposures vs. tiles output, reported in #1649.
Example outputs are in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/tsnr_exptile for night 20210314 which observed the unwisebrightblue tile 80866 and had the GOALTIME inconsistency.
Original tiles-orig.csv subset:
```
TILEID       FAFLAVOR          FAPRGRM      PROGRAM GOALTYPE GOALTIME
------ ------------------- ---------------- ------- -------- --------
80866 sv1unwisebluebright unwisebluebright  bright   bright   1000.0
```
New tiles.csv subset with corrected PROGRAM and GOALTYPE:
```
TILEID       FAFLAVOR          FAPRGRM      PROGRAM GOALTYPE …
```

fix unwisebluebright PROGRAM; fix exp/tile GOALTIME consistency

---

bin/plot_spectra

This PR fixes #1693 where plot_spectrum is broken due to astropy 5 auto-masking of table inputs.  This uses the `desispec.io.read_table wrapper` instead so that blank strings just remain blank strings.
This case now works again:
```
cd /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/20140/20211117/
plot_spectra -i coadd-0-20140-thru20211117.fits -t 39627438107395133 --redrock redrock-0-20140-thru20211117.fits
```

fix plot_spectra astropy 5 table masking

---

py/desispec/tile_qa_plot.py

This PR addresses https://github.com/desihub/desispec/issues/1697.
It avoids to trigger an error in tile_qa_plot when GOALTIME=0.

Set GOALTIME as np.float32 (avoids divide by zero error)

---

bin/desi_zcatalog

This PR propagates a HEALPIX column into the output stacked redshift catalog when `desi_zcatalog --group healpix ...`, thus enabling a row of the catalog to trace back to the input redrock/coadd/spectra files from which it came (analogous to the pernight catalogs having a NIGHT column).
Full disclosure: this is "HEALPIX" to be more enduser friendly than "HPXPIXEL", and partially to disambiguate the column from the input target catalogs which have HPXPIXEL but could potentially be at a different nside than this column (they happen to both be 64 right now, but that in principle could change).  Header keywords HPXNSIDE=64 and HPXNEST=True record what nside and that these are nested not ring healpix numbers.  Note that the input targeting HPXPIXEL is *not* propagated through fiberassign or …

propagate HEALPIX into zpix redshift catalogs

---

bin/desi_qso_qn_afterburner

This PR is the subset of changes from @echaussidon in PR #1703 just to fix the missing qso_qn output problem (issue #1700), while not including the changes for the qso catalog maker.  I'll comment more in PR #1703 about that, while keeping this focused on the minimum necessary to finish Fuji and Guadalupe.
For context: `quasarnp.io.load_desi_coadd()` filters out targets that are completely masked.  When those targets are mixed in with good targets, `desi_qso_qn_afterburner --target_selection all --save_target all ...` includes them in the output with NaN placeholders so that the output has the same targets as the inputs.  But if the input file was entirely masked targets (sometimes happens with corner case healpix), it was writing a *.notargets file instead.  This update makes it …

qso_qn output even if all inputs are masked

---

bin/desi_zcatalog

This PR propagates the input SPGRPVAL header keywords into the desi_zcatalog output ZCATALOG tables.  For the perexp, pernight, and cumulative groups this is redundant with EXPID, NIGHT, and LASTNIGHT columns, but for custom coadds like 1x_depth, 4x_depth, lowspeed it provides a generic way to record which input set contributed to each row.
Example outputs are in /global/cfs/cdirs/desi/users/sjbailey/dev/fuji/zcat:
* ztile-1x_depth.fits  ztile-4x_depth.fits  ztile-lowspeed.fits : proposed redshift catalogs to include with fuji
* ztile-sv1-dark-pernight.fits example reprocessing of the existing fuji/zcatalog/ztile-sv1-dark-pernight.fits, differing only by the addition of the SPGRPVAL column.
The one future-proofing trick is that it tries to use np.int32 as the dtype if it can (applies to …

add SPGRPVAL to desi_zcatalog output for custom coadds/redshifts

---

bin/plot_spectra

Add the ability to plot errors on spectra to plot_spectra even when --rebin is specified.  Currently the --errors argument only works when --rebin is not set; with this PR, --errors now works even for rebinned spectra.  I also changed the behavior of --errors in two ways:
- I also show a simple line plot of the errors offset by 2, in addition to the error bars
- I replaced the individual lines with a shaded region.
Here is a resulting spectrum:
`
plot_spectra -i ~/redux/daily/tiles/cumulative/7893/20220219/coadd-7-7893-thru20220219.fits --zrange 5 6 --redrock ~/redux/daily/tiles/cumulative/7893/20220219/redrock-7-7893-thru20220219.fits --rebin 5 --errors
`
and zooming in

Let plot_spectra show errors even when --rebin is specified.

---

py/desispec/io/spectra.py

This PR adds a "group" argument to io.spectra.read_tile_spectra, so that one can do group='cumulative' to get the cumulative tile spectra.  I also needed to special case the file name for 'cumulative' spectra so that it looked for thruYYYYMMDD in the file name, rather than just YYYYMMDD.
I have not tried to be exhaustive about handling all of the different possibilities for groups.  But this will now read the "normal" cumulative groups again.  It's possible that the default should be group='cumulative'?

Add 'group' feature to io.spectra.read_tile_spectra.

---

bin/desi_zcatalog

**Candidate for including in final fuji redshift catalogs**, if we can get review by Monday 
~noon Pacific Time; I think this is simple enough to be viable for that (despite the long PR description...)
This PR fixes the missing sv1 FLUX_IVAR_W1/W2 values in the stacked zcatalog files (but not in the fibermap through redrock files; too late for Fuji).  These values are missing in fiberassign tiles designed prior to 20201212.  `desi_zcatalog --patch-missing-ivar-w12 ...` identifies the rows with missing `FLUX_IVAR_W1/W2` values, looks up the original values in the sv1 targeting files (i.e. what would have been propagated if that column had been included by fiberassign at the time), and patches the zcatalog columns before writing out the files.
Originally I thought I would use external …

desi_zcatalog patch missing sv1 FLUX_IVAR_W1/W2

---

py/desispec/scripts/qproc.py

Suggestion from @julienguy: add `deggy=0` to the list of automatic qproc options to use a constant offset for the CCD y-coordinates rather than a polynomial. The new default should fix the B camera DY out-of-range issue reported in several Nightwatch tickets (e.g. desihub/nightwatch#263).
- Before fix: https://nightwatch.desi.lbl.gov/20220227/00124229/qa-camera-00124229.html
- After fix: https://data.desi.lbl.gov/desi/users/sybenzvi/nightwatch/20220227/00124229/qa-camera-00124229.html

Fit constant offset to CCD y coordinates.

---

py/desispec/data/batch_config.yaml
py/desispec/scripts/tile_redshifts.py

Enables `rrdesi_mpi` to run on GPUs (see [redrock #204](https://github.com/desihub/redrock/pull/204)) for automatically-generated Slurm batch scripts when `--system-name perlmutter-gpu` is specified on the command line for `desi_tile_redshifts` on Perlmutter. This change does not affect the behavior of `desi_tile_redshifts` on Cori.

Enable GPUs on Perlmutter in slurm script for rrdesi_mpi

---

py/desispec/workflow/exptable.py

This addresses email thread [desi-survey 3581] initiated by David Schlegel, where he advocated for more stringent efftime_etc cuts on the data. 
The code changes are minimal. We move from a cut at 5% of goaltime to fixed cuts of:
- dark: efftime_etc < 100s
- bright: efftime_etc < 20s
- backup: efftime_etc < 0.5s,
where the exposure is not flux calibrated or fit for redshifts if it fails the relevant criterion.
Below I include plots David provided for bright and dark time respectively showing all main survey exposures currently marked as good, and highlighting those that would now be cut in red:
The plots are in efftime_spec, but he verified that the cuts do not change with efftime_etc. The red points will be manually rejected to make past data consistent with future data.

New main survey minimum exposure efftime_etc

---

py/desispec/tile_qa_plot.py

This PR does two minor modifications to the tile-qa-*.png plots:
- n(z) plot: the x-axis is extended from 0 to -0.1, in order to make more visible a (dubious) peak in the first redshift bin
- Z vs. FIBER plot: the secondary-only targets are now displayed with a different color-scheme (as those can have some very specific patterns in this plot).
- 
Here is an example (which prompted the secondary-only feature, as those are responsible for the Z~0.08 patch on PETAL_LOC=6):
Before:
Now:
Remarks for the secondary-only feature:
- I use the `DESI_TARGET` column to identify those: that will of course "fail" with any non-main tile, with identifying zero secondary-only (as that `DESI_TARGET` column will exist, but be filled with zeros); I assumed that is fine, as the goal is to ease the dailyops …

tile_qa_plot : highlight secondary-only fibers in Z vs. FIBER

---

py/desispec/preproc.py

- Define a CCD band next to overscan columns but in active region
- Measure charge per row
- If above a threshold of 50,000 ADUs, ignore values in overscan rows (replace by interpolated values from good overscan rows)
This solves https://github.com/desihub/desisurveyops/issues/28
This change  to the preprocessing still needs to be validated on a larger set of exposures/cameras (including ones with noisy amps and large OSTEP values, and other instances of cosmics near the overscan region).

Ignore overscan rows with large charge deposit detected in preceeding active CCD pixels

---

py/desispec/preproc.py

This PR is an addendum to PR #1720 to interpolate over overscan rows that might be impacted by bright cosmics.  It reflects the code that I actually used when testing that PR.  I had factored out the new logic into a separate function to make it easier to run independently of preproc itself, but forgot to commit my changes before merging the PR.  The actual output is identical to PR #1720.

make find_overscan_cosmic_trails separate function

---

py/desispec/desi_proc_dashboard.py

This is a small pull request to correct the file counting in the spectro pipeline dashboard for the 1s flats used for CTE identification. These are extracted in the pipeline, but aren't used to create fiberflats, which then show up as red (meaning failed) in the dashboard based on the `OBSTYPE` being 'flat'. 
This update creates a new category of expected files called 'cteflat' that is detected as `OBSTYPE == 'flat' and EXPTIME < 2.0`. Normal flats have much longer integration times, so this should be appropriate, but I could just as easily select on `'cte' in PROGRAM` if people don't like the `EXPTIME` based selection.
An example of the dashboard run with this branch can be found here:
https://data.desi.lbl.gov/desi/users/kremin/PRs/dash_ignore_short_flats/dashboard.html
Screenshot …

add cte flat class to dashboard so it reflects expected files

---

py/desispec/parallel.py
py/desispec/test/test_parallel.py

This modification ensures that the partitioning encoded in `max_per_proc` limits the size of subgroups returned by `desispec.parallel.dist_discrete_all` by removing the `target` and `over` variables.
If the expected behaviour of `dist_discrete_all` is to return a configuration that minimizes the maximum of work done over all subgroups, as is likely, then this modification should be adopted. 
This issue was discovered with @dmargala during review for redrock [PR #204](https://github.com/desihub/redrock/pull/204) for very similar code in redrock. The changes here are essentially identical to those in redrock [PR #207](https://github.com/desihub/redrock/pull/207).
Please review and merge if appropriate.

Remove mean work per process from subgroup partitioning

---

py/desispec/scripts/extract.py
py/desispec/scripts/fluxcalibration.py
py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/stdstars.py
py/desispec/util.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/zcatalog.py

The `zcatalog.py` now has three extra functions. The `create_summary_catalog()` function will be useful for creating summary redshift catalogs that combines all zpix*/ztile*cumulative files and adds the PRIMARY columns that flag the "best" spectra for a given TARGETID. The code can be run as follows: 
```
import zcatalog.create_summary_catalog as cz
path = ".\"
filename = path+"zpix-sv-all.fits"
cz(spec_release = 'fuji', version = 'zpix', output_filename = filename)
filename = path+"ztile-sv-all.fits"
cz(spec_release = 'fuji', version = 'ztile', output_filename = filename)
filename = path+"zpix-main-all.fits"
cz(spec_release = 'guadalupe', version = 'zpix', output_filename = filename)
filename = path+"ztile-main-all.fits"
cz(spec_release = 'guadalupe', version = 'ztile', output_filename = …
```

Create Summary Catalogs for Fuji/Guadalupe

---

py/desispec/scripts/trace_shifts.py

This PR will fix an infinite loop in qproc that occurs when it tries reducing the polynomial order of trace fit offsets. The fix is needed because the existing logic at [line 277 of trace_shifts.py](https://github.com/desihub/desispec/blob/98fc62ef166c05557c62027562ec240074c26102/py/desispec/scripts/trace_shifts.py#L277) is incompatible with the initial condition `degyy=0`. The PR has two fixes:
1. Line 277 is changed to `if degxy>0 or degyy>0 and degxy>degxx and degyy>degyx:`
2. An iteration limit is imposed to avoid infinite loops. When the limit is reached, `degxx=degxy=degyx=degyy=0`.

Iteration limit

---

bin/desi_tile_vi

Skip filtering of tiles to un-VIed tiles if --tileids have been explicitly specified.
Currently desi_tile_vi only shows tiles that haven't been VIed yet.  This PR changes that behavior if called with an explicit list of tiles to VI.

Allow QA of already QAed tiles.

---

py/desispec/scripts/proc.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py

Set the shift of traces a default option for `desi_proc` (it happened too many times that we forget this option when running tests).
Add option `--no-traceshift`  and print a "deprecated" warning message if `--traceshift` option is set (for backward compatibility).
Tested with the processing of a flat field frame.

Trace shift by default

---

py/desispec/scripts/proc.py
py/desispec/scripts/specex.py
py/desispec/workflow/schedule.py

Improves specex error handling by modifying `workflow.scheduler.run()` to return the sum of all return values of jobs it runs, `fitbundles` to return a nonzero value if an exception is caught from `specex.main`, `specex.main` to return a nonzero value if an exception is caught from `merge_psf`, `specex.run()` to return the value of `workflow.scheduler.run()`, and finally for `proc` to increment `error_count` with the return value of `specex.run()`. 
Any uncaught exception raised during execution of `specex.specex.run_specex` will result in "`FAILED`" to be reported to stdout at the end of `proc` execution (after being caught by `fitbundles` when trying `specex.main`), such as
```
INFO:proc.py:1342:main: All done at Thu Apr 21 21:29:44 2022; duration 3m55s
srun: error: nid02340: task 0: …
```

Improve error handling for specex

---

py/desispec/tile_qa_plot.py

This PR is a simple fix for issue https://github.com/desihub/desispec/issues/1752 in tile_qa_plot (because of recent addition of `LOW_EFFTIME` in the `bad_qafstatus_mask`, zero fiber will be valid for not-yet-completed tiles, which make the code crash).
It just keeps `nqso_rr=0` in that case.

bugfix: handle nqso_rr if zero valid fiber

---

py/desispec/io/spectra.py
py/desispec/pixgroup.py
py/desispec/scripts/coadd_spectra.py
py/desispec/scripts/group_spectra.py
py/desispec/spectra.py

This PR adds the ability for `desi_group_spectra` to directly output a coadd file instead of requiring that we first output an uncoadded spectra file and then run `desi_coadd_spectra` to coadd it.
Example usage, with example outputs in `/global/cscratch1/sd/sjbailey/coadd`, to compare with spectra and coadds in `fuji/tiles/cumulative/100/20210505` (tile based coadds) and `fuji/healpix/sv3/dark/105/10520/` (healpix based coadds):
```
cd $SCRATCH/coadd
export SPECPROD=fuji
rx=$DESI_SPECTRO_REDUX
desi_group_spectra --expfile $rx/fuji/healpix/sv3/dark/105/10520/hpixexp-sv3-dark-10520.csv \
-o spectra-sv3-dark-10520.fits -c coadd-sv3-dark-10520.fits --healpix 10520 \
--header SPGRP=healpix SPGRPVAL=10520 HPXPIXEL=10520 HPXNSIDE=64 HPXNEST=True SURVEY=sv3 PROGRAM=dark
desi_coadd_spectra -i …
```

desi_group_spectra --coadd option

---

py/desispec/preproc.py
py/desispec/scripts/preproc.py

Other tuning of the recipe to identify overscan rows to ignore because of the effect of a cosmic ray hit. Here we add a margin of +-2 pixel around the pre-identified rows. This solves the case: https://nightwatch.desi.lbl.gov/20220424/00131715/preproc-b6-00131715-4x.html .
It is unclear why we need this because the effect of CTE trails should be independent from row to row.
But in this particular case (`preproc-b6-00131715.fits`), row y=3481 (starting counting at 0) has a max flux of only 10000 electrons but the same trail as rows y=3479-3480 which have a saturated pixel. See figure below.
Adding this margin is one more ad-hoc correction term to the recipe. It should prevent rare effects like this one (but should not trigger any new false detection).

Cosmics and overscans bis

---

bin/desi_compute_fiberflat_vs_humidity
bin/plot_frame
py/desispec/fiberflat_vs_humidity.py

Improve fiberflat vs humidity correction
- used all daily fiberflats from 2020,2021,2022
- change binning fiberflats : use the wavelength shift of the fiberflat in b0 instead of the humidity value from the metrology (in other words, we use b0 as a humidity probe)
- use one template for each step of 2A in the wavelength shift
- interpolate between bins using the template index rather than the humidity values of each template.
Example for the b0 fiber flat humidity correction template:
The following figure shows that the wavelength shift is not a monotonous function of the humidity from the telemetry at very low humidities (could be due to a time constant for the collimator mirror variations). This justifies using directly the wavelength shift as the index instead of the humidity. …

Improve fiberflat vs humidity

---

setup.py

**Context**: I recently upgraded my laptop base conda installation to use python 3.9.12, which effectively broke unit tests started via "python setup.py test".  I know the new procedure is to use pytest instead, but old habits die hard...
**Symptom**: The test_binscripts test of `desispec.scripts.stdstars.main` when called as a function (but not when called via a spawned script) would go crazy on the multiprocessing, and start running multiple versions of the test including multiple lines like "running build_ext", sometimes printing the message:
```
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.
This probably means that you are not using fork to start your
child processes and you have forgotten to use the proper idiom
in …
```

add ifmain check to setup.py

---

py/desispec/night_qa.py

This PR is a followup to the gzip PR #1756 to fix nightqa with the gzipped files:
* use `desispec.io.findfile` instead of constructing filepaths by hand
* use fitsio instead of astropy.io.fits for faster reading of gzipped files
I tested this on 20220505, fixing the original problems created by it not finding the newly gzipped files.  I also ran it on 20220504 to confirm that it still works with non-gzipped files too.  The runtime is slower with the gzipped files; it now takes ~16min to run nightqa, with most of the time spent on the sframe files (by eye watching it run, not detailed timing).
I'm running this through a PR for the record, but plan to self merge since this fixes a crash in nightqa in current master and I'd like to get it ready in place for tonight.

nightqa use findfile and fitsio

---

py/desispec/scripts/submit_night.py

This fixes a bug where desi_run_night crashes if `z_submit_types` is None and there are non-consecutive observations of a single tile. This was identified in a test run including 20211030 where a backup tile is observed twice with another tile observed in between.
The fix is simple and I verified that running the following command fails in master and succeeds in this branch:
`desi_run_night -n 20211030 --z-submit-types=None --dry-run-level=3`
I used my personal `SPECPROD` for the test, since no files were produced as output. `desi_run_night` just requires a `SPECPROD` with the corresponding exposure_table available for the night submitted, otherwise it will throw an error.

Fix crash in desi_run_night with non-consecutive tile obs

---

bin/desi_night_qa
bin/desi_tile_qa
py/desispec/scripts/exposure_qa.py
py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/tile_redshifts.py
py/desispec/util.py

This PR fixes a new intermittent failure on Cori KNL nodes, where importing healpy imports matplotlib which sometimes crashes with:
```
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```
It is unclear why this only occurs on KNL, and why it only occurs sometimes, or why we didn't see it with fuji (perhaps related to deforkproc causing more MPI ranks to import healpy/matplotlib instead of  spawning serial commands that loaded it).
Regardless, the workaround is to set a batch friendly backend before any other imports, using `desispec.util.set_backend` which we had previously used to work around backend issues with plotting libraries on Travis tests without $DISPLAY set.  I added this to desi_proc, …

set batch-friendly matplotlib backend

---

py/desispec/tile_qa.py
py/desispec/tile_qa_plot.py

This PR makes `tile_qa.py` and `tile_qa_plot.py` getting the exposure list from a tile from reading *all* the spectra files, not just the first one.
It fixes the issue identified in https://github.com/desihub/desisurveyops/issues/44 for tileid=42426.
For that tile:
- two exposures where made (130563 on 20220416, and 130673 on 20220417);
- but petal=0 is discarded in the second exposure 130673.
With the current master, the code infers that there is just exposure, 130563, as it reads `/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/42426/20220417/spectra-0-42426-thru20220417.fits`.
The qa plot looks like this:
And no `/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220417/00130673/exposure-qa-00130673.fits` file is generated.
With this PR, the qa plot look like this:
and …

get expids from all spectra files

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR parallelizes some functions, and brings several small improvements to the night_qa scripts.
I ll make more tests tomorrow for sanity, but I m sharing now, for any comments or suggestion of other small improvements to do, as this PR is a potpourri.
The (current) changes are:
- parallelization of:
- `create_dark_pdf()`
- `create_sframesky_pdf()`
- `create_ctedet_pdf()`
- `bin/desi_night_qa` (addressing https://github.com/desihub/desispec/issues/1783):
- remove deprecated `--html_only` argument
- add a `--compute_missing_only` argument
- small cleanup of the steps usage
- miscellaneous:
- define `petals` and `cameras` at top of the code
- `create_ctedet_pdf()`: print warning message if not using a 1s FLAG image
- `create_skyzfiber_png()`: protect against missing petal=0
- …

night_qa: parallelization, and various small improvements

---

py/desispec/data/batch_config.yaml
py/desispec/scripts/proc_tilenight.py
py/desispec/workflow/desi_proc_funcs.py

Adds script generation for `desi_proc_tilenight`. 
Example to run on Perlmutter:
```
source /global/common/software/desi/desi_environment.sh
DESI_SPECTRO_REDUX=/global/cfs/cdirs/desi/users/$USER/spectro/redux
night=20211014
tileid=6699
preprod_ngt () {
proddir=$DESI_SPECTRO_REDUX/$SPECPROD
mkdir -p $proddir
cd $proddir
if [ ! -d $proddir/exposure_tables/${night:0:6} ] ; then 
copyprod $CFS/desi/spectro/redux/$cpspec . --night $night --filter-exptables
fi
rm -rf $proddir/exposures/$night $proddir/preproc/$night
}
common_args="-n $night -t  $tileid --mpi --batch --queue regular"
SPECPROD=gpuext-gpuspc; preprod_ngt
desi_proc_tilenight $common_args --system-name perlmutter-gpu
SPECPROD=cpuext-cpuspc; preprod_ngt
desi_proc_tilenight $common_args --system-name perlmutter-cpu …
```

Batch script generation for desi_proc_tilenight

---

bin/desi_psf_fit

Adds the script `bin/desi_psf_fit` in order to wrap `specex` and fixes desihub/specex#66. Example:
```
source /global/common/software/desi/desi_environment.sh main
branchdir=$SCRATCH/desispec
git clone -b desi_psf_fit git@github.com:desihub/desispec.git $branchdir 
export PYTHONPATH=$branchdir/py:$PYTHONPATH 
export PATH=$branchdir/bin:$PATH
a=/global/cfs/cdirs/desi/spectro/redux/himalayas/preproc/20211013/00104057/preproc-r8-00104057.fits.gz
i=/global/cfs/cdirs/desi/spectro/redux/himalayas/exposures/20211013/00104057/shifted-input-psf-r8-00104057.fits
l=/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/specex/0.8.4/lib/python3.9/site-packages/specex/data/specex_linelist_desi.txt
o=/tmp/fit-psf-r8-00104057_06.fits
desi_psf_fit -a $a --in-psf $i --out-psf $o --lamp-lines $l …
```

Add specex wrapper desi_psf_fit

---

py/desispec/emlinefit.py

This PR corrects the units in the docstring for the emline functions.
The fitted was wrongly reported to be per-Angstrom; and I also noticed that the units where not provided for the equivalent-width; and a typo (`e-17` -> `1e-17`).

Emline files: correct units in docstring

---

doc/api.rst
py/desispec/io/photo.py

This PR has a partial-line change in `desispec.io.photo._gather_tractorphot_onebrick` which is needed to fix https://github.com/desihub/fastspecfit/issues/75. This function is not used anywhere else except by FastSpecFit and to generate the photometric VAC, so I'm going to self-merge momentarily since the issue this addresses is a blocking factor.

require PHOTSYS when matching to get DR9 photometry

---

py/desispec/io/__init__.py
py/desispec/io/sky.py
py/desispec/io/tpcorrparam.py
py/desispec/scripts/proc.py
py/desispec/scripts/procexp.py
py/desispec/scripts/sky.py
py/desispec/sky.py
py/desispec/skygradpca.py
py/desispec/test/test_sky.py
py/desispec/tpcorrparam.py
py/desispec/workflow/desi_proc_funcs.py

This PR replaces the current per-fiber, per-camera TPCORR parameters with a model.  The TPCORR parameters are fits of the brightness of individual sky lines in a fiber's spectrum, relative to the average sky in a given camera.  This is motivated by the TPCORR parameters introducing significant differences in the sky levels between the B/R cameras, leading to cases where we get spurious redshifts when the moon is bright.  The model has the biggest impact on the B band, where TPCORR was least well measured due to the reliance on a single bright sky line.  In R and Z it has less impact, but is also applied there.
The model is that TPCORR is a cubic polynomial in a fiber's location within its patrol radius, derived from fitting past TPCORR measurements.  On top of this, there are two PCA …

Replace TPCORR per-fiber corrections with a model

---

py/desispec/scripts/specex.py

Fixes a minor bug that was introduced during #1802 that causes an error message to be logged instead of the timing for PSF fitting.

Fix rank bug in specex.py

---

py/desispec/fiberbitmasking.py
py/desispec/scripts/stdstars.py
py/desispec/sky.py
py/desispec/test/test_binscripts.py
py/desispec/test/test_sky.py

This PR fixes #1810 for standard star fitting:
* use the correct fiber when applying the fiberflat and sky subtraction
* when scaling the flux by the fiberflat, also scale the ivar to match
Testing on all exposures of 20210531, this results in a distinct improvement in the scatter of the data-model G-R colors:
The test outputs are in `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/stdstar`, which used guadalupe inputs and re-ran just the stdstar fitting step for each tile.

stdstar correct sky and flat fiber; scale ivar

---

py/desispec/fluxcalibration.py
py/desispec/io/fluxcalibration.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/stdstars.py
py/desispec/sky.py
py/desispec/test/test_fiberbitmask.py
py/desispec/test/test_sky.py
py/desispec/workflow/desi_proc_funcs.py

This PR fixes issues
* #1785: examples of stdstars running out of memory for tiles with many exposures
* #1789: go back to using a max of 30 stdstars instead of 50; make that an option not a hardcode
* #1813: stdstars FIBERMAP HDU is now in the same sort order as the other HDUs
* #1781: stdstar jobs would claim to "succeed" (at the slurm level) even if some petals had failed; now if any petal fails the job is flagged as failing
Test runs are in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/stdmem (this branch) and stdmem-main (current master), testing
```
time srun -N 1 -n 30 -c 4 --cpu-bind=cores desi_proc_joint_fit --obstype science --mpi --mpistdstars \
--cameras a0123456789 -n 20210928 -e 102103,102104,102105,102106,102107,102108 
time srun -N 1 -n 30 -c 4 --cpu-bind=cores …
```

stdstar memory optimization

---

py/desispec/scripts/proc.py

This 2-character PR fixes #1816 where @paulmartini reported a bug with the desi_proc call to stdstars.main and correctly identified the fix.  I independently verified that it works by processing a real data exposure; Paul had previously verified that it worked on a simulated exposure.  I plan to self merge after tests pass since this is effectively a review of what Paul had already suggested and tested.
For context, the standard pipeline uses a joint fit across exposures for the standard star step, and thus we had missed testing this case of single-exposure stdstar fitting.  Thanks for catching it and reporting the fix.

fix desi_proc stdstars args

---

py/desispec/scripts/healpix_redshifts.py
py/desispec/scripts/tile_redshifts.py
py/desispec/workflow/desi_proc_funcs.py

Fixes a bug in which desi_proc crashes when the --system-name option is not specified by adding the default value for system_name in `scripts.tile_redshifts.parse`, `scripts.healpix_redshifts.parse`, and `workflow.desi_proc_funcs.get_shared_desi_proc_parser` through `workflow.batch.default_system`. 
For example, on Perlmutter:
```
% desi_proc -n 20211014 -e 104277 --cam r1 --nostdstarfit --nofluxcalib --batch --nosubmit
INFO:batch.py:60:default_system: Guessing default batch system perlmutter-gpu
...
Wrote /global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec_1824.run0/run/scripts/night/20211014/prestdstar-20211014-00104277-r1.slurm
... 
% grep constraint /global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec_1824.run0/run/scripts/night/20211014/prestdstar-20211014-00104277-r1 …
```

Default system_name in parsers

---

py/desispec/sky.py

The tpcorr modeling code broke the sector implementation.  This PR addresses fixes a few bugs with the sector fitting code:
- Check all amps for sectors
- Report correct sector amplitudes
- Apply correct sector amplitudes
- Add sectors to modeled sky
- Divide sectors by flat field (sectors are in detector counts; frame fluxes are flattened by dividing by flat).
This fixes https://github.com/desihub/desispec/issues/1823 identified by Julien.

Restore sector offsets

---

bin/desi_purge_night

This PR adds `bin/desi_purge_night` which purges an entire night from a production, primarily intended for cleanup when a night fails early in the processing (e.g. in the cals) and needs to be restarted from the beginning (e.g. due to flagging cameras as bad when the existing scripts and processing table entries were generated including those bad cameras).
It doesn't go into the messier bookkeeping of purging perexp redshifts, cumulative redshifts on future nights, or healpix redshifts, but as long as those limitations are understood I think this has enough functionality to be useful (I wrote it to help with Himalayas cleanup).
It removes:
* calibnight/NIGHT
* preproc/NIGHT
* exposures/NIGHT
* nightqa/NIGHT
* run/scripts/night/NIGHT
* tiles/cumulative/*/NIGHT
* tiles/pernight/*/NIGHT
* …

add desi_purge_night

---

py/desispec/io/iotime.py
py/desispec/test/test_io.py

This PR fixes a bug where `desispec.io.iotime.parse_logfile(filename)` would crash if given a logfile that didn't have any iotime messages in it.  Now it returns `None` instead of crashing.

iotime.parse_logfile dont crash on logs without iotime messages

---

py/desispec/preproc.py

This PR fixes #1829 by making $SPECPROD optional for `desi_preproc`.  It was being used to look for the nightly bias.  Now if $SPECPROD isn't set, that is equivalent to the nightly bias not being there.  i.e.
If `desi_preproc --bias ...` is given, that will be used regardless of whether $SPECPROD is set or not.  Otherwise:
If $SPECPROD is set, desi_preproc will use that to look for the nightly bias, falling back to the default bias if a nightly bias isn't found in that specprod.
If $SPECPROD is not set, desi_preproc will use the default bias, equivalent to a missing nightly bias.
Tested with:
```
unset SPECPROD
desi_preproc -i $CFS/desi/spectro/data/20211010/00103648/desi-00103648.fits.fz --cameras b0 -o $SCRATCH/temp/blat.fits --bias …
```

SPECPROD optional for desi_preproc

---

py/desispec/night_qa.py

This PR addresses https://github.com/desihub/desispec/issues/1839, with adding in the night qa page a check on the existence of the `biasnight` files.
With adding this third set of files (in addition to `psfnight` and `fiberflatnight`), the table gets too big, so I ve removed from the reported name the night.
In case of a link to another file, the linked basename (with the night) will/should be reported.
Besides, I also correct a small (but embarassing...) bug: because of an indentation error, if a file was missing, it was not printed out; now it is.
Before:
Now:

Nightqa v13

---

py/desispec/scripts/proc.py
py/desispec/scripts/proc_tilenight.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py

Modifies `scripts.proc_tilenight.main` to catch and log exceptions from `scripts.proc.main` and `scripts.proc_joint_fit.main`. This improves logging of errors and allows other exposures to be processed prior to terminating early.
Increases `tilenight` and `flat` batch job time limits as specified in `workflow.desi_proc_funcs.determine_resources`, based on running the equivalent of Guadalupe on Perlmutter. 
Fixes a minor bug where `internal_id` was not being incremented in `workflow.profcuncs.submit_tilenight`.
Changes to desispec in preparation to run the pipeline in production mode on Perlmutter are ongoing; this is an incremental update to simplify the integration and documentation of changes to the main branch.
@sbailey please review merge if the changes look good (particularly the …

Catch exceptions in tilenight and revise batch time limits on Perlmutter

---

bin/desi_run_night
py/desispec/scripts/submit_night.py
py/desispec/test/test_scripts.py

As first outlined in [[desi-survey 3824] ](https://desi.lbl.gov/trac/tracmailman/browser/private/desi-survey/2022-August/003823.html), this PR adds the logic to desi_run_night so that it only submit completed tiles for processing. After discussion in that email thread and in a telecon, the final selection was chosen to be the OR of the following:
- `ZDONE == 'true'`   # selects main archived tiles and SV tiles with enough time
- `(EFFTIME_SPEC > 0.1*GOALTIME)  &  SURVEY != 'main'`  # selects non-main (including special) tiles with enough time
- `(EFFTIME_SPEC > 0.1*GOALTIME)  &  FAPRGRM == 'backup'`  # selects any backup tiles with enough time
The email proposal specified using `MINTFRAC` (typically 0.85) rather than the final 0.1 reflected in this PR. The choice applies to non-main …

desi_run_night only runs completed tiles by default

---

py/desispec/ccdcalib.py
py/desispec/preproc.py
py/desispec/scripts/proc.py
py/desispec/test/test_preproc.py

This PR fixes #1788 where desi_compute_nightly_bias would crash for CCDs in 2-amp readout mode, e.g. r8 and z6 on nights 20211116 - 20211118.  It also fixes a bug where `desi_proc` was not propagating the `--cameras` option to `desi_compute_nightly_bias`, and improves the MPI error handling such that any biasnight failures don't cause MPI to get stuck until the job times out.
Test results in `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/biasnight/calibnight`, tested with:
```
srun -n 2 desi_proc --nightlybias --cameras r8z6 -n 20211118 --mpi
```
main: incorrectly processes all cameras and crashes+hangs on r8z6 until job times out (see #1788 for details)
PR: processes only r8z6 and succeeds
```
srun -n 2 desi_compute_nightly_bias --cameras r8z6 -n 20211118 --mpi
```
main: crashes …

Fix 2-amp biasnight

---

py/desispec/scripts/submit_night.py

This solves issue #1847 with a one line fix. I tested that it produces the correct output. Instead of sorting on `TILEID` alone, which appears to implicitly sort on other columns, it now sorts on `TILEID`, then `EXPID`. This should now always produce the correct numeric ordering of `EXPID`'s.
Now running: `desi_run_night -n 20220113 --tiles="4403" --z-submit-types=cumulative --laststeps="all,skysub,fluxcal" --all-tiles --dry-run-level=3`
shows the correct ordering of `EXPID`'s, as shown in this snippet:
`INFO:procfuncs.py:184:check_for_outputs_on_disk: stdstarfit job with exposure(s) [118524 118525]`

Sort on EXPID as well as TILEID in desi_run_night

---

.github/workflows/python-package.yml
py/desispec/scripts/tile_redshifts.py

This addresses issue #1851 . `emlinefit` was run by-hand in fuji and guadalupe but is now ready to be incorporated into the pipeline. The implementation directly mimics those of the QSO afterburners, which were already included in the redshift script.
I tested this on tile 22469 from night 20220514. The scripts and results can be found here at: `/global/cfs/cdirs/desi/users/kremin/PRs/integrate_emlinefit`
The test included `perexp`, `pernight`, and `cumulative` redshifts. The tile had two exposures to test combining spectra (though none of that code was modified).
The `emlinefit` code was called for all spectrographs and the outputs and logs were written to the proper locations in all flavors of the redshifts tested.

Add emlinefit afterburner to redshift scripts

---

py/desispec/io/util.py
py/desispec/scripts/tile_redshifts.py
py/desispec/test/test_io.py

This solves issue #1836 where the globbing in the redshift scripts is picking up temporary files that are labeled as `*.fits_temp??????.gz` when we only want it finding `*.fits` and `*.fits.gz`. This resolves that using a "{" brackets to only check those two specific file endings. This produces an error for one or the other (either `cframes` were all gzipped or not so one of the two `ls` evaluations always fails to find any files). That means we have to catch the error and then we need a new mechanism to check whether the glob succeeded. I use the number of glob templates compared to the identified `cframes` as a test of glob success instead. It is a lower limit, but I can't be more restrictive, since a given glob could correspond to anywhere from one to three exposures (depending on the …

Improve cframe file globbing and tempfilename

---

py/desispec/scripts/extract.py
py/desispec/scripts/proc.py

This PR updates `desi_extract_spectra` to pass the value of its `--psferr` command line argument through to `specter.extract.ex2d`.
To preserve consistency with fuji and guadalupe reductions, this PR also removes the `--psferr 0.1` added to the `desi_extract_spectra` command in `desi_proc` since that was ignored anyway.
The default value for the `--psferr` command line argument in  `desi_extract_spectra` is `None`. Both specter and gpu_specter handle the case of `psferr is None` in the same way: they use the value of the "PSFERR" keyword in the PSF header and, if that is not defined, they use a default value of `0.01`.
`desi_extract_spectra` is already passing `psferr` through when using gpu_specter so no action is needed there. (Comparing extractions using desi_proc with …

fix psferr option in desi_extract_spectra

---

py/desispec/io/__init__.py
py/desispec/io/meta.py
py/desispec/scripts/extract.py
py/desispec/scripts/preproc.py
py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/test/test_io.py
py/desispec/workflow/desi_proc_funcs.py

This PR implements #1842 by adding support for $DESI_ROOT_READONLY to specify the read-only /dvs_ro/cfs/cdirs/desi mount of /global/cfs/cdirs/desi.
* new `findfile(..., readonly=False/True)` option to request the read-only filepath
* new function `desispec.io.meta.get_readonly_filepath(filepath)` to convert a read-write filepath into a read-only filepath
* new helper function `desispec.io.meta.get_desi_root_readonly()` used by `findfile` and `get_readonly_filepath` that checks for $DESI_ROOT_READONLY, checks that it actually exists, and caches the answer so that subsequent calls to `findfile` and `get_readonly_filepath` don't have to keep re-checking.
In all cases, if $DESI_ROOT_READONLY isn't set or is set to a value that doesn't exist (e.g. /dvs_ro/cfs/cdirs is mounted on cori compute …

Add support for NERSC CFS readonly mount

---

py/desispec/ccdcalib.py
py/desispec/test/test_ccdcalib.py

This resolves issue #1840 where compute_nightly_bias was failing for cameras without enough calibration zeros. Those nights sometimes have other zeros taken as part of e.g. dark sequences. We want to only use calibration zeros when there are enough, but when there are not enough we want to fallback to using non-calibration zeros automatically without the need for human intervention.
This does so by finding and tracking calibration and non-calibration zeros separately in the `compute_nightly_bias` code, and using the non-calibration zeros only when a special flag is set (this maintains the old use-case) OR if the code determines that there are not enough calibration zeros and there are enough non-calib zeros for a given camera to compute a nightly bias. 
There are three note-worthy choices …

Use non-calibration zeros if not enough calib zeros available

---

py/desispec/scripts/proc_joint_fit.py
py/desispec/workflow/batch.py
py/desispec/workflow/desi_proc_funcs.py

This is a minimally invasive edit to the default_system() function to return `perlmutter-cpu` instead of `perlmutter-gpu` when running `ccdcalib`, `nightlybias`, or `arc` exposures. If the optional jobdesc is provided and set to one of those values then `perlmutter-cpu` is returned, otherwise `perlmutter-gpu` is returned as before. The argument is optional and no argument results in`perlmutter-gpu`.
I ask @marcelo-alvarez to verify that there are no unintended knock-on effects from this and that the resource allocation makes sense when using `perlmutter-cpu`'s. @sbailey please review/comment on implementation.
Caveats:
1. The only caveat is if `desi_proc` or `desi_proc_joint_fit` are run from the command line then the default for `system_name` is defined at start time as …

Default to Perlmutter CPU nodes for nightlybias, ccdcalib, and arcs

---

bin/desi_night_qa

Very simple addition to the `desi_night_qa` script so that it announces when it is done and says how long it took. This resolves issue #1846 , which points that out. This is nice so that the end user knows that the code ran to completion rather than crashing.
I tested this on one night with the following:
`desi_night_qa --nproc=2 -p daily -n 20220927 -o ./nightqa/20220927 &>> nightqa-20220927.log`
The outputs can be seen here:
`/global/cfs/cdirs/desi/users/kremin/PRs/nightqa_timelog`
This includes the proper log message:
`kremin@cori07:/global/cfs/cdirs/desi/users/kremin/PRs/nightqa_timelog> tail -n 2 nightqa-20220927.log` :
```
INFO:night_qa.py:1174:create_petalnz_pdf: selecting 359 tracer targets from /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/24869/20220927/zmtl-9-24869 …
```

Have desi_night_qa announce its completion

---

py/desispec/skygradpca.py
py/desispec/tpcorrparam.py

This PR replaces NaNs in FIBERASSIGN_X/Y in skygradpca with 0s.  It also replaces NaNs and 0s in skytpcorr with the nominal locations of the fibers.
This addresses https://github.com/desihub/desispec/issues/1864.  This is unlikely to change any tile that previously succeeded, since any NaNs in FIBERASSIGN_X/Y would lead to all NaNs in the corresponding skygradpca columns due to the removal of the mean.  It's conceptually possible that there were other cases of FIBER_X/Y = 0 without FIBERASSIGN_X/Y = NaN that would now be set to default nominal values in skytpcorr; i.e., this would be a ~non-backward compatible change.  I don't know if any such tiles exist, and they'd clearly be problematic.
Ideally I'd set all NaNs / 0s to the nominal centers of the fibers, but I don't know how to …

Sanitize x/y inputs to skytpcorr, skygradpca.

---

py/desispec/scripts/daily_processing.py

A small change to prevent unnecessary waiting at the end of desi_daily_proc_manager when being run on previous night's data using over_ride night. In `main` it waits 300 seconds at the end of each iteration. In this PR it waits 300 seconds after each iteration unless override_night is set and a debugging flag is not set.
I tested this by running with override_night set and with it unset and the proper behavior is observed in each instance. This is small enough that I will self merge.

Don't wait for new data when override_night set in daily_proc_manager

---

py/desispec/ccdcalib.py

This addresses issue #1867 . If no calibration or non-calibration zeros were present then it was assigned to an empty array (`np.array([])`), which was made type 'float'. Then subsequent appending, etc. always promoted the other integers to floats.
This PR fixes the root cause of the problem and then also adds several other type conversions as a belt and suspenders solution. 
I tested this on the night of 20210629 that crashed in the ticket and it now works.

Ensure expids are ints in ccdcalib

---

py/desispec/workflow/desi_proc_funcs.py

stdstar jobs used to get a time limit of `(8+2*nexp)*timefactor` minutes, which on cori-knl for a single exposure was (8+2*1)*3 = 30 minutes.  PR #1820 contributed memory and speed improvements to stdstar fitting, with the test cases there taking 9-10 minutes, so the job timelimit was reduced to `(5+1*nexp)*timefactor` i.e. 18 minutes on cori-knl, thinking that a factor of 2 overhead was sufficient.
Apparently that was too aggressive and stdstar jobs are timing out on stdstars again, e.g. multiple Himalayas sv3 bright and backup tiles on 20210529, though not obviously for bad I/O reasons.
This PR restores the `(8+2*nexp)*timefactor` limit.
Full disclosure: I have not tested whether this fixes all cases of timeouts or what is different about the PR #1820 test cases and these, but it at …

give more time to stdstar jobs

---

py/desispec/frame.py
py/desispec/io/frame.py
py/desispec/scripts/stdstars.py
py/desispec/test/test_binscripts.py

This PR fixes #1871 where an indexing bug lead to standard star crashes.  It happened to be on a backup tile with Gaia standards, but the actual bug was not directly related to that.  It was a problem with a pre-filter that the standard stars have valid photometry and fragility with multiple ways of filtering: slicing frames, tracking lists of indices, tracking lists of booleans.  This update simplifies the tracking by dropping the independent (and inconsistent in this case) tracking of indices, treating slicing frames as the primary method.  It does still keep the `starfibers` array which is redundant with `frame.fibermap['FIBER']` but convenient for logging and convenient since there are N>1 frames but they all have the same fiber selections (which is explicitly verified).
Command that …

fix stdstar indexing crash

---

py/desispec/emlinefit.py

This PR corrects a bug in `emlinefit.emlines_gaussfit()` for the equivalent width measurement.
It fixes https://github.com/desihub/desispec/issues/1876.

bugfix: correct (1+z) factor in equivalent width

---

py/desispec/calibfinder.py

This fixes #1880 by falling back to DESI_SPECTRO_CALIB in cases where no suitable darks are found in DESI_SPECTRO_DARK.

fix fallback to DESI_SPECTRO_CALIB if DESI_SPECTRO_DARK is set and no suitable files found

---

py/desispec/scripts/fluxcalibration.py
py/desispec/scripts/proc.py
py/desispec/scripts/stdstars.py
py/desispec/workflow/desi_proc_funcs.py

This PR adds one option to desi_proc (--no-barycentric-correction) and fixes issues/bugs when running with option '--apply-sky-throughput-correction'.
The latter option was considered only when writing the sframe files when it is also applicable for the standard star fit, the flux calibration code, and when writing the cframe files (any time we subtract the sky). 
Both changes are need to run the current version of the pixel-level simulations. They have no impact on real data processing (we don't use the options).

Corrections for sims

---

bin/copyprod
py/desispec/io/util.py
py/desispec/scripts/humidity_corrected_fiberflat.py
py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/test/test_io.py

This PR fixes #1873 by adding `desispec.io.util.relsymlink(src, dst)` which creates a relative symlink from `dst` -> `src`, while treating $DESI_ROOT and $DESI_ROOT_READONLY as the same root.  i.e. this symlink in the daily prod:
```
lrwxrwxrwx 1 desi desi 123 Oct 26 21:27 exposures/20221025/00150146/fiberflatexp-r0-00150146.fits.gz -> ../../../../../../../../../../dvs_ro/cfs/cdirs/desi/spectro/redux/daily/calibnight/20221025/fiberflatnight-r0-20221025.fits
```
becomes this link in the test prod `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/symlinks`:
```
lrwxrwxrwx 1 sjbailey desi 60 Oct 27 20:19 exposures/20221025/00150146/fiberflatexp-r0-00150146.fits.gz -> ../../../calibnight/20221025/fiberflatnight-r0-20221025.fits
```
i.e. the symlinks become portable if the directories are …

fix relative symlinks to $DESI_ROOT_READONLY files

---

py/desispec/io/util.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/test/test_io.py

This PR fixes #1890, i.e. a bug introduced with relative symlinks in PR #1888 that broke the symlinks creation for multi-exposure stdstar fitting.  This PR adds two redundant fixes:
1. `relsymlink(src, dst)` now accepts relative paths for `src` instead of requiring two absolute paths and deriving the relative path.  If `src` is a relative path, it is relative to `dirname(dst)`, not relative to the current directory (same behavior as `os.path.symlink`).  I added tests to confirm this behavior.
2. `desi_proc_joint_fit` no longer derives the relative path, leaving it to `relsymlink` instead.  In this case `desi_proc_joint_fit` was deriving the correct path anyway so fix (1) would have been sufficient, but it has the possible future fragility of /dvs_ro/cfs vs. /global/cfs, so I also updated …

bugfix: stdstars and relsymlink

---

bin/desi_daily_proc_manager
bin/desi_run_night
py/desispec/scripts/daily_processing.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/submit_night.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py

Currently the choice of specter vs gpu_specter when running desi_run_night is dependent on system_name, such that gpu_specter is only used for system_name == 'perlmutter-gpu'. 
This PR makes gpu_specter the default for any value of system_name with desi_run_night. Specter is only used if --use-specter is specified. GPUs will be used with gpu_specter if system_name == 'perlmutter-gpu'.
I have checked that the slurm files are as expected by running desi_run_night --dry-run-level 1 ... on cori and perlmutter.
@sbailey and @akremin please review for style and unintended consequences. 
<s>
We can either (1) merge this PR as is or (2) change the default to gpu_specter by using --use-specter, instead, since eventually gpu_specter will be the default. 
</s>

add --use-specter to desi_run_night

---

bin/copyprod

This PR adds a `copyprod --tiles ...` option to filter a night by specific tiles.  I find that easier than creating a separate file of NIGHT EXPIDs to include via the `--explist` option (which is more flexible, but requires more steps for most of the cases where I'm making a mini prod for testing).

copyprod --tiles option

---

py/desispec/scripts/stdstars.py

This PR fixes an indexing bug in fibermap when there is a mix of LEGACY and GAIA stars among the standard stars.
The down selection of the LEGACY stars was not considered for the fibermap (only for starfibers  and the frames).
This fixes issue #1892. But I wouldn't mind a second pair of eyes on this! (because we have made several indexing mistakes for the selection of std stars in the past).

fix indexing bug in fibermap when mix of LEGACY and GAIA.

---

py/desispec/scripts/procexp.py
py/desispec/sky.py

This PR fixes a bug introduced recently in PR #1886 where the amplitude correction was applied twice when cosmic_nsig>0 .
The changes are :
- modify and subtract a copy of the skymodel.flux array in subtract_sky
- do not run twice the sky subtraction when flagging cosmic rays because this is not necessary. this was justified when the throughput corrections were computed during the sky subtraction but it is not the case any more.
I will rerun the tiles of PR #1886 to verify this does not cause new problems.

Sky subtraction bug fix

---

py/desispec/gpu.py
py/desispec/scripts/proc_tilenight.py

This PR fixes the GPU memory and rank:GPU allocation problems reported in issue #1897, using the methods suggested by @dmargala in that issue.  This PR provides a new `desispec.gpu` module with helper functions
* `is_gpu_available()`: standardizing if a GPU+cupy+numba.cuda is available (will be used more in a future PR that will remove the other places we do the same sorts of calculations)
* `free_gpu_memory()`: free unused GPU memory if possible, no-op if we're not using GPUs
* `redistribute_gpu_ranks(comm)`: redistribute MPI rank:GPU mapping, handling case of `comm=None` and the case of no GPUs.
Testing was bogged down by:
* typos resulting in NameError and ValueError exceptions that were getting swallowed by stdout buffering before the job was killed
* a surprising feature/bug where …

GPU memory and rank allocation

---

py/desispec/workflow/desi_proc_funcs.py

nightlyflat jobs were getting a runtime limit of 5 minutes, which is borderline for KNL on bad I/O days.  Most job types get an additional timefactor scaling (3 in the case of KNL) to acknowledge that some systems are faster than others.  Previously nightlyflat and arc jobs were excluded from this.  For arcs that was to avoid ridiculously long job timelimit requests, while just accepting occasional timeouts and resubmissions.  It's unclear why nightlyflat was also previously excluded.
This PR re-enables timefactor scaling for nightlyflat jobs, which results in 15 minute requests on KNL, which is still short-enough and a comfortable overhead to the typical 5 minutes runtime.  We may not use KNL for productions ever again, but a few test jobs are still using it for some comparisons and this …

apply timefactor scaling to nightlyflat too

---

bin/desi_compute_pixel_flatfield
bin/desi_interpolate_fiber_psf
bin/plot_fiber_traces
py/desispec/preproc.py
py/desispec/scripts/preproc.py

In this PR the preprocessing code looks for the keyword COSMICS_C2 in the calibration yaml file config if the argument is not set.
This is needed to process the new MOSAIC CCD (500 micron-tick device).

Cosmic ray rejection parameter in yaml file

---

py/desispec/io/fibermap.py
py/desispec/test/test_fibermap.py

This PR implements #1723 by having assemble_fibermap standardize any missing SURVEY, FAPRGRM, FAFLAVOR keywords from early fiberassign files.  The added utility function `update_survey_keywords` could also be used to update fiberassign files in svn if/when we're ready to do that.
Unit tests cover the known cases; example `assemble_fibermap` outputs in `/global/cfs/cdirs/desi/users/sjbailey/dev/faprogram/test/update` (this PR) and `main/` (current main branch).
Current main, with missing keywords:
```
[login34 test] fitsheader -e FIBERMAP -k TILEID -k SURVEY -k FAPRGRM -k FAFLAVOR main/fibermap*.fits
WARNING: main/fibermap-00050988.fits (HDU FIBERMAP): Keyword SURVEY not found. [astropy.io.fits.scripts.fitsheader]
WARNING: main/fibermap-00050988.fits (HDU FIBERMAP): Keyword FAPRGRM not …
```

add update_survey_keywords to standardize early FA headers

---

bin/desi_run_night
py/desispec/fluxcalibration.py
py/desispec/gpu.py
py/desispec/scripts/extract.py
py/desispec/scripts/fluxcalibration.py
py/desispec/scripts/humidity_corrected_fiberflat.py
py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/proc_tilenight.py
py/desispec/scripts/stdstars.py
py/desispec/scripts/submit_night.py
py/desispec/scripts/tile_redshifts.py
py/desispec/test/test_extract.py
py/desispec/test/test_gpu.py
py/desispec/workflow/batch.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py
py/desispec/workflow/utils.py
requirements.txt

This PR contains a number of fixes in preparation for running productions on Perlmutter:
* Standardize GPU/CPU defaults following suggestions in issue #1799.  Basically GPU usage is now opt-out: if the code can find a GPU it will use it unless `--no-gpu` (single script) or by setting $DESI_NO_GPU (global opt-out).  This replaces `--use-gpu` (stdstars) and `--gpuextract` (extractions).
* gpu_specter is default everywhere, instead of `--use-specter` at some levels and `--gpuspecter` at others.
* `--system-name` is used by pipeline wrappers to know what kinds of batch jobs to generate and where to send them, but once the code wakes up it uses whatever resources it finds
* On Perlmutter, not specifying `--system-name` automatically picks between CPU and GPU for each job type, and for the jobs …

GPU vs. CPU production running

---

py/desispec/coaddition.py
py/desispec/scripts/coadd_spectra.py
py/desispec/workflow/desi_proc_funcs.py

This PR moves "ownership" of the coadd cosmics_nsig=4.0 default from individual scripts into the `desispec.coaddition.coadd()` function itself.  Previously `desispec.scripts.coadd_spectra` had an argparse default of 4.0, while `desispec.scripts.group_spectra` used the different default (0.0) from `desispec.coaddition.coadd`, resulting in coaddition differences from `desi_group_spectra ... --coaddfile coadd.fits` vs. `desi_coadd_specra ... --outfile coadd.fits`.
This PR is into the desi_zproc branch (not main) because it is needed for final verification testing that that branch produces the same answer with refactored script workflow.
Tested with:
```
$> desi_group_spectra \
--inframes \
exposures/20201215/00067972/cframe-z0-00067972.fits.gz \ …
```

coadd cosmics_nsig default cleanup

---

bin/desi_edit_exposure_table
bin/desi_job_graph
py/desispec/fluxcalibration.py
py/desispec/scripts/editexptable.py
py/desispec/scripts/fluxcalibration.py
py/desispec/scripts/proc_tilenight.py

This is a logging cosmetic PR to add {camera} throughout the flux calibration logging so that if there is a warning or error log amidst N>>1 MPI ranks, you can tell which camera it came from.  This will (or would have...) been useful for Himalayas log debugging.
It also adds some checks in `desi_edit_exposure_tables` to print warnings if the requested exposures don't actually exist in the exposure table for the given night.  Since it can be useful to specify ranges of exposures where there might be a gap, it is only fatal if none of the exposures match; otherwise it prints which ones don't match but proceeds anyway.
I've tested this with an end-to-end minitest of a single tile, though that didn't generate error/warning log message for every case I edited, so I'll double check syntax in …

fluxcalib logging with camera

---

bin/desi_run_night
py/desispec/scripts/proc_tilenight.py
py/desispec/workflow/desi_proc_funcs.py

This PR fixes a tilenight laststep+badcamword bug causing at least some of the problems reported in issue #1911 .  The core problem was that it was deriving the camword to use for stdstars based upon all exposures for a tile before filtering on laststep, meaning that a laststep=ignore entry with all cameras could trigger it to try to fit stdstars on spectrographs that were otherwise excluded on all other good exposures.
This adds a `desi_proc_tilenight --laststeps ...` option with a default of "all" which matches what we use by default for productions, but I did **not** add the plumbing through 6 function calls spread across 3 files to connect the `desi_run_night --laststeps ...` option to the eventual `desi_proc_tilenight` call in a batch script.  That might be easier to address as part …

tilenight options and bug fixes

---

py/desispec/io/util.py
py/desispec/scripts/proc_tilenight.py
py/desispec/test/test_io.py
py/desispec/workflow/procfuncs.py

This PR fixes a bug discovered on 20221121, where z7 was bad but b7 and r7 were still good.  The stdstar jobs were excluding sp7, but the poststdstar jobs were still trying to include b7 and r7 and failing since stdstar-7-*.fits didn't exist.  It's unclear to me whether this is a new bug, or whether in the past we flagged all cameras of a spectrograph as bad if any of them were bad since we knew we couldn't get to redshifts for that spectrograph anyway (I have some vague memory of that hack...)
This PR fixes it by checking the PROCCAMWORD of each poststdstar job and making sure that it doesn't exceed the cameras included in its corresponding stdstar job.
I have not tested whether we have a similar bug in use-tilenight, but since that follows a different logic flow it may not.  This is …

poststd can't fit more cams than stdstar did

---

py/desispec/night_qa.py
py/desispec/tile_qa_plot.py

This PR is a "cosmetic" PR for the tile_qa plots: the (red) alerts message is now printed on several lines.
It fixes this kind of cases, where the alerts message is too long, hence prevents to see anything:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/83235/20221119/tile-qa-83235-thru20221119.png
With this PR, it now looks like this:
@schlafly : better now? any suggestion?
ps: I also sneaked in a minor typo-correction in the title of the sframesky plots (`TILED` -> `TILEID`).

Qa plot display

---

py/desispec/scripts/zproc.py
py/desispec/test/test_zproc.py

This PR fixes a bug in `desispec.scripts.zproc.distribute_ranks_to_blocks` where it was creating more blocks (i.e. MPI subcommunicators) than requested.  e.g.
```python
from desispec.scripts.zproc import distribute_ranks_to_blocks
nblocks, block_size, block_rank, block_num = distribute_ranks_to_blocks(nblocks=3, rank=63, size=64)
print(f"{nblocks=} {block_size=} {block_rank=} {block_num=}")
main   --> nblocks=3 block_size=21 block_rank=0 block_num=3
thisPR --> nblocks=3 block_size=21 block_rank=20 block_num=2
```
note that the main returned `block_num=3` is too big; it should have been 0, 1, or 2 based upon the requested number of `nblocks=3`.  The consequence was that the GPU node (size=64) zproc script was creating 4 blocks to process 3 afterburners, and there is a race condition with …

bugfix in distribute_ranks_to_blocks

---

py/desispec/workflow/redshifts.py

Currently desi_run_night fails at line 368 in workflow/redshifts.py when an exposure table that was read does not have a BADCAMWORD column. These changes make desi_run_night backwards compatible with an exposure table that is missing a column named BADCAMWORD by adding a blank one of the same name just after it has been read.
The latest commit to this branch has been tested as the desi user with 
```
SPECPROD=daily
desi_create_exposure_tables -n 20221121
desi_run_night -n 20221121 --use-tilenight --z-submit-types cumulative --all-tiles --dry-run-level 1
```
and no longer fails.
@sbailey please review and merge if it looks good.

Allow desi_run_night to read exposure tables missing BADCAMWORD column

---

py/desispec/calibfinder.py

This is a minor update to the calibfinder logging:
* log the detector, ccd config, ccd timing parameters that it is trying to match
* if falling back to desi_spectro_calib dark, log which CCD (useful when there are multiple CCDs processed and logged in parallel)
I tested these while debugging what became issue #1920, so intend to self-merge.

more calibfinder logging

---

bin/desi_tsnr_afterburner

This PR has some small updates for running `desi_tsnr_afterburner` on Perlmutter:
* `--mpi` mode uses `--nproc` (default 1 = no multiprocessing) instead of overriding nproc and forcing it to use multiprocessing, since MPI+multiprocessing doesn't work reliably on Perlmutter
* minor efficiency updates using fitsio instead of astropy.io.fits
With this branch I was able to process tsnr for Himalayas in 3 hours (!) using
```
time srun -N 4 -n 256 -c 4 desi_tsnr_afterburner --mpi --recompute --nproc 1 \
--aux /global/cfs/cdirs/desi/survey/observations/SV1/sv1-tiles.fits \
--gfa-proc-dir /global/cfs/cdirs/desi/survey/GFA/ \
-o exposures-$SPECPROD.fits -t tiles-$SPECPROD.fits &> tsnr.log
```
Note that this didn't include `--compute-sky-mags` which would take even longer.  It did include …

tsnr afterburner MPI+MP; fitsio

---

py/desispec/night_qa.py

This PR highlights IVAR=0 pixels in the sframesky-NIGHT.pdf plots in the the night qa.
I picked the yellow color, so that it does not attract too much the eye.
For instance for EXPID=154146 on 20221121, where b8 is flagged:
Current:
With this PR:
I am wondering if I should go for something a bit more fancier, with rather overplotting with transparency the yellow thing, so that one would still see the masked features (here b8), at the risk of losing in readibility...
any suggestion is welcome!

create_sframesky_pdf(): display IVAR=0 pixels in yellow

---

py/desispec/preproc.py

This PR fixes a problem in `desispec.preproc.compute_background_between_fiber_blocks` where a row with a completely negative background resulted in the median of an empty array, causing the background model to have NaNs, which then broke things downstream like traceshift fitting.
Example of this case occurring:
```
desi_preproc -i /global/cfs/cdirs/desi/spectro/data/20221126/00154927/desi-00154927.fits.fz \
--cameras b4 --bkgsub-for-science   --model-variance \
--bias /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20221126/biasnight-b4-20221126.fits.gz \
-o ./preproc-b4-00154927.fits.gz
```
In current main, this results in NaN for row 3247 from columns 453-836 (spanning two bundles):
in this PR these the bkg is interpolated and subtracted without artifacts:
I think the original …

NaN fix for negative CCD bkg

---

py/desispec/preproc.py

Currently whenever a dark file is specified by the `--dark` option the setting will be overruled by entries from DESI_SPECTRO_CALIB or DESI_SPECTRO_DARK.
This fix should allow to specify a specific dark used in the preprocessing.

check for type of the dark option in preprocessing

---

bin/desi_run_night
py/desispec/scripts/submit_night.py

Small PR to add a flag `--do-cte-flat` to `desi_run_night` that tells it to submit a 1s flat as part of the processing for that night. These are used in the daily operations to help identify CTE issues in the cameras. This is always done in `desi_daily_proc_manager`, which is the typical script used to process data for the daily pipeline, but that script lacks tilenight logic and therefore is highly inefficient on perlmutter. This PR lets `desi_run_night` be used for daily operations tasks on perlmutter, assuming all data for a night are available in an exposure table generated with `desi_create_exposure_tables` and this new flag is used.
Results of tests can be found at:  `/global/cfs/cdirs/desi/users/kremin/PRs/runnight_cte`
I tested this with two nights, 20221114 and 20221214, using …

Add flag to submit a 1s flat in desi_run_night

---

py/desispec/night_qa.py

This PR adds, for the night_qa dark plots, the median profiles for each pair of amplifiers along both directions.
It is prompted by this slack discussion about P5 in 20221209: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1670887277610869 (and previous messages in the channel).
Credits to @julienguy for this diagnosis, and the suggestion to implement that.
The new plots look like this (here for P5 in 20221209):
As said in the slack discussion, in this 5min dark, the r5 image looks nice (though it has been shown that the it does not for 1200s morning dark of that night).
Note also that z5 has a small offset for the leftmost amplifiers in the horizontal profiles, which may be consistent with @schlafly s report that some offset can be seen in the sframesky images.
Besides, I notice …

Night qa : create_dark_pdf(): median profile side panels

---

py/desispec/fiberbitmasking.py

Do not set ivar=0 to UNASSIGNED fibers by default because they might be useful for some analysis.
This addresses part of desisurveyops issue desihub/desisurveyops#76 .
(The other part being the counterintuitive default values of redrock redshifts for spectra with zero valid data)

do not set ivar=0 to UNASSIGNED fibers by default

---

py/desispec/tile_qa_plot.py

[re-opening a PR requesting to merge in "daily" this time]
This PR addresses https://github.com/desihub/desispec/issues/1951.
It is a speed-up in the desispec.tile_qa_plot.get_expids_efftimes() function.
Instead of opening both all the spectra and the cframe files, this PR only opens the spectra files.
The output should be identical.
I verified this with running the function on ~100 random exposures of the himalayas redux.
For the problematic case (TILEID=80617 in himalayas), it reduces the computation time by 50% (or more, it depends).

Tile_qa_plot: get_expids_efftimes(): speed-up, with only reading spectra files

---

.github/workflows/python-package.yml
requirements.txt

This PR updates desispec to use desimodel/0.18.0 for testing.  This version of desimodel includes an endianness fix for compatibility with scipy/1.10.0 (see desihub/desimodel#164).  This is the underlying cause of the test failures in recent PRs (e.g. #1950, which temporarily fixed it by pinning to an older scipy; also #1954 and #1955).
I plan to self-merge as long as tests do indeed use scipy/1.10.0 and pass.  After this PR I'll also merge daily -> main to pickup this and other recent updates to daily.

use desimodel/0.18.0 for testing

---

bin/desi_run_night
py/desispec/scripts/submit_night.py

This PR adds support to desi_run_night to submit cumulative redshifts only for tiles for which the current night is the last night that they were observed.  This allows them to be tracked in the processing tables (see issue #1952) while not submitting cumulative redshift jobs for nights earlier than the LASTNIGHT for each tile.
I did *not* implement an option to override this and submit cumulative redshifts for every tile, even if they have future observations (current behavior).  The code is already complex from supporting tilenight, non-tilenight, productions, and daily-like "is this the last exposure for this tile or the end of the night?" style logic, and I didn't want to add additional options that we may never use and then feel obligated to support those in any future refactors.  If …

submit cumulative redshifts only for lastnight of each tile

---

bin/desi_run_night
py/desispec/scripts/submit_night.py

This solves issue #1943 in which tiles observed after the Year 1 cutoff date were being processed as a completed tile in himalayas because they had subsequent observations that got them to full depth during Y2. This PR addresses the issue by adding a new command line argument, `--complete-tiles-thrunight`, to `desi_run_night` to define the last night through which a tile could be observed and be considered complete. 
I have also added some additional logging to the completed_tiles determination to print out the tiles it has selected as complete and well as counting the number of tiles it selected. These are used below to show that the code is working as expected. 
**Note**: This doesn't actually determine whether a tile reached full depth before the date set in `complete_tiles_thrunight`. …

Allow Cutoff Date for Tile Completion during Reprocessing

---

py/desispec/tile_qa_plot.py

This small PR fixes a (possible corner case?) where one camera is not present in the `spectra` file.
In that case, I set TSNR2=0 for that camera, in a consistent manner with what s done in `exposure_qa.py`:
https://github.com/desihub/desispec/blob/b9a681a0b983a6a4e1cc9aa99ff9735ef4267d86/py/desispec/exposure_qa.py#L323
I encountered that while re-running the tile-qa for all main tiles.
I don't know if this only happens for some early main tiles processed with daily, or if it can still happen.
But as far as I know, it didn t happen so far, so that s probably the former.
Example with the current main/daily for a 20210616 tile:
```
>>> from desispec.tile_qa_plot import get_expids_efftimes
>>> d = get_expids_efftimes("/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/1892/20210616/ti …
```

Tile_qa_plot: get_expids_efftimes(): handle missing camera (set TSNR2=0)

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR adds the 1200s morning dark (temporary) processing + plot to the night_qa.
It is a follow-up of this PR https://github.com/desihub/desispec/pull/1945 (also see this slack thread: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1670887277610869).
The code looks for the latest 1200s dark image of the night.
As the 1200s morning dark are not currently processed by the daily pipeline, this PR script does the processing on-the-fly in a temporary folder, so that night_qa can generate the plots.
On a cori-haswell interactive node, it runs in 2min, so it should not make the `desi_night_qa` script too long to run.
The call to `desi_preproc` is here:
https://github.com/desihub/desispec/blob/b584b5556e66c2ffaf605ae4f1b2e97ada3112b0/py/desispec/night_qa.py#L481-L488
@julienguy suggested: …

Night qa: add 1200s morning dark

---

bin/copyprod

This PR fixes #1961, where copyprod would crash when the daily prod was the input, due to early commissioning (CMX) nights that don't have exposure tables (and never will).  This PR prints a warning that it is skipping known early CMX nights, and will error+exit if it encounters a missing exposure table on a later night (which really should exist).  I'd also be fine with not printing the CMX warning at all.
This should only create warning messages if desi/spectro/redux/daily is the input production; all other productions shouldn't have those nights in the first place and won't print warning messages.

copyprod when missing exposure tables

---

bin/desi_job_graph
py/desispec/io/meta.py
py/desispec/pixgroup.py
py/desispec/scripts/group_spectra.py
py/desispec/scripts/healpix_redshifts.py
py/desispec/scripts/tile_redshifts.py
py/desispec/scripts/zproc.py
py/desispec/scripts/zprocdashboard.py
py/desispec/test/test_io.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py
py/desispec/workflow/redshifts.py
py/desispec/zmtl.py

This PR adds support for processing healpix redshifts with the new zproc infrastructure:
* Update desi_zproc / desispec.scripts.zproc to support healpix redshifts while re-using as much of the tile-based redshift code as possible.  Multiple healpix can be processed in a single job similar to multiple petals of a single tile-based redshift.
* Update desi_healpix_redshifts / desispec.scripts.healpix_redshifts to submit multiple healpix-redshift jobs with a `--bundle-healpix` option to control how many healpix should be processed in a single job.
* Add findfile(healpix=...) option for better symmetry with tile-based files instead of using groupname option for both healpix number and cumulative,pernight,etc.  It still supports groupname=healpix_number for backwards compatibility.
* Naming …

healpix redshifts added to zproc

---

py/desispec/scripts/zproc.py

Redrock+GPU used to run out of memory on input files with >1k targets (e.g. large healpix), which we had worked around in zproc by checking the number of targets and falling back to CPU-only on big inputs.  desihub/redrock#211 fixed the problem, so this PR removes the ntargets check from zproc.  I tested by rerunning himalayas sv3 dark healpix 10152 with 2192 targets and confirming that zproc ran redrock with GPU and that it completed fine.
This PR also fixes a bug where `zproc --batch ...` was accidentally forcing `--no-gpu` unless `--mpi` was also specified.

re-allow redrock+GPU on large inputs

---

py/desispec/workflow/desi_proc_funcs.py

Trivial PR to change the timing for zproc jobs on Cori. Right now it is set to 10 nodes, which are throttled back to 5 nodes in the realtime, and 10 minutes. 10 minutes isn’t enough time for realtime queue jobs using 5 nodes. Empirical testing showed roughly 12 minute job times on 5 nodes, so we’re being very conservative here with 20 minutes. Rather than using 10 nodes in the regular queue, we will set all queue types to be 5 nodes.

Change zproc on Cori to 5 nodes and 20 mins

---

py/desispec/workflow/desi_proc_funcs.py

Another trivial PR to change the timing for `desi_zproc` jobs on Cori. Right now it is set to 5 nodes for 20 minutes. After further empirical testing I've found that we can accomplish the same results with 2 nodes in roughly 17 minute. To be conservative, I've set it to 30 minute to account for jobs with more than one exposure and for I/O slowdowns.
Timing information for a single cumulative tile with a single exposure:
```
NODES   TIME
1      ~27 min
2      ~17 min
5      ~11 min
```

Change zproc on Cori to 2 nodes and 30 mins

---

py/desispec/workflow/desi_proc_funcs.py

In the pre-iron "i1" test production, the only job timeouts were from the flats.  This is due to fluctuations in the extraction runtime, with a tail taking us up to the current job time limit (12 minutes on perlmutter GPU).  Since a single flat failure blocks the entire night from processing, I'm increasing the time to 20 minutes in the hopes that they will rarely timeout.
Detail: determine_resources is normalized to cori-haswell, so 40 minutes becomes 40//2 = 20 minutes on perlmutter after it accounts for the 2x timing scale factor.
```
In [9]: determine_resources(30, "FLAT", queue='regular', system_name="cori-haswell")[2]
Out[9]: 40.0
In [10]: determine_resources(30, "FLAT", queue='regular', system_name="perlmutter-gpu")[2]
Out[10]: 20.0
```
(upper plot is extraction time; lower is …

increase flat job time limit

---

doc/changes.rst
py/desispec/cosmics.py
py/desispec/fluxcalibration.py
py/desispec/mgii_afterburner.py
py/desispec/preproc.py
py/desispec/scripts/fibercrosstalk.py

Unit tests have myriad deprecation warnings of the sort:
```
/home/runner/work/desispec/desispec/py/desispec/preproc.py:14: DeprecationWarning: 
Please use `median_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` 
namespace is deprecated.
from scipy.ndimage.filters import median_filter
```
https://github.com/desihub/desispec/actions/runs/3919211294/jobs/6700069463#step:5:65
The `scipy.ndimage.filters` namespace was deprecated as far back as `scipy/0.19.1` (I think), so I didn't bother to support both new and old versions.

remove imports from deprecated scipy.ndimage.filters namespace

---

py/desispec/scripts/procdashboard.py

Short PR that adds some information about the calibnight jobs into the exposure dashboard. I didn't change the columns, so the `ccdcalib` job is uninformative (like the `zero` and `dark` jobs currently are), but the `psfnight` and `nightlyflat` jobs now show the number of files.
After this is merged I will build upon it to include up-to-date queue information on the jobs, which will make the inclusion of the `ccdcalib` row slightly more useful/meaningful.
I have run a test in `/global/cfs/cdirs/desi/users/kremin/PRs/dash_calibnights/dashboard`. A snapshot of a single nights dashboard is below showing the newly included `ccdcalib`, `psfnight`, and `nightlyflat` rows properly populated.

Add calibnight jobs to exposure dashboard

---

bin/desi_update_tiles_specstatus
py/desispec/specstatus.py
py/desispec/test/test_specstatus.py

This PR changes the behavior of desi_update_tiles_specstatus to completely update the tiles-specstatus.ecsv file rather than only updating tiles with updated LASTNIGHT.
I have changed the previous --all argument to be the default, and replaced it with an --only argument to revert to the original behavior.
I also added a --clear-qa option that sets the QA = None.  This option can only be used when --tileid is specified (we don't want to accidentally allow the whole QA column to be blasted).  This is better than our current approach of manually editing the file to clear QA status after reprocessing.
I updated the tests to conform to the new interface & defaults (basically moving update_all = True to update_only = False).
I went through somewhat laboriously and tried to make sure that all of …

Completely sync tiles-specstatus

---

py/desispec/io/util.py
py/desispec/workflow/procfuncs.py

This resolves Issue #1983 in which joint fit calibration jobs were being assigned the cameras (camword) of the first exposure in the set rather than the combination of all exposures. The assumption held in earlier productions because all exposures are typically taken with the same set of cameras available. However, we've recently flagged cameras that fail psf calibrations, which has increased the number of exposures that differ from the rest of the set. This was also an issue in himalayas, but was not caught before the start of iron.
This PR changes the code to use all exposures to generate the correct camword. I have run checks to ensure that for the 6 nights in the github issue the new code now produces the correct camword. I have also verified that for all other nights the generated …

Define joint cal job camwords with all input exposures

---

bin/desi_queue_status

This PR adds a new script desi_queue_status for summarizing jobs in the queue and recent history; this is useful for monitoring during a production run.  Currently it tracks SUCCESS, FAILED, and TIMEOUT jobs, but not CANCELLED (e.g. cancelled due to a dependency failing).  It could be better, but it is useful as-is and I'd like to get it into the next tag, and then continue improvements in future PRs (like adding CANCELLED once I figure out how to get sacct to report those too without already knowing the job IDs).
Example output, running as sjbailey but checking the desi queue for jobs from yesterday+today (default is today only, but we haven't run much today to be interesting):
```
[login08 desispec] desi_queue_status -u desi -S 2023-01-26
Fri Jan 27 15:50:36 2023
0 jobs running, 0 …
```

desi_queue_status

---

py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/redshifts.py

This PR turns off the hardcoding of $DESI_ROOT_READONLY in the batch scripts.  If it is set in the environment when the script is submitted, it will still be used, but we no longer force a specific path in the script itself.  Given the recent problems with /dvs_ro/cfs/cdirs/desi on Perlmutter, this gives us the flexibility to try alternate paths or disable using it at the time of submission without requiring another code change after this one.
I just commented out the code instead of completely removing it since the situation with NERSC I/O is still in flux.
I verified this with `desi_run_night -n 20220129 --z-submit-types pernight --dry-run-level 1` and verifying that none of the scripts set DESI_ROOT_READONLY, and they differ from the 0.56.2 scripts only by that line.

don't hardcode DESI_ROOT_READONLY in batch script

---

py/desispec/io/sky.py
py/desispec/scripts/sky.py
py/desispec/sky.py

Hi, 
This is a proposal patch to to be able to compute custom skymodels with desi_compute_sky while either
* removing some targetids from being treated as sky
* or completely override the sky target list
without having overwrite the OBJTYPE in the fibermap.
It adds a couple of options to desi_compute_sky --override_sky_targetids and --exclude-sky-targetids
(see #2000  )
It is helpful for custom coadds while removing sky fibers contaminated by interstellar emission lines for example.

Allow to override the targetids of sky fibers when computing sky models

---

py/desispec/night_qa.py

This PR adds a special color-coding for calibration files done in a different day (likely in the morning).
(prompted by here: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1677616742851819)
The approach is to read the timestamp, and compare its YYYYMMDD vs. the considered night.
It assumes that the calibrations are done either before observations (so on the same "night"), or in the morning (so on a different "night").
Example here: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v19/nightqa-20230227.html
(updated at 4:09pm on Tue. Feb., 28, to account for the https://github.com/desihub/desispec/pull/2011/commits/2bbc3997ef651f131f4e381f4477d5ba0f29782d commit)
@schlafly @akremin : any suggestion is welcome!

Nightqa: flag calibration files done on a different day

---

doc/conf.py

Recent PRs are failing documentation build tests because of missing pytz, which is apparently new.  This PR starts with a minor formatting change to try to reproduce the problem independent of the code changes in other PRs, before I proceed with attempting to fix it.  If I don't succeed quickly, I'll call for more expert help, and apologies in advance for any github email churn from attempts on this.

fix documentation tests on github

---

bin/plot_spectra

This PR is a bug fix for plot_spectra for the case when the requested targetid is at index 0 in the file.  Due to a "list of booleans" for "list of indices" bug, current main claims that target isn't in the file.
e.g. with main:
```
$> cd $DESI_ROOT/spectro/redux/fuji/tiles/cumulative/325/20210406
$> plot_spectra -i coadd-0-325-thru20210406.fits -t 39633118721738882
INFO:spectra.py:291:read_spectra: iotime 1.873 sec to read coadd-0-325-thru20210406.fits at 2023-03-08T13:27:31.083235
TARGETID=39633118721738882
WARNING:plot_spectra:137:<module>: TARGETID 39633118721738882 not in spectra
ERROR:plot_spectra:176:<module>: no data to show
```
with this branch
```
INFO:spectra.py:291:read_spectra: iotime 1.061 sec to read coadd-0-325-thru20210406.fits at 2023-03-08T13:28:37.332746 …
```

fix plot_spectra targetid selection

---

py/desispec/scripts/submit_night.py

There is a bug in `desi_run_night` when wanting to process a `LASTSTEP=skysub` exposure that has no `LASTSTEP=all` observations. This is in the new logic that only submits cumulative redshift jobs for tiles in which the night being submitted is the last night the tile was observed.
The behavior wasn't seen in Iron because we didn't process skysub exposures in Iron.
Directory `/global/cfs/cdirs/desi/users/kremin/PRs/runnight_maxnight` has log outputs when running `desi_run_night` on night 20230309. The main branch crashes (`daily_20230309-main.log`), while this branch (`daily_20230309-runnight_maxnight.log`) succeeds.

Don't crash submit_night if no laststep=all exposures for a tile

---

py/desispec/scripts/proc_tilenight.py
py/desispec/workflow/desi_proc_funcs.py

Fixes #1992 by considering the intersection of current camwords for each step with those of the args.cameras option, effectively making the argument to --cameras the superset for all steps resulting from the desi_proc_tilenight command.
@sbailey please test and/or provide a test case to try. Thanks.

consider the --cameras option in desi_proc_tilenight 

---

py/desispec/scripts/proc_tilenight.py
py/desispec/scripts/submit_night.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/procfuncs.py

Fixes #2007 by propagating the --laststeps option through to tilenight. I have tested with:
```
% desi_run_night -n 20230210 --z-submit-types=cumulative --laststeps="all,skysub,fluxcal" --all-tiles --dry-run-level=1
```
and I obtain the correct flags in the tilenight batch script:
```
% grep desi_proc_tilenight /global/cfs/cdirs/desi/users/malvarez/spectro/redux/tilenight-skysub/run/scripts/night/20230210/tilenight-20230210-5627.slurm  | grep -v echo
srun -N 1 -n 64 -c 2 --cpu-bind=cores desi_mps_wrapper desi_proc_tilenight -n 20230210 -t 5627 --mpi --mpistdstars --laststeps="all,skysub,fluxcal" --timingfile /global/cfs/cdirs/desi/users/malvarez/spectro/redux/tilenight-skysub/run/scripts/night/20230210/tilenight-20230210-5627-timing-$SLURM_JOBID.json
```
@sbailey please take a look and …

desi_proc_tilenight processes skysub when --laststeps=skysub

---

py/desispec/bootcalib.py
py/desispec/fluxcalibration.py
py/desispec/test/test_bootcalib.py

This PR closes #1963. The simplest solution is to eliminate all locale manipulation and pass the encoding explicitly to `Table()`:
```python
nist_tbl = Table.read(nist_file, format='ascii.fixed_width', encoding='UTF-8')
```

Set encoding when reading NIST files

---

py/desispec/scripts/proc.py

This PR updates desi_proc (desispec.scripts.proc.main) to *not* create an output exposures/NIGHT/EXPID directory for DARK and ZEROs exposures, since they only create preproc/NIGHT/EXPID output but don't have any spectral extractions to put in exposures/NIGHT/EXPID .  I also enforced UPPERCASE obstype values since that is how it was used in all but one place.
This was motivated by previous production runs having empty exposures/NIGHT/EXPID directories for the nightly 300 sec darks, leading to bookkeeping confusion about why they existed with no contents and whether that was a processing crash or harmless.
I tested with a ccdcalib job in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/temp (admittedly before the second commit standardizing UPPERCASE).  ccdcalib ran, produced expected …

Dark no expdir

---

py/desispec/night_qa.py

This PR addresses the case where some cameras are missing in the dark processing.
`desi_night_qa` processes the dark on-the-fly if those are not processed yet (which currently is the case for the morning darks).
For simplicity, I just parse the header extnames of the dark `desi-EXPID.fits.fz` file.
Here an example for 20230303, where the spectro. 3 is missing: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v20/morningdark-20230303.pdf
Calling sequence (from an interactive node):
```
desi_night_qa -p /global/cfs/cdirs/desi/spectro/redux/daily -n 20230303 -g cumulative -o /global/cfs/cdirs/desi/users/raichoor/nightqa_dev/nightqa_v20 --steps morningdark --nproc 8
```

Night_qa: create_dark_pdf(): handle missing cameras in desi_preproc

---

py/desispec/scripts/daily_processing.py

This is a one-line change to the recently merge `desi_daily_proc_manager` modifications to add tilenight support. It restricts the appending of `skysub`-only exposures to when `use_tilenight` is True to maintain the old behavior for non-tilenight runs.
I've run a short test on 20230416, which had a tile observed with two exposures but the second of which was a skysub only exposure. I've run it with current main, this PR, and this PR using `--use-tilenight` to show that I didn't break any of the new functionality. They show the desired outcome -- `use_tilenight=False` doesn't append the skysub exposure, but the `use_tilenight=True` does.
output files are in: `/global/cfs/cdirs/desi/users/kremin/PRs/tilenight_dailyproc_cori`

Only add skysub exposures if doing tilenight in daily proc

---

bin/desi_run_night
py/desispec/scripts/submit_night.py

This resolves Issue #2035 by adding an option, `--all-cumulatives`, to `desi_run_night` to process cumulative redshifts for all tiles even if observed on a later night.
I ran two tests, one with the flag set, and one without. The logs are both here: `/global/cfs/cdirs/desi/users/kremin/PRs/all_cumulatives`. The relevant lines are copied below showing that the addition works correctly:
```
> grep "Submitting cumulative redshifts for" *.log
noflag_20230414.log:INFO:submit_night.py:252:submit_night: Submitting cumulative redshifts for 30/31 tiles for which 20230414 is the last night: [1587, 2693, 2783, 2845, 3647, 3689, 4727, 5658, 5915, 5958, 7352, 7353, 7486, 8904, 9024, 9043, 9410, 9889, 22475, 24657, 25110, 25205, 43034, 83295, 83297, 83308, 83309, 83310, 83311, 83312] …
```

Add option to process cumulative redshifts for all tiles in desi_run_night

---

.github/workflows/python-package.yml
py/desispec/scripts/daily_processing.py
py/desispec/workflow/procfuncs.py

Implements a temporary patch for a new bug with the Slurm system on Perlmutter since April 26 maintenance by removing the job dependency flag for jobs that are complete.
Testing on this branch for Perlmutter and Cori with:
```
DESI_SPECTRO_REDUX=$CFS/desi/users/$USER/spectro/redux/desispec-sbatch
SPECPROD=sbatch-patch_${NERSC_HOST}
nightr=20230416
nightd=20230417
mkdir -p $DESI_SPECTRO_REDUX/$SPECPROD
mkdir -p $DESI_SPECTRO_REDUX/$SPECPROD/exposure_tables/$month
cp $CFS/desi/spectro/redux/daily/exposure_tables/$month/*$nightr.csv $DESI_SPECTRO_REDUX/$SPECPROD/exposure_tables/$month/
desi_daily_proc_manager      --override-night $nightd -q realtime --ignore-cori-node 
desi_run_night -n $nightr -q realtime 
jobids=$(cat $DESI_SPECTRO_REDUX/$SPECPROD/processing_tables/processing_table_$SPECPR …
```

Workaround for sbatch bug on Perlmutter

---

bin/desi_purge_night

This PR adds a warning message to the end of `desi_purge_night` similar to the one at the end of `desi_purge_tilenight` so that if you are in dry run mode (i.e. not --not-dry-run) it makes that more obvious and tells you what to do to actually purge files.  i.e. end with this:
```
INFO:desi_purge_night:79:<module>: Done purging daily night 20230509
WARNING:desi_purge_night:82:<module>: That was a dry run with no files removed; rerun with --not-dry-run to actually remove files
```
Current main doesn't include the last line, making it too easy to think that the message "Done purging daily night 20230509" actually purged stuff (it didn't).
I have tested this branch with and without `--not-dry-run` on night 20230509 which unfortunately we've had to purge twice now (and at least once I thought …

warn that purge_night was a dry run

---

py/desispec/workflow/procfuncs.py
py/desispec/workflow/queue.py

Fixes #2038 and #2041. Two ongoing tests started on my own account initiated with 
```
source /global/cfs/cdirs/desi/users/malvarez/testscripts/sacct-dryrun.sh 1
```
and
```
source /global/cfs/cdirs/desi/users/malvarez/testscripts/sacct-dryrun.sh
```
to run the daily processing in separate SPECPROD directories,
```
/global/cfs/cdirs/desi/spectro/redux/sacct-dryrun-dryrunlevel-1
```
and
```
/global/cfs/cdirs/desi/spectro/redux/sacct-dryrun-dryrunlevel-0
```
with and without the `--dry-run-level 1` argument added to the `desi_daily_proc_manager` command, respectively, are proceeding normally on tonight's data, with the ccdcalib job (jobid 8951789) submitted as of this posting.
@sbailey please do any additional checks and merge when ready. Thanks.

Restore dry-run and add sacct retries

---

py/desispec/exposure_qa.py
py/desispec/tsnr.py

This PR fixes #1978 where tile QA was crashing due to NaN values in TSNR2 scores, which was also resulting in missing EFFTIME values.
Belt and suspenders:
* the underlying cause of the TSNR2 NaN was traces going just off the edge of the CCD for some amps.  This was being treated as an effective readnoise=0 in a denominator instead of readnoise=large.  Fixed.
* even if a NaN or Inf slips through, invalid TSNR2 values are now converted to EFFTIME=0 so that they don't further propagate into NaN in means and medians.
There might be a better way to handle the case of traces off the edges of the CCDs, but since this is better than what we currently have (code crashes) I plan to self merge and catch up on tiles from yesterday (20230525), then will return to more historic cleanup next week.

avoid TSNR,EFFTIME NaN

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR adds the option to additionally display the dark/morningdark processed with the `--bkgsub-for-science` option for a set of cameras.
- this has come up with the follow-up of the new b8 ccd, which is the previously retired b4, which can have significant features, but such features should be corrected in the science exposures with the `--bkgsub-for-science` option;
- this would be used as a visual, qualitative test to assess that it works as expected;
- the current default behavior is to display that for the b-camera (so a row for a petal would have 4 panels: b, b with bkgsub, r, and z).
Examples generated with the current version of this PR: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v21/v0.
For instance for 20230512: …

Night_qa: dark: add possibility of plots with --bkgsub-for-science

---

py/desispec/scripts/submit_night.py

Fixes #1889 and #2051 by performing the final processing check even if processing table is empty, in order to process single exposures / tiles on a given night, for which there are no previous entries in the processing table, by definition.
I have checked this for the tile and night from #2051, respectively, using
```
desi_run_night --night 20230512 --dry-run-level 1 --z-submit-types=cumulative --append-to-proc-table --all-tiles --tiles=7471
```
and
```
desi_run_night --night 20230512 --dry-run-level 1 --z-submit-types=cumulative --append-to-proc-table --all-tiles
```
with results in
```
/global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2051/single-tile-20230512-7471
```
and
```
/global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-2051/single-tile-20230512-all
```
In …

Perform final processing check in desi_run_night when processing table is empty

---

py/desispec/coaddition.py
py/desispec/test/test_coadd.py

This PR fixes three bugs/issues in coadd_fibermap():
- https://github.com/desihub/desispec/issues/2055 cos(dec) term is now multiplied;
- https://github.com/desihub/desispec/issues/2054 the aggregate quantities `{MEAN|STD}_FIBER_{RA|DEC}, {MEAN|RMS}_DELTA_{X|Y}, MEAN_PSF_TO_FIBER_SPECFLUX` are now computed over only the `good_coadds` when available (len>0), otherwise over the "bad" coadds;
- https://github.com/desihub/desispec/issues/2046 the `{MEAN|STD}_FIBER_{RA|DEC}` are now computed on the subset with "good" coordinates (i.e., avoiding missing cases with `FIBER_RA=FIBER_DEC=0`
Example test cases for Healpix coadd and for Tile (cumulative) coadd: 
```
from astropy.table import Table, setdiff
from desispec import coaddition
test_type = 'healpix'
#test_type = …
```

fixed cos(dec), good_coadds in aggregate columns, missing fiber coords

---

py/desispec/coaddition.py
py/desispec/test/test_coadd.py

Small change to compute the `FIRSTNIGHT`, `LASTNIGHT` over all files/exposures on disk (not only over the "good_coadds"/"compute_coadds"). Added some comments to clarify the choice for the NIGHT columns versus the choice for the MJD columns.
Also a small change to replace `TARGET_DEC` with `FIBER_DEC` when computing the STD_FIBER_RA here:
```
if 'FIBER_RA' in fibermap.colnames:
dec = fibermap['TARGET_DEC'][jj][compute_coadds&compute_coords][0]
vals = fibermap['FIBER_RA'][jj][compute_coadds&compute_coords]
std = np.std(vals+360.0) * 3600 * np.cos(np.radians(dec))
tfmap['STD_FIBER_RA'][i] = std
```
This has the advantage to remove the dependency on TARGET coordinates, and the function runs well on FIBERMAP inputs that may not have those coordinates such as some EXP_FIBERMAP extensions.
Both …

changed first,lastnight and removed target_dec dependency

---

bin/desi_daily_proc_manager
py/desispec/scripts/daily_processing.py

This PR adds a `desi_daily_proc_manager --exp-cadence-time ...` option to adjust the amount of time that it sleeps between exposures.  The default is 2 seconds, the same as before (previously hardcoded).  This allows `desi_daily_proc_manager` tests that are purposefully spread out to mimic data arriving throughout the night.
I'm somewhat ambivalent about adding a new option that is intended to be used only for testing, which we might only need for a limit time period and then not use again (this was motivated by Perlmutter stability testing).  @akremin if you don't like this new option, I could also install the branch and run the tests out of the branch and never merge this PR into main.

daily proc --exp-cadence-time option

---

py/desispec/scripts/specex.py

Solves #1980 by not increasing the error count on ranks corresponding to already-completed PSF fits written by a previous job. Instead, a message is written to the log noting that there is nothing to do for each such rank and the arc job returns the same error code as it would have if those ranks had completed those fits.
I tested this by:
1. taking the outputs from a previously successful arc exposure (EXPID) processing
2. removing one of the psf files (i.e. fit-psf-z0-EXPID.fits)
3. rerunning the arc*.slurm script
The resulting log files are in 
```
/global/cfs/cdirs/desi/users/malvarez/spectro/redux/desispec-spxmidjobfail/specex-midjobfail-20230512-all/run/scripts/night/20230512/arc-20230512-00180239-a0123456789-9829453.log
```
and
``` …
```

Do not report failure when skipping previously-written PSF fits

---

py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/proc_tilenight.py

Fixes #2039 by returning `num_err` in `proc_joint_fit` instead of zero, so that psfnight, fiberflatnight and other jobs will report a failure instead of success when errors have occurred within `proc_joint_fit`.
@sbailey I am in the processing of testing, but feel free to get a start with the review, thanks.

Propagate joint fit error code

---

bin/desi_tile_vi

This PR ~hacks the QA column to be 20 characters long on read in in desi_tile_vi.  This is intended to resolve issues like
https://github.com/desihub/desisurveyops/issues/125
where all the max length QA status was 4 characters long, making new unsure tiles get truncated down to 'unsu' tiles.
This PR's fix is pretty marginal, reading the file in with Table.read(...) as usual and then pulling out the 'QA' column and changing its type to be longer.
It feels to me like the "correct" solution would involve telling the ecsv file to use a longer datatype for the string.  But AFAICT the ecsv string data type is just string, and can handle arbitrary length on read-in and write out.  The problem is that it then gets read into a fixed length structure by astropy/python.
I'm surprised that we don't …

Force QA string field to have a minimum length.

---

py/desispec/image_model.py

When trying to import desispec.trace_shifts 
I get the circular import 
```python
File ~/pyenv310/lib/python3.10/site-packages/desispec/image_model.py:25
23 from desispec.qproc.qsky import qproc_sky_subtraction
24 from desispec.qproc.qfiberflat import qproc_apply_fiberflat
---> 25 from desispec.trace_shifts import compute_dx_from_cross_dispersion_profiles
27 @numba.jit
28 def numba_proj(image,x,sigma,flux) :
29     '''
30     Add a spectrum to a model of the pixel values in a CCD image assuming a Gaussian cross-dispersion profile.
31 
(...)
36        flux : 1D numpy array of size image.shape[0], quantity to project (for design usage: electrons per pixel) for each CCD row
37     '''
ImportError: cannot import name 'compute_dx_from_cross_dispersion_profiles' from partially initialized …
```

fix circular import with trace_shifts

---

py/desispec/scripts/archive_tilenight.py

This PR implements options for archiving tiles with purposefully missing petals, even if they had previously been archived with those petals.  For context see #2080 and desihub/desisurveyops#126.
* new option `desi_archive_tilenight --rearchive` to handle the case where tiles-specstatus.ecsv already says that tile is done (ZDONE=true, QA=good) but we want to force rearchiving anyway
* new option `desi_archive_tilenight --badpetals A,B,C` to acknowledge that petals A,B,C are missing from current prod even if they existed in a previous archiving.  In this case it will propagate a new zmtl file for the missing petals, setting ZWARN BAD_PETALQA bit. It is treated as an error if
* any of those petals actually do exist
* a petal is missing from the prod, exists in a previous archive, but isn't …

archive options for missing petals

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR changes the way night_qa decides to report calibration files in orange (in the `calibnight` section).
Before, it was based on comparing the calibration files timestamps to the considered night.
However, what really matters is if the calibration files timestamps are earlier than the processed science exposure files.
This PR should implement that.
For each {camera}{petal}, the code now:
- looks for all the processed files in `{prod}/exposures/{night}/{expid}/*-{camera}{petal}-*fits` for the list of considered `expids`, and retains the earliest one;
- then compares it with the calibration file timestamp;
- and it also dumps in the log those timestamps.
To do that I had to change the argument list of `night_qa.write_nightqa_html()`; but I guess it s fine, as this is the only place in …

write_nightqa_html: use earliest science exposure timestamp for orange

---

py/desispec/coaddition.py
py/desispec/test/test_coadd.py

This PR fixes #2078 to deal with RA wrap-around when calculating MEAN_FIBER_RA and STD_FIBER_RA.  I'm not aware of any current cases with that problem, so this is some future proofing.  For efficiency, it doesn't try to solve the completely generic problem near the dec = +-90 poles or broadly distributed RA values, but I think it solves the future potential problem of RA values spanning the RA=0 boundary but away from the poles.
@dstndstn could you double check this?  I made enough errors testing this and catching corner cases that I would appreciate some fresh eyes on it.  @stephjuneau heads up you are welcome to review it too if you have cycles / interest.
This includes unit tests to check scatter crossing the RA=0 boundary with a mean at 0, just above 0, and just below 360, for various …

coadd_fibermap handle RA wraparound

---

py/desispec/io/spectra.py
py/desispec/test/test_spectra.py

A function to read a single spectrum from a fits file instead of reading in all the spectra in the file. As requested by @sbailey .
This function also adds the option to either read in or not read in the `"FIBERMAP", "EXP_FIBERMAP", "SCORES", "EXTRA_CATALOG", "MASK", "RESOLUTION"` HDUs. 
I have currently not included the option to read in a subset of spectra from each file. I did this because this is incompatible with another option I would rather include: reading a subset of columns from for example the fibermap. This makes it possible to minimise the amount of data read in to the bare minimum needed for any purpose.
This should minimise the amount of data read from the disk and reduce the read time when reading many spectra from separate files.

add read_single_spectrum function

---

py/desispec/night_qa.py

This PR hopefully improves a bit the displaying of the dark images in the night_qa webpage:
- the y-axis should now be correctly displayed, with the y-values increasing towards the top;
- I ve added xlabel and yabel
- I ve also added the amplifier names.
For reference, here s the image from Fig. 2 of Guy+2023:
And here an example for 20230807 (run from an interactive node):
```
PROD=/global/cfs/cdirs/desi/spectro/redux/daily
NIGHT=20230807
OUTDIR=/global/cfs/cdirs/desi/users/raichoor/nightqa_dev/nightqa_v23/v0
desi_night_qa -p $PROD -n $NIGHT -o $OUTDIR --nproc 32 --steps dark > $OUTDIR/nightqa-$NIGHT.log
```
https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v23/v0/dark-20230807.pdf
Displaying here the petal=1:
[I think I ve some missing settings in my test run, e.g. …

night_qa: dark image: flip y-axis and display amplifier names

---

py/desispec/coaddition.py
py/desispec/specscore.py
py/desispec/test/test_coadd.py

This PR fixes the COADD_FIBERSTATUS bit propagation bug reported in #2032  .
For good targets, COADD_FIBERSTATUS is unchanged = the bitwise AND of input FIBERSTATUS.
For targets where all input spectra are bad, this PR changes COADD_FIBERSTATUS to the bitwise OR of input FIBERSTATUS values.  This fixes the case in #2032 where the input spectra were all bad, but for different reasons, resulting in a bitwise OR of 0, incorrectly implying that the input FIBERSTATUS were ok.  This will also result in other bad targets getting additional bits set (due to OR instead of AND).
Note that the incorrect COADD_FIBERSTATUS=0 cases had all ivar=0 anyway, which leads to ZWARN!=0 so we weren't getting incorrectly "good" redshifts for these anyway, but some analyses/bookkeeping were treating …

update COADD_FIBERSTATUS to bitwise OR when all inputs are bad

---

py/desispec/coaddition.py
py/desispec/test/test_coadd.py

This PR fixes #2077 by coadding the bitwise OR of targeting bits instead of assuming that they are the same on every tile (see #2077 for context).
I added a unit test with toy examples, but would also like to test it on real cases if @stephjuneau @geordie666 or @araichoor could dig up the email/slack threads to post examples.
@geordie666 and/or @stephjuneau, please double check that I got the complete set of column names correct (I had a few iterations of confusion on SV1_DESI_TARGET vs. SV1_TARGET, etc).  For consideration: Instead of a specific list of colnames, I could update this to propagate bitwise OR for any column that matches
```
colname.endswith('_TARGET') and colname != FA_TARGET
```
thoughts?

coadd bitwise OR of targeting bits

---

py/desispec/coaddition.py
py/desispec/test/test_coadd.py

This PR fixes #2092 by adding 3 new boolean columns to EXP_FIBERMAP (`IN_COADD_B/R/Z`) to record which input exposures were actually used by the coadd per-camera.  This augments the coadded FIBERMAP column `COADD_NUMEXP` which records the number of exposures that contributed to the coadd but loses the details of which ones.
I also refactored the selection logic into a separate `use_for_coadd(fiberstatus, band)` function to be used by `coadd`, `coadd_cameras`, and `coadd_fibermap` instead of them each doing their own selection logic using the `get_all_fiberbitmask_with_amp` bitmask.  It's not that many lines of code, but I was nervous that `coadd_fibermap` was doing independent logic from `coadd` when reporting what was used by `coadd`.
This includes a bunch of unit tests that I think …

Add IN_COADD_B/R/Z columns

---

py/desispec/qproc/qfiberflat.py
py/desispec/trace_shifts.py

Hi, 
while investigating trace_shifts I noticed that there is a couple places in desispec that use np.polyfit weights assuming those weigths are inverse variances, while they should be inverse errors:  https://github.com/desihub/desispec/blob/bf216b2e65b066367d9607315605e3f2f5863a5e/py/desispec/trace_shifts.py#L569
https://github.com/desihub/desispec/blob/bf216b2e65b066367d9607315605e3f2f5863a5e/py/desispec/qproc/qfiberflat.py#L83
cf. docs 
https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html
The patch fixes that. (I am assuming that the patch should be pretty safe)

fix incorrect use of polyfit 

---

bin/desi_zcatalog

This PR fixes #2087 by adding a `desi_zcatalog --recoadd-fibermap` option to recoadd the spectra FIBERMAP -> FIBERMAP, EXP_FIBERMAP instead of propagating the previously coadded versions from the redrock files.  This enables us to rebuild the stacked redshift catalogs while bringing in the bug fixes from e.g. PRs #2100 (IN_COADD_B/R/Z), #2094 (target bit bitwise OR), and #2093 (COADD_FIBERSTATUS bug fixes).
A companion option `--ztile` flags whether this is a tile-based coadd (vs. a healpix based coadd).  I plan a separate PR to simplify the `desi_zcatalog` options and this might change again, but I've tried to focus this PR on the minimal changes needed to support adding re-coadding.
One non-minimal change for simplicity is dropping support for the "ZBEST" HDU (renamed "REDSHIFTS") and …

desi_zcatalog --recoadd-fibermap option

---

bin/desi_zcatalog
py/desispec/scripts/group_spectra.py
py/desispec/scripts/zproc.py
py/desispec/test/test_pixgroup.py
py/desispec/test/test_util.py
py/desispec/util.py

This PR fixes the datatype of the HPXNEST keyword in spectra files and stacked redshift catalogs.  This was coming in via `desi_group_spectra --header HPNEST=True ...` (i.e. not propagated from an input file), but that was incorrectly resulting in a string 'True    ' instead of the FITS boolean T.  Several layers of fix:
* `--header KEY=VAL` parsing explicitly handles booleans now, and is put into a new function `desispec.util.parse_keyval` since we were doing similar logic in both `desi_group_spectra` and `desi_zcatalog`.
* `desi_group_spectra --healpix N ...` automatically sets healpix-based keywords now, so it is no longer necessary to explicitly set `--header HPXNEST=True` anyway, but we still need to set other new header keywords so we might was well get it right for any future …

fix HPXNEST header type

---

bin/desi_zcatalog
py/desispec/io/util.py

This PR adds a `desi_zcatalog --add-units` option to reapply units when creating stacked redshift catalogs, using desidatamodel/py/desidatamodel/data/column_descriptions.csv .
Example outputs are in /pscratch/sd/s/sjbailey/desi/dev/zcat_units/zpix*.fits, compared to $CFS/desi/spectro/redux/iron/zcatalog/zpix*.fits which don't have TUNITnn header keywords.
This PR does *not* attempt to fix the underlying problem of why units aren't propagated in the fibermaps in the upstream files; see issue #2068 for context about that.  This is is just the minimal update for patching the final DR1 redshift catalogs.
This PR uses `desiutil.annotate.load_csv_units` to parse column_descriptions.csv, then it uses `desispec.io.util.write_bintable` to add the units while writing.  It does *not* use …

desi_zcatalog --add-units option for DR1 patching

---

.readthedocs.yml
doc/rtd-requirements.txt

This adds the `.readthedocs.yml` file that will be required after about 24 September for RTD to work at all.
This branch built successfully on RTD: https://desispec.readthedocs.io/en/rtd-updates/.
Closes #2074.

Update ReadTheDocs configuration

---

bin/desi_zcatalog

This PR fixes a `desi_zcatalog --group cumulative --recoadd-fibermap ...` bug introduced in PR #2109 which tested `--recoadd-fibermap` without the additional `--group cumulative` flag.
Symptom: the code tries to add a LASTNIGHT column that already exists, and crashes.
Reason: In Iron-era data, individual tile coadded fibermaps did not have a LASTNIGHT column because they would have been the same for every row, so `desi_zcatalog --group cumulative ...` would add that column when combining across fibermaps.  But PR #2067 (post-Iron) adds the LASTNIGHT to every coadded fibermap even if the value is the same for all targets.  But then when desi_zcatalog tried to add that column again, it crashes.
Workaround: only add LASTNIGHT if it doesn't already exist.
This is a small update that I intend …

fix zcat cumulative LASTNIGHT stacking

---

bin/desi_zcatalog

This PR significantly updates desi_zcatalog to add parallelism and make it easier to use for productions.  Relative to current main, this PR changes the script options/usage but does not change the actual outputs other than their sort order.  The code changes are big enough that it might be easiest to evaluate the final state and outputs rather than the code diff.
The updated script supports two modes:
* `desi_zcatalog --indir ...` : recursively find redrock*.fits files under an arbitrary input directory and stack them.  This is useful for creating test redshift catalogs from custom runs of redrock that might be organized outside of the context of a production.
* `desi_zcatalog --group healpix|cumulative|pernight|perexp --survey SURVEY --program PROGRAM ...` uses a standard specprod …

desi_zcatalog refactor

---

py/desispec/night_qa.py

This PR should address https://github.com/desihub/desispec/issues/2119.
In such cases, the new code throws a `log.warning()`, ignores the problematic exposure, and proceeds to the next one.
sounds good?

Night_qa: get_surveys_night_expids() : protect against missing OBSTYPE keyword

---

bin/desi_zcatalog
py/desispec/coaddition.py
py/desispec/test/test_coadd.py

This PR moves the FIRSTNIGHT,LASTNIGHT calculation from `desispec.coaddition.coadd_fibermap` to `desi_zcatalog` (the script the stacks N>>1 redrock files into the final redshift catalogs) to fix a problem on tiles that are missing different petals on different nights.  Although `coadd_fibermap` was correctly considering all nights in its input fibermap, the problem is that those per-petal input fibermaps can have a different set of nights per petal, resulting in different FIRSTNIGHT,LASTNIGHT values per-petal when they are supposed to be per-tile values.  This is especially important for LASTNIGHT which is used to trace back to the original spectra in tiles/cumulative/TILEID/LASTNIGHT/spectra-PETAL-*.fits.gz (same LASTNIGHT for all PETALs, even if some PETAL wasn't included on that …

fix FIRSTNIGHT/LASTNIGHT when missing petals

---

py/desispec/io/spectra.py
py/desispec/test/test_spectra.py

Fixes #2125. No unit tests added yet, because my solution is a bit of a hack, if someone passes the `rows` argument.
@sbailey @dirkscholte

return the correct number of rows in exp_fibermap when specifying targetids to read_spectra

---

bin/desi_average_flux_calibration

This is really a tiny difference that does not affect the pipeline:
Add option to desi_average_flux_calibration to remove flatfield correction.

Minor PR: add option bin/desi_average_flux_calibration

---

bin/desi_exposure_info

This is still a work in progress. I developed this tool to summarize info about an exposure from sources I thought were relevant. It includes showing the raw data location, the preproc and exposures directories, the pipeline exposure_table entry, the summary `exposures-SPECPROD.csv` entry, the surveyops `exposures.ecsv` file, and the entry in the workflow dashboard.

Add script that summarizes info about an exposure in a specprod

---

py/desispec/scripts/proc.py

Set psferr=0.04 instead of 0.01 for the blue cameras to avoid having many spectral pixels with the ```specmask.BAD2DFIT``` bit set.
(in the call ```desi_extract_spectra --psferr xxx``` in ```desi_proc```).
This value has been tuned on exposure 197796 from night 20230923 and checked on exposure 192356 from night 20230824.
The psferr parameter increases the pixel variance by (psferr*model_flux)**2 in the chi2 of the 2D spectral extraction. It is used to account for modeling uncertainties. The value of 0.01 was not large enough in the blue cameras. It results in large chi2 on the brightest sky lines where psf errors dominate the noise.
The following plot shows the sum of masked spectral pixels per camera (among 500) as a function of wavelength for various psferr values. For psferr=0.04 most …

Set psferr=0.04 for blue cameras

---

py/desispec/data/qa/qa-params.yaml
py/desispec/tile_qa_plot.py

This PR adds in the tile-qa*png plot:
- report of the min(VCCDSEC) value over all {camera,petals} for each exposure;
- a "red alert" message if min(VCCDSEC) is below 72000s=20h; that value is stored in `desispec/data/qa/qa-params.yaml`;
- and also a `log.warning()` message is written in that case.
We can surely change that threshold=20h value, based on our experience with those events: @schlafly ?
I picked that threshold=20h value based on this plot, which looks at the `b0` campet VCCDSEC values for all exposures since  Dec. 2021:
(file here: https://data.desi.lbl.gov/desi/users/raichoor/spectro/daily/vccdsec-b0-202112-202310.asc)
Comments:
- this tile-qa plots starts to be quite busy...
- I squeezed a bit the per-exposure infos reported on the top to add this new VCCDSEC column
- I …

Tile_qa_plot: add VCCDSEC info and alert

---

py/desispec/io/spectra.py
py/desispec/test/test_spectra.py

This PR is a followup to #2052, fixing a bug with `read_spectra(..., skip_hdus=['EXP_FIBERMAP', ...])`
The original code looping over HDUs had
```python
...
elif name == "EXP_FIBERMAP" and name not in skip_hdus:
...
elif ...
```
The problem was that if "EXP_FIBERMAP" was in skip_hdus, then it would continue down the elif chain and eventually get interpreted as a catchall user-provided "BAND_EXTRANAME" image HDU, which would then trip on reading a table as an image.
The fix is
```python
...
elif name == "EXP_FIBERMAP":
if name not in skip_hdus:
...
elif ...
```
so that if it finds "EXP_FIBERMAP" but it is in `skip_hdus` then it will stop checking rather than continuing to try to parse the name as meaning other things.  I applied that same pattern to all other cases of known HDU names that …

fix read_spectra skipping exp_fibermap

---

py/desispec/coaddition.py
py/desispec/specscore.py
py/desispec/test/test_coadd.py

This PR adds support for running `coadd_cameras` on a Spectra object that purposefully doesn't have resolution data.  It adds a unit test that previously failed but now passes.

support coadd_cameras without resolution

---

bin/plot_fiber_traces

This PR adds two options to plot_fiber_traces:
* `--zscale` : use the IRAF / ds9-like zscale algorithm to pick vmin/vmax values when plotting the image
* `--mask`: use the image mask when plotting the image to be able to differentiate masked bad pixels from unmasked bad pixels.

plot_fiber_traces --mask and --zscale

---

bin/plot_fiber_traces
py/desispec/trace_shifts.py

This PR fixes the crash reported in #2148 for traceshifts on CCDs where half of the amps are masked.  The underlying problem was a median over fibers to make a median spectrum, but that can fall apart if >half of the fibers are masked (or in previous cases, luckily sort-of succeeding when 249 fibers were masked...).  The solution is to only median over unmasked fibers.
This fixes the previous crash case:
```
cd $CFS/desi/users/desi/debug/traceshifts
desi_compute_trace_shifts --degxx 2 --degxy 0 --degyx 2 --degyy 0 --sky \
--image preproc-b5-00207663.fits.gz \
--psf psfnight-b5-20231126.fits \
--outpsf $SCRATCH/psf-b5-00207663.fits
``` 
I verified with plot_fiber_traces that the offset traces look good, including that the masked traces are ok and don't have bad solutions causing overlaps …

Fix traceshifts when half CCD amps are masked

---

py/desispec/night_qa.py

With this PR, the night_qa`create_petalnz_pdf()` now parses the `redrock*fits` files to identify the processed petals, instead of the `zmtl*fits` file.
It addresses https://desisurvey.slack.com/archives/C01HNN87Y7J/p1703203812637849.
I.e. when we archived+mtl-updated a tile, then realized a petal was bad, so we re-process the tile, with creating a "dummy" `zmtl*fits` file (but no redrock or other files).
The `create_petalnz_pdf()` function was looking for `zmtl*fits` files to parse the existing petals.
Here it would find the "dummy" `zmtl*fits` file, but then crash as there s no `redrock*fits` file.
I ve successfully run on night here: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v25/20231209/.

create_petalnz_pdf(): look for redrock*fits instead of zmtl*fits

---

py/desispec/test/test_photo.py

Tentative fix for #2138 but we'll need to confirm if this fixes this part of the issue you identified, @sbailey:
```
@moustakas we're getting test_photo failures at NERSC, e.g. see https://data.desi.lbl.gov/desi/spectro/redux/dailytest/log/perlmutter/desispec.log . 
When run as part of the full test suite, I'm getting one failure like
...
if legacysurveydir is None:
legacysurveydir = os.path.join(desi_root, 'external', 'legacysurvey', 'dr9')
if not os.path.isdir(legacysurveydir):
errmsg = f'Legacy Surveys directory {legacysurveydir} not found.'
log.critical(errmsg)
>           raise IOError(errmsg)
E           OSError: Legacy Surveys directory /tmp/tmpgio7la0q/external/legacysurvey/dr9 not found.
and two failures like
fiberfile = os.path.join(fiberassign_dir, stileid[:3], …
```

Fix #2138.

---

py/desispec/io/spectra.py
py/desispec/test/test_spectra.py
py/desispec/test/test_util.py
py/desispec/test/util.py
py/desispec/util.py

This PR has several bug fixes and updates for `desispec.io.read_tile_spectra`:
**BUGFIX**: fixes the matching of a redshift table (with one row per TARGETID) to a uncoadded spectra fibermap
(with potentially multiple rows per TARGETID in a different order), when filtering by FIBER.  The previous logic
was simply wrong (mea culpa).  I introduced a new `desispec.util.argmatch` function to isolate and test this
matching logic, as well as introducing additional higher-level `read_tile_spectra` tests that would have caught the
original bug but now pass.  Usage: `ii = argmatch(a, b)` returns indices `ii` such that `a[ii] == b` is True for all entries.
* @geordie666 and @araichoor heads up: `desispec.util.argmatch` is similar to `desitarget.geomask.match_to`, but it supports duplicate entries …

fixes/updates to read_tile_spectra

---

.github/workflows/python-package.yml
py/desispec/spectra.py
py/desispec/test/test_spectra.py

This PR adds methods to convert `desispec.spectra.Spectra` to and from `specutils.SpectrumList`.
For testing purposes, `specutils` is only installed for the coverage test.

Spectra to specutils

---

bin/desi_compute_dark_nonlinear
bin/desi_make_regular_darks
py/desispec/ccdcalib.py

This adds a check for VCCDSEC when computing dark/bias models, current default is set to a minimum of 6h after VCCDON
VCCDSEC/VCCDON for the file with lowest VCCDSEC are propagated to the output files
If VCCDSEC is not inside input files, those files will be used, but a warning is issued.
Tested this on a range of 5-10 nights prior to 20240101 (usual behaviour), 20231215 (change of VCCD) and 20230805 (keyword not in  some input files) to check the different tests

Dark_changes_and_calib_ledger

---

bin/copyprod

This is a PR of an old branch that I forgot to open a PR for at the time.  It fixes some corner cases for handling links when running copyprod multiple times, e.g. to extend the link farm with new tiles, though I'd have to re-derive from the code what the exact situation was that I was fixing.  I'll leave this open for a few days if anyone wants to take a look, and then self merge sometime next week.

better handling of copyprod links

---

bin/desi_make_dark_tables
py/desispec/calibfinder.py
py/desispec/preproc.py
py/desispec/scripts/preproc.py
py/desispec/scripts/qproc.py

This mainly promotes the case of not finding a usable DARK in DESI_SPECTRO_DARK to a critical I/O error, thus crashing the code in that case. I guess we might want an option to use the previous DESI_SPECTRO_CALIB fallback instead when needed.

Promote dark errors

---

py/desispec/mgii_afterburner.py

Redrock made a non-backward-compatible change to a function parameter name that broke the MgII afterburner as outlined in issue #2167 .
This fixes it by updating the afterburner to use the new variable name "template_path" rather than the old "template_dir". 
I have tested this by linking over an exposure directory from last night and running off of `main` to reproduce the error, then running out of this branch, which succeeded.
I'm self-merging so we can use this for daily operations.

template_dir to template_path for redrock templates

---

bin/desi_link_calibnight
doc/api.rst
py/desispec/io/meta.py
py/desispec/scripts/link_calibnight.py
py/desispec/test/test_link_calibnight.py

New `desi_link_calibnight` script to simplify linking calibnight files from one night to another:
```
usage: desi_link_calibnight [-h] --refnight REFNIGHT --newnight NEWNIGHT [-c CAMERAS]
[--include INCLUDE] [--exclude EXCLUDE] [--dryrun]
options:
-h, --help            show this help message and exit
--refnight REFNIGHT   Reference night with calibs
--newnight NEWNIGHT   New night without calibs, to link to refnight
-c CAMERAS, --cameras CAMERAS
Camword of cameras to link, e.g. a0123b6r7z8
--include INCLUDE     prefixes of types of calibnight files to create links
--exclude EXCLUDE     prefixes of types of calibnight files to exclude from links
--dryrun              dry run; don't actually create links
```
By default this links badcolumns,biasnight,fiberflatnight,psfnight files, with a …

add desi_link_calibnight script

---

doc/changes.rst
py/desispec/io/__init__.py
py/desispec/io/meta.py
py/desispec/io/spectra.py
py/desispec/io/table.py
py/desispec/spectra.py
py/desispec/test/test_io.py
py/desispec/test/test_spectra.py
py/desispec/test/test_util.py
py/desispec/util.py

This PR that adds `read_spectra_parallel(targets_table, ...)` to simplify the process of reading N>>1 targets from M>>1 different files, taking subsets as needed and then stacking them back together into a single Spectra result.  It supports multiprocessing or MPI for parallelism, and auto-derives from the columns of the targets_table whether to read tiles/cumulative spectra or healpix spectra.
The intended use case would be to read a zcatalog/ or equivalent redshift catalog, filter down to the targets you want, then call `read_spectra_parallel` to efficiently read them.  Beware: you'll probably blow memory if you try to read 1M quasars in a single call, but this is still useful to read in batches by nside=16 healpix or groups of 10 tiles, etc.
This includes a suite of unit tests for …

Read spectra parallel

---

py/desispec/scripts/procdashboard.py

One-line fix to update the rules for short (cte) flats in the processing dashboard to be consistent with `desi_proc`. By default `desi_proc` only performs the fiberflat step if the exptime > 10.  The dashboard now reflects that.

Update dashboard rules for cte flats

---

py/desispec/night_qa.py

This PR updates the amp bookkeeping in nightqa to support 2amp mode, in particular tested on z3 data on 20240221:
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20240221/nightqa-20240221.html
Note that the amps are labeled correctly on the dark image:
And the previously bad CTE offsets (from 20240220):
Now don't have a step across the middle-of-the-CCD up/down boundary, though there is still an uncalibrated offset.![image](https://github.com/desihub/desispec/assets/218471/d6362df3-5026-4ccb-ac9d-cfa970d7b7d3)
Admittedly, those above/below labels still reference amps C and D, basically using those labels for quadrants even though the data weren't really read out through C and D.  Does anyone care enough to suggest alternate labels?
I'd like to merge this today so that it is …

nightqa support 2amp mode

---

.github/workflows/python-package.yml
py/desispec/correct_cte.py
py/desispec/io/__init__.py
py/desispec/io/fibermap.py
py/desispec/preproc.py
py/desispec/test/test_lite.py

This PR moves some imports around to simplify the dependencies needed to do basic operations with DESI spectra:
* desispec.io.read_spectra
* filter spectra by desitarget masks
* desispec.coaddition.coadd and .coadd_cameras
* desispec.spectra.stack
* desispec.io.write_spectra
These actions can be done with a minimal environment of:
```
conda create -n desilite --yes python=3.10 astropy scipy numba pytest ipython
conda activate desilite
pip install fitsio
python -m pip install git+https://github.com/desihub/desiutil.git
python -m pip install git+https://github.com/desihub/desitarget.git
python -m pip install git+https://github.com/desihub/desispec.git@desilite
```
(after merging that `@desilite` branch specification won't be needed).
e.g. you no longer need specter, speclite, or desimodel …

simplify installation requirements

---

py/desispec/calibfinder.py

This mildly increases the temperature threshold for DARK models to be picked up and used, should allow the last remaining case in #2164 (r9 for 20210610) to run through.

increase temperature tolenrance slightly

---

py/desispec/correct_cte.py

This fixes an issue with the CTE correction on amplifiers which read out in the "flipped" direction.  The correction was being done "correctly" but needed to be flipped back before being applied to the image.  This now occurs.
Figure shows 20240304/00228660/preproc-r7-00228660.fits.gz, left: daily preproc, middle: CTE corrected without this PR, right: CTE-corrected with this PR.

Fix CTE direction flip.

---

py/desispec/calibfinder.py
py/desispec/correct_cte.py
py/desispec/preproc.py
py/desispec/scripts/fit_cte_night.py

This PR makes the CTE correction code more flexible for cases when not correction is needed:
* when generating the CTE corrections, desi_fit_cte_night first checks if a CTE correction is even needed for a camera before complaining about things like BADCAMWORD being set.  It also checks the science exposures and doesn't try to generate a CTE correction for a camera that is flagged as bad all night anyway.
* @akremin this still only checks CAMWORD and BADCAMWORD; I could use some help for how to also check BADAMPS
* when using the CTE corrections, desi_preproc first checks if the correction is needed for a given camera before checking for the existence of $DESI_SPECTRO_REDUX/$SPECPROD/calibnight/NIGHT/ctecorr-NIGHT.csv .  This restores the ability to preproc non-CTE-problematic cameras …

ctecorr flexibility

---

py/desispec/scripts/group_spectra.py

Fix #2198 
I also write a INFILNUM keyword to the header. I wasn't sure if it's better to always write it, or only if the number is >1000.
I did the latter.

Fix the desi_group_spectra with more than 1000 files

---

bin/desi_proc_night
py/desispec/scripts/proc_night.py
py/desispec/scripts/tile_redshifts.py
py/desispec/test/test_proc_night.py
py/desispec/test/util.py
py/desispec/workflow/calibration_selection.py
py/desispec/workflow/processing.py
py/desispec/workflow/science_selection.py

This is a "PR on a PR" to document the changes I made to the pipelinerefactor branch in PR #2187 while testing daily mode, and to allow @akremin an opportunity to review them before they are added to that branch.  Changes are:
* BUGFIX: `log.log` -> `log.info` typo
* FEATURE: Added more logging to make it easier to see the boundaries between multiple invocations of `desi_proc_night --daily ...` when they are all piped to the same log.
* FEATURE: changed "ok to proceed with submitting cals" criteria to require a 1s flat instead of requiring 3 cte flats.
* Reasoning: Although we currently take 3 cte flats and thus --daily works for current data, the pipeline only requires/uses the 1s flat so this makes the pipeline job logic closer to what is actually required.  This enables testing on …

pipelinerefactor daily mode updates

---

py/desispec/night_qa.py

Quick fix to issue #2204 . ccdcalib now lists flats used for cte corrections, if performed, which broke the qa code looking for the dark exposure. This fixes it by taking the first exposure if multiple are present, which is the dark exposure based on the pipeline logic. We could do additional sanity checks to make sure it is a dark expid, but this is programmatically how the pipeline currently works. If it breaks in the future then I suggest we do a more rigorous and in-depth patch.
@anand please check to see if you're happy with this intellectually. Then we're safe to merge and rerun nightqa for last night.

Make nightqa dark sel robust to new ccdcalib

---

py/desispec/night_qa.py

Second trivial PR to fix a second ccdcalib exposure parsing issue in nightqa. The code now works for last night in `daily` so self merging.

fix nightqa ccdcalib expid selection

---

py/desispec/scripts/proc_joint_fit.py
py/desispec/scripts/proc_night.py
py/desispec/test/test_proc_night.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/processing.py
py/desispec/workflow/timing.py

This is the code changes to resolve issue #2189 by introducing new allowed override file keywords and implementing the code to interpret those and pass them to `autocalib_fiberflat` inside `desi_proc_joint_fit`. This is done by introducing a new flag to `desi_proc_joint_fit` that when set, runs `autocalib_fiberflat` with the `--solve-gradient` flag.
The new override file format differs from the recommendation in the issue. The format is:
```
calibration:
nightlyflat:
flags: ['--autocal-ff-solve-grad'] 
```
This follows the logic from the calibration linking, where jobs that are only performed once per night can be uniquely identified by their `JOBDESC` (job description) in the override files. This approach breaks down for per-exposure or per-tile specifications but the simplicity here …

Add hooks for autocalib_fiberflat flag into override file and pipeline

---

py/desispec/correct_cte.py
py/desispec/scripts/fit_cte_night.py
py/desispec/test/test_util.py
py/desispec/util.py

This resolved issue #2197 in which the ctecorr code crashes if all table entries are from a different night than the night being processed. However, we want to support this case since there are nights with no valid calibration data where we need to link the information from another night.
This introduces a new function `desispec.util.difference_nights` that uses `datetime.date` to handle the difference in days between two nights. The ctecorr code is updated to accept any calibration data within 14 days of the current night being processed (either before or after the current night).
I've tested this on the test night that originally identified the problem, and it now runs in this branch. I also tested on a new night I set up to link the ctecorrnight from a different night, and it worked …

Ctenightcheck

---

bin/desi_create_override_file
doc/api.rst
py/desispec/scripts/createoverride.py

This adds a script called desi_create_override_file that will prompt the user for relevant information that can be included in an override file. Some of the information can be provided via the command line for easier scripting. This was used to create the override files needed to set the `autocalib_fiberflat` `--solve_gradient` flag for about a month's worth of nights in 2023 and 2024 (issue #2174). The files are in the proper format, which I tested by running `desi_proc_night` on a test night, which correctly propagated the `--autocal-ff-solve-grad` to `desi_proc_joint_fit`.
Note, because of the way the `pyyaml` module dumps information, the lists will be printed in long form rather than abbreviated bracket ([]) notation if `linkcal` is specified. This minor inconvenience was outweighed …

Add script to create override file

---

doc/changes.rst
py/desispec/io/fibermap.py

This PR replaces any `NaN` `TARGET_RA`/`TARGET_DEC` values with the associated `FIBER_RA`/`FIBER_DEC` values via `assemble_fibermap()`.
This should address #1711.
An example of the behavior before and after the update, running:
```assemble_fibermap --night 20210422 --outfile $SCRATCH/blat.fits --expid 86004 --overwrite```
is in:
```fitsio.read("/pscratch/sd/a/adamyers/foo.fits")``` (before)
```fitsio.read("/pscratch/sd/a/adamyers/blat.fits")``` (after)
Testing:
```
import fitsio
a = fitsio.read("/pscratch/sd/a/adamyers/foo.fits")
b = fitsio.read("/pscratch/sd/a/adamyers/blat.fits")
ii = np.isnan(a["TARGET_RA"])
print(a[ii][["TARGET_RA", "TARGET_DEC", "FIBER_RA", "FIBER_DEC"]])
print("----")
print(b[ii][["TARGET_RA", "TARGET_DEC", "FIBER_RA", "FIBER_DEC"]])
[(nan, nan, …
```

Replace NaN TARGET_RA/TARGET_DEC with FIBER_RA/FIBER_DEC values

---

py/desispec/scripts/qproc.py

Recent `spec_tests` exposures are consistently using `OBSTYPE=OTHER`. This PR ensures that `qproc` completely processes the exposure.
The change has been running (uncommitted) at KPNO since March but not on NERSC. As a result, images from `OTHER` exposures are not completing preprocessing and QA. Here are tests from 20240424 which were not processed by qproc,
https://nightwatch.desi.lbl.gov/20240424/exposures.html
versus two exposures processed with this change:
https://data.desi.lbl.gov/desi/users/sybenzvi/nightwatch/20240424/exposures.html

Enable processing of "OTHER" exp types in tests.

---

py/desispec/io/photo.py
py/desispec/test/test_photo.py

This PR is not on the critical path for Jura, but it would be nice to get it into a tag at some point. The only changes are to `io.photo`, which are not part of main production.
In essence, I've just added the option of matching exclusively to either the north (BASS+MzLS) *or* south (DECaLS) Tractor catalogs (rather than doing a resolve), as part of some photometric tests which I'm doing using photometry of objects in the overlap region.

optionally gather Tractor photometry from exclusively the 'north' or 'south' LS regions

---

py/desispec/io/meta.py
py/desispec/scripts/zproc.py

This PR adds the `rrdesi --model ...` option to the desi_zproc workflow so that redrock models are automatically output as part of the pipeline.
Example job script /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/rrmodel/run/scripts/tiles/cumulative/11607/20240408/ztile-11607-thru20240408.slurm ran 
```
srun -N 1 -n 64 -c 2 --gpu-bind=map_gpu:3,2,1,0 --cpu-bind=cores desi_zproc -t 11607 -g cumulative -n 20240408 -e 235004 -c a0123456789 --mpi --run-zmtl --max-gpuprocs 4
```
which ran rrdesi commands like
```
redrock.external.desi.rrdesi([
'-i', '/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/rrmodel/tiles/cumulative/11607/20240408/coadd-0-11607-thru20240408.fits',
'-o', '/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/rrmodel/tiles/cumulative/11607/20240408/redrock-0-11607-thru …
```

add rrdesi --model option to desi_zproc

---

bin/desi_proc_night
py/desispec/scripts/proc_night.py
py/desispec/test/test_workflow_queue.py
py/desispec/workflow/processing.py
py/desispec/workflow/queue.py
py/desispec/workflow/utils.py

This PR reduces the sleep time between job commits from 0.5s to 0.1s. It also introduces caching of Slurm jobid states, which can be checked before job submission instead of querying `sacct`. Since querying one ID or ten ID's was roughly the same amount of time, I made the choice of re-querying all jobids if any jobid in the list is not in the cache. This allows us to update information without loss of time and simplifies the code.
The reason we need to check sacct is that Slurm has two databases, one for operations that tracks current jobs, and one long-term database for storing job information. Roughly 10 minutes after a job stops, it is purged from the operational database and can only be identified via the long-term database using `sacct`. At that point a new job submitted to depend …

Reduce submission times with lower sleep and slurm state caching

---

py/desispec/correct_cte.py
py/desispec/io/meta.py
py/desispec/scripts/fit_cte_night.py
py/desispec/scripts/proc_night.py
py/desispec/workflow/calibration_selection.py

This is a draft pull request so that Stephen and Julien can see what I'm thinking for incorporating different CTE transfer functions.
The approach is:
- parameter names in CTE file go to PARAM1 ... PARAM5; simplified_regnault only using PARAM1 and PARAM2 and translates those into amplitude and fracleak.  regnault uses all 5 and translates those to cmax, fin, fout, alpha, beta.
- Add CTEFUNC{amp} to spec.yaml file.
There are related changes:
- The actual new transfer function implementations
- Change the get_transfer_function to do the parameter translation as well.
- Add a get_transfer_function_chi_guess_diff that returns some of the stuff needed to fit the CTE.  There we also need to have the function that evaluates the residuals, the initial guess, and the size of the difference step.
- …

Allow different CTE functions for different nights / cameras.

---

etc/desispec.module
py/desispec/scripts/makezmtl.py
py/desispec/scripts/qsoqn.py
py/desispec/zmtl.py

This PR makes the necessary changes to run the linear version of QuasarNET rather than the logarithmic. The code will automatically determine whether to use the linear grid or not by checking if the word "linear" appears in the weights file name.
This means that script is backwards compatible, such that if the environment variable $QN_MODEL_FILE is set to the old weights file (at `science/lya/qn_models/boss_dr12/qn_train_coadd_indtrain_0_0_boss10.h5`) then this script should reproduce previous results. Also unchanged is the default weights file, if no QN_MODEL_FILE is provided qsoqn.py will still load the old weights file by default. I am not opposed to changing this.
The new linear QuasarNET weights file is now located at `science/lya/qn_models/desi/qn_train_desi_guadalupe_linear.h5`. In …

Add necessary code to run linear QuasarNET

---

py/desispec/xytraceset.py

This PR fixes a bug in BADAMP header keyword parsing when multiple amps are bad.  The keyword is just the characters without commas, e.g. "AC" not "A,C".  This PR updates to support either case in the future though.
Previously fails, now works:
```
desi_compute_psf --input-image /dvs_ro/cfs/cdirs/desi/spectro/redux/j1/preproc/20231204/00207924/preproc-b5-00207924.fits.gz --input-psf /dvs_ro/cfs/cdirs/desi/spectro/redux/j1/exposures/20231204/00207924/shifted-input-psf-b5-00207924.fits --output-psf $SCRATCH/fit-psf-b5-00207924.fits --broken-fibers 342,400
```
I will self merge once tests pass so that we can update and run with this for pre-Jura testing.

fix multi-badamp parsing

---

py/desispec/scripts/proc.py
py/desispec/scripts/proc_joint_fit.py

This PR fixes another badamp related conceptual bug: PSF fitting rejects CCDs with >12.5% of the pixels flagged as having bad readnoise.  But now that we have better handling of bad amps that are pre-flagged as bad, we don't care what the readnoise is on those amps.
And example is night 20231205 where b5A and b5C are flagged as bad due to high readnoise.  desi_proc was discarding the b5 arcs (without actually counting it as a fatal error) and then the psfnight was failing due to missing individual exposure psfs.
With this PR
* bad readnoise is only counted if it is on pixels not already flagged as part of a known bad amp
* if it passes threshold, this is treated as an error so that the job will exit with an error.  i.e. we want to catch these cases and flag as bad in the exposure tables …

only count bad readnoise on amps not already flagged as bad

---

py/desispec/test/test_workflow_batch.py
py/desispec/test/test_workflow_queue.py
py/desispec/workflow/batch.py
py/desispec/workflow/processing.py

This PR adds support for specifying separate reservation names for CPU and GPU reservations, with either of them optionally being None, e.g. if we had a CPU reservation but not a GPU reservation.
Examples in $CFS/desi/users/sjbailey/spectro/redux/j1
```
desi_proc_night -n 20240409 --dry-run-level 3 --reservation blat &> submit-20240409-singlereservation.log
desi_proc_night -n 20240409 --dry-run-level 3 --reservation blat_cpu,foo_gpu &> submit-20240409-dualreservations.log
desi_proc_night -n 20240409 --dry-run-level 3 --reservation blat_cpu,None &> submit-20240409-cpuonlyreservation.log
```
grep for "sbatch" in each of those log files:
* singlereservation: all jobs have `--reservation=blat`
* dualreservation: jobs have `--reservation=blat_cpu` or `--reservation=foo_gpu` depending upon …

add reservation parsing for cpu vs. gpu

---

py/desispec/workflow/batch.py

This makes a minimal change to have nightlyflat jobs run on GPU's. This doesn't actually change the underlying code to utilize the GPU's, but the whole job is very fast and therefore not that inefficient. This simplifies the job scheduling logic when dealing with separate CPU and GPU partitions.

Move nightlyflat to gpu job

---

py/desispec/trace_shifts.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/queue.py

This PR includes 3 updates to make running Jura just a bit easier:
* `write_traces_in_psf` uses an intermediate temporary filename
* we tripped on this when a job had an I/O error while writing PSF traces, leaving behind a 0-length PSF file of the right name, tricking further re-submissions to skip over that step.
* Increase the tilenight job runtime by 5 minutes (10 minutes * 0.5 perlmutter-gpu speed factor).
* Update `queue_info_from_qids` to work in batches of 100 qids at a time when calling sacct.  I don't know what the upper limit is, but emperically 8*100 works but 800 doesn't.
`write_traces_in_psf` tested with
```
desi_compute_trace_shifts -i /dvs_ro/cfs/cdirs/desi/spectro/redux/jura/preproc/20220104/00116769/preproc-b4-00116769.fits.gz --psf …
```

tweaks for running jura

---

py/desispec/scripts/proc_night.py
py/desispec/test/test_workflow_calibration_selection.py
py/desispec/workflow/calibration_selection.py

This fixes a bug introduced by me in PR #2221 that is causing crashes in `determine_calibrations_to_proc()` when no valid flats are available on a night.
The fix is simple, we now check that there is at least one valid 120s flat before trying to add the cte flats. Given that we need a 120s flat to do the cte correction, this is a reasonable thing to do.
The traceback was the following:
```
File "/global/common/software/desi/perlmutter/desiconda/20240425-2.2.0/code/desispec/0.63.0/bin/desi_proc_night", line 137, in <module>
proc_night(**args.__dict__)
File "/global/common/software/desi/perlmutter/desiconda/20240425-2.2.0/code/desispec/0.63.0/lib/python3.10/site-packages/desispec/scripts/proc_night.py", line 429, in proc_night
cal_etable = …
```

Only select cte if have 120s flat in proc_night

---

py/desispec/test/test_workflow_calibration_selection.py
py/desispec/workflow/calibration_selection.py

This PR fixes #2247 where the pipeline was generating a ccdcalib job for camword a01456789 but later needing CTE corrections for z3 not included in that camword.
The underlying reason was that the job camword is tied to the selected dark, and `select_calibrations_to_proc` was picking the first calib dark instead of the one with the most available cameras.
With this PR, `desi_proc_night -n 20231028 --dry-run-level 1` now selects a different dark and generates a ccdcalib job for all cameras.
20231028 is the only night in Jura that I'm aware of that is impacted by this issue, though it is possible that other nights would pick a different dark with this branch.
Additional notes:
* I pulled the dark selection out into a function `select_calib_dark(etable)`.  Upstream from that function the …

select calib dark with most cameras; fixes 20231028 for Jura

---

py/desispec/scripts/procdashboard.py

This is a minor update to the pipeline dashboard that now expects the files for cameras with a badamp. Before recent updates to the code those cameras were excluded and therefore the dashboard was told to also exclude them.
I have tested it by running the new dashboard code on the month of May 2021 in Jura. In the main branch 20210503 has "overful" calibrations because they weren't expecting the badamp camera to be processed. The updated code shows correctly that they are correctly processed.
The updated dashboard is here: https://data.desi.lbl.gov/desi/spectro/redux/kremin/dashboard.html
Note the script could use some cleanup, but I don't attempt that here beyond what was needed for this change.

Update dashboard now that cals support badamps

---

py/desispec/scripts/proc_night.py
py/desispec/test/test_proc_night.py

Previously the camword for the linkcal jobs were given the default ('a0123456789') camword, but on at least one night we don't need all cameras and the night we were linking to didn't have all cameras. This updates the code to look at the current night under consideration and identify all good cameras available for at least one exposure. It then requests that union of good cameras as the camword. This does not check if the reference night has those cameras to link to, that is up to the person creating the override file to verify. The linkcal job will crash in that instance, at which time they'll have to find a different night to reference.
I've tested the code on the night that currently crashes in `main` and we now submit the correct camword:
`INFO:processing.py:499:create_batch_script: …

Define camword for linkcal 

---

py/desispec/scripts/procdashboard.py

This fixes a variable name typo introduced in PR #2258 affecting only the dashboard. I'll self merge.

fix row typo in dashboard

---

py/desispec/scripts/proc_night.py
py/desispec/workflow/processing.py

This contains two unrelated bug fixes identified with a corner case encountered in Jura.
The first was that if purging and rerunning a tile on a night with linking, `desi_proc_night` crashed when trying to rebuild it's internal state from the processing table and override file. That is now fixed.
The second is that the recently introduced camword derivation for linking jobs used a vstack command to combine the calibration etable and science etable, but if all calibrations have already been submitted then the calibration etable was `None` and vtack didn't like that. Now the default is an empty etable such that we can stack it.
The command:
`desi_proc_night -n 20210130 --tiles 80720 --complete-tiles-thrunight=20240410 --dry-run-level=3`
crashes in `main` but passes in this branch.

Pipeline Corner Case Bug Fixes

---

bin/desi_create_tiletable
py/desispec/scripts/zcatalog.py
py/desispec/tsnr.py

This PR adds several I/O optimizations and a placeholder script for creating a tiles-SPECPROD.fits file outside of the context of the tsnr afterburner.  This script is what is used for the tiles file currently in jura (as of 2024-05-24) but will need to be updated before the final Jura release.
* new script bin/desi_create_tiletable
* zcatalog uses /dvs_ro instead of /global, and glob instead of iterfiles
* tsnr caches the tsnr_ensemble instead of re-reading it from disk every time `tsnr2_to_efftime` is called

optimizations for creating specprod tiles table

---

py/desispec/scripts/group_spectra.py

This PR fixes a bug in header keyword propagation for healpix=0.  Previously
```python
if args.healpix:
spectra.meta['SPGRP'] = 'healpix'
spectra.meta['SPGRPVAL'] = args.healpix
...
```
was filling in the healpix headers for all healpix except 0, because 0 evaluates to False.  I changed this to `if args.healpix is not None`, i.e. if the option is set on the command line, propagate the value.
I intend to self-merge, tag, and then re-run Jura healpix 0 to fix the headers (because otherwise they also crash the summary catalog creation code).

fix healpix=0 headers

---

bin/desi_tsnr_afterburner
py/desispec/test/test_tilecompleteness.py
py/desispec/tilecompleteness.py

This PR closes #2250.
* `read_gfa_data()` returns the GFA summary file with the most recent date, independently of any label (`SV1`, `SV2`, `SV3`, `main`, `foobar`, etc.).
* `read_gfa_data()` is moved into `desispec.tilecompleteness`, which makes it easier to write a unit test.
* Cleaned up some unused import statements.

Refactor read_gfa_data function

---

bin/desi_compute_gain

Minor PR with changes to desi_compute_gain to work with CCDs read in 2-amp mode.
(uses the CalibFinder to find the list of amplifiers from the first image header)

Adapt desi_compute_gain to 2-amp mode

---

etc/desispec.module

This PR reverts the desispec modules file to use the old QuasarNET weights file, $DESI_ROOT/target/catalogs/lya/qn_models/qn_train_coadd_indtrain_0_0_boss10.h5
We'll use this one for daily until we've further debugged the new weights file + afterburners.  The new weights file qn_train_desi_guadalupe_linear.h5 was used in Jura and for data processed 20240603 - 20240616.
I've discussed with @akremin and plan to self merge to get this update in before tonight's processing (20240617).

revert QN_MODEL_FILE to old weights

---

bin/desi_resubmit_zpix

This PR refactors desi_resubmit_zpix to parallelize the file checking for dramatically faster runs.  It also prints all of the TODO items at the end instead of having them interspersed with N>>1 other log messages.
This PR is useful for Jura, but not urgent since we can run --dry-run outside of the jura env and it doesn't impact any actual processing.

parallelize zpix check

---

bin/desi_assemble_tilepix

This PR has a minimal fix for desi_assemble_tilepix needed for generating jura/healpix/tilepix.* .  Apparently parse_cameras works with a list of cameras but not an array of cameras.  It would be nice to fix that too, but for now I'm focusing on the minimal fix to be able to generate these tilepix files for Jura.
Note: merging this into the jura branch, not main.  Afterwards we'll make the final (?) 0.63.x tag for Jura, merge the jura branch back into main, and proceed with main for future development.  main is already ahead of jura for contributions not used in Jura.

fix desi_assemble_tilepix for Jura

---

py/desispec/io/util.py
py/desispec/scripts/zprocdashboard.py
py/desispec/test/test_io.py
py/desispec/workflow/proc_dashboard_funcs.py
requirements.txt

This updates the redshift dashboard to account for cross night information in the processing of a cumulative tile. This is important when on an earlier night e.g. 10 petals were available but on a later night e.g. 8 petals were available. Before the dashboard would show purple "overfull" values for such tiles because it was expecting 8 redrock files from the 8 petals on that night. Now it correctly identifies that there is petal information for all 10 petals available to the cumulative coadd from the previous night and expects 10 redrock files to be generated. 
I tested this on iron, jura, and daily. It worked on all three. Iron shows some missing pernight files, which upon further investigation were accidentally run and then deleted. The dashboard correctly identified them in the …

Add cross night information to zdashboard

---

py/desispec/io/meta.py
py/desispec/pixgroup.py
py/desispec/scripts/group_spectra.py
py/desispec/scripts/zproc.py
py/desispec/test/test_io.py
requirements.txt

This PR is for a branch originally started by @akremin .  It updates desi_group_spectra to filter by healpix immediately after reading each cframe, instead of collecting up all cframes and filtering at the end.  This saves memory, which was a problem during the Jura run.  I also updated this branch to use `findfile('cframe', ..., readonly=True)` for faster reads.
For context, the original implementation purposefully did not filter while reading because it was maintaining a cache of completely cframes that could be used for neighboring healpix without re-reading the same cframes multiple times.  However, using that cache feature was dropped in a previous refactor, and keeping all the cframes in memory simultaneously was blowing memory during Jura.
I have verified that the outputs are the …

healpix group spectra memory and I/O optimizations

---

py/desispec/scripts/group_spectra.py

This PR adds optional MPI parallelization to desi_group_spectra.  I have not yet integrated this into desi_zproc because that will require more plumbing on the zproc side, but at minimum this provides a standalone way to generate large healpix if needed so I'm opening this as an independent PR and will do the zproc integration in a followup PR.
e.g. one of our largest most problematic healpix in jura was special other 27258 with over 4000 input frame files.  This branch can group those spectra in 11 minutes with
```
HPIX=27258
time srun -n 64 -c 4 desi_group_spectra --mpi --healpix $HPIX \
--expfile $DESI_SPECTRO_REDUX/$SPECPROD/healpix/special/other/272/$HPIX/hpixexp-special-other-$HPIX.csv \
-o $SCRATCH/temp/spectra-special-other-$HPIX.fits -c …
```

optionally parallelize group_spectra

---

bin/plot_fiber_traces

This PR updates `plot_fiber_traces --fibers` to accept "true" fiber numbers 0-4999, not just the index per camera 0-499.  e.g. this fails in main but now works on this branch:
```
plot_fiber_traces -i exposures/20220102/00116442/psf-z1-00116442.fits \
--image preproc/20220102/00116442/preproc-z1-00116442.fits.gz \
--zscale --fibers 551
```
Previously this would have required `--fibers 51` instead.  That's not too hard in this case, but it's a pain when cutting-and-pasting lists of bad fibers from other cases, e.g. issue #2288 .
Caveats:
* this just does `fibers = fibers%500` so the above example also would have accepted `--fibers 2551` and done the same thing, even though fiber 2551 is a legitimate fiber number on a completely different camera.  User beware.  It appears that the input PSF …

plot_fiber_traces --fibers allow true fiber numbers, not just 0-499

---

bin/desi_tile_qa_reference
doc/changes.rst
py/desispec/io/fibermap.py
py/desispec/io/meta.py
py/desispec/io/photo.py
py/desispec/scripts/archive_tilenight.py
py/desispec/workflow/exptable.py

This PR fixes #2272.
This PR introduces a new environment variable, `DESI_TILES`, similar to `DESI_SURVEYOPS` and also uses `DESI_SURVEYOPS` more extensively.
`DESI_TILES` will be defined in desimodules (as a fix to desihub/desimodules#49).

Replace hard-coded paths with environment variables

---

py/desispec/scripts/zproc.py
py/desispec/tile_qa.py

This more fully solves the issue presented in issue #2263, before beginning the large implementation of cross-night dependencies needed for issue #2264.
First, in `zproc.py` it now requires the input exposure-qa's to exist before proceeding in producing the tileqa file. Previously it would run even if they didn't exist.
Second, this fixes a typo in `tile_qa.py` such that the exposure-qa file will be created for each night if the code is run and the exposure-qa file is missing. Of course, the first change in this PR makes it so that this doesn't occur when running from `zproc`, but this is still a useful fix when running outside of the pipeline where old data may not have the exposure-qa files pre-generated.
I ran a test on tile 9203  observed on nights 20240408 and 20240409 with exposures …

Have zproc require input exposure-qa files for tileqa 

---

py/desispec/pixgroup.py
py/desispec/scripts/group_spectra.py
py/desispec/test/test_pixgroup.py

This PR fixes the desi_group_spectra large number of warnings from incorrectly merging per-exposure keywords reported in #2200.
The vast majority of keywords in the frame FIBERMAP HDUs are inherited from the raw data, and either conflict when combined (humidities, temperatures, exposure times...) or are fairly meaningless for a fibermap even if they don't conflict (CCD dimensions, clock settings...).  This PR treats it as an opt-in list to propagate: by default only
```python
keep_keywords = ['SURVEY', 'PROGRAM', 'EXTNAME', 'LONGSTRN',
'INSTRUME', 'OBSERVAT', 'OBS-LAT', 'OBS-LONG', 'OBS-ELEV', 'TELESCOP']
```
and if `onetile=True` it also propagates keywords related to the input fiberassignment, which apply to all observations of a single tile but not coadds across tiles (healpix).
I …

desi_group_spectra  header propagation cleanup

---

doc/changes.rst
etc/desispec.module

@weaverba137 in PR #2294 it appears that we forgot to update the etc/desispec.module file to not set the environment variables that are now set in desimodules.  This PR updates the modules file to *not* set:
- DESI_SPECTRO_CALIB
- DESI_SPECTRO_DARK
- MPICH_GNI_FORK_MODE
- KMP_AFFINITY
- QN_MODEL_FILE
- SQ_MODEL_FILE

don't set envs now set in desimodules

---

py/desispec/io/util.py
py/desispec/parallel.py

This PR fixes #2269 by merging any per-rank log files leftover from a previous crash before proceeding with a new stdout/stderr log redirect per-rank.  Previously these logfiles would get overwritten, losing the record of the crash.
I tested this with $CFS/desi/users/sjbailey/dev/stdout_redirect/mpi_test_redirect which purposefully crashes a requested rank.  e.g.
```
$> srun -n 4 python mpi_test_redirect
Starting up; will crash rank -1
INFO:parallel.py:465:stdouterr_redirected: Begin log redirection to blat.log at Thu Jul 25 17:46:51 2024
INFO:parallel.py:524:stdouterr_redirected: End log redirection to blat.log at Thu Jul 25 17:46:51 2024
All done
$> ls
blat.log  mpi_test_redirect
$> srun -n 4 python mpi_test_redirect 2
Starting up; will crash rank 2 …
```

cleanup redirected stdout crash before re-redirecting

---

py/desispec/scripts/qsoqn.py

This PR addresses #2293 and updates the QuasarNET afterburner to run using a prior defined based on the QuasarNET redshift rather than a constant width prior across the entire redshift range. 
Using the width of the QN output grid boxes in redshift space we determine that the width of the prior goes as $\Delta z = a (1 + z)$. We can calculate the necessary value of $a$ from the QN output grid bin widths. The following snippet of code will calculate the width necessary for the new RR priors, assuming QuasarNET uses 13 output bins (which any and all weights files we've used thus far in DESI do) and a logarithmic scaled grid:
https://github.com/desihub/desispec/blob/07bdb749263d2c52eadfa9d00de49f9dc7ecb5bc/py/desispec/scripts/qsoqn.py#L312-L322
This value is about `0.0814` Note that this …

Rerun Redrock with dynamic priors based on QN redshift

---

py/desispec/io/meta.py
py/desispec/scripts/zproc.py
py/desispec/test/test_io.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/redshifts.py

This PR adds support for custom groups of exposures for zproc, e.g. to enable 1x_depth processing through zproc itself, instead of running the underlying commands by hand like was done for previous prods.  The key update is adding the concept of a user-specified "subgroup" to findfile and zproc to be used for custom groupings.  For pernight and cumulative, subgroup defaults to night, and perexp and healpix also work as before.
Examples in /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/jura1x
```
desi_zproc --batch --nosubmit -t 80605 \
--groupname 1x_depth --subgroup 1 -n 20210205 20210130 -e 74781 73702
desi_zproc --batch -q debug -t 80605 \
--groupname 1x_depth --subgroup 2 -n 20201215 20210205 -e 67975 74782
desi_zproc --batch --nosubmit -t 1000 -n 20210517
```
The first and last …

support custom groups for zproc, e.g. 1x_depth

---

bin/desi_night_qa
py/desispec/night_qa.py

This PR introduces a new plot to diagnose possible cte occurences.
The plot was suggested by @schlafly here: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1722543734755599?thread_ts=1722538227.361809&cid=C01HNN87Y7J
Copying from there: "load the 1 s flat, do a row by row extraction, plot the residuals."
In addition to @schlafly initial "recipe", I made these changes:
- subtract the median value of the residuals (`res_median`, reported on the plot);
- restrict the color range to (-2, 2);
- add per-amplifier infos:
- the amplifier name, with its related region on the CCD (using 0-index convention);
- any existing correction (`OFFCOLS` and/or `CTECOLS`): column range is reported, along with a line to visualize it.
The plots come as a new pdf file (`ctedetrowbyrow-NIGHT.pdf`), with one …

Night_qa: introduce new ctedet row-by-row diagnosis plot

---

doc/changes.rst
py/desispec/calibfinder.py
py/desispec/io/fibermap.py
py/desispec/maskbits.py

This PR addresses issue #2304
- Add desispec.maskbits.fibermask  bits NEARCHARGETRAP ("Fiber trace near charge trap in one of the CCDs") and VARIABLETHRU ("Fiber has throughput variations we cannot model well")
- Add NEARCHARGETRAPFIBERS and VARIABLETHRUFIBERS to the list of keywords of calibfinder.badfibers
- Add code in desispec.io.fibermap.assemble_fibermap to set NEARCHARGETRAP and VARIABLETHRU fibermask bits by parsing the DESI_SPECTRO_CALIB configs of all cameras using the calibfinder.badfibers function and the raw fits file headers.
Example:
```
from desispec.io.fibermap import assemble_fibermap
from desispec.maskbits import fibermask
hdulist = assemble_fibermap(night=20220102, expid=116442)
fmap = hdulist["FIBERMAP"].data
print(fmap["FIBER"][(fmap["FIBERSTATUS"] & …
```

More FIBERSTATUS bits

---

doc/changes.rst
py/desispec/preproc.py

This PR addresses issue #2249.
If the keyword READNOISEPERROW is present in the calibration configuration, and the value contain the amp being preprocessed, the value of the read noise per CCD row is used instead of the average if this value is a positive 4 sigma outlier.
Here are some plots illustrating what happens. The first figure is a profile of the read noise per CCD row of amps A and C for one zero of SM7 b6 (it's the same situation for most images of b6 before we replaced the FEE in 2024/05/23).  One can see the problematic amp C with excess read noise in some rows.
Now looking only at amp C. The new code records for the read noise the profile in orange (if the config contains 'READNOISEPERROW: C') instead of an average over all rows.
Zoom
And this is what it looks like as images. …

Read noise per CCD row based on keyword READNOISEPERROW in config

---

py/desispec/io/fibermap.py
py/desispec/test/test_binscripts.py
py/desispec/test/test_bootcalib.py
py/desispec/test/test_calibfinder.py
py/desispec/test/test_extract.py
py/desispec/test/test_fiberflat.py
py/desispec/test/test_pixgroup.py
py/desispec/test/test_qlextract.py
py/desispec/test/test_scripts.py
py/desispec/test/test_spectra.py
py/desispec/test/test_util.py

This PR
* fixes #2315 (calib-related unit tests failing)
* fixes #2030 (skipped bootcalib tests)
* does general cleanup of tests to use tempdirs instead of the current directory
For the newly failing unit tests (#2315), the problem was triggered by assemble_fibermap in PR #2313 needing CalibFinder to look up which fibers need FIBERSTATUS bits set, but
1. the unit tests were checking corner cases in very old data that didn't have a dark model in $DESI_SPECTRO_DARK, causing the CalibFinder creation to crash even though assemble_fibermap itself doesn't need a dark; this was fixed using `fallback_on_dark_not_found=True`.  I considered updating CalibFinder itself to only crash if a missing dark was requested (instead of crashing at initialization time whether or not the dark was needed), but …

Fix unit tests

---

bin/desi_merge_psf
py/desispec/scripts/proc.py
py/desispec/scripts/specex.py
py/desispec/workflow/desi_proc_funcs.py

The function merge_psf was modified a few month ago to include the input PSF in order for the fit to finish even with bad amplifiers. This does not work if the input PSF is used only for traces as is the case for simulations. This PR adds an option to the processing so that we can run with sims.

Dont merge with psf input

---

py/desispec/io/meta.py

This PR addresses https://github.com/desihub/desispec/issues/2324, i.e. it sets `PROGRAM` to `bright` or `dark` for the `survey == "special"` tiles -- including the non-observed ones, thus replacing the `other` default value.
This information can be obtained from the `GOALTYPE` keyword in the fiberassign files.
For reference, this page has that info for all tertiary programs: https://data.desi.lbl.gov/desi/users/raichoor/tertiary-status/tertiary-status.html.
For the record, here is how I built the list (parsing the fiberassign folder where I design tiles, thus also grabbing non-observed-yet tiles):
```
faspdir = "/global/cfs/cdirs/desi/survey/fiberassign/special"
fns = glob(os.path.join(faspdir, "202?????", "fiberassign*fits*"))
fns += glob(os.path.join(faspdir, "202?????", "08?", …
```

Faflavor2program special tiles: fix other to bright or dark

---

py/desispec/fiberbitmasking.py
py/desispec/test/test_fiberbitmask.py

This PR adds FIBERSTATUS bit VARIABLETHRU to the mask of bad bits that should not be used for sky fibers and standard stars.
Most of the changes here are adding comments and unit tests to confirm current behavior; excluding VARIABLETHRU for sky and stdstars is the only functional change here.
After discussing with @julienguy, we decided to treat NEARCHARGETRAP as strictly informative and *not* exclude it from sky fibers since it is actually a per-AMP problem, not a per-FIBER problem, but we don't structurally have a way to encode that.
Related to #2304.

FIBERSTATUS VARIABLETHRU bad for sky and stdstars

---

py/desispec/tpcorrparam.py

This PR has the updates to the tpcorr creation code used for the k1 production, discussed in https://github.com/desihub/desispec/issues/2305 .  Specifically, it improves on the existing tpcorr creation code in the following ways:
- it updates the tpcorr gathering code to include both the measured residual tpcorr as well as the model tpcorr already applied
- it updates the tpcorr parameter computation to use the product of the model & residual tpcorr (to obtain the "total" measured tpcorr)
- it adds multithreading to the tpcorr gathering code
- it centralizes the 'bad data' marking to make_tpcorrparam_files and applies it to both the PCA and spatial modeling
- it changes the treatment of stuck fibers such that we don't consider multiple measurements of tpcorr if the fiber hasn't moved. …

Update tpcorr creation code.

---

bin/desi_compute_large_trace_shifts
doc/api.rst
py/desispec/large_trace_shifts.py
py/desispec/scripts/large_trace_shifts.py

Code to compute large trace shifts based on detection and match of spots in CCD image from an arc lamp exposure.
Example (based on data from the SM10 collimator mirror exchange):
```
cp $DESI_SPECTRO_REDUX/daily/calibnight/20220612/psfnight-r1-20220612.fits .
desi_preproc -i $DESI_SPECTRO_DATA/20220612/00139415/desi-00139415.fits.fz  --cam r1 preproc-r1-00139415.fits
desi_preproc -i $DESI_SPECTRO_DATA/20220613/00139516/desi-00139516.fits.fz  --cam r1 preproc-r1-00139516.fits
desi_compute_large_trace_shifts --ref-image preproc-r1-00139415.fits --image preproc-r1-00139516.fits  --ref-psf psfnight-r1-20220612.fits  -o psf-r1-first.fits --plot
desi_compute_trace_shifts --image preproc-r1-00139516.fits --psf psf-r1-first.fits --arc-lamps --outpsf psf-r1-refined.fits
```
scatter plot of …

Large trace shifts

---

bin/desi_create_tiletable
bin/desi_tsnr_afterburner
py/desispec/tilecompleteness.py
py/desispec/tsnr.py

This PR closes #2333.
This PR addresses:
* Warning when performing a sum over masked values in `desispec.tilecompleteness.compute_tile_completeness_table()`.
* Warn and replace unmasked NaN with zero when performing sums.
* Warn and replace unmasked NaN with zero when copying GFA summary data into exposure tables in `desi_tsnr_afterburner`.
* When replacement is required, data are copied, so that input data are not modified.
This PR does *not* address:
* Standardizing the operation of `desi_tsnr_afterburner` and/or `desi_tiles_completeness` at the end of specprod processing, but see #2335.
* A full refactor of `desi_tsnr_afterburner`, *i.e.* #1724.
@sbailey, we may want to set up an operational test of this before merging.

Safety checks and warnings for NaN or masked columns.

---

py/desispec/fiberbitmasking.py
py/desispec/fluxcalibration.py
py/desispec/sky.py
py/desispec/test/test_fiberbitmask.py
py/desispec/test/test_flux_calibration.py
py/desispec/test/test_sky.py

This PR fixes the usage of FIBERSTATUS bit VARIABLETHRU.  Putting it into desispec.fiberbitmasking for kind=sky and stdstars was not correct; that not only excludes it from being used for sky and stdstars, but also masks out the entire fiber with ivar=0 when applying sky subtraction.  This PR removes that bit from fiberbitmasking and moves the logic into `desispec.sky.get_sky_fibers` and `desispec.fluxcalib.isStdStar`.
I tested the preservation of ivar>0 with
```
cd /global/cfs/cdirs/desi/spectro/redux/k1/exposures/20230612/00185028
desi_process_exposure -i frame-z9-00185028.fits.gz \
--fiberflat fiberflatexp-z9-00185028.fits.gz \
--sky sky-z9-00185028.fits.gz \
--calib fluxcalib-z9-00185028.fits.gz \
-o $SCRATCH/cframe-z9-00185028.fits
```
With main, this results in fiber 4891 having …

fix usage of FIBERSTATUS VARIABLETHRU

---

py/desispec/spectra.py
py/desispec/test/test_spectra.py

This is a bookkeeping cleanup PR for `desispec.spectra.stack` for the case of stacking multiple tile-based spectra across different tiles.  Previously this case generates a bunch of warnings like:
```
from desispec.io import read_spectra
from desispec.spectra import stack as stack_spectra
c1 = read_spectra('21/20210503/coadd-0-21-thru20210503.fits')
c2 = read_spectra('211/20210501/coadd-3-211-thru20210501.fits')
cx = stack_spectra([c1,c2])
...
WARNING: MergeConflictWarning: Cannot merge meta key 'TILEID' types <class 'int'> and <class 'int'>, choosing TILEID=211 [astropy.utils.metadata.merge]
WARNING: MergeConflictWarning: Cannot merge meta key 'TILERA' types <class 'float'> and <class 'float'>, choosing TILERA=217.828 [astropy.utils.metadata.merge]
```
and it incorrectly propagated …

cross-tile spectra stack header cleanup

---

bin/desi_tsnr_afterburner
py/desispec/scripts/procexp.py
py/desispec/tsnr.py

This PR fixes 2 issues in TSNR calculation:
- avoid situations where we apply a correction based on a ratio of 2 small numbers for fibers that are off target (and have a low TSNR anyway).
- use the cframe.mask==0 and cframe.ivar>0 instead of frame.mask==0 and frame.ivar>0 in the computation of TSNR because some spectal values are masked during calibration.

Fix TSNR value when cframe mask or ivar=0 

---

py/desispec/scripts/zproc.py

This solves the issue identified in Issue #2342 that was introduced in PR #2306 .
zproc allows many modes to process healpix based redshifts and tile-based redshifts in per-exposure, per-night, cumulative, and custom varieties. Because of this the input structure and handling of information is complex and sometimes dependent on the type of job being requested. 
Originally the code looped over expids and night to get the list of expid-night combinations, but these are unique lists of the requested variables rather than index-matched lists. However, for pernight, cumulative, and custom tile-based jobs an exposure_table is populated from the set of nights and then subselected to the requested set of exposure ID's. So this table has the index-matched information we want to use. 
This PR …

Fix indexing bug in zproc expqa check

---

py/desispec/scripts/proc_night.py
py/desispec/scripts/submit_prod.py
py/desispec/workflow/calibration_selection.py
py/desispec/workflow/proctable.py

This PR implements three small changes to the workflow.
First I improved the logging of the processing table caching, which was printing a line for every file it read it. It now prints one line with a list of files it will load in the most concise way possible. This just improves the logging but doesn't impact the downstream jobs at all.
Second I changed the order of operations in desi_submit_prod so that it now checks for the existence of a processing table first before checking the number of jobs in the queue. This allows us to skip hundreds of completed nights without needing to query the queue each time. This resolves Issue #2347 .
Third, I fixed a bud in the calibration submission that arose when cleaning up nights that crashed due to Slurm issues. When some calibrations are in the …

Minor Kibo workflow fixes

---

bin/desi_use_reservation
py/desispec/workflow/queue.py

This PR adds a new script `desi_use_reservation` to assist in moving jobs from the regular queue into a batch reservation while running productions.  It moves "just enough" jobs to fill the reservation, but then pauses so that we don't overfill it because
1. once a job is in a reservation, you can't move it back into the regular queue (you have to move it to a different reservation, or otherwise cancel and resubmit)
2. reservations are handy for catching up on high priority reruns of specific jobs and we don't want thousands of other jobs backed up in the reservation queue.
The script auto-derives the size of the reservation, whether it is a CPU/GPU partition, and what regular queue jobs are eligible to be run.  It prioritizes "bottleneck" jobs like ccdcalib, nightlyflat, psfnight over …

desi_use_reservation for prods

---

py/desispec/night_qa.py

This PR should address:
- https://github.com/desihub/desispec/issues/2356: ignore `SCIENCE` exposure with no associated fiberassign file (kind of a bugfix, actually...);
- https://github.com/desihub/desispec/issues/2357: ignore tileids for a given survey if it s not in `tiles-{survey}.ecsv`;
- https://github.com/desihub/desispec/issues/2358: bugfix (in `create_petal_nz()`) to restrict to `sv1`, `sv2`, `sv3`, `main` in the case where all the tileids should be ignored.
Outputs of the `desi_night_qa` runs for those three cases / nights are here: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v28/
For 20201214 and 20210917, the `petalnz-{night}.pdf` file is empty, as no tiles are kept for the analysis.
I didn t run `desi_night_qa` for other nights; hopefully the changes are …

Nightqa: kibo fixes

---

bin/desi_tsnr_afterburner

While looking at the backup efftime calculations, I spotted this place where there is a check for len(indices) where indices is a boolean mask (seems to be an IDL'ism). 
I think the current code is not what the author meant, but probably still harmless. It's probably still better to fix.

fix a logical, but likely harmless indexing bug with backup efftime

---

bin/desi_proc_night
bin/desi_resubmit_queue_failures
py/desispec/scripts/proc_night.py
py/desispec/workflow/processing.py
py/desispec/workflow/queue.py

This PR addresses Issue #2350  and Issue #2329 . It also improves the queue querying by removing COMPLETED jobs from the list of Slurm job id's to request information about, since we already know what happened to those. This could be expanded to all "final" states, but for now I have left it as COMPLETED which is the most common final state in the processing tables and I'd like to think a little harder about any ramifications of not querying for other "final" states.
This solves #2350 by identifying failed dependencies and not submitting them. Instead printing a message notifying the user of the failed dependency and printing what it would have attempted had it not been for the failed dependency. It assigns a STATUS of "UNSUBMITTED", which is the outcome of the code in `main`, except that …

Improvements to Workflow Queue Tools

---

bin/desi_tsnr_afterburner
py/desispec/tilecompleteness.py

This PR:
* Updates `desispec.tilecompleteness.merge_tile_completeness_table()` to add an `UPDATED` column for database use.
* Closes #2367. Warnings now will only be printed if the corresponding exposure table entry is not already set to zero.
* When changes to GFA entries are detected, the night is recorded, which modifies the input to `compute_tile_completeness_table`. In one scenario, delayed GFA processing can result in updates to the tiles file, even if a night was not included in `--nights $NIGHT`.
* Adds some cosmetic and documentation changes to `desi_tsnr_afterburner`.
Open questions:
* There was an open question about how to return the output of `one_night()` to `main()` when running in MPI mode.  Is `desi_tsnr_afterburner` ever run in MPI mode?
* Why are `args.expids` and …

Add UPDATED timestamp column

---

py/desispec/scripts/zcatalog.py

Some early tiles in the `daily` specprod have `zbest` instead of `redrock` files. To support loading `daily` into a database, these need to be read by `desispec.scripts.zcatalog`.  In this PR:
* `read_redrock` detects whether a `zbest` file is being opened and attempts to reconstruct its output as best as possible to match a `redrock` file.
* Do not require the tiles file to be a FITS file.
* When writing out zcatalog files, include comments on columns as well as units.
Open questions:
* Do we want to put any more effort toward recovering missing data? For example, `MEAN_PSF_TO_FIBER_SPECFLUX` in the (coadded) fibermap table or the entire `TSNR2` table missing from `zbest` files?
* In order to reduce code complexity, in this PR, `read_redrock` *always* converts the per-exposure fibermap …

Support reading zbest redshift files

---

bin/desi_tsnr_afterburner
doc/changes.rst
py/desispec/specstatus.py

This PR removes the `UPDATED` column from a `tiles` table so it remains compatible with the `specstatus` table.

specstatus compatibility fix

---

py/desispec/scripts/coadd_spectra.py
py/desispec/scripts/zproc.py

This PR implements #2382 to have zproc select whether it needs to run `desi_group_spectra` (to generate both spectra and coadd files) or just run `desi_coadd_spectra` (to generate a coadd file from a pre-existing spectra file).
I tested this with a micro-prod in `$CFS/desi/users/sjbailey/spectro/redux/l1`.
In healpix/main/dark/100 I created dirs for healpix 10000 linking to the kibo spectra file, and healpix 10001 which did not link the spectra file.  
In tiles/cumulative/1000/20210517 I created links to spectra files for all petals except petal 0.
I then rank `desi_zproc --batch --nosubmit ...` to create batch files and ran them for this tile / these healpix.  The jobs correctly used the links if they existed (by calling only desi_coadd_spectra), and if they didn't exist it correctly …

zproc run group_spectra vs. coadd_spectra

---

py/desispec/scripts/zproc.py

This PR provides two changes to `desispec.scripts.zproc.main` to enable it to be called from other scripts:
* Return an integer error code instead of calling `sys.exit` directly.  Previously even upon success, it would call `sys.exit(0)` instead of returning to the calling function.  The command line script `bin/desi_zproc` already includes `sys.exit(zproc.main())` so that did not need to be changed.
* Generate the command line from input `args` or `sys.argv`.  This is needed for the `--batch` option, which previously assumed the command line was coming only from `sys.argv` which isn't the case if a wrapper script is calling `zproc.main` with a list of strings.
* Caveat: if the wrapper script calls `zproc.main` with an `args.Namespace` object, this will still incorrectly generate the …

enable zproc.main to be called from other scripts

---

py/desispec/scripts/proc_night.py

desi_proc_night is designed to pick up where it left off based on information saved in the processing_table. However, there was a bug in the code that applies only to nights with some processing table entries and no science data where it was exiting due to an `if` statement checking whether there were new science exposures. The `if` statement was meant to speed up the exiting of the script so that it didn't need to run multiple computationally intensive functions just to arrive at the same conclusion. Therefore, I decided not to remove the logic, but improve it such that it desi_proc_night still quickly exits if no new science exposures have been observed while fixing the case that was failing before.
Case that was failing before:
We had processed 4 arcs but nothing else. (This arose due …

Allow desi_proc_night to restart mid processing in calibrations

---

py/desispec/tsnr.py

Following recent discussion on slack  @schlafly 
This is a PR (in development) addressing some issues with the effective exposure times of backup program
At the moment that just does removes the dust extinction correction when computing the tsnr2 for gbbackup/backup tracers.
* Another change that potentially needs changing is the nominal brightness for Poisson term
https://github.com/desihub/desispec/blob/801464161cc6385ed8f1fe185f65bcda423f5b43/py/desispec/tsnr.py#L588C9-L589C65
* Change of the template for backup program ? 
* And changes to desietc ? 
I would appreciate here any suggestions on the easiest way to test the effect of changes of tsnr.py on individual exposures without running the full pipeline. That would help understand the effect of changes.

Effective exposure times of backup program

---

py/desispec/efftime.py

Address the last point in the #2370 
by removing the E(B-V) factor for backup survey in efftime.py

get rid of the ebv factor in the backup efftime calculation in one more code location

---

py/desispec/scripts/qsoqn.py

This PR requires desihub/redrock#320 and fixes:
* #2299 (now it runs both HIZ and LOZ templates in a single call to Redrock, thus treating the overlap region self-consistently)
* #2281 (now it writes temporary files in the output directory instead of the input directory)
* #2398 (now it includes header keywords to record code versions, the location of $RR_TEMPLATE_DIR, $QN_MODEL_FILE, and exactly which Redrock template files were used)
I have not addressed #2375 in this PR because that will change the data model of the QN output in more substantive ways so I want it isolated in its own PR.
Heads up @abrodze @dylanagreen @akremin

QuasarNet afterburner updates part I

---

py/desispec/scripts/procdashboard.py
py/desispec/scripts/zprocdashboard.py
py/desispec/workflow/proc_dashboard_funcs.py

This provides an update to `desi_proc_dashboard` and `desi_zproc_dashboard` to enable them to use the processing tables and display the current job status of the Slurm job, if available. If no Slurm job can be associated with the entry "unknown" is listed and highlighted in orange as an unexpected result. The coloring of all completed rows remains the same unless the files on disk differ from what is expected from the Slurm status. In those cases, the rows will be colored to alert the user.
If jobs are pending or running, they are shown in black and white so as not to draw attention to the incomplete job.
This PR also adds long overdue enhancements to speed up the codes and makes incremental progress in reducing the amount of repeated code between the two dashboards.
Test outputs from …

Use the Slurm status of a job to color and inform the processing dashboards

---

py/desispec/scripts/qsoqn.py

This PR updates the QuasarNet afterburner to
* Not re-run Redrock on SKY fibers that we know we want to discard anyway
* Add additional columns to the output
* Rename columns for consistency
* Use astropy Table instead of pandas dataframe to reduce number of different table libraries to deal with
New format:
```
Column              dtype   Comment
TARGETID            i8  
RA                  f8  
DEC                 f8  
DESI_TARGET         i8  
IS_QSO_QN_NEW_RR    b1
SPECTYPE_RR         S6      Renamed SPECTYPE->SPECTYPE_RR; S10->S6
Z_RR                f8      f4->f8 (increase precision back to orig)
Z_QN                f4
C_LYA               f4
C_CIV               f4
C_CIII              f4
C_MgII              f4
C_Hbeta             f4
C_Halpha            f4
Z_LYA               f4
Z_CIV …
```

Update QuasarNet afterburner outputs

---

py/desispec/efftime.py

In #2395,  the ebvfac was still used for one more calculation of efftime (for the photon noise computation). 
The patch fixes that issue.

backup program, one more place the ebv factor was still used

---

py/desispec/scripts/proc_night.py
py/desispec/workflow/processing.py
py/desispec/workflow/queue.py

This PR fixes a limitation in `desi_proc_night` for resubmissions. In current main it trys to resubmit jobs, but refuses if any job has been resubmitted twice (for a total of three processing attempts). Now it will try to process all jobs 3 times (2 resubmissions) before quitting on a given job. The code only refuses to proceed if a calibration continues to fail, otherwise it will proceed with submitting future tiles since issues on a given tile are sometimes independent and worth attempting.
The logic for `desi_resubmit_queue_failures` remains effectively unchanged. It resubmits any job that is incomplete, up to a default 100 attempts. We've never come close to running a job that number of times.
Minor note -- I can't reproduce the doc test error at NERSC, and can't find the issue in the …

Resubmit all jobs in daily twice before giving up in desi_proc_night

---

py/desispec/io/filters.py
py/desispec/io/raw.py
py/desispec/pixgroup.py
py/desispec/spectra.py
py/desispec/tsnr.py

This PR addresses several import speed issues identified in #2379, especially for `desispec.io`.
`desispec.io`: deferring imports of specutils, speclite.filters, and desispec.preproc improves "import desispec.io" from 4.1 seconds to 1.3 seconds (best of 5, pwd on scratch).  The remaining time is dominated by importing astropy.table (1.0 sec), which would be messy to defer everywhere.
`desispec.tsnr`: deferring import astropy.convolution improves "import desispec.tsnr" from 2.9 to 2.3 sec. Remaining big imports are astropy.table and astropy.coordinates via desiutil.dust.
`desispec.pixgroup`: removing unused import healpix improves "import desispec.pixgroup" from 3.7 to 3.15 sec.  Remaining big imports are desispec.tsnr (could be deferred, though this is a bit messy since TSNR is …

improve top-level import speed with deferred imports

---

bin/desi_night_qa
py/desispec/night_qa.py
py/desispec/scripts/preproc.py

This resolves Issues https://github.com/desihub/desispec/issues/2401 and https://github.com/desihub/desispec/issues/2412. It skips over steps where the output file already exists (except for HTML), unless `--recompute` is given. Previously it raised an error if the file existed and `--recompute` wasn't set. It also adds two new options, `--skip-cal-steps` and `--skip-dark-steps`. If `--skip-cal-steps` is set then none of the calibration steps are run, even if provided in `--steps="list,of,steps"`. If `--skip-dark-steps` is set then none of the steps involving calibration darks are performed, even if specified in `--steps="list,of,steps"`. These are both useful when rerunning nightqa after "cleaning up" science tiles on a night in daily operations where the calibrations haven't changed. …

Update nightqa multiprocessing and add new options for skipping some steps

---

py/desispec/fluxcalibration.py
py/desispec/test/test_flux_calibration.py

Proposed  fix to #2420 
I've added an extra test is for test_fluxcalibration which tests  a case of infinite S/N spectra, but finite S/N for calibration vector. In that case the correct S/N of the flux-calibrated spectrum should be the same as of the calibration vector 
Previously the tests only considered the case of infinite S/N fluxcalib vector.

Fluxcalib variance fix

---

py/desispec/qa/qa_quicklook.py
py/desispec/scripts/qproc.py
py/desispec/scripts/trace_shifts.py
py/desispec/trace_shifts.py

This is the proposed followup from #2386 (assuming it's merged)
I propose to save the trace-shift offsets (in wavelength) in the psf file, to allow monitoring/improvement/debugging.
The extension/column names are somewhat temporary/can be changed if needed.
The increase in the file size from this is tiny ~ 5% for ~ 1Mb sized psf files. 
One could in principle make this optional, i.e. save the offsets if some command-line argument is passed.

save the trace shift offsets in the psf file

---

py/desispec/scripts/qproc.py

The function `fit_trace_shifts` now outputs three data structures instead of a single `XYTraceSet` instance when `shift_psf` is set to `True`. This fix will unbreak qproc for processing of science and calibration exposures ([see nightwatch#444](https://github.com/desihub/nightwatch/issues/444)).

Update to new output from fit_trace_shifts.

---

py/desispec/scripts/zcatalog.py

This PR updates the `read_redrock` function to handle many different styles of per-tile redshift catalogs and return consistent results.
Note that some columns are created with dummy values. For example, when reading from zbest files, there is no obvious way to re-generate the TSNR2 columns (unlike regenerating the fibermap and per-exposure fibermap columns).
If there _is_ an easy way to re-generate TSNR2 columns, we should do that.
I've generated `ztile-*-*-cumulative.fits` files for all survey-programs in `daily` and the columns were consistent across all files, and also basically the same as `loa`.

Fix zcatalog columns when reading from many epochs of redshift catalog types

---

bin/desi_proc_night
py/desispec/scripts/proc_night.py

This adds a new feature in `desi_proc_night` that is turned off by default. When explicitly enabled it prevents the code from trying to resubmit old jobs in the processing table that were found to have failed, timed out, etc.
The reason for this feature is that I'm working in the daily prod on old nights where multiple problems exist. I want to be able to solve the problems one by one, but the code crashes when trying first to resubmit old jobs that can no longer be run without special intervention.
I've tested that this solves my current problem and the code works fine with this minimal change.

Add option to not resub failed exposures in proc_night

---

.github/workflows/python-package.yml
doc/changes.rst
py/desispec/test/test_fiberflat.py
setup.py

This PR is similar to desihub/desitarget#832, restoring the ability to pip install desispec with the latest desiutil that no longer has DesiTest.  This will remove the ability to run `python setup.py test`, but we've been using `pytest` with desispec for awhile now.
I expect this might also enter into github actions dependency hell unrelated to the changes here, so I'll get that sorted out on the desitarget side first.

fix install without DesiTest

---

bin/desi_compute_pixmask
py/desispec/ccdcalib.py
py/desispec/io/raw.py
py/desispec/preproc.py
py/desispec/scripts/preproc.py

This PR adds the option to only use a "good" section of the overscan region for preproc. This is done by reading the GOODBIASSEC{amp} parameter from the yaml file and it overrides BIASSEC{amp} in the header.
This is option is needed to fix the overscan contamination issue https://github.com/desihub/desispec/issues/2433 in z1 (amps A and C). The updated yaml files (with the GOODBIASSEC parameters added in sm10-z.yaml) are already committed to svn, but they won't do anything until this PR is merged.

Add option to select "good" overscan region in preproc

---

bin/desi_purge_night
doc/api.rst
py/desispec/scripts/purge_night.py
py/desispec/scripts/purge_tilenight.py

This solves issue #2388. desi_purge_night as it exists in the main branch removes all of the directories and files associated with the specified night, but doesn't remove future cumulative redshifts that used the data being deleted. This update now does that by leveraging the existing `desi_purge_tilenight` code, which will remove future redshifts for a specified set of tiles.
In implementing I've also refactored the scripts so that the code is under `/py/desispec/scripts/purge_night.py`. I've also updated it to use `desiutil.log` rather than `print` statements, and to share common code with `desi_purge_tilenight`.
Note: lots of tests are failing because of a `fitsio` issue that appears to be unrelated to this PR.
Tests can be found here: …

Remove future night redshifts when running purge night

---

py/desispec/io/spectra.py

This PR allows desispec.io.read_spectra to read FITS files that contains unrecognized FITS extensions. Instead of throwing a fatal error, it now prints a warning and ignores the unrecognized extensions.
Example:
```
from desispec.io import read_spectra
spec = read_spectra('/pscratch/sd/r/rongpu/desi_dust_y1_release/spectra/main/bright/0/0/rvspecfit-main-bright-0.fits')
```
output:
```
WARNING:spectra.py:385:read_spectra: FITS extension REDSHIFTS is not recognized and is ignored
WARNING:spectra.py:385:read_spectra: FITS extension RVTAB is not recognized and is ignored
WARNING:spectra.py:385:read_spectra: FITS extension WAVELENGTH is not recognized and is ignored
WARNING:spectra.py:385:read_spectra: FITS extension SPECMOD is not recognized and is ignored
INFO:spectra.py:392:read_spectra: …
```

Prevent error when read_spectra sees unrecognized FITS extensions

---

py/desispec/scripts/proc_night.py
py/desispec/workflow/science_selection.py

This solves issue #2387. There are circumstances where the tilenight job has already been submitted but we wish to submit additional redshift jobs that depend on those spectra. A common example is deleting spectra and redshifts from an earlier night in daily operations. Any future cumulative redshifts must also be deleted since they used the deleted data. This allows us to resubmit those cumulative jobs within the structure of the pipeline with proper dependencies and processing_table tracking.
I did a number of tests to make sure the new functionality works:
1. That on a night with all requested redshifts the code submits nothing and exists.
2. On a night that hasn't been submitted, it submits everything with the appropriate dependencies.
3. On nights with missing redshifts, the code …

Allow desi_proc_night to submit new redshift jobs even if tilenight exists

---

py/desispec/scripts/trace_shifts.py
py/desispec/trace_shifts.py

PR with improvements to the trace shift code in case of large shifts
- for the fit of traces with the option --arc-lamps (used in particular when shifting the traces before the refined PSF fit):
- compute a list of x,y CCD coordinates of spots expected from the trace set and the arc lamp spectrum stored with the code
- detect a set of spots in the preprocessed arc lamp images
- iteratively match the two lists of spots in a scan of possible delta_x offsets (which can be ambiguous)
- apply the median delta_x and delta_y from the matched spots to the trace coordinates
- use this starting point to fit the traces with the standard procedure (cross dispersion profiles, and cross-correlation of spectra)
- automated iteration over both delta_x and delta_y to converge to a precise offset .
As an …

Trace shifts can now accommodate large offsets when analyzing arc lamp exposures

---

bin/desi_tsnr_afterburner

It appears that PR #1950 didn't fully resolve issues related to nights with no valid science data, or another bug was reintroduced. This PR fixes that.
The code was crashing because it was trying to use a list of computed sky magnitudes to get the list of columns in each row of that list. However, on nights with no valid exposures, no rows are computed, and that caused a crash.
The fix was a simple one-line change with an extra line for logging. I also took the opportunity to update the afterburner to use `findfile` to identify the pipeline `exposure_table`(s).
I tested this in `/global/cfs/cdirs/desi/users/kremin/PRs/tsnr_skymagcrashfix` and the code now runs and produces the correct results on the test night that is crashing in `daily`.

Fix tsnr afterburner bug causing crash on nights with no "good" data

---

py/desispec/scripts/proc_night.py
py/desispec/workflow/science_selection.py

This resolves issue #2408 and fixes a typo identified after merging PR #2441. 
The solution to the issue is to remove a redundant cut on exposure time. All science exposures less than 60s are already labeled as `LASTSTEP=skysub` automatically by the pipeline. If the user doesn't want such low signal-to-noise data, they can specify `science_laststeps="all"`.

Resolve unknown statuses in the dashboard and fix typo

---

bin/desi_resubmit_queue_failures
py/desispec/workflow/processing.py

This makes changes to `desi_resubmit_queue_failures` and `desispec.workflow.processing.update_and_recursively_submit()` to allow the user to specify either exposure ID's or tile ID's that they want to resubmit failures for. The code warns the user that any dependencies that failed will also be resubmitted but only submits the specified jobs and any required dependencies. If a specified job was successful, the script skips that entry. The command line script accepts a comma-separated list of exposures or tiles. If both are specified it raises an error. If none are specified it resubmits all failures on the night, as it did prior to this code change.
I ran 5 tests and confirmed that it did what I expected in all 5 circumstances. Logs for all 5 tests can be found in: …

Allow user to specify exposures or tiles to resubmit

---

doc/changes.rst
py/desispec/io/meta.py
py/desispec/skygradpca.py
py/desispec/test/test_io.py
py/desispec/tpcorrparam.py

This PR makes `$DESI_SPECTRO_REDUX` optional for the purposes of `desispec.io.findfile`.  If it is set, it will be used just like it currently is, but if not set it will default to `$DESI_ROOT/spectro/redux`.  I updated the tests to confirm this behavior. The motivation for this is to make the required environment setup for end-users as simple as possible, in particular for the tutorials (`$DESI_ROOT` will be the only required environment variable for end-user analysis, while still allowing `$DESI_SPECTRO_REDUX` override).  Ditto for `$DESI_SPECTRO_DATA` defaulting to `$DESI_ROOT/spectro/data` if not set.
I did *not* scrub `$DESI_SPECTRO_REDUX` from absolutely everywhere in desispec, so I suggest that we continue to set it and use it like before.  I did update two custom path creations …

default DESI_SPECTRO_REDUX

---

bin/desi_ccd_xy
py/desispec/scripts/proc.py
py/desispec/scripts/trace_shifts.py
py/desispec/trace_shifts.py

Second PR on trace shifts, this time to address the fit of continuum/LED exposures when there are large trace shifts
(the previous PR was for arc lamp exposures).
* Add a first scan for large trace shifts when running `desi_compute_trace_shift` with option `--continuum`.
* Add option `--no-large-shift-scan` to disable this feature.
* This feature is not used in daily pipeline reduction of flat field exposures because a correct PSF (fitted from previous exposures is used).
Example:
```
desi_preproc -i /global/cfs/cdirs/desi/spectro/data/20250214/00279014/desi-00279014.fits.fz --cam r7 -o preproc-r7-00279014.fits
desi_compute_trace_shifts --psf /global/cfs/cdirs/desi/users/jguy/teststand/desi_spectro_calib/spec/sm8/psfnight-r7-20250120.fits --continuum -i preproc-r7-00279014.fits …
```

Also scan for large trace shifts in continuum/LED exposures

---

py/desispec/fluxcalibration.py

The calibration vector `ccalibration` is normalized by the fiber aperture correction factor `FLAT_TO_PSF_FLUX` (`point_source_correction` in the code), but its inverse variance was not normalized accordingly. This PR fixes that.
I tested the new code on a B camera for a dark tile. For most fibers with good fiber positioning (`FIBERSTATUS==0`), the effect should be negligible (less than 1% change in the average cframe IVAR). However, for very bright sources (standard stars and particularly bright galaxies), the new IVAR can be on average ~40% lower.
The largest effect is on the stuck positioners used as sky fibers. They have particularly large `FLAT_TO_PSF_FLUX ` due to their large DELTA_X/Y, and combined with this bug their IVARs are much underestimated. For example, below is the …

Fix bug in fiber aperture correction that affects cframe IVAR

---

py/desispec/fiberfluxcorr.py

This PR include two changes to fluxcalib:
1. Excluding sky fibers from the `point_source_correction` normalization calculation; sky fibers are now always assigned `point_source_correction=1`;
2. Changing the normalization calculation from mean to median so that it is robust against outliers.
Before this fix, fibers with very large fiber positioning offsets (mostly used as sky fibers) biases the normalization calculation, causing the `FLAT_TO_PSF_FLUX` value (`point_source_correction` in the code) to be significantly lower than 1 for the "good" fibers (see below the per-petal median `FLAT_TO_PSF_FLUX` value for 100 random tiles). Fortunately, downstream code cancels out this "correction" and the final flux calibration is unbiased for the good fibers. In addition to bringing the …

Fix fiber aperture correction: normalization and sky fibers

---

py/desispec/io/spectra.py
py/desispec/test/test_io.py

This PR fixes a bug found by @araichoor where `desispec.io.read_frame_as_spectra` was broken because it was creating a `Spectra` object with `meta` as a `astropy.io.fits.FITSHDR` instead of a `dict`.  This includes a unit test demonstrating the bug, and now it passes with this update.
Note: We do not use `read_frame_as_spectra` in the pipeline anymore thus we hadn't noticed that it was broken (we use `read_frame` and `read_spectra` instead).

fix read_frame_as_spectra

---

py/desispec/workflow/calibration_selection.py

This PR logs an error message with details for the case when an arc/flat set are rejected due to having too large a time difference.  I don't recall what night I was debugging when I added this to my local copy, but previously the code could reject all arc/flat sets, without anything in the log indicating why they were rejected.  The change is to add an else clause to this if statement instead of silently moving on:
```python
if np.abs(arcstart-flatend) < max_mjd_dt or np.abs(flatstart-arcend) < max_mjd_dt:
...
else:
log.error(f'arc/flat time diff too large (>{max_mjd_dt}): {np.abs(arcstart-flatend)=}, {np.abs(flatstart-arcend)=}')
```

log error when arc/flat set are rejected due to large time diff

---

py/desispec/io/fibermap.py
py/desispec/spectra.py
py/desispec/test/test_io_fibermap.py

This cleanup PR avoids
* WARNINGs about new fiberassign keywords (FA_HA,  NOWTIME, SVNDM, SVNMTL) when stacking spectra
* ERRORs about new columns IN_COADD_B/R/Z (from PR #2100) when writing spectra
Example:
```
from desispec.io import read_spectra_parallel, write_spectra
zcat = Table.read('/pscratch/sd/s/sjbailey/desi/temp/minizcat.fits')
sp = read_spectra_parallel(zcat, specprod='loa')
write_spectra('blat.fits', sp)
```
Previously this printed
```
WARNING: MergeConflictWarning: Cannot merge meta key 'FA_HA' types <class 'float'> and <class 'float'>, choosing FA_HA=-3.4317088 [astropy.utils.metadata.merge]
WARNING: MergeConflictWarning: Cannot merge meta key 'NOWTIME' types <class 'str'> and <class 'str'>, choosing NOWTIME='2024-04-10T06:54:33+00:00' …
```

IN_COADD_B/R/Z cols and new FA keywords when stacking spectra

---

bin/desi_purge_night
bin/desi_purge_tilenight
py/desispec/scripts/purge_night.py
py/desispec/scripts/purge_tilenight.py

This PR adds the option for `desi_purge_night` and `desi_purge_tilenight` to copy files to `$SPECPROD/attic/` before deletion.
Only the last purged version is preserved in attic: if a file already exist in the attic, the purge will overwrite it.
This option is enabled by default, and can be disabled with `--no_attic`.

Copy purged redux files to attic

---

bin/desi_calib_config
py/desispec/calibfinder.py

New version of the `desi_calib_config` intended to be used in place of the manual edits of the config yaml files with the hope to reduce the number of mistakes we make.
- Please have a look at it and send me comments. It works with the current version of the DESI_SPECTRO_CALIB yaml files that I just updated for this purpose.
- It does not yet contain all of the tests we could do to verify that the calibration configuration is valid, but it is still much better than a pure manual edit.
Example:
```
desi_calib_config sm10-r.yaml 
Current configuration names for sm10-r in the YAML file:
['V20250114', 'V20241125', 'V20241120', 'V20241024', 'V20240815b', 'V20240815a', 'V20240424', 'V20231218', 'V20231129', 'V20230804', 'V20230323', 'V20220613', 'V20220414', 'V20220201', 'V20220104', …
```

New DESI calibration configuration editor

---

py/desispec/coaddition.py
py/desispec/io/fibermap.py
py/desispec/io/spectra.py
py/desispec/pixgroup.py
py/desispec/spectra.py
py/desispec/test/test_spectra.py

Since **kibo**, we have added support in **redrock** to write out best-fit model files (`rrmodel-?*.fits`) alongside the redshift fits. These files are now available on **NERSC** along with the Redrock redshift outputs.
This pull request adds support to `desispec.io.spectra.read_spectra()` to optionally **return the Redrock model fits**, if the corresponding `rrmodel` file exists on disk for the given input spectra or directly from the `infile` if model exists in it. This adds a <1 s runtime to the existing code (if the model needs to be returned). Also added support to return **REDSHIFTS** table if user wants it either from `redrock-*.fits` file of from the `infile` if it exists
This simple addition will make it easier for users to directly access the **best-fit redrock models** without …

Added support to return redrock models in read_spectra

---

py/desispec/ccdcalib.py
py/desispec/scripts/nightly_bias.py

Currently `desi_compute_nightly_bias` crashes with a KeyError if `calibfinder` can't find a valid BIAS calibration file for the current camera configuration. This updates logs an informative error message and skips that camera, allows MPI ranks to complete the remaining jobs, and returns an error code with the number of failed cameras.
I tested this with `desi_compute_nightly_bias -n 20250415 -c a01` which crashes in daily but exits with error code in this branch:
main:
```
ERROR:calibfinder.py:573:find_darks_in_desi_spectro_dark: Didn't find matching z1 calibration darks in $DESI_SPECTRO_DARK, falling back to $DESI_SPECTRO_CALIB
File "/global/common/software/desi/perlmutter/desiconda/20240425-2.2.0/code/desispec/main/bin/desi_compute_nightly_bias", line …
```

Have desi_compute_nightly_bias gracefully exit if default bias is missing

---

bin/desi_compute_nightly_bias
py/desispec/scripts/nightly_bias.py

Patch to PR #2468 . In that we have `sys.exit()` in the function instead of the script in `bin`. The wrapper `main()` script was being called by another function within python and causing that other function to crash. Now we only `sys.exit()` if we call the command line script directly.

sys.exit in script for nightly_bias not in function

---

py/desispec/coaddition.py

`scipy.linalg.eigh(..., turbo=True)` was deprecated in scipy version v1.5.0 and removed in v1.12.0.  The latest version is v1.15.2.
This PR provides the suggested workaround of using `scipy.linalg.eigh(..., driver='gvd')` instead, which also requires explicitly setting the second parameter to be an identity matrix (other drivers implicitly assume that if not provided).  With current desiconda/20240425-2.2.0 scipy/1.8.1 I confirmed that these two options produce identical answers.  Using scipy/1.15.2 the change in this PR is necessary for the tests to pass.
See https://docs.scipy.org/doc/scipy-1.13.1/reference/generated/scipy.linalg.eigh.html as the last doc before the `turbo` option was removed.
@weaverba137 I came across this while patching numpy 2 tests in a fresh environment.

scipy.linalg.eigh deprecated turbo option

---

py/desispec/night_qa.py
py/desispec/tile_qa_plot.py

This PR adds few improvements to the night_qa / tile_qa plots:
- dark/morningdark: adds the ` --model-variance --no-traceshift` options when using `--bkgsub-for-science`; see https://github.com/desihub/desispec/issues/2472
- skyzfiber plot:
- enlarge a bit the ylim so that the maximum z=7 redshift is visible
- also displays the petal id; I find that convenient, instead of always counting with pointing with my finger on the plot...
- tile_qa plot: adds a `z=7` ylabel in the Z vs. FIBER plot; so that we re sure we see the whole redshift range.
Files generated for "development" here: https://data.desi.lbl.gov/desi/users/raichoor/nightqa_dev/nightqa_v29/20250427/.
Displaying here:
- dark / morning dark: works nicely (thanks @julienguy!), before (left), after (right):
- skyzfiber: before …

Nightqa v29

---

py/desispec/scripts/nightly_bias.py

This is a repeat of the trivial PR I added then reverted earlier in the week. We have now finished observing the deep cosmos tile, and therefore have finished processing the nights containing the deep cosmos tile. Those will all be self-consistent with 25 zeros used for their bias. Now I can merge this and we can start using 50 zeros for the nightly bias, when available, starting tonight. I will also use the newly merged version of the code to make a special prod of the cosmos deep tiles for comparison with the 25-zero-bias case.

Update nightly_bias.py to use 50 zeros by default

---

bin/desi_calib_config
py/desispec/fibercrosstalk.py
py/desispec/test/test_fibercrosstalk.py

This PR addresses the issue https://github.com/desihub/desisurveyops/issues/309 where it was found that the fiber cross talk of SM8 z7 has increased with time.
Here are the fiber cross talk values as a function of wavelength in the NIR cameras of the 10 spectrographs measured in 2025 (solid curves) and compared to the original measurements used as a correction (dots):
The amplitude of the fiber cross talk in z7 has doubled. It has increased by 30% in z1, and apparently is now lower in z5 (we don't understand why).
The variation for z7 as a function of time:
The default fiber cross talk parameters are stored in the code data directory (file `desispec/data/fiber-crosstalk.yaml`). Here we add the possibility to use a custom file per camera, which path is saved in the calibration yaml file. …

Use custom fiber cross talk correction

---

bin/desi_tile_vi

This PR enables the `Main DARK1B` tiles to pop up in the `desi_tile_vi` script used in the dailyops tasks.
I m not super-familiar with that script, hence I d appreciate another pair of eyes here.
But it seemed to worked in the small test I did, calling for `20250506`, where we observed the three first `DARK1B` tiles, copied below.
Also, before merging, we would want to be sure that all the hooks are in place in the `desitarget` mtl routines to properly work with those `DARK1B` tiles, so that there is no issue with the next mtl update we will do (@geordie666).
Small test:
```
desi_tile_vi --prod daily -i tiles-specstatus.ecsv --user raichoor --viewer display --night 20250506
INFO:desi_tile_vi:152:main: prod    = /global/cfs/cdirs/desi/spectro/redux/daily
INFO:desi_tile_vi:153:main: qa dir …
```

desi_tile_vi: enable main/dark1b tiles

---

py/desispec/night_qa.py
py/desispec/preproc.py
py/desispec/test/test_preproc.py

This PR should address the small required updates to handle the bright1b/dark1b programs.
Modifications only are for:
- the `skyzfiber-NIGHT.png` plot;
- the `petalnz-NIGHT.pdf` plot.
My test bed is `20250506`, where we observed three dark1b tiles.
For the `skyzfiber-NIGHT.png` plot:
I was lazy and did a simple tweak to the code always "merge" the "1b" cases with the "normal" ones; if backup+backup1b, bright+bright1b, dark+dark1b (even if there will never be a backup1b program).
Here is the plot with current main branch:
and here s with this PR branch (where the three dark1b tiles are added on the right panel):
Couple of remarks:
- the "ALL" case does not change: looking at the code, I think this "ALL" case is really all tiles, so ok;
- the transparency drops for the new version for the …

Nightqa: handle bright1b/dark1b

---

py/desispec/fluxcalibration.py
py/desispec/io/fluxcalibration.py
py/desispec/scripts/fluxcalibration.py

This PR fixes issue #2494 .
An error floor was added to the uncertainties of the standard star spectra when computing the calibration vectors. This was to reduce the weight of the brightest stars (whose models are uncertain). It was also used to avoid masking pixels values with small uncertainties in the outlier rejection loop. The issue is that we left this error floor when computing the final calibration uncertainties, artificially inflating the calibration vector variance.
We fix this issue in this PR. After the fit, without altering the calibration vector values, we recompute the calibration vector variance using the original uncertainties in the spectra.
Because the calibration uncertainties are propagated to the uncertainties of the targets calibrated spectra, those were also …

Improve calibration uncertainty

---

.github/workflows/python-package.yml
doc/changes.rst
py/desispec/badcolumn.py
py/desispec/scripts/exposuretable.py
py/desispec/scripts/processingtable.py
py/desispec/scripts/reformat_exptables.py
py/desispec/scripts/reformat_proctables.py
py/desispec/scripts/submit_prod.py
py/desispec/test/test_preproc.py
py/desispec/test/test_rowbyrowextract.py
py/desispec/util.py
py/desispec/workflow/calibration_selection.py
py/desispec/workflow/desi_proc_funcs.py
py/desispec/workflow/proc_dashboard_funcs.py
py/desispec/workflow/timing.py

This PR updates the test matrix to include tests with NumPy >2.0. Since it was relatively easy to get the full suite of tests to pass, I've gone ahead and moved this to the PR stage, although some NumPy deprecations still need to be cleaned up, and further testing is needed.
Initial findings:
* Numba does not support NumPy > 2.2, so we cannot test NumPy 2.3.x yet.
* Several NumPy deprecation warnings are coming from specter and gpu_specter, so we may need to patch those first, *then* make sure tests still pass.

[WIP] NumPy 2 compatibility

---

py/desispec/tile_qa_plot.py

This PR changes the xlim from `(-0.1, 6)` to `(-0.1, 1.5)` for n(z) plot in the tile_qa png for `BRIGHT1B` tiles.
I ve not tested it but the change is simple enough that I don t expect any issue...
Here s how it currenty looks:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/121078/20250611/tile-qa-121078-thru20250611.png

make_tile_qa_plot(): adapt n(z) xlim for bright1b

---

py/desispec/io/spectra.py
py/desispec/test/test_spectra.py

Must cut the `redshifts` HDU to match the fibermap and spectra.
In the test case shown in #2507, the incorrectly returned TARGETIDs are simply the first two rows in the file, but reversed because it hits this logic: https://github.com/desihub/desispec/blob/main/py/desispec/io/spectra.py#L540
which indexes it by [1,0].  So the returned `redshifts` has length 2, but it's the wrong two elements.

index redshifts by rows to fix #2507

---

bin/desi_tsnr_afterburner
py/desispec/io/meta.py
py/desispec/test/test_io.py

This PR tries to address https://github.com/desihub/desispec/issues/2498.
Copying here the goal: "_we want PROGRAM="dark1b" and GOALTYPE="dark" (and similarly for bright1b / bright). This matches the FAPRGRM and GOALTYPE keywords of the original fiberassign files, and the PROGRAM keyword of the desi*.fits.gz raw data files (which gets its PROGRAM from NTS)._"
I am not familiar with all the possibly involved pieces of code here, and I don t know how to test that.
so it would be great if someone from the data team could take over.
the couple of commits I ve made should hopefully correctly set:
- the `PROGRAM` column value (in the `faflavor2program()` function);
- the `GOALTYPE` column value (in the `desi_tsnr_afterburner` script).
maybe that s all that is required? I admit I don t really …

Goaltype and program in exposures file for dark1b/bright1b tiles

---

py/desispec/coaddition.py
py/desispec/io/spectra.py
py/desispec/test/test_coadd.py

In this PR, I have fixed the `desispec.coaddition.coadd_cameras` to resolve the failure in case of duplicate targetids in `spectra.fibermap["TARGETID"]`. The issue is described in #2481.
Example run for sanity check. I ran both `main` and this branch on a file:
```
from desispec.io.spectra import read_spectra, write_spectra
specfile = f'/global/cfs/cdirs/desi/spectro/redux/loa/tiles/cumulative/24501/20221104/coadd-0-24501-thru20221104.fits'
coadd = read_spectra(specfile)
from desispec.coaddition import coadd_cameras
import time
t0 = time.time()
old_coadd_cams = coadd_cameras(coadd)
print(f'INFO: old coadding took {time.time()-t0:.3f} [sec]')
write_spectra('/pscratch/sd/a/abhijeet/test_desispec/main_coadded_spec.fits', old_coadd_cams)
```
**this branch**
Same script and saved the coadded …

Fix coadd_cameras for model coaddition and duplicate TARGETID handling

---

py/desispec/scripts/archive_tilenight.py
py/desispec/specstatus.py

This PR fixes a bug introduced in PR #2512 which inadvertently resulted in a PROGRAM column being added to the desisurveyops tiles-specstatus.ecsv file when running `desi_archive_tilenight`.  I fixed the file by hand to remove that column; this PR fixes `desi_archive_tilenight` so that the column doesn't re-appear when it is run the next time.
Explanation for the record:  in PR #2512 I added a PROGRAM column to the tiles table after reading it from tiles-specstatus.ecsv.  This was for convenience for filtering and printing the table, but I hadn't remembered that this in-memory copy was later updated and written back out to the tiles-specstatus.ecsv file, resulting in a new column appearing, which then broke `desi_update_tiles_specstatus` which has strict column checking for safety.  The …

avoid adding specstatus PROGRAM column

---

py/desispec/ccdcalib.py
py/desispec/io/raw.py
py/desispec/preproc.py
py/desispec/scripts/compute_dark.py
py/desispec/scripts/proc.py
py/desispec/util.py
py/desispec/workflow/desi_proc_funcs.py

This PR makes several updates to support making nightly biases and darks even without a $DESI_SPECTRO_CALIB configuration.  This simplifies the bootstrapping process when generating the files for a new config after a hardware change.  i.e. the automated pipeline would create the nightly bias for you (needed for darks), and you can create the dark without having to create a dummy config first.  Note that a config is still needed to create the final pixmask, since that requires the pixflat found via the config.
* preproc
* don't try to create a CalibFinder objects if not needed (no dark, bias, or pixflat requested)
* desi_compute_nightly_bias (via preproc), if calib isn't found
* skip GOODBIASSEC check (currently only used in some historic but not current configs of sm10-z)
* don't compare …

nightlybias and darks without a calib config
